import {GL_MakeAliasModelDisplayLists} from '../src/engine/render/gl_mesh.js';
import {AliasMeshSignature,AliasMeshValidate} from '../src/newer/assets/alias_mesh_format.js';
import {R_AliasMeshLookup,R_AliasMeshRemember,R_AliasMeshCacheStatus} from '../src/newer/assets/r_aliasmeshcache.js';
const check=(v,m)=>{if(!v)throw Error(m);},same=(a,b,m)=>check(a===b,`${m}: ${a} != ${b}`),bits=a=>Buffer.from(a.buffer,a.byteOffset,a.byteLength);
function header(offset=0){return{numverts:4,numtris:2,skinwidth:74,skinheight:58,numposes:3,triangles:[{facesfront:0,vertindex:[0,1,2]},{facesfront:1,vertindex:[0,2,3]}],stverts:[{onseam:1,s:0,t:0},{onseam:0,s:20,t:0},{onseam:1,s:20,t:20},{onseam:0,s:0,t:20}],poseverts:Array.from({length:3},(_,pose)=>Array.from({length:4},(_,v)=>({v:[offset+v,pose*9,offset-pose-v],lightnormalindex:pose*4+v}))) };}
Deno.test('alias cache reuses only command/order bytes and public display-list construction always references current header poses',()=>{
 const original=header();GL_MakeAliasModelDisplayLists({name:'public-original'},original);const remembered=R_AliasMeshLookup(original);check(remembered,'first uncached public build populates cache');const fresh=header(1000);same(AliasMeshSignature(fresh),AliasMeshSignature(original),'pose changes do not change topology authority');GL_MakeAliasModelDisplayLists({name:'public-current-poses'},fresh);check(bits(fresh.commands).equals(bits(original.commands)),'same original command bits reused');check(bits(fresh.meshVertexOrder).equals(bits(original.meshVertexOrder)),'same original vertex order reused');
 for(let pose=0;pose<fresh.numposes;pose++)for(let i=0;i<fresh.poseverts_count;i++){same(fresh.posedata[pose][i],fresh.poseverts[pose][fresh.meshVertexOrder[i]],'actual current pose object retained');check(fresh.posedata[pose][i]!==original.posedata[pose][i],'no stale first-header pose retained');}
 const expected=R_AliasMeshLookup(fresh);fresh.commands.fill(0);fresh.meshVertexOrder.fill(0);remembered.commands.fill(0);remembered.order.fill(0);const unchanged=R_AliasMeshLookup(header());check(bits(unchanged.commands).equals(bits(expected.commands))&&bits(unchanged.order).equals(bits(expected.order)),'header and public lookup result mutation cannot alter authority');
});
Deno.test('cache authority includes active ordered topology, facesfront, ST/seam and skin dimensions but excludes unused native scratch-array tails',()=>{
 const original=header();GL_MakeAliasModelDisplayLists({name:'public-invalidation'},original);for(const change of [h=>h.triangles.reverse(),h=>h.triangles[0].vertindex.reverse(),h=>h.triangles[0].facesfront^=1,h=>h.stverts[1].s++,h=>h.stverts[1].t++,h=>h.stverts[1].onseam^=1,h=>h.skinwidth++,h=>h.skinheight++]){const next=header();change(next);check(AliasMeshSignature(next)!==AliasMeshSignature(original),'actual input change invalidates signature');same(R_AliasMeshLookup(next),null,'changed input cannot borrow previous cached commands');}
 const padded=header();padded.triangles.push({facesfront:999,vertindex:[999,999,999]});padded.stverts.push({onseam:999,s:999,t:999});same(AliasMeshSignature(padded),AliasMeshSignature(original),'unused shared decoder scratch tails never become cache inputs');check(R_AliasMeshLookup(padded),'same active model hits despite prior decoder leftovers');
});
Deno.test('malformed command primitives, nonfinite UVs, illegal order entries and missing represented triangles cannot become prepared alias lists',()=>{
 const h=header();GL_MakeAliasModelDisplayLists({name:'public-validate'},h);const record={commands:Array.from(h.commands),order:Array.from(h.meshVertexOrder)};const good=AliasMeshValidate(record,h);check(bits(good.commands).equals(bits(h.commands)),'valid original command bytes accepted');
 const cases=[null,{commands:[0],order:[]},{commands:[0,0],order:[]},{...record,commands:record.commands.slice(0,-1)},{...record,order:record.order.slice(1)},{...record,order:record.order.map((n,i)=>i===0?h.numverts:n)},{...record,order:record.order.map((n,i)=>i===0?-1:n)},{...record,commands:record.commands.map((n,i)=>i===1?0x7fc00000:n)},{...record,commands:record.commands.map((n,i)=>i===0?2:n)},{...record,commands:record.commands.map((n,i)=>i===0?-2147483648:n)},{...record,commands:new Array(8193).fill(0)}];
 for(const bad of cases){let rejected=false;try{AliasMeshValidate(bad,h);}catch{rejected=true;}check(rejected,'malformed prepared alias rejected');}
});
Deno.test('runtime alias cache owns copied input arrays and remains bounded after more than64 distinct valid model layouts',()=>{
 const h=header();GL_MakeAliasModelDisplayLists({name:'public-bound-source'},h);const commands=h.commands.slice(),order=h.meshVertexOrder.slice(),remembered={...h,skinwidth:10001};R_AliasMeshRemember(remembered,commands,order);commands.fill(0);order.fill(0);check(bits(R_AliasMeshLookup(remembered).commands).equals(bits(h.commands)),'remember copies mutable caller arrays');
 const oldest={...h,skinwidth:11000};R_AliasMeshRemember(oldest,h.commands,h.meshVertexOrder);for(let i=1;i<=70;i++)R_AliasMeshRemember({...h,skinwidth:11000+i},h.commands,h.meshVertexOrder);same(R_AliasMeshLookup(oldest),null,'oldest unprepared model evicted beyond64');const status=R_AliasMeshCacheStatus();same(status.entries,64,'entry count capped at64');check(status.bytes>0&&status.bytes<=8*1024*1024,'reported complete key/array byte ownership stays within budget');
});
