// Actual native loopback, renderer alias/camera, input and host-loop boundaries.
// Browser GPU presentation is independently exercised by bestiary_trial.
import {readFileSync} from 'node:fs';
import * as pak from '../src/pak.js';
import {VID_SetPalette} from '../src/vid.js';
import {Mod_Init} from '../src/gl_model.js';
import {PR_InitBuiltins} from '../src/pr_cmds.js';
import {PR_ExecuteProgram} from '../src/pr_exec.js';
import * as progs from '../src/progs.js';
import {ED_FindFunction,ED_FindField,ED_NewString,GetEdictFieldValue} from '../src/pr_edict.js';
import {sv,svs,client_t,set_host_client,skill} from '../src/server.js';
import {SV_CheckForNewClients,SV_Init} from '../src/sv_main.js';
import {SV_SetPlayer,SV_SetFrametime,SV_Physics_Client,sv_gravity} from '../src/sv_phys.js';
import * as cmd from '../src/cmd.js';
import * as vars from '../src/cvar.js';
import {Host_InitCommands} from '../src/host_cmd.js';
import {CL_Init,CL_Disconnect_f} from '../src/cl_main.js';
import {cls,cl,cl_entities,cl_visedicts,cl_dlights,set_cl_numvisedicts,ca_disconnected} from '../src/client.js';
import {NET_Init,NET_SendMessage,NET_GetMessage,NET_CanSendMessage} from '../src/net_main.js';
import {SZ_Clear} from '../src/common.js';
import {R_Init} from '../src/gl_rmain.js';
import {V_Init} from '../src/view.js';
import {SV_RunClients} from '../src/sv_user.js';
import * as travel from '../src/sv_seamless.js';
import {R_DemoLoadingCancel} from '../src/r_demoloading.js';
const check=(x,m)=>{if(!x)throw Error(m);},same=(a,b,m)=>check(a===b,`${m}: ${a} != ${b}`),text=i=>progs.PR_GetString(i);
const bytes=readFileSync(new URL('../pak0.pak',import.meta.url));
pak.COM_AddPack(pak.COM_LoadPackFile('pak0.pak',bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.length)));
VID_SetPalette(pak.COM_FindFile('gfx/palette.lmp').data);Mod_Init();PR_InitBuiltins();SV_Init();cmd.Cbuf_Init();cmd.Cmd_Init();CL_Init();R_Init();V_Init();Host_InitCommands();
for(const c of[skill,sv_gravity,travel.sv_seamless])if(!vars.Cvar_FindVar(c.name))vars.Cvar_RegisterVariable(c);
svs.maxclients=svs.maxclientslimit=1;svs.clients=[new client_t()];NET_Init();cls.state=ca_disconnected;cls.demoplayback=false;
function acknowledge(){const c=svs.clients[0];if(c?.active&&c.netconnection&&cls.netcon&&!cls.netcon.disconnected&&c.message.cursize&&NET_CanSendMessage(c.netconnection)){NET_SendMessage(c.netconnection,c.message);NET_GetMessage(cls.netcon);SZ_Clear(c.message);}}
function finishConnect(){SV_CheckForNewClients();const c=svs.clients[0];check(c.active&&c.netconnection&&cls.netcon?.driverdata===c.netconnection,'actual local loopback is paired');set_host_client(c);SV_SetPlayer(c.edict);cmd.Cmd_ExecuteString('spawn',cmd.src_client);SV_RunClients();cmd.Cmd_ExecuteString('begin',cmd.src_client);cls.signon=4;cl.intermission=0;acknowledge();R_DemoLoadingCancel();check(c.edict.v.health>0&&text(c.edict.v.classname)==='player','actual native spawn command initializes living player');return c.edict;}
async function command(value){acknowledge();cmd.Cmd_ExecuteString(value,cmd.src_command);await Promise.resolve();return finishConnect();}
async function fresh(map='e1m1'){vars.Cvar_SetValue('r_hdr',1);vars.Cvar_SetValue('skill',1);vars.Cvar_SetValue('sv_seamless',1);return command('map '+map);}

import * as THREE from 'three';
import * as bestiary from '../src/r_bestiary.js';
import * as main from '../src/gl_rmain.js';
import * as post from '../src/gl_post.js';
import * as host from '../src/host.js';
import * as keys from '../src/keys.js';
import * as input from '../src/cl_input.js';
import {IN_Move} from '../src/in_web.js';
import * as loading from '../src/r_demoloading.js';
import * as parts from '../src/r_part.js';
import {R_ShellTrace} from '../src/r_shelltrace.js';
import {SV_Move,SV_LinkEdict,MOVE_NOMONSTERS,MOVE_NORMAL} from '../src/world.js';
import {R_DrawAliasModel} from '../src/gl_mesh.js';
import {r_refdef,entity_t} from '../src/render.js';
const near=(a,b,m,e=1e-6)=>check(Math.abs(a-b)<=e,`${m}: ${a} != ${b}`);
const store=new Map(),storageDescriptor=Object.getOwnPropertyDescriptor(globalThis,'localStorage');Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,String(v))}});
keys.Key_Init();
const catalog=bestiary.R_BestiaryEntries(),living=()=>sv.edicts.slice(0,sv.num_edicts).filter(e=>e&&!e.free&&e.v.health>0&&e.v.deadflag===0&&catalog.some(c=>c.classes.includes(text(e.v.classname))));
const identify=e=>catalog.find(c=>c.classes.includes(text(e.v.classname)));
async function game(map){const prior=bestiary.R_BestiarySnapshot().unlocked;const p=await fresh(map);cl.worldmodel=sv.worldmodel;cl.model_precache=sv.models.slice();cl.maxclients=1;cl.viewentity=1;cl.stats[0]=p.v.health;cl.time=cl.oldtime=sv.time;cl.mtime[0]=cl.mtime[1]=sv.time;cl.paused=false;sv.paused=false;keys.set_key_dest(keys.key_game);input.CL_SuspendGameButtons();p.v.flags|=64;p.v.velocity=[0,0,0];cl.viewangles.set(p.v.v_angle);bestiary.R_BestiaryCancel();bestiary.R_BestiaryFrame(host.realtime);for(let i=0;i<12;i++)host.Host_Frame(.05);check(prior.every(id=>bestiary.R_BestiarySnapshot().unlocked.includes(id)),'actual new map retains all prior journal discoveries');return p;}
function poseCamera(p,goal){const eye=Array.from(p.v.origin,(v,i)=>v+(i===2?22:0)+1/32),delta=goal.map((v,i)=>v-eye[i]),angles=[-Math.atan2(delta[2],Math.hypot(delta[0],delta[1]))*180/Math.PI,Math.atan2(delta[1],delta[0])*180/Math.PI,0];r_refdef.vrect.width=640;r_refdef.vrect.height=400;r_refdef.fov_x=90;r_refdef.fov_y=2*Math.atan(1/1.6)*180/Math.PI;r_refdef.vieworg.set(eye);r_refdef.viewangles.set(angles);main.R_SetupFrame();main.R_SetFrustum();main.R_SetupGL();return{eye,angles};}
function centreOf(e){return Array.from(e.v.origin,(v,i)=>v+(e.v.mins[i]+e.v.maxs[i])/2);}
function drawEnemy(e){const ent=new entity_t();ent.model=sv.models[e.v.modelindex];check(ent.model?.cache?.data,'native alias data loaded');ent.origin.set(e.v.origin);ent.angles.set(e.v.angles);ent.frame=e.v.frame;ent._entityIndex=e.index;cl_entities[e.index]=ent;const mesh=R_DrawAliasModel(ent,ent.model.cache.data,new Float32Array(256).fill(1),1);main.scene.add(mesh);mesh.visible=true;mesh.updateMatrixWorld(true);cl_visedicts[0]=ent;set_cl_numvisedicts(1);return ent;}
function clearPair(p,prefer=null,allowKnown=false){for(const e of living().sort((a,b)=>Math.hypot(...Array.from(a.v.origin,(v,i)=>v-p.v.origin[i]))-Math.hypot(...Array.from(b.v.origin,(v,i)=>v-p.v.origin[i])))){if(prefer&&identify(e).id!==prefer||!allowKnown&&bestiary.R_BestiarySnapshot().unlocked.includes(identify(e).id))continue;const candidate=drawEnemy(e),visualCentre=new THREE.Box3().setFromBufferAttribute(candidate._aliasMesh.geometry.attributes.position).applyMatrix4(candidate._aliasMesh.matrixWorld).getCenter(new THREE.Vector3()).toArray();for(const distance of[256,192,128,96,64])for(const d of[[1,0],[-1,0],[0,1],[0,-1],[Math.SQRT1_2,Math.SQRT1_2],[-Math.SQRT1_2,Math.SQRT1_2],[Math.SQRT1_2,-Math.SQRT1_2],[-Math.SQRT1_2,-Math.SQRT1_2]]){const origin=[e.v.origin[0]+d[0]*distance,e.v.origin[1]+d[1]*distance,e.v.origin[2]],fit=SV_Move(origin,p.v.mins,p.v.maxs,origin,MOVE_NORMAL,p),eye=[origin[0],origin[1],origin[2]+22];if(fit.startsolid||fit.allsolid)continue;const tr=R_ShellTrace(cl.worldmodel,eye,visualCentre,0,cl_entities);if(!tr.startsolid&&!tr.allsolid&&tr.fraction>=.999){p.v.origin=origin;p.v.velocity=[0,0,0];SV_LinkEdict(p,false);console.log('BESTIARY_NATIVE_VIEW '+JSON.stringify({map:sv.name,id:identify(e).id,classname:text(e.v.classname),player:origin,enemy:Array.from(e.v.origin),target:visualCentre}));return e;}}}throw Error('No hull-safe native unseen enemy sightline');}
const observe=e=>bestiary.R_BestiaryObserve(main.scene,main.camera,[e]);
Deno.test('actual native living enemy discovery rejects unsupported scopes, hidden aliases, dead bodies, rear views and opaque BSP before unlocking once',async()=>{
 const p=await game('e1m1'),enemy=clearPair(p),id=identify(enemy).id,ent=drawEnemy(enemy),goal=centreOf(enemy);poseCamera(p,goal);check(bestiary.R_BestiaryAllowed(),'actual live single-player loopback admitted');check(!bestiary.R_BestiarySnapshot().unlocked.includes(id),'control enemy is undiscovered');
 const reject=(label,change,restore)=>{change();try{check(!observe(ent),'no false discovery: '+label);check(!bestiary.R_BestiarySnapshot().unlocked.includes(id),'no progress mutation: '+label);}finally{restore();}};
 reject('Classic',()=>vars.Cvar_SetValue('r_hdr',0),()=>vars.Cvar_SetValue('r_hdr',1));reject('demo',()=>cls.demoplayback=true,()=>cls.demoplayback=false);reject('multiplayer',()=>svs.maxclients=2,()=>svs.maxclients=1);reject('client multiplayer header',()=>cl.maxclients=2,()=>cl.maxclients=1);reject('menu',()=>keys.set_key_dest(keys.key_menu),()=>keys.set_key_dest(keys.key_game));reject('welcome loading',()=>loading.R_DemoLoadingWelcome(),()=>loading.R_DemoLoadingCancel());reject('dead player',()=>p.v.health=0,()=>p.v.health=100);reject('inactive local client',()=>svs.clients[0].active=false,()=>svs.clients[0].active=true);reject('closed loopback peer',()=>svs.clients[0].netconnection.disconnected=true,()=>svs.clients[0].netconnection.disconnected=false);const oldDriver=cls.netcon.driver;reject('remote transport',()=>cls.netcon.driver=1,()=>cls.netcon.driver=oldDriver);const sourceWorld=cl.worldmodel;reject('stale client world',()=>cl.worldmodel={...sourceWorld},()=>cl.worldmodel=sourceWorld);reject('hidden alias',()=>ent._aliasMesh.visible=false,()=>ent._aliasMesh.visible=true);const health=enemy.v.health;reject('dead enemy',()=>enemy.v.health=0,()=>enemy.v.health=health);reject('native deadflag',()=>enemy.v.deadflag=2,()=>enemy.v.deadflag=0);
 const behind=goal.map((v,i)=>2*r_refdef.vieworg[i]-v);poseCamera(p,behind);check(!observe(ent),'rear native alias never unlocks');poseCamera(p,goal);
 const hidden=living().find(e=>{const trace=R_ShellTrace(cl.worldmodel,Array.from(r_refdef.vieworg),centreOf(e),0,cl_entities);return identify(e).id===id&&trace.fraction<.95&&!trace.startsolid;});check(hidden,'native BSP supplies an occluded living same-type control');const hiddenEnt=drawEnemy(hidden);poseCamera(p,centreOf(hidden));check(hiddenEnt._aliasMesh.visible,'occluded control still has a real drawable alias');check(!observe(hiddenEnt),'front-facing native monster behind real BSP stays undiscovered');poseCamera(p,goal);check(observe(ent),'actual clear living alias triggers discovery');same(bestiary.R_BestiarySnapshot().entry.id,id,'correct native classname catalog entry');same(bestiary.R_BestiarySnapshot().phase,'enter','actual observation starts bounded encounter');check(store.get('quaked.bestiary.v1')?.includes(id),'real runtime persists unlocked type');p.v.health=0;bestiary.R_BestiaryFrame(host.realtime+.1);same(bestiary.R_BestiarySnapshot().phase,'idle','native player death aborts presentation');same(bestiary.R_BestiaryTimeScale(),1,'death releases simulation ownership');check(bestiary.R_BestiarySnapshot().unlocked.includes(id),'death does not erase discovery');p.v.health=100;bestiary.R_BestiaryFrame(host.realtime+1);check(!observe(ent),'already discovered type does not retrigger');bestiary.R_BestiaryFrame(host.realtime);acknowledge();CL_Disconnect_f();
});
Deno.test('actual renderer camera borrows orientation and FOV while native player pose stays untouched and fresh dismiss input is consumed through its release',async()=>{
 const p=await game('e1m2'),enemy=clearPair(p,'knight'),ent=drawEnemy(enemy),goal=centreOf(enemy);poseCamera(p,goal);const original={position:main.camera.position.clone(),quaternion:main.camera.quaternion.clone(),fov:main.camera.fov,origin:Array.from(p.v.origin),angles:Array.from(p.v.v_angle),view:Array.from(cl.viewangles)},binding=keys.keybindings[keys.K_MOUSE1];cl.viewent.model=sv.models[sv.model_precache.indexOf(text(p.v.weaponmodel))];cl.viewent.origin.set(main.camera.position.toArray());cl.viewent.angles.set(r_refdef.viewangles);main.R_DrawViewModel();const held=cl.viewent._aliasMesh;check(held?.material,'actual native held material exists for isolation control');const weaponTags=JSON.stringify({mesh:held.userData,material:held.material.userData}),dynamicBefore=JSON.stringify(cl_dlights);same(bestiary.R_BestiaryPortraitLight(),null,'idle has no portrait source');post.R_BuildWorldLights(cl.worldmodel);const select=()=>post.R_SelectWorldLights(main.camera.matrixWorldInverse,0,new Array(64).fill(264),cl_dlights,cl.time);check(!select().some(l=>l.source?.bestiary),'idle renderer selection has no portrait light');let earlyLight=null,earlyFade=0,earlyRange=0,earlyColour=0;keys.keybindings[keys.K_MOUSE1]='+attack';keys.Key_ClearStates();keys.Key_Event(keys.K_MOUSE1,true);cmd.Cbuf_Execute();check(input.in_attack.state&1,'preexisting held attack is genuine positive control');check(observe(ent),'second native type starts encounter');same(input.in_attack.state,0,'encounter suspends actual held gameplay button');const start=host.realtime;
 for(const age of[.2,.4,.6,.75]){bestiary.R_BestiaryFrame(start+age);poseCamera(p,goal);same(main.camera.position.toArray().join(),original.position.toArray().join(),'render presentation never moves native eye');same(Array.from(p.v.origin).join(),original.origin.join(),'presentation never teleports player');same(Array.from(p.v.v_angle).join(),original.angles.join(),'presentation never writes server view angles');same(Array.from(cl.viewangles).join(),original.view.join(),'presentation never writes client view angles');check(main.camera.fov<=original.fov&&main.camera.fov>0,'finite symmetric focus lens');near(main.camera.matrixWorld.determinant(),1,'camera remains a proper rigid basis');const light=bestiary.R_BestiaryPortraitLight(),picked=select().find(l=>l.source===light);check(light?.bestiary&&picked,'real portrait source enters existing light selection');check(picked.color.every(Number.isFinite)&&picked.color[0]>0,'portrait radiance is finite and positive');if(age===.2){earlyLight=light;earlyFade=light.fade;earlyRange=picked.range;earlyColour=picked.color[0];}else{same(light,earlyLight,'portrait keeps one stable source identity');same(picked.range,earlyRange,'portrait receiver reach stays stable while intensity fades');}if(age===.75){same(light.fade,1,'held portrait reaches full intended light');check(picked.color[0]>earlyColour&&earlyFade<1,'light rises through actual controller progress');const center=new THREE.Box3().setFromBufferAttribute(ent._aliasMesh.geometry.attributes.position).applyMatrix4(ent._aliasMesh.matrixWorld).getCenter(new THREE.Vector3());const expected=center.lerp(main.camera.position,.7);light.pos.forEach((v,i)=>near(v,expected.getComponent(i),'portrait world position lies on real eye-to-enemy segment'));}}
 const focus=new THREE.Box3().setFromBufferAttribute(ent._aliasMesh.geometry.attributes.position).applyMatrix4(ent._aliasMesh.matrixWorld).getCenter(new THREE.Vector3()).project(main.camera),state=bestiary.R_BestiarySnapshot();near(focus.x,state.side==='left'?-.5:.5,'actual camera places target in its selected screen half',.03);check(Math.abs(main.camera.quaternion.dot(original.quaternion))<.9999||main.camera.fov<original.fov,'actual camera visibly changes instead of status-only intro');keys.Key_Event(keys.K_MOUSE1,true);cmd.Cbuf_Execute();same(bestiary.R_BestiarySnapshot().phase,'hold','held-before-encounter repeat cannot dismiss');keys.Key_Event(keys.K_MOUSE1,false);cmd.Cbuf_Execute();keys.Key_Event(keys.K_MOUSE1,true);cmd.Cbuf_Execute();same(bestiary.R_BestiarySnapshot().phase,'return','fresh actual mouse binding dismisses');same(input.in_attack.state,0,'dismissal is not a shot');bestiary.R_BestiaryFrame(start+.95);poseCamera(p,goal);const fading=bestiary.R_BestiaryPortraitLight();check(fading===earlyLight&&fading.fade>0&&fading.fade<1,'same physical portrait source fades during return');bestiary.R_BestiaryFrame(start+1.201);poseCamera(p,goal);same(bestiary.R_BestiarySnapshot().phase,'idle','camera return finishes');near(1-Math.abs(main.camera.quaternion.dot(original.quaternion)),0,'normal R_SetupGL restores original camera quaternion');near(main.camera.fov,original.fov,'normal R_SetupGL restores lens');same(bestiary.R_BestiaryPortraitLight(),null,'finished encounter owns no light');check(!select().some(l=>l.source?.bestiary),'idle light selection drops portrait source');same(JSON.stringify(cl_dlights),dynamicBefore,'portrait never borrows or mutates native explosion/muzzle slots');same(JSON.stringify({mesh:held.userData,material:held.material.userData}),weaponTags,'portrait never changes held receiver or coating userdata');keys.Key_Event(keys.K_MOUSE1,true);cmd.Cbuf_Execute();same(input.in_attack.state,0,'held dismissal repeat after return remains consumed');keys.Key_Event(keys.K_MOUSE1,false);cmd.Cbuf_Execute();keys.Key_Event(keys.K_MOUSE1,true);cmd.Cbuf_Execute();check(input.in_attack.state&1,'a new physical press after release regains native attack');keys.Key_Event(keys.K_MOUSE1,false);cmd.Cbuf_Execute();keys.keybindings[keys.K_MOUSE1]=binding;bestiary.R_BestiaryCancel();bestiary.R_BestiaryFrame(host.realtime);acknowledge();CL_Disconnect_f();
});

Deno.test('real Host_Frame freezes server and client clocks, due native AI and live particles throughout hold/return, then restores existing timescale without firing dismissal',async()=>{
 const p=await game('e1m3'),particleScene=new THREE.Scene();parts.R_SetParticleExternals({scene:particleScene,sv_gravity});parts.R_InitParticles();parts.R_ParticleExplosion(Array.from(p.v.origin,(v,i)=>v+(i===2?24:0)));const scaleVar=vars.Cvar_FindVar('host_timescale'),savedScale=scaleVar?.string,savedBinding=keys.keybindings[keys.K_MOUSE1],navigatorDescriptor=Object.getOwnPropertyDescriptor(globalThis,'navigator');let pad=null;keys.keybindings[keys.K_MOUSE1]='+attack';keys.Key_ClearStates();input.CL_SuspendGameButtons();
 try{host.Host_Frame(.05);parts.R_DrawParticles();const cloud=[...particleScene.children,...main.scene.children].find(o=>o.isPoints);check(cloud&&cloud.geometry.drawRange.count>100,'actual live particle buffer has nonempty coverage');const initial=cloud.geometry.attributes.position.array.slice(),firstTime=cl.time,baselineFrame=host.host_frametime;host.Host_Frame(.05);parts.R_DrawParticles();check(cl.time>firstTime&&initial.some((v,i)=>v!==cloud.geometry.attributes.position.array[i]),'actual native clock and particle physics advance before encounter');const enemy=clearPair(p),ent=drawEnemy(enemy),goal=centreOf(enemy);poseCamera(p,goal);check(observe(ent),'third actual unseen enemy starts host-owned encounter');
  for(let i=0;i<30&&bestiary.R_BestiarySnapshot().phase!=='hold';i++){host.Host_Frame(.05);parts.R_DrawParticles();}same(bestiary.R_BestiarySnapshot().phase,'hold','real host clock reaches held encounter');check(bestiary.R_BestiaryFrozen(),'actual runtime reports zero simulation scale');check(enemy.v.think>0,'real target has native AI thinker');enemy.v.nextthink=sv.time; // A due thinker detects an erroneous Physics(0) call.
  const frozen={server:sv.time,client:cl.time,qc:progs.pr_global_struct.time,real:host.realtime,frame:enemy.v.frame,nextthink:enemy.v.nextthink,origin:Array.from(enemy.v.origin),ammo:p.v.ammo_shells,particles:cloud.geometry.attributes.position.array.slice(),count:cloud.geometry.drawRange.count};pad={index:0,connected:true,axes:[.8,-.8,.8,-.8],buttons:Array.from({length:16},()=>({pressed:false,value:0}))};Object.defineProperty(globalThis,'navigator',{configurable:true,value:{userAgent:'native-bestiary-test',getGamepads:()=>[pad]}});const heldAngles=Array.from(cl.viewangles),heldCmd={forwardmove:31,sidemove:17,upmove:9};IN_Move(heldCmd);same([heldCmd.forwardmove,heldCmd.sidemove,heldCmd.upmove].join(),'0,0,0','actual IN_Move clears movement despite active analog axes');same(Array.from(cl.viewangles).join(),heldAngles.join(),'actual gamepad analog look cannot bypass encounter lock');
  check([frozen.server,frozen.client,frozen.qc,frozen.real].every(Number.isFinite),'all clock oracles read actual finite exported state');for(let i=0;i<8;i++){host.Host_Frame(.05);parts.R_DrawParticles();same(sv.time,frozen.server,'server time frozen');same(cl.time,frozen.client,'client clock frozen');same(progs.pr_global_struct.time,frozen.qc,'actual QuakeC clock frozen');same(host.host_frametime,0,'actual host simulation delta is zero');same(enemy.v.nextthink,frozen.nextthink,'due native AI is not executed with fake zero delta');same(enemy.v.frame,frozen.frame,'native AI pose frozen');same(Array.from(enemy.v.origin).join(),frozen.origin.join(),'native actor position frozen');same(cloud.geometry.drawRange.count,frozen.count,'particle lifetime frozen');check(frozen.particles.every((v,k)=>v===cloud.geometry.attributes.position.array[k]),'actual live particle positions frozen');same(vars.Cvar_FindVar('host_timescale'),scaleVar,'encounter never replaces or invents a timescale cvar');if(scaleVar)same(scaleVar.string,savedScale,'existing timescale preference never overwritten');same(sv.paused,false,'native server pause preference untouched');same(cl.paused,false,'native client pause preference untouched');}
  check(host.realtime>frozen.real,'real presentation clock still advances while simulation holds');same(Array.from(cl.viewangles).join(),heldAngles.join(),'held analog axes never accumulate delayed look during actual host frames');pad.axes.fill(0);pad.buttons[7]={pressed:true,value:1};IN_Move({forwardmove:0,sidemove:0,upmove:0});cmd.Cbuf_Execute();same(bestiary.R_BestiarySnapshot().phase,'return','fresh actual gamepad trigger follows native key path to begin return');same(input.in_attack.state,0,'shooting dismissal never enters actual attack state');let returned=false;for(let i=0;i<12;i++){host.Host_Frame(.05);parts.R_DrawParticles();if(bestiary.R_BestiarySnapshot().phase==='idle'){returned=true;break;}same(sv.time,frozen.server,'server remains frozen while camera returns');same(cl.time,frozen.client,'client remains frozen while camera returns');}check(returned,'bounded native host frames finish return');same(p.v.ammo_shells,frozen.ammo,'dismissal does not fire or consume native ammunition');check(sv.time>frozen.server&&cl.time>frozen.client,'actual world and client clocks resume');check(enemy.v.nextthink>frozen.nextthink,'due native AI executes after return');host.Host_Frame(.05);parts.R_DrawParticles();near(host.host_frametime,baselineFrame,'original actual host timestep restored by ordinary path');check(frozen.particles.some((v,i)=>v!==cloud.geometry.attributes.position.array[i]),'real particle physics resumes');pad.buttons[7]={pressed:false,value:0};IN_Move({forwardmove:0,sidemove:0,upmove:0});pad.axes=[.8,-.8,.8,-.8];const restoredAngles=Array.from(cl.viewangles),restoredCmd={forwardmove:0,sidemove:0,upmove:0};IN_Move(restoredCmd);check(restoredCmd.forwardmove!==0||restoredCmd.sidemove!==0,'actual analog movement resumes after return');check(Array.from(cl.viewangles).some((v,i)=>v!==restoredAngles[i]),'actual analog look resumes after return');cl.viewangles.set(restoredAngles);pad.axes.fill(0);
  console.log('BESTIARY_NATIVE_PAUSE '+JSON.stringify({id:identify(enemy).id,frozen:{server:frozen.server,client:frozen.client,qc:frozen.qc,particles:frozen.count},resumed:{server:sv.time,client:cl.time,qc:progs.pr_global_struct.time,frametime:host.host_frametime},ammo:p.v.ammo_shells}));
 }finally{if(navigatorDescriptor)Object.defineProperty(globalThis,'navigator',navigatorDescriptor);else delete globalThis.navigator;if(scaleVar)vars.Cvar_Set(scaleVar.name,savedScale);keys.keybindings[keys.K_MOUSE1]=savedBinding;bestiary.R_BestiaryCancel();input.CL_SuspendGameButtons();parts.R_ClearParticles();parts.R_SetParticleExternals({scene:main.scene,sv_gravity});acknowledge();CL_Disconnect_f();}
});


Deno.test('public native observation reads extended QuakeC death callbacks and optional variant fields rather than absent JavaScript properties',async()=>{
 const p=await game('e1m2'),enemy=clearPair(p,'knight',true),ent=drawEnemy(enemy),goal=centreOf(enemy);poseCamera(p,goal);const death=GetEdictFieldValue(enemy,'th_die');check(death&&death.ofs>=0,'real loaded progs supplies th_die field offset');same(enemy.v.th_die,undefined,'native exported entvars deliberately has no th_die convenience property');const original={functions:progs.pr_functions,defs:progs.pr_fielddefs,count:progs.progs.numfielddefs,death:death.accessor.getInt32(death.ofs),classname:enemy.v.classname,model:enemy.v.model};
 // Shipped base progs has no infected extension. Alias a real, saved scalar
 // field slot in this test's declaration table; no fake entvars property or
 // variant AI is installed/executed. The public accessor handles all writes.
 const scratch=ED_FindField('wait');check(scratch&&scratch.ofs!==death.ofs,'loaded QC offers independent scalar fixture slot');const scratchValue=enemy._fieldAccessor.getFloat(scratch.ofs),infectedDef={type:2,ofs:scratch.ofs,s_name:ED_NewString('infected')};const evict=()=>{GetEdictFieldValue(enemy,'origin');GetEdictFieldValue(enemy,'angles');};let bridgeClock=host.realtime+10;const active=()=>{bestiary.R_BestiaryCancel();bestiary.R_BestiaryFrame(bridgeClock+=1);poseCamera(p,goal);check(bestiary.R_BestiaryAllowed(),'native adapter scope remains admitted');};let functions=original.functions.slice();const callback=name=>{const index=functions.length;functions.push({...original.functions[original.death],s_name:ED_NewString(name)});return index;};const infected=callback('knight_infected_die'),sleeper=callback('boss_final_death1');progs.PR_SetFunctions(functions);
 try{
  check(bestiary.R_BestiarySnapshot().unlocked.includes('knight'),'ordinary knight already discovered is a negative-control identity');check(!GetEdictFieldValue(enemy,'infected'),'base program really lacks infected field');death.accessor.setInt32(death.ofs,infected);active();check(!observe(ent),'callback name without actual infected field stays base knight');check(!bestiary.R_BestiarySnapshot().unlocked.includes('infected_knight'),'missing field cannot grant infected page');
  progs.PR_SetFieldDefs([...original.defs,infectedDef]);progs.progs.numfielddefs=original.count+1;evict();const field=GetEdictFieldValue(enemy,'infected');check(field&&field.ofs===scratch.ofs,'public lookup resolves declared typed extension');field.accessor.setFloat(field.ofs,1);death.accessor.setInt32(death.ofs,original.death);active();check(!observe(ent),'infected float with ordinary death callback remains base knight');check(!bestiary.R_BestiarySnapshot().unlocked.includes('infected_knight'),'wrong callback never grants variant');death.accessor.setInt32(death.ofs,infected);active();check(observe(ent),'real typed callback plus extended float unlocks infected through native observation');same(bestiary.R_BestiarySnapshot().entry.id,'infected_knight','adapter resolves actual callback index to its program string');
  // The same visible native alias/edict is an adapter transport fixture for
  // the boss metadata tuple; this does not claim a Dawn boss encounter or AI.
  enemy.v.classname=ED_NewString('monster_boss');enemy.v.model=ED_NewString('progs/boss.mdl');field.accessor.setFloat(field.ofs,0);death.accessor.setInt32(death.ofs,original.death);active();check(observe(ent),'ordinary boss tuple admits original Chthon control');same(bestiary.R_BestiarySnapshot().entry.id,'chthon','wrong callback retains earlier supplied Chthon page');death.accessor.setInt32(death.ofs,sleeper);active();check(observe(ent),'actual th_die index distinguishes confirmed Sleeper callback');same(bestiary.R_BestiarySnapshot().entry.id,'chthon_sleeper','correct native callback selects separate Sleeper folio');console.log('BESTIARY_NATIVE_FIELD_BRIDGE '+JSON.stringify({thDieOffset:death.ofs,infectedFixtureOffset:scratch.ofs,nativeThDieProperty:typeof enemy.v.th_die,infectedCallbackIndex:infected,sleeperCallbackIndex:sleeper,programFunctions:original.functions.length}));
 }finally{bestiary.R_BestiaryCancel();enemy.v.classname=original.classname;enemy.v.model=original.model;death.accessor.setInt32(death.ofs,original.death);enemy._fieldAccessor.setFloat(scratch.ofs,scratchValue);progs.PR_SetFunctions(original.functions);progs.PR_SetFieldDefs(original.defs);progs.progs.numfielddefs=original.count;evict();}
 await game('e1m2');same(GetEdictFieldValue(svs.clients[0].edict,'infected'),null,'native program reload removes temporary optional-field declaration');check(!progs.pr_functions.some(f=>text(f.s_name)==='knight_infected_die'||text(f.s_name)==='boss_final_death1'),'native reload removes test callback-name additions');const clean=clearPair(svs.clients[0].edict,'knight',true),cleanEnt=drawEnemy(clean);poseCamera(svs.clients[0].edict,centreOf(clean));check(!observe(cleanEnt),'reloaded ordinary knight remains known base identity, not another variant');bestiary.R_BestiaryCancel();acknowledge();CL_Disconnect_f();
});


Deno.test('public native observation transports Guardian owners and refreshes program-specific statue and Hell Spawn capability gates',async()=>{
 const p=await game('e1m2'),enemy=clearPair(p,'knight',true),ent=drawEnemy(enemy),goal=centreOf(enemy),original={functions:progs.pr_functions,classname:enemy.v.classname,model:enemy.v.model,owner:enemy.v.owner,skin:enemy.v.skin,flags:enemy.v.spawnflags};let clock=host.realtime+20,functions=original.functions.slice();const active=()=>{bestiary.R_BestiaryCancel();bestiary.R_BestiaryFrame(clock+=1);poseCamera(p,goal);check(bestiary.R_BestiaryAllowed(),'real local scope admitted');};const stage=(classname,model,{owner=0,skin=0,flags=0}={})=>{enemy.v.classname=ED_NewString(classname);enemy.v.model=ED_NewString(model);enemy.v.owner=owner;enemy.v.skin=skin;enemy.v.spawnflags=flags;active();};const positive=id=>{check(observe(ent),'native metadata tuple must discover '+id);same(bestiary.R_BestiarySnapshot().entry.id,id,'public adapter selected exact identity');};const capability=name=>{functions=[...functions,{...original.functions[0],s_name:ED_NewString(name)}];progs.PR_SetFunctions(functions);};
 // Metadata transport fixture retains a real native edict, posed alias, local
 // connection and BSP sightline. Variant programs/AI are not executed here.
 try{
  stage('monster_knight','progs/knight.mdl',{skin:1,flags:2});check(!observe(ent),'stock QC does not reinterpret flags and skin as statue');capability('knight_pause');active();check(!observe(ent),'one statue routine alone is insufficient');capability('hknight_pause');active();positive('statue_knight');
  stage('monster_tarbaby','progs/tarbaby.mdl',{skin:1});positive('spawn'); // Base type was not encountered by the prior native cases.
  active();check(!observe(ent),'skin alone in stock-capability program remains known base Spawn');capability('tbaby_mitosis');active();positive('hell_spawn');
  stage('monster_morph','progs/morph_gr.mdl',{owner:p.index});same(enemy.v.owner,p.index,'owner travels through actual typed entvars slot');positive('guardian');stage('monster_morph','progs/morph_gr.mdl',{owner:0});positive('quakes_guardian');stage('monster_morph','progs/morph_eg.mdl',{owner:0});positive('egyptian_guardian');stage('monster_morph','progs/morph_az.mdl',{owner:0});positive('quakes_high_priest');
  progs.PR_SetFunctions(original.functions);stage('monster_hell_knight','progs/hknight.mdl',{skin:1,flags:2});positive('death_knight');check(!bestiary.R_BestiarySnapshot().unlocked.includes('statue_death_knight'),'restored stock program cannot inherit prior statue capability cache');console.log('BESTIARY_NATIVE_CAPABILITY_BRIDGE '+JSON.stringify({nativeOwner:p.index,guardianOwnerZero:0,requiresBothStatueRoutines:true,hellSpawnRoutine:'tbaby_mitosis',stockProgramRestored:true}));
 }finally{bestiary.R_BestiaryCancel();progs.PR_SetFunctions(original.functions);enemy.v.classname=original.classname;enemy.v.model=original.model;enemy.v.owner=original.owner;enemy.v.skin=original.skin;enemy.v.spawnflags=original.flags;}
 acknowledge();CL_Disconnect_f();
});

Deno.test('restore bestiary native fixture boundaries',()=>{bestiary.R_BestiaryCancel();acknowledge();CL_Disconnect_f();if(storageDescriptor)Object.defineProperty(globalThis,'localStorage',storageDescriptor);else delete globalThis.localStorage;});
