import '../src/newer/install.js'; // Newer Game plugs into the engine's hooks (src/engine/common/hooks.js)
// Real public book/menu and glyph pipeline, without starting a gameplay map.
await import('../src/engine/render/gl_rsurf.js');
const [draw,menu,cmd,keys,pak,wad,vidModule,bestiary]=await Promise.all(['engine/render/gl_draw','engine/client/menu','engine/common/cmd','engine/client/keys','engine/common/pak','engine/common/wad','engine/render/vid','newer/ui/r_bestiary'].map(n=>import('../src/'+n+'.js')));
const canvas=document.querySelector('#book'),ctx=canvas.getContext('2d'),report=document.querySelector('#report'),vid={width:innerWidth,height:innerHeight};
const bytes=await(await fetch('../games/shareware/pak0.pak')).arrayBuffer();pak.COM_AddPack(pak.COM_LoadPackFile('book-nav-trial',bytes));
const gfx=pak.COM_FindFile('gfx.wad').data;wad.W_LoadWadFile(gfx.buffer.slice(gfx.byteOffset,gfx.byteOffset+gfx.byteLength));const palette=pak.COM_FindFile('gfx/palette.lmp').data;vidModule.VID_SetPalette(palette);
draw.Draw_SetExternals({vid,host_basepal:palette});cmd.Cbuf_Init();cmd.Cmd_Init();draw.Draw_Init(canvas);menu.M_Init();let destination=keys.key_game;
menu.M_SetExternals({vid,key_dest_get:()=>destination,key_dest_set:v=>{destination=v;},cls:{demonum:-1},Draw_CachePic:draw.Draw_CachePic,Draw_TransPic:draw.Draw_TransPic,Draw_Pic:draw.Draw_Pic,Draw_Character:draw.Draw_Character,Draw_FadeScreen(){},S_LocalSound(){}});
let footer=[],frame=0,errors=[],receipt={},lastTouch=null;const nativeDraw=ctx.drawImage.bind(ctx);
ctx.drawImage=(image,...args)=>{const entry=Object.entries(draw.Draw_CacheBookNavigation()||{}).find(([,pic])=>pic.canvas===image);if(entry)footer.push({label:entry[0],rect:args,alpha:ctx.globalAlpha,smoothing:ctx.imageSmoothingEnabled});return nativeDraw(image,...args);};
window.addEventListener('error',e=>errors.push(e.message));window.addEventListener('unhandledrejection',e=>errors.push(String(e.reason)));
function resize(){vid.width=innerWidth;vid.height=innerHeight;canvas.width=Math.floor(vid.width*devicePixelRatio);canvas.height=Math.floor(vid.height*devicePixelRatio);}resize();addEventListener('resize',resize);
function render(){footer=[];draw.Draw_BeginFrame();menu.M_Draw();receipt={frame:++frame,state:menu.m_state===menu.m_bestiary?'book':'main',viewport:[vid.width,vid.height],dpr:devicePixelRatio,footer,lastTouch,errors};report.textContent=JSON.stringify(receipt,null,2);requestAnimationFrame(render);}
function key(k){menu.M_Keydown(k);}document.querySelector('#cover').onclick=()=>cmd.Cmd_ExecuteString('menu_bestiary');document.querySelector('#previous').onclick=()=>key(keys.K_LEFTARROW);document.querySelector('#next').onclick=()=>key(keys.K_RIGHTARROW);document.querySelector('#last').onclick=()=>{let presses=2+bestiary.R_BestiarySpreads().length;const step=()=>{if(presses-->0){key(keys.K_RIGHTARROW);setTimeout(step,450);}};step();} /* (a press during a turn is ignored, card [7]: one press a turn, 2 + one per family spread) */;document.querySelector('#exit').onclick=()=>key(keys.K_ESCAPE);
canvas.addEventListener('click',e=>{lastTouch={x:e.offsetX,y:e.offsetY,width:vid.width,height:vid.height};menu.M_TouchInput(e.offsetX,e.offsetY,vid.width,vid.height);});addEventListener('keydown',e=>{if(e.target.tagName==='BUTTON')return;const k={ArrowLeft:keys.K_LEFTARROW,ArrowRight:keys.K_RIGHTARROW,Enter:keys.K_ENTER,Escape:keys.K_ESCAPE}[e.key];if(k!==undefined){e.preventDefault();key(k);}});
document.querySelector('#capture').onclick=async()=>{const image=new Image();image.id='proof';image.src=canvas.toDataURL();image.onclick=()=>image.remove();document.body.append(image);if(new URLSearchParams(location.search).has('evidence')){const result=await fetch('/__book_capture',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:image.src,receipt})});if(!result.ok)throw Error('Evidence capture failed');}};
cmd.Cmd_ExecuteString('menu_bestiary');render();
