// Independent public progress/timing contracts. Native visibility, host-clock,
// input and render-camera checks follow through the runtime public interface.
import {BESTIARY_ENTRIES,BestiaryJournal,BestiaryEncounter,Bestiary_Identify,BESTIARY_COLLECTION_IDS} from '../src/bestiary_state.js';
const check=(v,m)=>{if(!v)throw Error(m);},same=(a,b,m)=>check(a===b,`${m}: ${a} != ${b}`),near=(a,b,m,e=1e-9)=>check(Math.abs(a-b)<=e,`${m}: ${a} != ${b}`);
const ids=['dog','grunt','enforcer','knight','death_knight','rotfish','zombie','scrag','ogre','spawn','fiend','vore','shambler','chthon','shub','centroid','electric_eel','phantom_swordsman','multi_grenade_ogre','chthon_sleeper','shub_awakened','splitting_spawn','infected_death_knight','overlord','infected_enforcer','egyptian_guardian','dragon','infected_knight','infected_grunt','ranged_death_knight','demo_dog','mummy','statue_knight','statue_death_knight','rocket_ogre','gremlin','blood_shambler','hell_spawn','wrath','spike_mine','orb','armagon','hephaestus','chthon_vengeance','guardian','quakes_guardian','quakes_high_priest'];
const collection='grunt,infected_grunt,enforcer,infected_enforcer,knight,infected_knight,death_knight,ranged_death_knight,infected_death_knight,dog,demo_dog,rotfish,electric_eel,dragon,zombie,mummy,phantom_swordsman,statue_knight,statue_death_knight,scrag,ogre,multi_grenade_ogre,rocket_ogre,fiend,gremlin,vore,shambler,blood_shambler,spawn,hell_spawn,splitting_spawn,wrath,overlord,centroid,spike_mine,orb,armagon,hephaestus,chthon,chthon_vengeance,chthon_sleeper,guardian,quakes_guardian,egyptian_guardian,quakes_high_priest,shub,shub_awakened'.split(',');
const entry=id=>BESTIARY_ENTRIES.find(e=>e.id===id);
function memory(){const values=new Map(),calls=[];return{values,calls,getItem:key=>values.get(key)??null,setItem:(key,value)=>{calls.push([key,value]);values.set(key,String(value));}};}
Deno.test('bestiary catalog preserves fifteen base-game identities and appends supplied folios without changing prior identities or printed numbering',()=>{
 same(BESTIARY_ENTRIES.map(e=>e.id).join(),ids.join(),'literal complete enemy catalog in folio order');same(BESTIARY_ENTRIES.map(e=>e.folio).join(),[...Array.from({length:15},(_,i)=>i+1),16,20,21,22,46,47,45,44,29,43,32,34,42,41,40,37,28,26,27,36,17,38,23,24,18,39,19,30,35,25,31,33].join(),'authored folio numbers retain gaps17 through19');
 same(BESTIARY_ENTRIES.filter(e=>e.image).map(e=>e.id).sort().join(),[...ids].sort().join(),'all forty-seven entries have supplied canonical artwork');for(const e of BESTIARY_ENTRIES)same(e.image,e.id==='dog'?'rottweiler.png':e.id.replaceAll('_','-')+'.png','exact corresponding creature illustration '+e.id);
 const classes=['monster_dog','monster_army','monster_enforcer','monster_knight','monster_hell_knight','monster_fish','monster_zombie','monster_wizard','monster_ogre','monster_tarbaby','monster_demon1','monster_shalrath','monster_shambler','monster_boss','monster_oldone'];same(BESTIARY_ENTRIES.filter(e=>!e.image).map(e=>e.id).join(),'','every catalog entry now has supplied artwork');BESTIARY_ENTRIES.forEach((e,i)=>{if(i<15)check(e.classes.includes(classes[i]),'actual native monster identity '+classes[i]);check(typeof e.title==='string'&&e.title.length>0,'every locked or pending entry has a title');check(!('description'in e)&&!('lore'in e)&&!('stats'in e),'missing pages do not invent descriptive information');});
});
Deno.test('journal persists exact known discoveries across instances and merges independent tabs without replacing earlier progress',()=>{
 const store=memory(),a=new BestiaryJournal({storage:()=>store}),b=new BestiaryJournal({storage:()=>store});same(a.unlock('dog'),true,'first actual type is newly discovered');same(a.unlock('dog'),false,'repeat type is not another discovery');same(store.calls.length,1,'repeat type does not rewrite storage');same(b.unlock('knight'),true,'second tab discovers another type');a.reload();same(a.snapshot().unlocked.join(),'dog,knight','current tab merges stored union');same(new BestiaryJournal({storage:()=>store}).snapshot().unlocked.join(),'dog,knight','new run reads both discoveries');same(b.unlock('dog'),false,'another tab cannot rediscover already stored type');same(a.unlock('not-an-enemy'),false,'unknown identity never unlocks');same(a.unlock('__proto__'),false,'prototype-like string is not an enemy');same(a.snapshot().unlocked.join(),'dog,knight','invalid IDs cannot pollute persisted progress');same(a.snapshot().storageStatus,'ready','normal browser storage is healthy');
});
Deno.test('expanded classifier recognizes verified classes while requiring every Rogue multi-grenade discriminator',()=>{
 for(const[classname,id]of[['monster_scourge','centroid'],['monster_eel','electric_eel'],['monster_sword','phantom_swordsman']])same(Bestiary_Identify(classname)?.id,id,'verified expansion classname '+classname);
 const rogue={rogueOgre:true,spawnflags:2,model:'progs/ogre.mdl',skin:1};same(Bestiary_Identify('monster_ogre',rogue)?.id,'multi_grenade_ogre','verified Rogue model/skin/flag classification');
 for(const options of[{}, {...rogue,rogueOgre:false},{...rogue,spawnflags:0},{...rogue,model:'progs/custom_ogre.mdl'},{...rogue,skin:0}])same(Bestiary_Identify('monster_ogre',options)?.id,'ogre','each missing discriminator preserves ordinary Ogre identity');
 same(Bestiary_Identify('monster_ogre',{...rogue,spawnflags:3})?.id,'multi_grenade_ogre','unrelated additional spawnflags do not hide verified variant');same(Bestiary_Identify('monster_ogre_marksman',rogue)?.id,'ogre','marksman is not invented multi-grenade alias');for(const name of['monster_centroid','monster_electric_eel','monster_phantom','monster_multi_ogre','unknown'])same(Bestiary_Identify(name,rogue),null,'unverified names cannot unlock pages '+name);
 const store=memory();store.values.set('quaked.bestiary.v1',JSON.stringify({version:1,unlocked:['dog','ogre','spawn','chthon','shub','unknown']}));const journal=new BestiaryJournal({storage:()=>store});same(journal.snapshot().unlocked.join(),'dog,ogre,spawn,chthon,shub','expanded catalog reads existing version1 identities without renumbering');journal.unlock('electric_eel');const saved=JSON.parse(store.values.get('quaked.bestiary.v1'));same(saved.version,1,'existing persistence format retained');check(saved.unlocked.includes('dog')&&saved.unlocked.includes('electric_eel'),'new page merges with old discoveries');check(!saved.unlocked.includes('unknown'),'unknown legacy strings never acquire new identities');
});
Deno.test('malformed or unsupported journal records never unlock unknown pages and cannot erase already known in-memory progress',()=>{
 for(const value of['not json','null','{}',JSON.stringify({version:2,unlocked:['dog']}),JSON.stringify({version:1,unlocked:'dog'}),JSON.stringify({version:1,unlocked:['dog',7]})]){const store=memory();store.values.set('quaked.bestiary.v1',value);const journal=new BestiaryJournal({storage:()=>store});same(journal.snapshot().unlocked.length,0,'invalid typed record grants no discoveries');same(store.calls.length,0,'reading malformed data never destroys stored input');}
 const store=memory(),journal=new BestiaryJournal({storage:()=>store});journal.unlock('dog');store.values.set('quaked.bestiary.v1','broken');journal.reload();same(journal.snapshot().unlocked.join(),'dog','failed reload retains existing session progress');store.values.set('quaked.bestiary.v1',JSON.stringify({version:1,unlocked:['knight','unknown','__proto__']}));journal.reload();same(journal.snapshot().unlocked.join(),'dog,knight','known IDs merge while unknown IDs are excluded');
});
Deno.test('unavailable or quota-limited storage keeps current-play discoveries usable without throwing or crossing storage origins',()=>{
 const unavailable=new BestiaryJournal({storage:()=>{throw Error('storage disabled');}});same(unavailable.unlock('zombie'),true,'discovery still works in current play');check(unavailable.has('zombie'),'current-play progress remains available');same(unavailable.snapshot().storageStatus,'unavailable','persistence limitation is explicit');
 const store=memory();store.setItem=()=>{throw Error('quota');};const quota=new BestiaryJournal({storage:()=>store});same(quota.unlock('scrag'),true,'quota cannot interrupt encounter');check(quota.has('scrag'),'failed save never removes newly discovered type');same(quota.snapshot().storageStatus,'unavailable','quota failure visible');
 const first=memory(),second=memory();new BestiaryJournal({storage:()=>first}).unlock('fiend');same(new BestiaryJournal({storage:()=>second}).snapshot().unlocked.length,0,'separate origin storage cannot inherit another profile');same(new BestiaryJournal({storage:()=>first,key:'separate-profile'}).snapshot().unlocked.length,0,'explicit namespace remains isolated');
});
Deno.test('encounter cancellation cannot clear journal progress and reloading a run preserves discoveries when artwork becomes available',()=>{
 const store=memory(),journal=new BestiaryJournal({storage:()=>store}),encounter=new BestiaryEncounter();journal.unlock('ogre');for(let i=0;i<5;i++){encounter.start(entry('ogre'),i);encounter.cancel();journal.reload();same(journal.snapshot().unlocked.join(),'ogre','transient encounter cleanup never resets persistent progress');}same(typeof journal.reset,'undefined','journal has no accidental new-map reset API');const next=new BestiaryJournal({storage:()=>store});check(next.has('ogre')&&entry('ogre').image==='ogre.png','existing discovery recognizes newly supplied Ogre art without rewriting identity');
});
Deno.test('encounter decelerates boundedly before holding and remains fully paused through the camera return',()=>{
 const encounter=new BestiaryEncounter({random:()=>0});check(encounter.start(entry('dog'),0),'idle controller admits encounter');same(encounter.snapshot().phase,'enter','starts entering');same(encounter.snapshot().scale,1,'initial native simulation speed preserved');let previous=1;for(const time of[.05,.15,.275,.4,.549,.55,.65,.749]){const s=encounter.tick(time);check(s.scale>=0&&s.scale<=previous,'simulation scale decreases monotonically within bounds');check(s.progress>=0&&s.progress<=1&&s.opacity>=0&&s.opacity<=1,'camera/page interpolation stays bounded');previous=s.scale;if(time===.55)near(s.scale,0,'physics reaches zero by550ms');}const hold=encounter.tick(.75);same(hold.phase,'hold','camera/page settle before hold');same(hold.scale,0,'hold freezes simulation');same(hold.opacity,1,'held page fully visible');for(const time of[1,20,100])same(encounter.tick(time).phase,'hold','hold never dismisses on a timeout');check(encounter.dismiss(100),'fresh dismissal accepted in hold');same(encounter.snapshot().phase,'return','camera returns instead of snapping');for(const time of[100.01,100.2,100.449])same(encounter.tick(time).scale,0,'simulation remains frozen until camera returns');const done=encounter.tick(100.451);same(done.phase,'idle','return completes after450ms');same(done.scale,1,'native time resumes only after return');same(done.opacity,0,'encounter page retired');
});
Deno.test('card [1] review: the page\'s own clocks: t in each phase, paused from the moment the game stops (.55 s into the enter), carried unchanged through the dismissal\'s fade',()=>{
 const e=new BestiaryEncounter({random:()=>0});e.start(entry('dog'),10);
 let s=e.tick(10.3);near(s.t,.3,'enter t',1e-9);same(s.paused,0,'not yet stopped');
 s=e.tick(10.55);near(s.paused,0,'the game stops at .55',1e-9);s=e.tick(10.7);near(s.paused,.15,'paused counts from .55',1e-9);
 s=e.tick(10.75);same(s.phase,'hold','hold');same(s.t,0,'hold t restarts');near(s.paused,.2,'paused continuous into the hold (.75-.55)',1e-9);
 s=e.tick(11.75);near(s.paused,1.2,'paused counts on through the hold',1e-9);
 e.dismiss(11.75);s=e.tick(11.9);same(s.phase,'return','returning');near(s.paused,1.2,'the drawing stays where it had got while the page fades',1e-9);
});
Deno.test('encounter rejects early dismissal and reentry, chooses both sides, and cancellation restores time without changing progress',()=>{
 for(const[value,side]of[[0,'left'],[.999999,'right']]){const encounter=new BestiaryEncounter({random:()=>value});check(!encounter.start(null,0),'missing enemy does not enter');check(!encounter.start({id:'unknown'},0),'uncatalogued enemy does not enter');check(encounter.start(entry('knight'),0),'valid entry admitted');same(encounter.snapshot().side,side,'random side bound');check(!encounter.start(entry('dog'),.1),'active encounter cannot be replaced by another visible enemy');check(!encounter.dismiss(.1),'entering key cannot queue dismissal');same(encounter.tick(.75).phase,'hold','early dismissal stays discarded');check(encounter.dismiss(.8),'hold accepts dismissal');check(!encounter.dismiss(.9),'dismissal is not reentrant');check(!encounter.start(entry('dog'),1),'returning camera still owns encounter');encounter.cancel();same(encounter.snapshot().phase,'idle','cancellation retires ownership');same(encounter.snapshot().scale,1,'cancel always releases simulation hold');same(encounter.snapshot().entry,null,'cancel releases old enemy reference');check(encounter.start(entry('dog'),2),'next actual discovery can start after cleanup');}
});

Deno.test('completion requires all forty-seven supplied collection identities rather than a partial catalog or forty-six plus an unknown',()=>{
 same(BESTIARY_COLLECTION_IDS.join(),collection.join(),'literal supplied Contents collection order');same(new Set(BESTIARY_COLLECTION_IDS).size,47,'every required identity unique');const store=memory(),journal=new BestiaryJournal({storage:()=>store});for(const id of ids.slice(0,28))journal.unlock(id);same(journal.complete(),false,'all twenty-eight display entries are not full collection');for(const id of collection.filter(id=>id!=='infected_grunt'))journal.unlock(id);same(journal.snapshot().unlocked.length,46,'all forty-six distinct known discoveries retained, including future types');same(journal.unlock('unknown_forty_seventh'),false,'unknown cannot substitute for final known type');same(journal.complete(),false,'forty-six plus unknown remains incomplete');same(journal.unlock('infected_grunt'),true,'last supplied identity admitted');same(journal.complete(),true,'exact forty-seven completes collection');same(journal.unlock('infected_grunt'),false,'repeated final identity is not new');same(new BestiaryJournal({storage:()=>store}).complete(),true,'completion survives real version1 serialization and reload');same(new BestiaryJournal({storage:()=>store}).snapshot().unlocked.length,47,'all future identities survive reload');const encounter=new BestiaryEncounter();same(encounter.start({id:'unknown_forty_eighth'},0),false,'uncatalogued identity is not a fabricated runtime encounter');
 for(const missing of collection){const subset=memory();subset.values.set('quaked.bestiary.v1',JSON.stringify({version:1,unlocked:[...collection.filter(id=>id!==missing),'unknown',collection.find(id=>id!==missing)]}));same(new BestiaryJournal({storage:()=>subset}).complete(),false,'each required type is independently necessary '+missing);}
});
Deno.test('collection completion reloads shared version1 progress and cannot erase known future identities on an unrelated discovery',()=>{
 const store=memory(),journal=new BestiaryJournal({storage:()=>store});store.values.set('quaked.bestiary.v1',JSON.stringify({version:1,unlocked:collection}));journal.reload();same(journal.complete(),true,'public reload merges other-tab completion just as it merges ordinary discoveries');const exact=store.values.get('quaked.bestiary.v1');same(store.calls.length,0,'read-only completion does not rewrite storage');same(store.values.get('quaked.bestiary.v1'),exact,'completion inspection preserves bytes');const other=memory();other.values.set('quaked.bestiary.v1',JSON.stringify({version:1,unlocked:['shub_awakened','infected_grunt']}));const later=new BestiaryJournal({storage:()=>other});later.unlock('dog');const saved=JSON.parse(other.values.get('quaked.bestiary.v1'));check(saved.unlocked.includes('shub_awakened')&&saved.unlocked.includes('infected_grunt')&&saved.unlocked.includes('dog'),'new base-game discovery preserves stored future collection types');same(saved.version,1,'no persistence migration or replacement key');
});

Deno.test('all forty-seven catalog identities preserve unique saved snapshots and bounded encounter admission',()=>{const store=memory();store.values.set('quaked.bestiary.v1',JSON.stringify({version:1,unlocked:collection}));const journal=new BestiaryJournal({storage:()=>store}),saved=journal.snapshot();same(saved.unlocked.length,47,'full collection snapshot has exactly47 rows');same(new Set(saved.unlocked).size,47,'display and collection rows never duplicate');for(const e of BESTIARY_ENTRIES){check(e.classes.length>0,'all forty-seven current folios have researched class mappings '+e.id);same(new BestiaryEncounter().start(e,0),true,'mapped folio admits its identified encounter '+e.id);}const unsupported=collection.filter(id=>!ids.includes(id));same(unsupported.length,0,'all supplied collection identities now have catalog entries');for(const id of unsupported)same(new BestiaryEncounter().start({id},0),false,'collection-only identity cannot invent an encounter '+id);for(const id of ids)check(collection.includes(id),'every display folio belongs to supplied completion list '+id);});
Deno.test('new variant folios require researched resolved models and native variant state without stealing ordinary enemies',()=>{
 const infected=[['monster_knight','progs/knight.mdl','knight_infected_die','infected_knight','knight'],['monster_enforcer','progs/enforcer.mdl','enforcer_infected_die','infected_enforcer','enforcer'],['monster_hell_knight','progs/hknight.mdl','hknight_infected_die','infected_death_knight','death_knight']];
 for(const[classname,model,deathFunction,id,ordinary]of infected){const state={model,deathFunction,infected:1};same(Bestiary_Identify(classname,state)?.id,id,'native infected callback/state identifies '+id);for(const wrong of[{}, {...state,infected:0},{...state,infected:2},{...state,model:'progs/custom.mdl'},{...state,deathFunction:'ordinary_die'}])same(Bestiary_Identify(classname,wrong)?.id,ordinary,'missing exact variant evidence preserves '+ordinary);}
 const split={model:'progs/tarbaby.mdl',slime:1,splittingSpawn:true};same(Bestiary_Identify('monster_tarbaby',split)?.id,'splitting_spawn','actual splitting capability and live slime field identify variant');for(const wrong of[{}, {...split,slime:0},{...split,slime:-1},{...split,splittingSpawn:false},{...split,model:'progs/custom.mdl'}])same(Bestiary_Identify('monster_tarbaby',wrong)?.id,'spawn','ordinary Spawn is not attributed to variant');
 for(const[classname,model,id]of[['monster_oldone_new','progs/oldone.mdl','shub_awakened'],['monster_super_wrath','progs/s_wrath.mdl','overlord'],['monster_dragon','progs/dragon.mdl','dragon'],['monster_morph','progs/morph_eg.mdl','egyptian_guardian']]){same(Bestiary_Identify(classname,{model})?.id,id,'unique class plus actual model '+id);same(Bestiary_Identify(classname),null,'classname alone is insufficient '+id);same(Bestiary_Identify(classname,{model:'progs/custom.mdl'}),null,'incorrect resolved model cannot unlock '+id);}
 same(Bestiary_Identify('monster_dragon_dead',{model:'progs/dragon.mdl'}),null,'death-only Dragon class never unlocks living page');same(Bestiary_Identify('monster_morph',{spawnflags:6,model:'progs/morph_az.mdl'})?.id,'quakes_high_priest','Aztec-resolved overlapping flags select High Priest instead of Egyptian Guardian');same(Bestiary_Identify('monster_morph',{spawnflags:6,model:'progs/morph_eg.mdl'})?.id,'egyptian_guardian','resolved Egyptian model also identifies native children');same(Bestiary_Identify('monster_oldone',{model:'progs/oldone.mdl'})?.id,'shub','original Shub remains original identity');same(Bestiary_Identify('monster_boss',{model:'progs/boss.mdl',deathFunction:'boss_final_death1'})?.id,'chthon_sleeper','confirmed final-death callback identifies distinct Sleeper');for(const state of[{}, {model:'progs/boss.mdl'},{model:'progs/boss.mdl',deathFunction:'boss_death1'},{model:'progs/custom.mdl',deathFunction:'boss_final_death1'}])same(Bestiary_Identify('monster_boss',state)?.id,'chthon','missing exact Sleeper evidence preserves original Chthon');
});

Deno.test('final folios classify actual resolved native variants while rejecting unverified aliases and missing capabilities',()=>{
 const unique=[['monster_ranged_knight','progs/rknight.mdl','ranged_death_knight'],['monster_mummy','progs/mummy.mdl','mummy'],['monster_gremlin','progs/grem.mdl','gremlin'],['monster_super_shambler','progs/shambler_blood.mdl','blood_shambler'],['monster_wrath','progs/wrath.mdl','wrath'],['monster_orb','progs/teleporter_eye_blink.mdl','orb'],['monster_armagon','progs/armalegs.mdl','armagon'],['monster_lava_man','progs/lavaman.mdl','hephaestus']];for(const[classname,model,id]of unique){same(Bestiary_Identify(classname,{model})?.id,id,'verified unique class/model '+id);same(Bestiary_Identify(classname,{model:'progs/custom.mdl'}),null,'wrong model cannot unlock '+id);}
 const infected={model:'progs/soldier.mdl',infected:1,deathFunction:'army_infected_die'};same(Bestiary_Identify('monster_army',infected)?.id,'infected_grunt','native callback identifies infected Grunt');for(const wrong of[{...infected,infected:0},{...infected,deathFunction:'army_die'},{...infected,model:'progs/custom.mdl'}])same(Bestiary_Identify('monster_army',wrong)?.id,'grunt','ordinary Grunt retains identity without full variant evidence');
 same(Bestiary_Identify('monster_dog',{model:'progs/dog_explosive.mdl',deathFunction:'demodog_die'})?.id,'demo_dog','actual explosive dog model and callback');same(Bestiary_Identify('monster_dog',{model:'progs/dog_explosive.mdl'})?.id,'dog','model without verified callback stays original Dog');same(Bestiary_Identify('monster_ogre',{model:'progs/ogre_rocket.mdl'})?.id,'rocket_ogre','resolved Rocket Ogre model precedes base fallback');
 for(const[classname,model,id,base]of[['monster_knight','progs/knight.mdl','statue_knight','knight'],['monster_hell_knight','progs/hknight.mdl','statue_death_knight','death_knight']]){const state={model,skin:1,spawnflags:2,rogueStatues:true};same(Bestiary_Identify(classname,state)?.id,id,'actual statue capability and resolved fields');for(const wrong of[{...state,rogueStatues:false},{...state,skin:0},{...state,spawnflags:0},{...state,model:'progs/custom.mdl'}])same(Bestiary_Identify(classname,wrong)?.id,base,'missing statue evidence preserves base identity');}
 for(const skin of[1,2])same(Bestiary_Identify('monster_tarbaby',{model:'progs/tarbaby.mdl',skin,hellSpawn:true})?.id,'hell_spawn','Hell Spawn retains native colour while pain callback is temporarily disabled');for(const state of[{model:'progs/tarbaby.mdl',skin:1},{model:'progs/tarbaby.mdl',skin:0,hellSpawn:true},{model:'progs/tarbaby.mdl',skin:3,hellSpawn:true},{model:'progs/custom.mdl',skin:1,hellSpawn:true}])same(Bestiary_Identify('monster_tarbaby',state)?.id,'spawn','missing exact Hell Spawn evidence stays base');
 same(Bestiary_Identify('monster_boss',{model:'progs/boss.mdl',spawnflags:2,deathFunction:'boss_death1'})?.id,'chthon_vengeance','second form is separate Vengeance');same(Bestiary_Identify('monster_boss',{model:'progs/boss.mdl',spawnflags:2,deathFunction:'boss_final_death1'})?.id,'chthon_sleeper','final callback wins over earlier second-form flag');same(Bestiary_Identify('monster_boss',{model:'progs/boss.mdl',spawnflags:2})?.id,'chthon','flag alone cannot rename original Chthon');
 same(Bestiary_Identify('trap_spike_mine',{model:'progs/spikmine.mdl',deathFunction:'spikemine_Touch'})?.id,'spike_mine','actual map trap class and callback identify mine');same(Bestiary_Identify('trap_spike_mine',{model:'progs/spikmine.mdl'}),null,'decorative trap without death callback excluded');same(Bestiary_Identify('monster_spikemine',{model:'progs/spikmine.mdl',deathFunction:'spikemine_Touch'}),null,'unverified placeholder monster alias excluded');
});
Deno.test('native Guardian ownership distinguishes all lesser forms from resolved bosses without health or spawnflag guesses',()=>{
 for(const[model,boss]of[['progs/morph_eg.mdl','egyptian_guardian'],['progs/morph_gr.mdl','quakes_guardian'],['progs/morph_az.mdl','quakes_high_priest']]){same(Bestiary_Identify('monster_morph',{model,owner:0})?.id,boss,'world-owned resolved boss '+boss);for(const owner of[1,137])same(Bestiary_Identify('monster_morph',{model,owner,skin:3,spawnflags:14,health:1})?.id,'guardian','summoned owner dominates changing appearance or damage');same(Bestiary_Identify('monster_morph',{model,owner:-1}),null,'invalid owner cannot guess boss identity');}same(Bestiary_Identify('monster_morph',{model:'progs/custom.mdl',owner:1}),null,'unknown model not promoted by owner');
});
