// Pixel-level independent oracle for the authored five-piece reveal. The
// registered guide was checked separately against its red strokes; these
// literal boundaries are independent of the compositor's exported polygons.
import {readFileSync,readdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {BESTIARY_ENTRIES,BestiaryJournal} from '../src/bestiary_state.js';
import {BESTIARY_FRONTISPIECE_PIECES,Bestiary_ComposeFrontispiece,Bestiary_FrontispieceMask,Bestiary_HeaderHeight} from '../src/bestiary_art.js';
const canvasAPI=await import(process.env.QUAKED_CANVAS_MODULE||'/Users/bri/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/@napi-rs/canvas/index.js');
const check=(v,m)=>{if(!v)throw Error(m);},same=(a,b,m)=>check(a===b,`${m}: ${a} != ${b}`),base=new URL('../newer/bestiary/',import.meta.url),ids=['scrag','shambler','ogre','fiend','vore'];
const blank=await canvasAPI.loadImage(readFileSync(new URL('frontispiece-blank.png',base))),clean=await canvasAPI.loadImage(readFileSync(new URL('frontispiece.png',base)));
const raster=image=>{if(image.getContext)return image.getContext('2d').getImageData(0,0,image.width,image.height).data;const c=canvasAPI.createCanvas(image.width,image.height),ctx=c.getContext('2d');ctx.drawImage(image,0,0);return ctx.getImageData(0,0,c.width,c.height).data;};
Deno.test('frontispiece registration uses five literal authored IDs and preserves exact supplied blank and clean endpoints',()=>{
 const expected=[{id:'scrag',polygon:[[0,0],[.174,0],[.378,.43915],[0,.43915]]},{id:'shambler',polygon:[[.174,0],[.814,0],[.634,.43915],[.378,.43915]]},{id:'ogre',polygon:[[.814,0],[1,0],[1,.43915],[.634,.43915]]},{id:'fiend',polygon:[[0,.58201],[.5,.58201],[.5,1],[0,1]]},{id:'vore',polygon:[[.5,.58201],[1,.58201],[1,1],[.5,1]]}];same(JSON.stringify(BESTIARY_FRONTISPIECE_PIECES),JSON.stringify(expected),'registered source-page polygons');same(createHash('sha256').update(readFileSync(new URL('frontispiece-blank.png',base))).digest('hex'),'fa32d63bce28d06ae2ee71909b3f7a1c538457675a7a94eed3c121b4bdbb926b','original blank illustration unchanged');same(createHash('sha256').update(readFileSync(new URL('frontispiece.png',base))).digest('hex'),'e15133f6202ece71164da0f5a51a46355e27fcabe43594d730a51e2ea02fa5a6','new clean illustration unchanged');let allocated=0;const make=()=>{allocated++;return canvasAPI.createCanvas(1,1);};same(Bestiary_ComposeFrontispiece(blank,clean,[],make),blank,'zero discoveries returns exact blank');same(Bestiary_ComposeFrontispiece(blank,clean,ids,make),clean,'all five returns exact clean, including its different title band');same(allocated,0,'complete endpoints allocate no derived bitmap');same(Bestiary_FrontispieceMask(['multi_grenade_ogre','rocket_ogre','infected_grunt','unknown']),0,'related variants and unrelated enemies cannot reveal a fragment');same(Bestiary_FrontispieceMask(['ogre','ogre']),4,'base Ogre alone reveals only its own piece once');
});
Deno.test('all thirty-two reveal combinations preserve every interior pixel outside exactly the independently registered unlocked pieces',()=>{
 const width=1024,height=1536,a=raster(blank),b=raster(clean),groups=Array.from({length:6},()=>[]),top=.43915*height,bottom=.58201*height,left0=.174*width,leftSlope=(.378-.174)*width/top,right0=.814*width,rightSlope=(.634-.814)*width/top;let excluded=0;
 for(let y=0;y<height;y++)for(let x=0;x<width;x++){const px=x+.5,py=y+.5;let group=0,edge=Math.min(Math.abs(py-top),Math.abs(py-bottom));if(py<top){const left=left0+leftSlope*py,right=right0+rightSlope*py;edge=Math.min(edge,Math.abs(px-left)/Math.hypot(1,leftSlope),Math.abs(px-right)/Math.hypot(1,rightSlope));group=px<left?1:px>right?3:2;}else if(py>bottom){edge=Math.min(edge,Math.abs(px-width*.5));group=px<width*.5?4:5;}if(edge<=2){excluded++;continue;}groups[group].push((y*width+x)*4);}
 check(groups.every(g=>g.length>10000),'all five pieces and fixed title band have substantial independent coverage');let compared=0,changed=0;for(let mask=0;mask<32;mask++){const unlocked=ids.filter((_,i)=>mask&(1<<i)),output=Bestiary_ComposeFrontispiece(blank,clean,[...unlocked,'multi_grenade_ogre','knight'],()=>canvasAPI.createCanvas(1,1)),pixels=raster(output);same(output.width,width,'output width');same(output.height,height,'output height');for(let group=0;group<6;group++){const original=mask===31||group>0&&(mask&(1<<(group-1)))?b:a;for(const p of groups[group]){for(let k=0;k<4;k++)if(pixels[p+k]!==original[p+k])throw Error(`mask ${mask}, region ${group}, pixel ${p/4}: unexpected source component`);compared++;if(pixels[p]!==a[p]||pixels[p+1]!==a[p+1]||pixels[p+2]!==a[p+2])changed++;}}}check(changed>1000000,'unlocked illustration actually changes rendered pixels');console.log('BESTIARY_REVEAL_PIXELS '+JSON.stringify({combinations:32,comparedInteriorPixels:compared,excludedBoundaryPixelsPerCombination:excluded,changedPixels:changed}));
});
Deno.test('every locked header is an exact original top crop with original folio and no body pixels',async()=>{
 const expected=BESTIARY_ENTRIES.map(e=>e.id+'.png').sort(),actual=readdirSync(new URL('headers/',base)).filter(n=>n.endsWith('.png')).sort();same(actual.join(),expected.join(),'exactly one crop for each of47 stable identities');for(const entry of BESTIARY_ENTRIES){const original=await canvasAPI.loadImage(readFileSync(new URL(entry.image,base))),header=await canvasAPI.loadImage(readFileSync(new URL('headers/'+entry.id+'.png',base))),height=['shub_awakened','infected_death_knight','ranged_death_knight'].includes(entry.id)?240:196;same(Bestiary_HeaderHeight(entry.id),height,'literal multiline-title boundary '+entry.id);same(header.width,original.width,'header uses original full width '+entry.id);same(header.height,height,'header includes only selected original top rows '+entry.id);const hp=raster(header),op=raster(original);check(hp.every((v,i)=>v===op[i]),'original name and original folio pixels retained exactly '+entry.id);}same(createHash('sha256').update(readFileSync(new URL('entry-blank.png',base))).digest('hex'),'f11b86ba03d9fdfca4486853d91fb0901beb956f2ab01f1aec1ee840a22e7942','blank-body source unchanged');
});
Deno.test('progressive composition is read-only and honors previously persisted base discoveries without granting variants',()=>{
 const data=new Map([['quaked.bestiary.v1',JSON.stringify({version:1,unlocked:['scrag','ogre','multi_grenade_ogre']})]]),writes=[],journal=new BestiaryJournal({storage:()=>({getItem:k=>data.get(k)??null,setItem:(k,v)=>{writes.push([k,v]);data.set(k,v);}})}),before=data.get('quaked.bestiary.v1'),unlocked=journal.snapshot().unlocked;same(Bestiary_FrontispieceMask(unlocked),5,'existing Scrag and ordinary Ogre reveal only correct two pieces');Bestiary_ComposeFrontispiece(blank,clean,unlocked,()=>canvasAPI.createCanvas(1,1));same(data.get('quaked.bestiary.v1'),before,'composition never rewrites prior profile');same(writes.length,0,'composition never grants encounter progress');same(journal.complete(),false,'five-piece art does not mean all47 complete');
});
Deno.test('public frontispiece getter restores stored progress, reuses unchanged masks and reserves Complete Edition for all47 discoveries',async()=>{
 const prior={Image:Object.getOwnPropertyDescriptor(globalThis,'Image'),document:Object.getOwnPropertyDescriptor(globalThis,'document'),localStorage:Object.getOwnPropertyDescriptor(globalThis,'localStorage'),setTimeout:globalThis.setTimeout,clearTimeout:globalThis.clearTimeout},completed=await canvasAPI.loadImage(readFileSync(new URL('frontispiece-complete.png',base))),sources={'frontispiece-blank.png':blank,'frontispiece.png':clean,'frontispiece-complete.png':completed},values=new Map([['quaked.bestiary.v1',JSON.stringify({version:1,unlocked:[]})]]),requests=[],pending=[],timers=new Map(),writes=[];let serial=0;
 Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:k=>values.get(k)??null,setItem:(k,v)=>{writes.push([k,v]);values.set(k,v);}}});Object.defineProperty(globalThis,'document',{configurable:true,value:{createElement:tag=>{same(tag,'canvas','derived artwork uses canvas only');return canvasAPI.createCanvas(1,1);}}});Object.defineProperty(globalThis,'Image',{configurable:true,value:class{constructor(){const c=canvasAPI.createCanvas(1,1);Object.defineProperty(c,'src',{configurable:true,set(url){if(url==='')return;const name=String(url).split('/').at(-1),image=sources[name];check(image,'only known authored frontispiece source requested');c.width=image.width;c.height=image.height;c.getContext('2d').drawImage(image,0,0);c.sourceName=name;requests.push(name);pending.push(c);}});return c;}}});globalThis.setTimeout=(fn,ms)=>{same(ms,30000,'actual image loader remains bounded');timers.set(++serial,fn);return serial;};globalThis.clearTimeout=id=>timers.delete(id);const settle=()=>{for(const c of pending.splice(0))c.onload();};
 try{const runtime=await import('../src/r_bestiary.js?progressive-real-pixels');same(runtime.R_BestiaryFrontispiece(),null,'first blank image waits for decode');same(requests.join(),'frontispiece-blank.png','unseen profile does not request concealed complete illustration');settle();const zero=runtime.R_BestiaryFrontispiece(),blankPixels=raster(blank);check(raster(zero).every((v,i)=>v===blankPixels[i]),'fresh profile renders exact blank source');let revealed=[];for(const id of ids){revealed.push(id);values.set('quaked.bestiary.v1',JSON.stringify({version:1,unlocked:[...revealed,'multi_grenade_ogre']}));runtime.R_BestiaryFrontispiece();settle();const image=runtime.R_BestiaryFrontispiece(),expected=Bestiary_ComposeFrontispiece(blank,clean,revealed,()=>canvasAPI.createCanvas(1,1)),actualPixels=raster(image),expectedPixels=raster(expected);check(actualPixels.every((v,i)=>v===expectedPixels[i]),'public persisted discovery renders correct region '+id);same(runtime.R_BestiaryFrontispiece(),image,'unchanged mask reuses derived bitmap');same(runtime.R_BestiarySnapshot().complete,false,'five artwork keys do not complete47 journal');}same(requests.filter(n=>n==='frontispiece.png').length,1,'clean source loaded once throughout incremental reveal');check(!requests.includes('frontispiece-complete.png'),'five discoveries never prematurely load Complete Edition');const five=runtime.R_BestiaryFrontispiece();values.set('quaked.bestiary.v1',JSON.stringify({version:1,unlocked:BESTIARY_ENTRIES.map(e=>e.id)}));same(runtime.R_BestiaryFrontispiece(),five,'all47 keeps prior illustration while complete edition waits');same(requests.at(-1),'frontispiece-complete.png','complete edition requested only at full journal');settle();const final=runtime.R_BestiaryFrontispiece(),fullPixels=raster(completed);check(raster(final).every((v,i)=>v===fullPixels[i]),'all47 uses exact completed authored image');same(runtime.R_BestiarySnapshot().unlocked.length,47,'complete presentation does not duplicate or lose progress');same(writes.length,0,'all presentation stages are read-only');same(timers.size,0,'all actual image-load deadlines retired');}finally{globalThis.setTimeout=prior.setTimeout;globalThis.clearTimeout=prior.clearTimeout;for(const name of['Image','document','localStorage'])if(prior[name])Object.defineProperty(globalThis,name,prior[name]);else delete globalThis[name];}
});
