// Exact installed PAK member reads avoid materializing the725MiB MG1 archive.
import {openSync,readSync,closeSync,readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {COM_AddPack,COM_LoadPackFile,COM_FindFile} from '../src/engine/common/pak.js';
import {VID_SetPalette} from '../src/engine/render/vid.js';
import {Mod_Init,Mod_ForName,Mod_LeafPVS,Mod_PointInLeaf,Mod_ClearAll} from '../src/engine/render/gl_model.js';
import {SV_HullPointContents} from '../src/engine/server/world.js';
import {GL_BuildLightmaps,MAX_LIGHTMAPS,lightmapTextures} from '../src/engine/render/gl_rsurf.js';
import {cl} from '../src/engine/client/client.js';
const check=(v,m)=>{if(!v)throw Error(m);},same=(a,b,m)=>check(a===b,`${m}: ${a} != ${b}`),hash=b=>createHash('sha256').update(b).digest('hex');
function member(path,name){const fd=openSync(new URL('../'+path,import.meta.url),'r');try{const header=Buffer.alloc(12);readSync(fd,header,0,12,0);same(header.toString('ascii',0,4),'PACK','actual archive signature');const offset=header.readInt32LE(4),size=header.readInt32LE(8),directory=Buffer.alloc(size);readSync(fd,directory,0,size,offset);for(let p=0;p<size;p+=64)if(directory.subarray(p,p+56).toString().split('\0')[0]===name){const start=directory.readInt32LE(p+56),length=directory.readInt32LE(p+60),bytes=Buffer.alloc(length);same(readSync(fd,bytes,0,length,start),length,'complete actual BSP member');return bytes;}throw Error('Missing installed member '+name);}finally{closeSync(fd);}}
const pack=readFileSync(new URL('../pak0.pak',import.meta.url));COM_AddPack(COM_LoadPackFile('bsp2-native-palette',pack.buffer.slice(pack.byteOffset,pack.byteOffset+pack.length)));VID_SetPalette(COM_FindFile('gfx/palette.lmp').data);Mod_Init();
Deno.test('actual installed DOPA and large MG1 BSP2 members load their exact widened geometry, PVS and collision data',()=>{
 const evidence=[];for(const [archive,name]of [['resources/dopa/pak0.pak','maps/e5sm1.bsp'],['resources/mg1/pak0.pak','maps/hub.bsp']]){
  const raw=member(archive,name),sourceSHA256=hash(raw),lump=i=>({offset:raw.readInt32LE(4+i*8),size:raw.readInt32LE(8+i*8)});Mod_ClearAll();COM_AddPack({data:raw.buffer.slice(raw.byteOffset,raw.byteOffset+raw.length),files:[{name,filepos:0,filelen:raw.length}]});const start=performance.now(),model=Mod_ForName(name,true);same(model.bspVersion,0x32505342,'actual installed format BSP2');same(hash(model.bspSourceBytes),sourceSHA256,'exact immutable loaded map bytes');same(model.numvertexes,lump(3).size/12,'all original vertices loaded');same(model.numsurfaces,lump(7).size/28,'all widened faces loaded');same(model.numnodes,lump(5).size/44,'all widened nodes loaded');same(model.leafs.length,lump(10).size/44,'all float-bound leaves loaded');
  let maxVertex=0;const edges=lump(12);for(let i=0;i<model.numedges;i++)for(let k=0;k<2;k++){const expected=raw.readUInt32LE(edges.offset+i*8+k*4);same(model.edges[i].v[k],expected,'every actual edge index exact');maxVertex=Math.max(maxVertex,expected);}const leaves=lump(10);for(let i=0;i<model.leafs.length;i+=Math.max(1,Math.floor(model.leafs.length/31)))for(let k=0;k<6;k++)same(model.leafs[i].minmaxs[k],raw.readFloatLE(leaves.offset+i*44+8+k*4),'actual float leaf bound retained');
  const row=(model.numleafs+7)>>3;let pvsRows=0;for(let i=0;i<model.leafs.length;i+=Math.max(1,Math.floor(model.leafs.length/31))){const pvs=Mod_LeafPVS(model.leafs[i],model);check(pvs.length>=row,'actual visibility row not truncated');pvsRows++;}
  for(let i=0;i<16;i++){const point=model.mins.map((min,k)=>min+(model.maxs[k]-min)*(((i*29+k*17)%97)/96));const leaf=Mod_PointInLeaf(point,model);check(leaf.contents<0,'actual draw BSP terminates in leaf');const collision=SV_HullPointContents(model.hulls[0],model.hulls[0].firstclipnode,point);let node=model.nodes[model.hulls[0].firstclipnode],onPlane=false;while(node.contents>=0){const d=point.reduce((sum,x,k)=>sum+x*node.plane.normal[k],0)-node.plane.dist;if(d===0)onPlane=true;node=node.children[d>=0?0:1];}same(collision,node.contents,'actual hull0 agrees with independent draw-tree walk using native collision tie rule');if(collision!==leaf.contents)check(onPlane,'different native draw/collision result requires exact-plane witness');for(let hull=1;hull<3;hull++)check(SV_HullPointContents(model.hulls[hull],model.hulls[hull].firstclipnode,point)<0,'actual widened collision hull terminates safely');}
  if(name==='maps/hub.bsp'){check(maxVertex>65535,'real MG1 edges exercise wide vertex index');check(model.leafs.length>65535&&model.numnodes>65535&&model.numsurfaces>65535,'real MG1 exceeds old leaf/node/face widths');}
  evidence.push({archive,name,sourceSHA256,vertices:model.numvertexes,faces:model.numsurfaces,nodes:model.numnodes,leaves:model.leafs.length,visLeaves:model.numleafs,rowBytes:row,maxVertex,pvsRows,loaderMS:performance.now()-start});
  cl.worldmodel=model;cl.model_precache[1]=model;cl.model_precache[2]=null;GL_BuildLightmaps();check(model.surfaces.slice(model.firstmodelsurface,model.firstmodelsurface+model.nummodelsurfaces).every(s=>s.polys),'actual geometry/lightmap preparation required by displacement baker completes');evidence.at(-1).lightmapCapacity=MAX_LIGHTMAPS;evidence.at(-1).lightmapTextures=lightmapTextures.length;if(name==='maps/hub.bsp')check(MAX_LIGHTMAPS>64&&MAX_LIGHTMAPS<=512,'actual wide map grows bounded atlas capacity only when needed');
 }
 const previous=lightmapTextures.slice();let disposed=0;for(const texture of previous)texture.addEventListener('dispose',()=>disposed++);Mod_ClearAll();const nativeModel=Mod_ForName('maps/e1m1.bsp',true);cl.worldmodel=nativeModel;cl.model_precache[1]=nativeModel;cl.model_precache[2]=null;GL_BuildLightmaps();same(MAX_LIGHTMAPS,64,'return to BSP29 resets original lightmap capacity');same(disposed,previous.length,'old wide-map GPU atlas textures are disposed on replacement');check(lightmapTextures.length<=64,'original map does not retain expanded texture array');console.log('BSP2_NATIVE_PROOF '+JSON.stringify({maps:evidence,returnToBSP29:{capacity:MAX_LIGHTMAPS,textures:lightmapTextures.length,disposed}}));
});
