// Public loader tests; independent widened record layouts are in the helper.
// References: QuakeSpasm Quake/bspfile.h and Quake/gl_model.c.
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {BSP2,PSB2,convertBsp29,splitBsp,joinBsp,widenFixture} from './helpers/bsp2_fixture.mjs';
import {COM_AddPack,COM_LoadPackFile,COM_FindFile} from '../src/engine/common/pak.js';
import {VID_SetPalette} from '../src/vid.js';
import {Mod_Init,Mod_ForName,Mod_ClearAll,Mod_LeafPVS,Mod_DecompressVis,Mod_PointInLeaf} from '../src/gl_model.js';
import {SV_HullPointContents,SV_RecursiveHullCheck,trace_t} from '../src/engine/server/world.js';
import {R_ParseBsp} from '../src/r_levelgraph.js';
import {R_BspTextureNames} from '../src/r_newertextures.js';
const check=(v,m)=>{if(!v)throw Error(m);},same=(a,b,m)=>check(a===b,`${m}: ${a} != ${b}`),hash=b=>createHash('sha256').update(b).digest('hex');
const pack=readFileSync(new URL('../pak0.pak',import.meta.url));COM_AddPack(COM_LoadPackFile('bsp2-native-fixture',pack.buffer.slice(pack.byteOffset,pack.byteOffset+pack.length)));VID_SetPalette(COM_FindFile('gfx/palette.lmp').data);Mod_Init();let serial=0;
const native=name=>Buffer.from(COM_FindFile(name).data);
function load(bytes,name='maps/bsp2-public-'+(++serial)+'.bsp'){const data=Buffer.from(bytes);COM_AddPack({data:data.buffer.slice(data.byteOffset,data.byteOffset+data.length),files:[{name,filepos:0,filelen:data.length}]});return Mod_ForName(name,true);}
function summary(m){const planes=new Map(m.planes.map((p,i)=>[p,i])),nodes=new Map(m.nodes.map((n,i)=>[n,i])),leaves=new Map(m.leafs.map((l,i)=>[l,i])),surfaces=new Map(m.surfaces.map((s,i)=>[s,i]));return{vertices:m.vertexes.map(v=>Array.from(v.position)),edges:m.edges.slice(0,m.numedges).map(e=>Array.from(e.v)),surfedges:Array.from(m.surfedges),surfaces:m.surfaces.map(s=>[s.firstedge,s.numedges,s.flags,planes.get(s.plane),m.texinfo.indexOf(s.texinfo),Array.from(s.texturemins),Array.from(s.extents),Array.from(s.styles),s.samples&&hash(s.samples)]),nodes:m.nodes.map(n=>[planes.get(n.plane),n.firstsurface,n.numsurfaces,Array.from(n.minmaxs),...n.children.map(c=>c.contents<0?-1-leaves.get(c):nodes.get(c))]),leaves:m.leafs.map(l=>[l.contents,...l.minmaxs,l.nummarksurfaces,l.firstmarksurface.map(s=>surfaces.get(s)),...l.ambient_sound_level]),clips:m.clipnodes.map(n=>[n.planenum,...n.children]),hull0:m.hulls[0].clipnodes.map(n=>[n.planenum,...n.children]),entities:m.entities};}
function trace(h,a,b){const t=new trace_t();t.allsolid=true;t.endpos.set(b);SV_RecursiveHullCheck(h,h.firstclipnode,0,1,a,b,t);return JSON.stringify([t.fraction,t.allsolid,t.startsolid,t.inopen,t.inwater,Array.from(t.endpos),Array.from(t.plane.normal),t.plane.dist]);}
function collisionEqual(a,b,label){for(let i=0;i<40;i++){const p=Array.from({length:3},(_,k)=>a.mins[k]+(a.maxs[k]-a.mins[k])*(((i*37+k*19)%101)/100)),q=p.map((v,k)=>v+(k===2?-96:73));same(Mod_PointInLeaf(p,a).contents,Mod_PointInLeaf(p,b).contents,label+' actual leaf contents');for(let h=0;h<3;h++){same(SV_HullPointContents(a.hulls[h],a.hulls[h].firstclipnode,p),SV_HullPointContents(b.hulls[h],b.hulls[h].firstclipnode,p),label+' hull'+h+' point');same(trace(a.hulls[h],p,q),trace(b.hulls[h],p,q),label+' hull'+h+' trace');}}}
Deno.test('converted actual E1M1 BSP2 and2PSB retain original geometry, entities, PVS and all three collision hulls',()=>{
 const raw=native('maps/e1m1.bsp'),original=load(raw),expected=JSON.stringify(summary(original)),row=(original.numleafs+7)>>3,pvs=original.leafs.map(l=>hash(Mod_LeafPVS(l,original).subarray(0,row)));
 for(const version of [BSP2,PSB2]){const converted=convertBsp29(raw,version),model=load(converted);same(model.bspVersion,version,'actual format identified');same(hash(model.bspSourceBytes),hash(converted),'exact loaded source bytes retained');same(JSON.stringify(summary(model)),expected,'widened layout changes no native data');for(let i=0;i<model.leafs.length;i++)same(hash(Mod_LeafPVS(model.leafs[i],model).subarray(0,row)),pvs[i],'every native leaf PVS retained');collisionEqual(original,model,'format'+version);same(JSON.stringify(R_ParseBsp(converted)),JSON.stringify(R_ParseBsp(raw)),'portal entity/submodel parser accepts same geometry metadata');same(R_BspTextureNames(converted).join(),R_BspTextureNames(raw).join(),'early texture prefetch sees identical real material roster');}
});
Deno.test('BSP2 float bounds retain fractional node and leaf limits without changing geometric collision',()=>{
 const raw=native('maps/b_shell0.bsp'),original=load(raw),converted=load(convertBsp29(raw,BSP2,{fractional:true}));for(const field of ['nodes','leafs'])for(let i=0;i<original[field].length;i++)for(let k=0;k<6;k++)same(converted[field][i].minmaxs[k],original[field][i].minmaxs[k]+(k<3?-.25:.5),field+' exact fractional bound');collisionEqual(original,converted,'fractional bounds');
});
Deno.test('both widened versions retain indices above65535 through edges, faces, marks, nodes, leaves, clipnodes and hull0',()=>{
 const raw=native('maps/b_shell0.bsp'),original=load(raw),base=splitBsp(raw),edge=base[12].readUInt16LE(4),facePlane=base[7].readUInt16LE(0),faceTex=base[7].readInt16LE(10);
 for(const version of [BSP2,PSB2]){const fixture=widenFixture(convertBsp29(raw,version,{fractional:version===BSP2}),version),name='maps/public-wide-reload.bsp';Mod_ClearAll();const wide=load(fixture.bytes,name),n=fixture.offset;same(wide.edges[1].v[0],n+edge,'high edge vertex remains32bit');same(wide.surfaces[n].plane,wide.planes[n+facePlane],'high face plane index retained');same(wide.surfaces[n].texinfo,wide.texinfo[n+faceTex],'high texture-info index retained');same(wide.marksurfaces[n],wide.surfaces[n+base[11].readUInt16LE(0)],'high marksurface reference retained');check(wide.nodes[0].firstsurface>=n,'high node firstface retained');check(wide.nodes[0].children.some(c=>wide.nodes.indexOf(c)>=n||wide.leafs.indexOf(c)>=n),'high child/leaf reference retained');check(wide.hulls[0].clipnodes[0].children.some(c=>c>=n),'hull0 map retains high drawing-node child');check(wide.clipnodes[n].children.some(c=>c>=n),'high collision child retained');check(wide.leafs.slice(n).some(l=>l.nummarksurfaces&&l.firstmarksurface.some(s=>wide.surfaces.indexOf(s)>=n)),'high leaf marksurface offset retained');
  const row=(wide.numleafs+7)>>3,all=Mod_LeafPVS(wide.leafs[0],wide);check(row>8192&&all.length>=row&&all.subarray(0,row).every(v=>v===255),'solid-leaf no-vis buffer grows to actual wide leaf count');const visible=Mod_LeafPVS(wide.leafs[n+1],wide);check(visible.length>=row&&visible.subarray(0,row).every(v=>v===255),'decompressed no-vis buffer grows without truncation');collisionEqual(original,wide,'high-index format'+version);
 }
});
Deno.test('truncated and malformed widened lumps, cyclic nodes and leaf marksurface ranges reject through public model loading',()=>{
 const original=convertBsp29(native('maps/b_shell0.bsp'),BSP2);
 function reject(label,mutate){const lumps=splitBsp(original);mutate(lumps);let error;try{load(joinBsp(lumps,BSP2));}catch(e){error=e;}check(error instanceof Error,label+' rejected');}
 for(const i of [5,7,9,10,11,12])reject('partial record '+i,l=>l[i]=l[i].subarray(0,-1));reject('cycle',l=>l[5].writeInt32LE(0,4));reject('out-of-range child',l=>l[5].writeInt32LE(999999,4));reject('shared non-tree child',l=>{l[5].writeInt32LE(1,4);l[5].writeInt32LE(1,8);});reject('out-of-range node plane',l=>l[5].writeInt32LE(999999,0));reject('out-of-range collision plane',l=>l[9].writeInt32LE(999999,0));reject('out-of-range collision child',l=>l[9].writeInt32LE(999999,4));reject('leaf marksurface range',l=>l[10].writeUInt32LE(999999,32));reject('marksurface face index',l=>l[11].writeUInt32LE(999999,0));const bad=Buffer.from(original);bad.writeInt32LE(bad.length+4,4);let error;try{load(bad);}catch(e){error=e;}check(error instanceof Error,'out-of-file lump rejected');
});
Deno.test('visibility RLE is bounded and rejects truncated, zero-length or overflowing runs without hanging',()=>{
 const large={numleafs:70000},row=(large.numleafs+7)>>3,encoded=[];for(let n=row;n>0;n-=Math.min(n,255))encoded.push(0,Math.min(n,255));const expanded=Mod_DecompressVis(Uint8Array.from(encoded),0,large);check(expanded.length>=row&&expanded.subarray(0,row).every(v=>v===0),'valid wide zero runs fill actual row');for(const [input,offset,leaves]of [[[],0,8],[[0],0,8],[[0,0],0,8],[[0,2],0,8],[[255],-1,8],[[255],1,8]]){let error;try{Mod_DecompressVis(Uint8Array.from(input),offset,{numleafs:leaves});}catch(e){error=e;}check(error instanceof Error,'malformed RLE rejected '+JSON.stringify(input));}
});
