// Integrated R_DemonBakePrepare + real local files, not only the store class.
import * as fs from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {spawn} from 'node:child_process';
import {gzipSync,gunzipSync} from 'node:zlib';
import {DisplacementHash} from '../src/displacement_store.js';
import {DemonBakeDecode,DemonBakeEncode} from '../src/demon_bake_format.js';
import {nativeStorage,recordingLocks} from './helpers/opfs_native_fixture.mjs';
import {customModel,addCustomSurface,readyCustom} from './helpers/custom_displacement_fixture.mjs';
import * as vars from '../src/engine/common/cvar.js';
import * as anim from '../src/r_anim.js';
import {r_hdr} from '../src/gl_post.js';
import {R_IntroReadinessChecks} from '../src/r_demoloading.js';
const check=(v,m)=>{if(!v)throw Error(m);},same=(a,b,m)=>check(a===b,`${m}: ${a} != ${b}`),turn=()=>new Promise(r=>setTimeout(r,0));let serial=0;
async function until(fn,label){for(let i=0;i<500&&!fn();i++)await turn();check(fn(),label);}
async function fixture(run){const root=await fs.mkdtemp(join(tmpdir(),'quaked-custom-cache-')),storage=nativeStorage(root),locks=recordingLocks(),previous=Object.getOwnPropertyDescriptor(globalThis,'navigator'),classic=anim.R_ClassicPassActive();if(!vars.Cvar_FindVar(r_hdr.name))vars.Cvar_RegisterVariable(r_hdr);const hdr=r_hdr.string;vars.Cvar_SetValue('r_hdr',1);anim.R_AnimSetClassicPass(false);Object.defineProperty(globalThis,'navigator',{configurable:true,value:{storage,locks}});const modules=[];
 const fresh=async()=>{const api=await import('../src/r_demonbakes.js?integrated-custom-'+(++serial));modules.push(api);return api;};
 try{await run({root,storage,locks,fresh,files:async()=>{try{return(await fs.readdir(join(root,'quaked-displacement-v1'))).filter(n=>n.endsWith('.json'));}catch(e){if(e.code==='ENOENT')return[];throw e;}}});}
 finally{modules.forEach(m=>m.R_DemonBakeRelease());await turn();if(previous)Object.defineProperty(globalThis,'navigator',previous);else delete globalThis.navigator;vars.Cvar_Set('r_hdr',hdr);anim.R_AnimSetClassicPass(classic);await fs.rm(root,{recursive:true,force:true});}
}
Deno.test('unknown source generation commits exact geometry to disk and a fresh module/process reuses it without runtime sculpt generation',()=>fixture(async f=>{
 const model=customModel(),api=await f.fresh();await readyCustom(api,model);same(api.R_DemonBakeStatus().source,'generated-and-stored','first unknown source really persisted');same((await f.files()).length,1,'one durable identity manifest');const original=api.R_DemonBakeSurface(model.surfaces[0]).data,expected=Array.from(new Uint32Array(original.positions.buffer));api.R_DemonBakeRelease();
 const old=Float32Array.prototype.every;let calls=0;Float32Array.prototype.every=function(...args){if(this.length===4){calls++;throw Error('Disk hit must not regenerate');}return old.apply(this,args);};
 try{const second=await f.fresh(),copy=customModel();await readyCustom(second,copy);same(second.R_DemonBakeStatus().source,'disk','new module reads real durable output');same(calls,0,'cached read bypasses generator validation');same(JSON.stringify(Array.from(new Uint32Array(second.R_DemonBakeSurface(copy.surfaces[0]).data.positions.buffer))),JSON.stringify(expected),'decoded geometry is bit-identical');second.R_DemonBakeRelease();}finally{Float32Array.prototype.every=old;}
 const child=spawn(process.execPath,[new URL('./helpers/custom_displacement_child.mjs',import.meta.url).pathname,f.root,model.name,'7'],{stdio:['ignore','pipe','pipe'],env:process.env});let stdout='',stderr='';child.stdout.on('data',x=>stdout+=x);child.stderr.on('data',x=>stderr+=x);const exit=await new Promise((resolve,reject)=>{child.on('error',reject);child.on('exit',resolve);});same(exit,0,'fresh process renderer-cache reuse '+stderr);const proof=JSON.parse(stdout.split('\n').find(line=>line.startsWith('CUSTOM_DISK_CHILD ')).slice(18));same(proof.state.source,'disk','fresh process confirms actual disk source');same(proof.generatorCalls,0,'fresh process generator trap untouched');check(proof.pid!==process.pid,'independent process lifetime');same(JSON.stringify(proof.positions),JSON.stringify(expected),'fresh process exact geometry bytes');console.log('CUSTOM_RENDERER_RESTART '+JSON.stringify({parent:process.pid,child:proof.pid,source:proof.state.source,triangles:proof.triangles,generatorCalls:proof.generatorCalls}));
}));
Deno.test('complete field membership and terminal actual texture readiness own the durable key, not merely currently visible surfaces',()=>fixture(async f=>{
 const model=customModel(),api=await f.fresh(),texture=model.textures[0].gl_texture;texture.userData.newerPicture=false;texture.userData.newerPending=true;const waiting=api.R_DemonBakePrepare(model,model.surfaces);same(waiting.status,'loading','pending actual art holds custom work');same(f.storage.attempts,0,'field membership not committed before art settles');same(api.R_DemonBakeStatus().pending,1,'waiting is reported globally');texture.userData.newerPending=false;texture.userData.newerPicture=true;addCustomSurface(model);api.R_DemonBakePrepare(model,[model.surfaces[0]]);await readyCustom(api,model);same(api.R_DemonBakeSurface(model.surfaces[1]).status,'ready','offscreen member included in complete map snapshot');same((await f.files()).length,1,'one complete-map key');
 model.surfaces[0].texinfo.texture.gl_texture.userData.newerHeight.displacement.depth=5;await readyCustom(api,model);same((await f.files()).length,2,'changed supported depth selects new durable identity');model.surfaces.pop();await readyCustom(api,model);same((await f.files()).length,3,'changed surface membership selects new identity');same(api.R_DemonBakeStatus().source,'generated-and-stored','new membership generated only after old authority invalidated');
}));
Deno.test('same-named source replacement and renamed identical bytes never inherit a different source/name key',()=>fixture(async f=>{
 const api=await f.fresh(),model=customModel();await readyCustom(api,model);model.bspSourceBytes=model.bspSourceBytes.slice();await readyCustom(api,model);same(api.R_DemonBakeStatus().source,'disk','copied equal bytes use durable content identity');same((await f.files()).length,1,'buffer identity alone does not duplicate files');model.bspSourceBytes=model.bspSourceBytes.slice();model.bspSourceBytes[0]^=1;await readyCustom(api,model);same((await f.files()).length,2,'same name changed source bytes creates new identity');model.name='maps/renamed-durable-public.bsp';await readyCustom(api,model);same((await f.files()).length,3,'renamed exact source has its own validated model identity');
}));
Deno.test('cancelling during closed-file persistence and revisiting cannot publish an obsolete owner or strand a new visit',()=>fixture(async f=>{
 const api=await f.fresh(),model=customModel();let entered=false,release;const held=new Promise(r=>release=r);f.storage.hooks.beforeClose=async name=>{if(name.endsWith('.gz')&&!entered){entered=true;await held;}};const first=api.R_DemonBakePrepare(model,model.surfaces);await until(()=>entered,'actual payload writer reaches hold');api.R_DemonBakeRelease();same(api.R_DemonBakeStatus().pending,0,'released owner immediately stops blocking current world');release();await first.promise;same(api.R_DemonBakeSurface(model.surfaces[0]).data,null,'late old result cannot publish after release');delete f.storage.hooks.beforeClose;await readyCustom(api,model);same(api.R_DemonBakeStatus().source,'generated-and-stored','revisit completes cleanly after cancelled pre-manifest write');same((await f.files()).length,1,'only completed visit publishes manifest');
}));
Deno.test('map switch and in-flight input change reject stale generated snapshots before publishing to the current scene',()=>fixture(async f=>{
 const api=await f.fresh(),a=customModel(),b=customModel('maps/second-durable-public.bsp',9);let waiting=false,release;const held=new Promise(r=>release=r);f.storage.hooks.beforeClose=async name=>{if(name.endsWith('.gz')&&!waiting){waiting=true;await held;}};const first=api.R_DemonBakePrepare(a,a.surfaces);await until(()=>waiting,'first map persistence held');api.R_DemonBakePrepare(b,b.surfaces);release();await first.promise;delete f.storage.hooks.beforeClose;await readyCustom(api,b);same(api.R_DemonBakeSurface(a.surfaces[0]).data,null,'old map cannot publish through new owner');same(api.R_DemonBakeSurface(b.surfaces[0]).status,'ready','new owner settles');
 api.R_DemonBakeRelease();const c=customModel('maps/changed-in-flight.bsp',10);let committing=false,finish;const pause=new Promise(r=>finish=r);f.storage.hooks.beforeClose=async name=>{if(name.endsWith('.json')&&!committing){committing=true;await pause;}};const pending=api.R_DemonBakePrepare(c,c.surfaces);await until(()=>committing,'captured identity reaches manifest commit');c.surfaces[0].polys.verts[0]+=1;finish();await pending.promise;check(api.R_DemonBakeSurface(c.surfaces[0]).status!=='ready','changed original polygon never accepts obsolete output');delete f.storage.hooks.beforeClose;await readyCustom(api,c);same(api.R_DemonBakeSurface(c.surfaces[0]).status,'ready','changed signature receives separately validated output');
}));
Deno.test('zero-sculpt cache failures remain explicit global blockers, while anonymous procedural worlds never require filesystem ownership',()=>fixture(async f=>{
 const api=await f.fresh(),model=customModel('maps/no-sculpt-public.bsp');model.surfaces=[];model.textures=[];f.storage.hooks.beforeOpen=()=>{throw Error('controlled inaccessible filesystem');};const work=api.R_DemonBakePrepare(model,[]);await work.promise;const status=api.R_DemonBakeStatus();same(work.status,'error','zero-member map still requires durable validation');same(status.pending,1,'global pending keeps zero-sculpt error visible');check(status.error.includes('inaccessible'),'filesystem diagnostic retained');check(R_IntroReadinessChecks({demon:{enabled:true,pending:0,preparedPending:status.pending,errors:[status.error]}}).pending.includes('sculpted surfaces'),'real startup collector cannot release zero-sculpt error');api.R_DemonBakeRelease();const anonymous=api.R_DemonBakePrepare({surfaces:[]},[]);same(anonymous.status,'unprepared','anonymous renderer helper preserves native fallback');same(api.R_DemonBakeStatus().pending,0,'anonymous helper has no false durable blocker');
}));
Deno.test('self-consistent cached payload from the wrong generator version holds with an error and is never silently regenerated',()=>fixture(async f=>{
 const model=customModel(),api=await f.fresh();await readyCustom(api,model);api.R_DemonBakeRelease();const directory=join(f.root,'quaked-displacement-v1'),name=(await f.files())[0],manifest=JSON.parse(await fs.readFile(join(directory,name),'utf8')),raw=gunzipSync(await fs.readFile(join(directory,manifest.payloadSha256+'.gz'))),length=raw.readUInt32LE(4),meta=JSON.parse(raw.subarray(8,8+length)),decoded=DemonBakeDecode(raw.buffer.slice(raw.byteOffset,raw.byteOffset+raw.byteLength),model.name,meta.bspSha256),records=[...decoded.records].map(([signature,r])=>({signature,settings:r.settings,fieldSha256:r.fieldSha256,data:r.data}));
 const stale=DemonBakeEncode({...meta,generatorVersion:'obsolete-generator'},records),compressed=gzipSync(stale),payloadSha256=await DisplacementHash(compressed);await fs.writeFile(join(directory,payloadSha256+'.gz'),compressed);await fs.writeFile(join(directory,name),JSON.stringify({...manifest,payloadSha256,rawSha256:await DisplacementHash(stale),rawBytes:stale.length,compressedBytes:compressed.length}));
 const next=await f.fresh(),old=Float32Array.prototype.every;let generated=0;Float32Array.prototype.every=function(...args){if(this.length===4){generated++;throw Error('Corruption must not regenerate');}return old.apply(this,args);};try{const replacement=customModel(),work=next.R_DemonBakePrepare(replacement,replacement.surfaces);await work.promise;const status=next.R_DemonBakeStatus();same(status.pending,1,'bad cached authority remains blocked');check(status.error?.includes('identity/coverage mismatch'),'generator mismatch retains explicit diagnostic');same(generated,0,'wrong-version cache never becomes an ordinary miss');same(next.R_DemonBakeSurface(replacement.surfaces[0]).data,null,'stale cached geometry is never published');}finally{Float32Array.prototype.every=old;}
}));
