// Actual native BSP, shipped gzip, public world/PVS and sun-caster integration.
// CPU-only: source scalar validation is guarded to detect any runtime sculpt
// generation after prepared authority is admitted. No renderer is simulated.
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {gunzipSync} from 'node:zlib';
import {DemonBakeDecode,DemonSurfaceSignature} from '../src/demon_bake_format.js';
import {expandAttribute,assertPointParity} from './helpers/compact_geometry_oracle.mjs';
import * as THREE from 'three';
import * as surf from '../src/gl_rsurf.js';
import * as post from '../src/gl_post.js';
import * as main from '../src/gl_rmain.js';
import * as anim from '../src/r_anim.js';
import * as vars from '../src/engine/common/cvar.js';
import {COM_AddPack,COM_LoadPackFile,COM_FindFile} from '../src/engine/common/pak.js';
import {Mod_Init,Mod_ForName,Mod_ClearAll} from '../src/gl_model.js';
import {VID_SetPalette} from '../src/vid.js';
import {cl} from '../src/engine/client/client.js';
import {entity_t,r_refdef} from '../src/render.js';
import {R_DemonBakePrefetch,R_DemonBakePrepare,R_DemonBakeSurface,R_DemonBakeRelease} from '../src/r_demonbakes.js';
import {R_IntroReadinessChecks,R_DemoLoadingWelcome,R_DemoLoadingCancel,R_DemoLoadingStatus} from '../src/r_demoloading.js';
const check=(v,m)=>{if(!v)throw Error(m);},same=(a,b,m)=>check(a===b,`${m}: ${a} != ${b}`),read=p=>readFileSync(new URL('../'+p,import.meta.url)),turn=()=>new Promise(r=>setTimeout(r,0));
async function until(predicate,label){for(let i=0;i<300&&!predicate();i++)await turn();check(predicate(),label);}
Deno.test('native prepared START preserves exact rendered/caster geometry, blocks pending work without runtime tessellation and keeps Classic/cancellation native',async()=>{
 const pack=read('pak0.pak');COM_AddPack(COM_LoadPackFile('prepared-native-source',pack.buffer.slice(pack.byteOffset,pack.byteOffset+pack.byteLength)));VID_SetPalette(COM_FindFile('gfx/palette.lmp').data);Mod_Init();const model=Mod_ForName('maps/start.bsp',true);cl.worldmodel=model;cl.model_precache[1]=model;cl.model_precache[2]=null;
 let world;const add=THREE.Group.prototype.add;THREE.Group.prototype.add=function(...objects){if(this.name==='quake_world')world=this;return add.apply(this,objects);};try{surf.GL_BuildLightmaps();}finally{delete THREE.Group.prototype.add;}
 let faces=model.surfaces.filter(s=>s.texinfo.texture.name==='dem4_1');const nativeBytes=faces.map(s=>Buffer.from(s.polys.verts.buffer,s.polys.verts.byteOffset,s.polys.verts.byteLength).toString('hex')),hulls=JSON.stringify(model.hulls);same(faces.length,2,'actual bundled START plaques');check(model.bspSourceBytes&&world,'loaded source identity and actual world group exist');const special=model.surfaces.filter(s=>s.flags&(4|16)).map(surface=>({surface,head:surface.polys,chains:(()=>{const out=[];for(let p=surface.polys;p;p=p.next)out.push(Array.from(p.verts));return JSON.stringify(out);})()}));check(special.length>0,'actual sky/water subdivision positive controls');
 async function settleFields(label){for(let i=0;i<300;i++){const work=R_DemonBakePrepare(model,faces);if(work.status==='error')throw Error(label+': '+work.error);const states=faces.map(R_DemonBakeSurface);if(states.some(state=>state.status==='error'))throw Error(label+': '+states.map(s=>s.error).join());if(states.every(state=>state.status==='ready'))return;await new Promise(r=>setTimeout(r,0));}throw Error(label);}

 const options=[post.r_hdr,anim.r_newer_normals,anim.r_newer_textures];for(const v of options)if(!vars.Cvar_FindVar(v.name))vars.Cvar_RegisterVariable(v);const saved=options.map(v=>v.string),oldFetch=globalThis.fetch;
 const raw=read('newer/textures/normals/demon-face.r16'),recipe=JSON.parse(read('newer/textures/index.json')).normals.dem4_1,field={width:256,height:512,sampling:recipe.sampling,data:Float32Array.from({length:256*512},(_,i)=>raw.readUInt16LE(i*2)/65535),displacement:{...recipe.displacement}};
 let release,requests=0,scalarGeneratorReads=0,reference,rawPayloadBytes,activeField=field;const requestURLs=[];
 field.data.every=()=>{scalarGeneratorReads++;throw Error('Prepared path unexpectedly invoked runtime sculpt generator');};
 globalThis.fetch=async url=>{requestURLs.push(String(url));const path=String(url).split('?')[0];if(path.startsWith('newer/rockfield/'))return new Response(read(path),{status:200});check(path.startsWith('newer/displacement/'),'native fixture loads actual prepared artifact only');requests++;await new Promise(r=>release=r);const compressed=read(path),expanded=gunzipSync(compressed);rawPayloadBytes=expanded.length;reference=DemonBakeDecode(expanded.buffer.slice(expanded.byteOffset,expanded.byteOffset+expanded.byteLength),model.name,createHash('sha256').update(model.bspSourceBytes).digest('hex'));return new Response(compressed,{status:200});};
 try{
  anim.R_AnimSetClassicPass(false);for(const v of options)vars.Cvar_SetValue(v.name,1);vars.Cvar_SetValue('r_newer_normals',0);const nativeCount=post.R_BuildSunOccluder(model);vars.Cvar_SetValue('r_newer_normals',1);
  for(const s of faces)s.texinfo.texture.gl_texture.userData.newerHeight=field;main.set_r_worldentity(new entity_t());main.set_r_viewleaf(null);r_refdef.vieworg.set([512,224,64]);main.d_lightstylevalue.fill(264);surf.R_MarkLeaves();
  const entry=R_DemonBakePrefetch(model.name,model.bspSourceBytes);await until(()=>!!release,'default fetch reaches held real gzip transport');R_DemoLoadingWelcome();surf.R_DrawWorld();same(surf.R_DemonReliefStatus().ready,0,'loading artifact does not fabricate world mesh');check(surf.R_DemonReliefStatus().pending===2,'both actual plaques remain pending');check(R_IntroReadinessChecks({demon:surf.R_DemonReliefStatus()}).pending.includes('sculpted surfaces'),'actual intro remains held');same(post.R_BuildSunOccluder(model),nativeCount,'sun also retains native backing while prepared transport pending');same(scalarGeneratorReads,0,'neither world nor sun tessellates while known prepared work loads');
  R_DemoLoadingCancel();anim.R_AnimSetClassicPass(true);surf.R_DrawWorld();release();await entry.promise;same(entry.status,'ready','actual gzip/default loader validates/decompresses installed artifact');same(requests,1,'same source prefetch/scene/sun share one request '+JSON.stringify(requestURLs));surf.R_DrawWorld();same(surf.R_DemonReliefStatus().ready,0,'cancelled Classic view does not install late enhanced meshes');same(R_DemoLoadingStatus().phase,'done','late decode cannot rearm cancelled startup');
  anim.R_AnimSetClassicPass(false);R_DemonBakePrepare(model,faces);await until(()=>faces.every(s=>R_DemonBakeSurface(s).status==='ready'),'all actual scalar sources validate');surf.R_DrawWorld();const status=surf.R_DemonReliefStatus();same(status.ready,2,'validated actual world overlays installed');same(status.pending,0,'only installed data clears pending');same(status.triangles,266240,'all original triangles and skirts retained');let meshes=world.children.filter(o=>o.material?.userData.realDisplacement);same(meshes.length,2,'one existing world mesh per plaque');
  const preparedData=faces.map(surface=>R_DemonBakeSurface(surface).data),packedBefore=Buffer.from(new Uint8Array(preparedData[0].interleaved.buffer));
  same(entry.decodedBytes,rawPayloadBytes,'runtime cache accounts for complete retained payload without compatibility getters');
  for(const data of preparedData)same(data.materializedAttributes,0,'decode,accounting and actual world construction never expand compatibility arrays');
  for(const mesh of meshes){const geometry=mesh.geometry,match=preparedData.find(d=>geometry.attributes.position.data?.array===d.interleaved);check(match,'actual world binds original packed tuple view');same(geometry.index.array,match.indices,'actual world binds original corner index view');check(geometry.attributes.position.count<geometry.index.count,'actual world retains unique vertices rather than hidden expansion');for(const [attribute,size,offset]of [['position',3,0],['normal',3,3],['uv',2,6],['uv1',2,8]]){const a=geometry.attributes[attribute];check(a.isInterleavedBufferAttribute,'actual '+attribute+' is interleaved');same(a.data.stride,10,'actual stride10');same(a.itemSize,size,'actual attribute width');same(a.offset,offset,'actual attribute offset');same(a.data,geometry.attributes.position.data,'one independent Three buffer per geometry');}check(mesh.castShadow&&mesh.userData.newerOnly,'ordinary shadow/Classic ownership retained');
   const surface=faces.find(s=>R_DemonBakeSurface(s).data===match),original=reference.records.get(DemonSurfaceSignature(surface)).data,baseline=new THREE.BufferGeometry();for(const [attribute,name]of [['position','positions'],['normal','normals'],['uv','uvs'],['uv1','lmuvs']]){check(Buffer.from(expandAttribute(geometry,attribute).buffer).equals(Buffer.from(original[name].buffer)),'actual '+attribute+' expands to exact prior bytes');baseline.setAttribute(attribute,new THREE.BufferAttribute(original[name],attribute.startsWith('uv')?2:3));}baseline.computeBoundingBox();baseline.computeBoundingSphere();const previous=new THREE.Mesh(baseline,mesh.material);mesh.updateMatrixWorld(true);previous.matrixAutoUpdate=false;previous.matrixWorld.copy(mesh.matrixWorld);
   try{for(const triangle of [0,Math.floor(original.topVertexCount/6)]){const a=new THREE.Vector3().fromArray(original.positions,triangle*9),b=new THREE.Vector3().fromArray(original.positions,triangle*9+3),c=new THREE.Vector3().fromArray(original.positions,triangle*9+6),normal=b.clone().sub(a).cross(c.clone().sub(a)).normalize(),centre=a.clone().add(b).add(c).multiplyScalar(1/3),ray=new THREE.Raycaster(centre.clone().addScaledVector(normal,12),normal.clone().negate(),0,24),describe=o=>ray.intersectObject(o).map(h=>({face:h.faceIndex,distance:h.distance,point:h.point.toArray(),uv:h.uv?.toArray(),normal:h.normal?.toArray()})),old=describe(previous),now=describe(mesh);check(old.length>0,'actual native ray has positive non-vacuous baseline hit');same(JSON.stringify(now),JSON.stringify(old),'native indexed raycast retains exact triangle/hit/UV/normal order');}}finally{baseline.dispose();}
  }
  const chunks=[];for(const surface of model.surfaces.slice(model.firstmodelsurface,model.firstmodelsurface+model.nummodelsurfaces)){if(!surface.polys||surface.flags&(4|16))continue;const native=[];for(let p=surface.polys;p;p=p.next){const at=(i,k)=>p.verts instanceof Float32Array?p.verts[i*7+k]:p.verts[i][k];for(let n=2;n<p.numverts;n++)for(const i of [0,n-1,n])for(let k=0;k<3;k++)native.push(at(i,k));}chunks.push(Buffer.from(new Float32Array(native).buffer));const original=reference.records.get(DemonSurfaceSignature(surface));if(original)chunks.push(Buffer.from(original.data.positions.buffer));}
  const ordered=Buffer.concat(chunks),setAttribute=THREE.BufferGeometry.prototype.setAttribute;let sunGeometry;THREE.BufferGeometry.prototype.setAttribute=function(name,attribute){if(name==='position')sunGeometry=this;return setAttribute.call(this,name,attribute);};try{same(post.R_BuildSunOccluder(model),nativeCount+266240,'sun caster contains exact same prepared relief triangles');}finally{THREE.BufferGeometry.prototype.setAttribute=setAttribute;}check(sunGeometry?.index,'actual sun uses compact indexed representation');check(sunGeometry.attributes.position.count<sunGeometry.index.count,'actual sun retains compact position count');check(Buffer.from(expandAttribute(sunGeometry,'position').buffer).equals(ordered),'actual expanded sun retains exact original native/relief triangle ordering');const oldSun=new THREE.BufferGeometry();oldSun.setAttribute('position',new THREE.BufferAttribute(new Float32Array(ordered.buffer.slice(ordered.byteOffset,ordered.byteOffset+ordered.byteLength)),3));try{assertPointParity(sunGeometry,oldSun,'actual native indexed sun versus prior nonindexed');}finally{oldSun.dispose();}same(scalarGeneratorReads,0,'ready world and shadow paths bypass every runtime scalar validation/generation');surf.R_DrawWorld();same(surf.R_DemonReliefStatus().triangles,266240,'repeat world draws reuse prepared topology');for(const data of preparedData)same(data.materializedAttributes,0,'actual raycasts,world,sun and point grouping keep zero compatibility allocations');
  let disposed=0;const oldMeshes=meshes.slice(),oldBuffers=oldMeshes.map(m=>m.geometry.attributes.position.data);for(const mesh of oldMeshes)mesh.geometry.addEventListener('dispose',()=>disposed++);activeField={...field,displacement:{...field.displacement},data:field.data.slice()};activeField.data.every=field.data.every;for(const surface of faces)surface.texinfo.texture.gl_texture.userData.newerHeight=activeField;R_DemonBakePrepare(model,faces);await until(()=>faces.every(s=>R_DemonBakeSurface(s).status==='ready'),'equivalent new field validates before rebuild');surf.R_DrawWorld();same(disposed,2,'public field replacement disposes both former geometries');meshes=world.children.filter(o=>o.material?.userData.realDisplacement);same(meshes.length,2,'public rebuild restores both overlays');check(meshes.every(m=>!oldBuffers.includes(m.geometry.attributes.position.data)),'rebuild owns independent Three interleaved wrappers');for(const data of preparedData)same(data.materializedAttributes,0,'disposal/rebuild never expands compatibility arrays');
  R_DemonBakeRelease();const addAgain=THREE.Group.prototype.add;THREE.Group.prototype.add=function(...objects){if(this.name==='quake_world')world=this;return addAgain.apply(this,objects);};try{surf.GL_BuildLightmaps();}finally{delete THREE.Group.prototype.add;}await settleFields('same-model rebuild validates retained compact data');for(const face of faces)same(face.polys.next,null,'opaque BSP rebuild never duplicates polygon chain');for(const item of special){same(item.surface.polys,item.head,'sky/water keep loader-owned subdivision chain identity');const chains=[];for(let p=item.surface.polys;p;p=p.next)chains.push(Array.from(p.verts));same(JSON.stringify(chains),item.chains,'sky/water subdivision bytes unchanged');}surf.R_DrawWorld();meshes=world.children.filter(o=>o.material?.userData.realDisplacement);same(meshes.length,2,'same-model rebuild installs both compact overlays');
  const previousSurfaces=faces.slice(),oldSource=model.bspSourceBytes;R_DemonBakeRelease();Mod_ClearAll();same(Mod_ForName('maps/start.bsp',true),model,'actual native reload reuses model slot');check(model.bspSourceBytes!==oldSource,'actual native reload captures fresh loaded bytes');faces=model.surfaces.filter(s=>s.texinfo.texture.name==='dem4_1');check(faces.every(s=>!previousSurfaces.includes(s)),'actual reload provides new native surface objects');for(const face of faces)face.texinfo.texture.gl_texture.userData.newerHeight=activeField;THREE.Group.prototype.add=function(...objects){if(this.name==='quake_world')world=this;return addAgain.apply(this,objects);};try{surf.GL_BuildLightmaps();}finally{delete THREE.Group.prototype.add;}await settleFields('actual unload/reload validates retained compact data');surf.R_DrawWorld();meshes=world.children.filter(o=>o.material?.userData.realDisplacement);same(meshes.length,2,'actual unload/reload installs both compact overlays');same(requests,1,'actual reload uses verified retained cache without redundant transport');check(Buffer.from(preparedData[0].interleaved.buffer).equals(packedBefore),'render,shadow,dispose,rebuild,reload never mutate shared packed authority');for(const data of preparedData)same(data.materializedAttributes,0,'complete ordinary lifecycle has zero compatibility getter allocations');console.log('COMPACT_NATIVE_LIFECYCLE '+JSON.stringify({surfaces:faces.length,triangles:status.triangles,payloadBytes:entry.decodedBytes,gpuBytes:preparedData.reduce((n,d)=>n+d.gpuBytes,0),compatibilityAllocations:preparedData.map(d=>d.materializedAttributes),skyWaterSurfaces:special.length,transports:requests}));
  vars.Cvar_SetValue('r_newer_normals',0);surf.R_DrawWorld();check(meshes.every(m=>!m.visible),'normals-off hides enhancements');same(post.R_BuildSunOccluder(model),nativeCount,'normals-off shadow retains native geometry');vars.Cvar_SetValue('r_newer_normals',1);anim.R_AnimSetClassicPass(true);surf.R_DrawWorld();check(meshes.every(m=>!m.visible),'Classic hides all prepared meshes');same(post.R_BuildSunOccluder(model),nativeCount,'Classic sun geometry unchanged');anim.R_AnimSetClassicPass(false);
  activeField.displacement.depth+=1;surf.R_DrawWorld();same(surf.R_DemonReliefStatus().ready,0,'changed unsupported prepared recipe removes obsolete overlays');check(surf.R_DemonReliefStatus().errors.length>0&&surf.R_DemonReliefStatus().pending===2,'known prepared mismatch is diagnosed and still blocks');same(post.R_BuildSunOccluder(model),nativeCount,'known mismatch cannot secretly generate displaced shadow geometry');same(scalarGeneratorReads,0,'known mismatch cannot invoke runtime generator fallback');
  faces.forEach((s,i)=>same(Buffer.from(s.polys.verts.buffer,s.polys.verts.byteOffset,s.polys.verts.byteLength).toString('hex'),nativeBytes[i],'native polygon bytes untouched'));same(JSON.stringify(model.hulls),hulls,'native collision hulls unchanged');
 }finally{release?.();globalThis.fetch=oldFetch;delete field.data.every;delete activeField.data.every;R_DemonBakeRelease();R_DemoLoadingCancel();anim.R_AnimSetClassicPass(false);options.forEach((v,i)=>vars.Cvar_Set(v.name,saved[i]));}
});
