// Startup-only public coordinator, native console and retained demo packet path.
// No game/server/browser/GPU is started.
import * as boot from '../src/r_demoloading.js';
import { LoadingScreen_FadeOut } from '../src/loading_screen.js';
const check = ( value, label ) => { if ( ! value ) throw new Error( label ); };
const same = ( a, b, label ) => check( a === b, `${label}: ${a} != ${b}` );
const settled = () => ( { world: 'maps/e1m1.bsp', signon: 4, rendered: true, pending: [], fallbacks: [] } );
async function splash() { boot.R_DemoLoadingAppReady(); boot.R_DemoLoadingConsoleDrawn(); boot.R_DemoLoadingSplash( () => Promise.resolve() ); await new Promise( resolve => setTimeout( resolve, 0 ) ); }
Deno.test( 'boot splash waits for an actual console presentation and app readiness, fades once, and terminal fallback readiness needs three completed draws', async () => {
	boot.R_DemoLoadingBoot(); boot.R_DemoLoadingAttract( true ); let fades = 0;
	boot.R_DemoLoadingSplash( () => fades ++ ); await Promise.resolve(); same( fades, 0, 'no fade before real console/app readiness' ); boot.R_DemoLoadingAppReady(); boot.R_DemoLoadingSplash( () => fades ++ ); await Promise.resolve(); same( fades, 0, 'app ready alone cannot expose uninitialized canvas' ); boot.R_DemoLoadingConsoleDrawn(); boot.R_DemoLoadingSplash( () => { fades ++; return Promise.resolve(); } ); await new Promise( resolve => setTimeout( resolve, 0 ) ); same( fades, 1, 'fade after actual console once' ); boot.R_DemoLoadingSplash( () => fades ++ );
	boot.R_DemoLoadingFrame( { ...settled(), pending: [ 'rock tile fetch' ] } ); same( boot.R_DemoLoadingStatus().phase, 'warming', 'pending field blocks reveal' ); boot.R_DemoLoadingFrame( { ...settled(), fallbacks: [ 'optional skin failed; native retained' ] } ); boot.R_DemoLoadingFrame( settled() ); same( boot.R_DemoLoadingStatus().phase, 'warming', 'not just first ready frame' ); boot.R_DemoLoadingFrame( { ...settled(), revision: 'new-material' } ); same( boot.R_DemoLoadingStatus().phase, 'warming', 'late material revision restarts completed-draw qualification' ); boot.R_DemoLoadingFrame( { ...settled(), revision: 'new-material' } ); same( boot.R_DemoLoadingStatus().phase, 'warming', 'changed revision needs two additional actual draws' ); boot.R_DemoLoadingFrame( { ...settled(), revision: 'new-material' } ); same( boot.R_DemoLoadingStatus().phase, 'rolling', 'three completed stable-revision draws allow native rollup' ); check( boot.R_DemoLoadingConsoleOverride(), 'native console remains owned throughout rollup' ); boot.R_DemoLoadingConsoleClosed(); same( boot.R_DemoLoadingStatus().phase, 'done', 'only native console closed retires startup' ); boot.R_DemoLoadingAttract( true ); check( ! boot.R_DemoLoadingHolding(), 'later attract loop never rearms startup' );
} );
Deno.test( 'manual intent cancels startup permanently; signon packets/timed demos are never frozen and failed splash has a terminal native fallback', async () => {
	for ( const manual of [ false, true ] ) { boot.R_DemoLoadingBoot(); if ( manual ) boot.R_DemoLoadingCancel(); else boot.R_DemoLoadingAttract( false ); boot.R_DemoLoadingAttract( true ); same( boot.R_DemoLoadingStatus().phase, 'done', 'manual/network/game intent cannot later rearm' ); check( ! boot.R_DemoLoadingFreeze( true, 4 ), 'cancel leaves ordinary demo timing unchanged' ); }
	boot.R_DemoLoadingBoot(); boot.R_DemoLoadingAttract( true ); for ( const stage of [ 0, 1, 2, 3 ] ) check( ! boot.R_DemoLoadingFreeze( true, stage ), 'signon packet allowed at stage' + stage ); check( boot.R_DemoLoadingFreeze( true, 4 ), 'post-signon first attract held' ); check( ! boot.R_DemoLoadingFreeze( true, 4, true ), 'timed demo never frozen' ); boot.R_DemoLoadingAppReady(); boot.R_DemoLoadingConsoleDrawn(); boot.R_DemoLoadingSplash( () => Promise.reject( new Error( 'optional splash DOM gone' ) ) ); await new Promise( resolve => setTimeout( resolve, 0 ) ); check( boot.R_DemoLoadingStatus().fadeDone, 'splash failure reaches terminal fallback' ); boot.R_DemoLoadingCancel();
} );
Deno.test( 'actual loading DOM fades only on its opacity transition; unrelated events do not remove it and missing/reduced-motion pages terminate', async () => {
	const savedRaf = Object.getOwnPropertyDescriptor( globalThis, 'requestAnimationFrame' ), savedMedia = Object.getOwnPropertyDescriptor( globalThis, 'matchMedia' ); let begin, removed = 0, end; const element = { style: {}, addEventListener: ( name, fn ) => { same( name, 'transitionend', 'event owns fade' ); end = fn; }, removeEventListener: () => {}, remove: () => { removed ++; } }, doc = { getElementById: () => element };
	try { globalThis.requestAnimationFrame = fn => { begin = fn; }; globalThis.matchMedia = () => ( { matches: false } ); const done = LoadingScreen_FadeOut( doc, 20 ); same( element.style.opacity, '1', 'opaque until a rendered frame boundary' ); same( removed, 0, 'not removed immediately' ); begin(); same( element.style.opacity, '0', 'actual next-frame fade target' ); end( { target: {}, propertyName: 'opacity' } ); end( { target: element, propertyName: 'transform' } ); same( removed, 0, 'unrelated transition cannot end fade' ); end( { target: element, propertyName: 'opacity' } ); await done; same( removed, 1, 'own opacity event completes exactly once' ); await LoadingScreen_FadeOut( { getElementById: () => null } ); globalThis.matchMedia = () => ( { matches: true } ); const reduced = LoadingScreen_FadeOut( doc ); begin(); await reduced; same( removed, 2, 'reduced motion removes immediately at same frame boundary' ); }
	finally { if ( savedRaf ) Object.defineProperty( globalThis, 'requestAnimationFrame', savedRaf ); else delete globalThis.requestAnimationFrame; if ( savedMedia ) Object.defineProperty( globalThis, 'matchMedia', savedMedia ); else delete globalThis.matchMedia; boot.R_DemoLoadingCancel(); }
} );

Deno.test( 'actual first-attract client freezes both clip time and packet cursor after native signon, screen renders behind full native console then rolls away only when terminal', async () => {
	const canvas = await import( process.env.QUAKED_CANVAS_MODULE || '/Users/bri/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/@napi-rs/canvas/index.js' ), draw = await import( '../src/gl_draw.js' ), consoleUI = await import( '../src/console.js' ), screen = await import( '../src/gl_screen.js' ), client = await import( '../src/cl_main.js' ), demo = await import( '../src/cl_demo.js' ), cmd = await import( '../src/cmd.js' ), vars = await import( '../src/cvar.js' ), post = await import( '../src/gl_post.js' ), host = await import( '../src/host.js' ), state = await import( '../src/client.js' ), pak = await import( '../src/pak.js' ), vid = await import( '../src/vid.js' ), wad = await import( '../src/wad.js' ), common = await import( '../src/common.js' ), keys = await import( '../src/keys.js' ), protocol = await import( '../src/protocol.js' );
	const oldWindow = Object.getOwnPropertyDescriptor( globalThis, 'window' ), oldDocument = Object.getOwnPropertyDescriptor( globalThis, 'document' ); let rendered = 0;
	globalThis.window = { devicePixelRatio: 1, innerWidth: 640, innerHeight: 400 }; globalThis.document = { createElement: tag => { same( tag, 'canvas', 'native draw only creates canvas' ); return canvas.createCanvas( 1, 1 ); } };
	try {
		const binary = await Deno.readFile( new URL( '../pak0.pak', import.meta.url ) ); pak.COM_AddPack( pak.COM_LoadPackFile( 'boot-public-native-pak', binary.buffer.slice( binary.byteOffset, binary.byteOffset + binary.length ) ) ); vid.VID_SetPalette( pak.COM_FindFile( 'gfx/palette.lmp' ).data ); const wadBytes = pak.COM_FindFile( 'gfx.wad' ).data; wad.W_LoadWadFile( wadBytes.buffer.slice( wadBytes.byteOffset, wadBytes.byteOffset + wadBytes.length ) );
		const network = await import( '../src/net.js' ); common.SZ_Alloc( network.net_message, 65536 ); common.COM_SetNetMessage( network.net_message ); cmd.Cbuf_Init(); cmd.Cmd_Init(); client.CL_Init(); const overlay = canvas.createCanvas( 640, 400 ); draw.Draw_SetExternals( { vid: { width: 640, height: 400 }, host_basepal: pak.COM_FindFile( 'gfx/palette.lmp' ).data } ); draw.Draw_Init( overlay ); consoleUI.Con_SetExternals( { cls: state.cls, getRealtime: () => 100, Draw_Character: draw.Draw_Character, Draw_ConsoleBackground: draw.Draw_ConsoleBackground } ); consoleUI.Con_Init(); common.Con_SetPrintFunctions( consoleUI.Con_Printf, () => {} ); screen.SCR_SetExternals( { cls: state.cls, cl: state.cl, vid: { width: 640, height: 400, recalc_refdef: true }, V_RenderView: () => { rendered ++; }, V_UpdatePalette: () => {} } ); screen.SCR_Init(); if ( !vars.Cvar_FindVar( post.r_hdr.name ) ) vars.Cvar_RegisterVariable( post.r_hdr ); vars.Cvar_SetValue( 'r_hdr', 1 ); keys.set_key_dest( keys.key_game ); host.set_host_frametime( .02 );
		function packet( bytes ) { const out = new Uint8Array( 16 + bytes.length ); new DataView( out.buffer ).setInt32( 0, bytes.length, true ); out.set( bytes, 16 ); return out; }
		const timeBytes = new Uint8Array( 5 ); timeBytes[ 0 ] = protocol.svc_time; new DataView( timeBytes.buffer ).setFloat32( 1, 1, true ); const signon = packet( new Uint8Array( [ protocol.svc_signonnum, 4 ] ) ), timed = packet( timeBytes ), header = new TextEncoder().encode( '-1\n' ), clip = new Uint8Array( header.length + signon.length + timed.length ); clip.set( header ); clip.set( signon, header.length ); clip.set( timed, header.length + signon.length );
		boot.R_DemoLoadingBoot(); demo.CL_PlayDemoFromData( clip.buffer, true ); same( state.cls.signon, 0, 'actual attract begins before signon' ); client.CL_ReadFromServer(); same( state.cls.signon, 4, 'actual native signon packet proceeds during loading' ); same( state.cls.demopos, header.length + signon.length, 'first timed packet retained until readiness' );
		const frozen = { time: state.cl.time, oldtime: state.cl.oldtime, cursor: state.cls.demopos }; for ( let frame = 0; frame < 5; frame ++ ) { client.CL_ReadFromServer(); same( state.cl.time, frozen.time, 'public client time held' ); same( state.cl.oldtime, frozen.oldtime, 'public oldtime held' ); same( state.cls.demopos, frozen.cursor, 'public demo file cursor held' ); }
		state.cl.worldmodel = { name: 'maps/boot-test.bsp' }; consoleUI.Con_Printf( 'Preparing actual enhanced demo\n' ); screen.SCR_UpdateScreen(); check( rendered > 0, 'real screen endpoint calls hidden renderer while held' ); check( boot.R_DemoLoadingStatus().consoleSeen, 'actual screen console draw notifies boot' ); const fullHeight = draw.Draw_GetVirtualHeight(); same( screen.scr_con_current, fullHeight, 'startup shows full native console despite enhanced mode' ); const nativePixel = overlay.getContext( '2d' ).getImageData( 320, 200, 1, 1 ).data; same( nativePixel[ 3 ], 255, 'native console drawn opaquely over hidden renderer' );
		await splash(); boot.R_DemoLoadingFrame( { ...settled(), world: state.cl.worldmodel.name, pending: [ 'point cube' ] } ); screen.SCR_UpdateScreen(); same( screen.scr_con_current, fullHeight, 'pending renderer work cannot roll console up' ); for ( let i = 0; i < 3; i ++ ) boot.R_DemoLoadingFrame( { ...settled(), world: state.cl.worldmodel.name } ); same( boot.R_DemoLoadingStatus().phase, 'rolling', 'terminal actual frames permit native rollup' ); screen.SCR_UpdateScreen(); check( screen.scr_con_current > 0 && screen.scr_con_current < fullHeight, 'native console moves rather than instant enhanced hide' );
		const beforeResume = state.cls.demopos; client.CL_ReadFromServer(); check( state.cls.demopos > beforeResume, 'exact retained clip resumes after readiness' ); same( state.cl.mtime[ 0 ], 1, 'retained native time packet parsed, not skipped' );
		for ( let i = 0; i < 80 && boot.R_DemoLoadingStatus().phase !== 'done'; i ++ ) screen.SCR_UpdateScreen(); same( screen.scr_con_current, 0, 'native console eventually rolls closed' ); same( boot.R_DemoLoadingStatus().phase, 'done', 'real screen closes startup scope' );
	} finally { boot.R_DemoLoadingCancel(); demo.CL_StopPlayback(); if ( oldWindow ) Object.defineProperty( globalThis, 'window', oldWindow ); else delete globalThis.window; if ( oldDocument ) Object.defineProperty( globalThis, 'document', oldDocument ); else delete globalThis.document; }
} );

Deno.test( 'actual manual and timed playback commands permanently bypass first-demo scope, and stopping first attract cannot rearm a later loop', async () => {
	const demo = await import( '../src/cl_demo.js' ), cmd = await import( '../src/cmd.js' ), state = await import( '../src/client.js' ), pak = await import( '../src/pak.js' ); const bytes = new TextEncoder().encode( '-1\n' ); pak.COM_AddPack( { filename: 'startup-public-intent-memory', data: bytes.buffer, files: [ { name: 'startup_intent.dem', filepos: 0, filelen: bytes.length } ] } );
	try { boot.R_DemoLoadingBoot(); demo.CL_PlayDemoFromData( bytes.buffer, false ); same( boot.R_DemoLoadingStatus().phase, 'done', 'actual manual/file playback cancels permanently' ); demo.CL_StopPlayback(); demo.CL_PlayDemoFromData( bytes.buffer, true ); same( boot.R_DemoLoadingStatus().phase, 'done', 'later actual attract never rearms after manual playback' ); demo.CL_StopPlayback(); boot.R_DemoLoadingBoot(); cmd.Cmd_ExecuteString( 'timedemo startup_intent', cmd.src_command ); check( state.cls.demoplayback && state.cls.timedemo, 'actual public timed intent entered' ); same( boot.R_DemoLoadingStatus().phase, 'done', 'actual timed command bypasses startup console/hold' ); demo.CL_StopPlayback(); boot.R_DemoLoadingBoot(); demo.CL_PlayDemoFromData( bytes.buffer, true ); same( boot.R_DemoLoadingStatus().phase, 'warming', 'actual first attract activated' ); demo.CL_StopPlayback(); same( boot.R_DemoLoadingStatus().phase, 'done', 'public StopPlayback cancels startup' ); demo.CL_PlayDemoFromData( bytes.buffer, true ); same( boot.R_DemoLoadingStatus().phase, 'done', 'second actual attract has established timing/presentation' ); } finally { demo.CL_StopPlayback(); boot.R_DemoLoadingCancel(); }
} );

Deno.test( 'welcome has an opaque native plaque with hidden draws, blocks public movement but sends reliable handshakes, and releases without demo console/fade or changing ordinary crossings', async () => {
	const canvas = await import( process.env.QUAKED_CANVAS_MODULE || '/Users/bri/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/@napi-rs/canvas/index.js' ), draw = await import( '../src/gl_draw.js' ), screen = await import( '../src/gl_screen.js' ), state = await import( '../src/client.js' ), client = await import( '../src/cl_main.js' ), common = await import( '../src/common.js' ), network = await import( '../src/net.js' ), vars = await import( '../src/cvar.js' ), keys = await import( '../src/keys.js' );
	const oldWindow = Object.getOwnPropertyDescriptor( globalThis, 'window' ), oldDocument = Object.getOwnPropertyDescriptor( globalThis, 'document' ), driver = network.net_drivers[ 7 ], oldDriver = { ...driver }, saved = { state: state.cls.state, demo: state.cls.demoplayback, signon: state.cls.signon, socket: state.cls.netcon, world: state.cl.worldmodel, messages: state.cl.movemessages }; let reliable = 0, moves = 0, rendered = 0;
	globalThis.window = { devicePixelRatio: 1, innerWidth: 640, innerHeight: 400 }; globalThis.document = { createElement: () => canvas.createCanvas( 1, 1 ) };
	try {
		const overlay = canvas.createCanvas( 640, 400 ); draw.Draw_Init( overlay ); screen.SCR_SetExternals( { cls: state.cls, cl: state.cl, vid: { width: 640, height: 400, recalc_refdef: true }, V_RenderView: () => rendered ++ } ); state.cls.state = state.ca_connected; state.cls.demoplayback = false; state.cls.signon = 4; state.cl.worldmodel = { name: 'maps/welcome-test.bsp' }; state.cl.movemessages = 4; vars.Cvar_SetValue( 'r_hdr', 1 ); keys.set_key_dest( keys.key_game );
		driver.initialized = true; driver.CanSendMessage = () => true; driver.QSendMessage = ( socket, message ) => { reliable ++; check( message.cursize > 0, 'real reliable packet supplied to transport' ); return 1; }; driver.SendUnreliableMessage = () => { moves ++; return 1; }; state.cls.netcon = { driver: 7, disconnected: false };
		boot.R_DemoLoadingBoot(); boot.R_DemoLoadingCancel(); boot.R_DemoLoadingWelcome(); same( boot.R_DemoLoadingStatus().mode, 'welcome', 'fresh game rearms welcome after demo cancellation' ); check( boot.R_WelcomeLoadingHolding() && boot.R_IntroLoadingHolding(), 'fresh game strict readiness scope' ); check( ! boot.R_DemoLoadingConsoleOverride() && ! boot.R_DemoLoadingFreeze( true, 4 ), 'game welcome does not borrow demo console/timing' );
		screen.SCR_UpdateScreen(); check( rendered > 0, 'actual welcome screen warms hidden world' ); same( screen.scr_con_current, 0, 'welcome shows no demo/native console' ); const top = overlay.getContext( '2d' ).getImageData( 8, 8, 1, 1 ).data; same( top[ 3 ], 255, 'actual welcome artwork backed by opaque full viewport' ); same( top[ 0 ] + top[ 1 ] + top[ 2 ], 0, 'native palette0 backing hides unready world' );
		common.SZ_Clear( state.cls.message ); common.MSG_WriteByte( state.cls.message, 4 ); const beforeMove = state.cl.movemessages; client.CL_SendCmd(); same( state.cl.movemessages, beforeMove, 'public command path emits no movement during welcome' ); same( moves, 0, 'movement never reaches actual transport callback' ); same( reliable, 1, 'reliable signon/input-independent channel still advances' ); same( state.cls.message.cursize, 0, 'reliable send clears acknowledged outgoing buffer' );
		boot.R_DemoLoadingFrame( { ...settled(), world: state.cl.worldmodel.name, pending: [ 'weapon image decode' ] } ); check( boot.R_WelcomeLoadingHolding(), 'pending world art still holds welcome' ); for ( let i = 0; i < 3; i ++ ) boot.R_DemoLoadingFrame( { ...settled(), world: state.cl.worldmodel.name } ); same( boot.R_DemoLoadingStatus().phase, 'done', 'welcome terminal frames release directly without console/fade prerequisite' ); client.CL_SendCmd(); same( moves, 1, 'same public input endpoint resumes movement after readiness' );
		state.cls.signon = 0; state.cl.worldmodel = null; const drawsBeforeCross = rendered; check( screen.SCR_ChangingLevel(), 'ordinary enhanced transition retains previous-world behavior' ); screen.SCR_UpdateScreen(); same( rendered, drawsBeforeCross, 'ordinary crossing retains old frame without hidden startup loop' ); same( boot.R_DemoLoadingStatus().phase, 'done', 'ordinary crossing cannot rearm welcome' );
	} finally { boot.R_DemoLoadingCancel(); Object.assign( driver, oldDriver ); state.cls.state = saved.state; state.cls.demoplayback = saved.demo; state.cls.signon = saved.signon; state.cls.netcon = saved.socket; state.cl.worldmodel = saved.world; state.cl.movemessages = saved.messages; if ( oldWindow ) Object.defineProperty( globalThis, 'window', oldWindow ); else delete globalThis.window; if ( oldDocument ) Object.defineProperty( globalThis, 'document', oldDocument ); else delete globalThis.document; }
} );

Deno.test( 'real Host_ServerFrame holds native world physics only for single-player welcome while reliable preparation continues, then native time advances normally', async () => {
	const model = await import( '../src/gl_model.js' ), progs = await import( '../src/progs.js' ), builtins = await import( '../src/pr_cmds.js' ), server = await import( '../src/server.js' ), sv = await import( '../src/sv_main.js' ), physics = await import( '../src/sv_phys.js' ), host = await import( '../src/host.js' ), vars = await import( '../src/cvar.js' ), keys = await import( '../src/keys.js' );
	try {
		model.Mod_Init(); builtins.PR_InitBuiltins(); if ( ! vars.Cvar_FindVar( physics.sv_gravity.name ) ) vars.Cvar_RegisterVariable( physics.sv_gravity ); vars.Cvar_SetValue( 'r_hdr', 1 ); server.svs.maxclients = 1; server.svs.clients = [ new server.client_t() ]; server.sv.active = false; sv.SV_SpawnServer( 'start' ); check( server.sv.active, 'real native START server initialized' ); keys.set_key_dest( keys.key_game ); host.set_host_frametime( .02 ); boot.R_DemoLoadingWelcome();
		const time = server.sv.time; server.sv.datagram.cursize = 5; server.sv.reliable_datagram.cursize = 5; host.Host_ServerFrame(); same( server.sv.time, time, 'actual native world time does not advance while welcome holds' ); same( server.sv.datagram.cursize, 0, 'normal host datagram setup still runs' ); same( server.sv.reliable_datagram.cursize, 0, 'normal reliable preparation/send stage still drains queued frame data' );
		boot.R_DemoLoadingCancel(); host.Host_ServerFrame(); check( Math.abs( server.sv.time - time - .02 ) < 1e-8, 'same real native physics advances after terminal release' );
	} finally { boot.R_DemoLoadingCancel(); server.sv.active = false; }
} );

Deno.test( 'public collector excludes disabled stale shadow/rock/demon caches and lists only the caller enabled asset roles', () => {
	const stale = { assets: [], rock: { active: false, pending: 8, missingVisibleTiles: 9, preparedState: 'loading' }, demon: { enabled: false, pending: 2 }, shadows: { pending: 8, spotReady: false, error: 'old map cube error' }, captureEnabled: false, spotOn: true, water: { pending: 0 } }, before = JSON.stringify( stale ), result = boot.R_IntroReadinessChecks( stale ); same( result.pending.length, 0, 'disabled lighting/point shadow or material toggles cannot hold on stale statuses' ); same( result.fallbacks.length, 0, 'disabled stale shadow error is not current initialization failure' ); same( JSON.stringify( stale ), before, 'collector does not mutate actual renderer status snapshots' );
	const enabled = boot.R_IntroReadinessChecks( { ...stale, assets: [ [ 'status bar', { settled: false } ] ] } ); same( enabled.pending.join(), 'status bar', 'actual enabled asset role remains independently required' );
} );

Deno.test( 'partial native asset failures cannot conceal other pending images or current source-shadow retries; frame stays held until both finish', () => {
	boot.R_DemoLoadingWelcome(); const frame = { assets: [ [ 'textures', { settled: false, failures: { failedWall: '404; native retained' } } ], [ 'enemy and item art', { settled: true, errors: { ogre: 'optional height failed; native/generated retained' } } ] ], captureEnabled: true, spotOn: true, shadows: { pending: 1, spotReady: false, error: 'cube capture interrupted', spotError: 'spot capture interrupted' } }, incomplete = boot.R_IntroReadinessChecks( frame ); check( incomplete.pending.includes( 'textures' ) && incomplete.pending.includes( 'source shadows' ), 'unsettled wall and shadow still block independently of fallback' ); check( incomplete.fallbacks.some( f => f.includes( 'failedWall' ) ) && incomplete.fallbacks.some( f => f.includes( 'ogre' ) ) && incomplete.fallbacks.some( f => f.includes( 'retrying' ) ), 'required native fallback/retry diagnostics retained' ); for ( let i = 0; i < 5; i ++ ) boot.R_DemoLoadingFrame( { ...settled(), ...incomplete } ); check( boot.R_WelcomeLoadingHolding(), 'terminal failure in one item never releases unrelated pending work' );
	const complete = boot.R_IntroReadinessChecks( { ...frame, assets: frame.assets.map( ( [ name, s ] ) => [ name, { ...s, settled: true } ] ), shadows: { pending: 0, spotReady: true } } ); same( complete.pending.length, 0, 'completed retries and native fallbacks are terminal' ); for ( let i = 0; i < 3; i ++ ) boot.R_DemoLoadingFrame( { ...settled(), ...complete } ); same( boot.R_DemoLoadingStatus().phase, 'done', 'all terminal assets release after stable draws' );
} );

Deno.test( 'terminal failed visible rock tiles release to native fallback while other missing tiles/jobs/prepared requests continue to block', () => {
	const terminal = { active: true, preparedState: 'ready', pending: 0, missingVisibleTiles: 2, failedVisibleTiles: 2, failedTiles: 2 }, fallback = boot.R_IntroReadinessChecks( { rock: terminal } ); same( fallback.pending.length, 0, 'all missing visible tiles are terminal native fallback' ); check( fallback.fallbacks.some( f => f.includes( '2 failed tiles' ) ), 'native relief fallback explicitly reported' );
	for ( const unfinished of [ { ...terminal, missingVisibleTiles: 3 }, { ...terminal, pending: 1 }, { ...terminal, preparedState: 'loading' }, { ...terminal, error: 'worker stopped', pending: 1 }, { ...terminal, error: 'worker stopped', preparedState: 'loading' } ] ) check( boot.R_IntroReadinessChecks( { rock: unfinished } ).pending.includes( 'continuous rock relief' ), 'partial failure cannot suppress independent unfinished rock work' );
	const failedGlobal = boot.R_IntroReadinessChecks( { rock: { ...terminal, error: 'all workers unavailable', pending: 0, preparedState: 'fallback' } } ); same( failedGlobal.pending.length, 0, 'global terminal native fallback does not deadlock on impossible missing tiles' ); check( failedGlobal.fallbacks.some( f => f.includes( 'all workers unavailable' ) ), 'global terminal failure visible' );
} );

Deno.test( 'GPU shader completion, sculpted surfaces and visible water remain independent readiness blockers despite optional shader failure diagnostics', () => {
	const frame = { assets: [ [ 'weapon models', { settled: true } ] ], shaderPending: true, shaderFailure: 'optional warm variant failed', demon: { enabled: true, pending: 1 }, water: { pending: 2 } }, result = boot.R_IntroReadinessChecks( frame ); same( result.pending.sort().join(), [ 'GPU shaders', 'sculpted surfaces', 'water reflections' ].sort().join(), 'all actual draw prerequisites independently awaited' ); check( result.fallbacks.some( f => f.includes( 'optional warm variant failed' ) ), 'GPU fallback diagnostics survive pending state' );
	const finished = boot.R_IntroReadinessChecks( { ...frame, shaderPending: false, demon: { enabled: true, pending: 0 }, water: { pending: 0 } } ); same( finished.pending.length, 0, 'all completed native/loaded prerequisites are terminal' ); boot.R_DemoLoadingCancel();
} );
