// Public prepared-displacement format/transport contracts. Synthetic map bytes
// isolate identity and corruption; native BSP/world draw coverage is separate.
import {createHash} from 'node:crypto';
import {DemonBakeEncode,DemonBakeDecode,DemonSurfaceSignature,DemonFieldSettings} from '../src/newer/assets/demon_bake_format.js';
import {DEMON_BAKES} from '../src/newer/assets/demon_bakes.js';
import {R_DemonBakePrefetch,R_DemonBakePrepare,R_DemonBakeSurface,R_DemonBakeRelease} from '../src/newer/assets/r_demonbakes.js';
import {R_DemonSurfaceData} from '../src/newer/render/r_demonrelief.js';
import {COM_AddPack,COM_FindFile} from '../src/engine/common/pak.js';
import {R_IntroReadinessChecks} from '../src/r_demoloading.js';
const check=(v,m)=>{if(!v)throw Error(m);},same=(a,b,m)=>check(a===b,`${m}: ${a} != ${b}`),bytes=a=>Buffer.from(a.buffer,a.byteOffset,a.byteLength),sha=a=>createHash('sha256').update(a instanceof ArrayBuffer?new Uint8Array(a):a).digest('hex'),ab=a=>a.buffer.slice(a.byteOffset,a.byteOffset+a.byteLength),turn=()=>new Promise(r=>setTimeout(r,0));
async function until(predicate,label){for(let i=0;i<100&&!predicate();i++)await turn();check(predicate(),label);}
const makeSurface=()=>{const field={width:2,height:2,data:new Float32Array([.1,.2,.3,.4]),sampling:'clamp',displacement:{depth:4,step:2,smoothing:0}};return{flags:0,plane:{normal:[0,0,1],dist:0},texinfo:{texture:{name:'dem4_1',width:64,height:128,gl_texture:{userData:{newerHeight:field}}},vecs:[[8,0,0,0],[0,16,0,0]]},polys:{numverts:3,verts:new Float32Array([0,0,0,0,0,.1,.2,8,0,0,1,0,.2,.2,0,8,0,0,1,.1,.3]),next:null}};};
const fieldOf=s=>s.texinfo.texture.gl_texture.userData.newerHeight;
const record=s=>({signature:DemonSurfaceSignature(s),settings:DemonFieldSettings(fieldOf(s)),fieldSha256:sha(fieldOf(s).data),data:R_DemonSurfaceData(s)});
function metadata(raw){const view=new DataView(raw.buffer,raw.byteOffset,raw.byteLength),length=view.getUint32(4,true);return{meta:JSON.parse(new TextDecoder().decode(raw.subarray(8,8+length))),start:(8+length+3)&~3};}
function rewrite(raw,mutate){const {meta,start}=metadata(raw);mutate(meta);const header=new TextEncoder().encode(JSON.stringify(meta)),next=(8+header.length+3)&~3,out=new Uint8Array(next+raw.length-start),view=new DataView(out.buffer);view.setUint32(0,0x31424451,true);view.setUint32(4,header.length,true);out.set(header,8);out.set(raw.subarray(start),next);return out;}
function rejects(fn,label){let error;try{fn();}catch(e){error=e;}check(error instanceof Error,label+' rejected instead of publishing geometry');}
Deno.test('prepared tuple-bit dedup restores exact Float32 signed-zero bits, complete attributes, triangle order and closed-skirt metadata',()=>{
 same(R_DemonBakeSurface({texinfo:{texture:{}}})?.status,'unprepared','ordinary world surface without a height field has an explicit safe state');same(R_DemonBakeSurface({flags:0,polys:{numverts:0,verts:[]}})?.status,'unprepared','anonymous procedural polygon needs no texture metadata');same(R_DemonBakePrepare({surfaces:[]},[]).status,'unprepared','anonymous procedural world remains supported unprepared input');
 const s=makeSurface(),r=record(s),raw=DemonBakeEncode({model:'maps/exact.bsp',bspSha256:'source'},[r]),decoded=DemonBakeDecode(ab(raw),'maps/exact.bsp','source').records.get(r.signature);check(decoded,'surface signature retained');same(decoded.settings,r.settings,'exact authored recipe retained');same(decoded.fieldSha256,r.fieldSha256,'height source identity retained');for(const name of ['positions','normals','uvs','lmuvs'])check(bytes(decoded.data[name]).equals(bytes(r.data[name])),'all '+name+' bits and original triangle order retained');for(const name of ['triangles','topVertexCount','skirtTriangles','tileRegions'])same(JSON.stringify(decoded.data[name]),JSON.stringify(r.data[name]),'exact '+name+' retained');check(r.data.skirtTriangles>0,'real fixture contains closed skirts');
 const data={positions:new Float32Array([0,0,0,1,0,0,0,1,0,-0,0,0,0,1,0,1,0,0]),normals:new Float32Array([0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1]),uvs:new Float32Array([0,0,1,0,0,1,0,0,0,1,1,0]),lmuvs:new Float32Array([0,0,1,0,0,1,0,0,0,1,1,0]),triangles:2,topVertexCount:6,skirtTriangles:0,tileRegions:[{origin:[0,0],startVertex:0,endVertex:6}]};
 const signed=DemonBakeEncode({model:'maps/bits.bsp',bspSha256:'s'},[{signature:'bits',settings:'{}',fieldSha256:'height',data}]);same(metadata(signed).meta.records[0].unique,4,'signed-zero tuple cannot incorrectly merge with positive-zero vertex');const restored=DemonBakeDecode(ab(signed),'maps/bits.bsp','s').records.get('bits').data;check(Object.is(restored.positions[9],-0),'negative-zero bit survives serialization');for(const name of ['positions','normals','uvs','lmuvs'])check(bytes(restored[name]).equals(bytes(data[name])),name+' byte-exact after duplicate-index reconstruction');
});
Deno.test('decoder rejects mismatched source, malformed sizes/indices/samples and nested region boundaries before publishing any data',()=>{
 const r=record(makeSurface()),raw=DemonBakeEncode({model:'maps/bounded.bsp',bspSha256:'s'},[r]),decode=b=>DemonBakeDecode(ab(b),'maps/bounded.bsp','s');
 rejects(()=>DemonBakeDecode(ab(raw),'maps/other.bsp','s'),'different model');rejects(()=>DemonBakeDecode(ab(raw),'maps/bounded.bsp','other'),'different BSP hash');rejects(()=>decode(raw.subarray(0,7)),'short header');rejects(()=>decode(raw.subarray(0,-1)),'truncated payload');rejects(()=>decode(new Uint8Array([...raw,0])),'trailing bytes');
 const changes=[['wrong version',m=>m.version++],['duplicate signature',m=>m.records.push({...m.records[0]})],['negative offset',m=>m.records[0].offset=-4],['overlapping offset',m=>m.records[0].offset=4],['excessive vertex count',m=>m.records[0].vertices=786435],['fractional unique count',m=>m.records[0].unique=.5],['triangle disagreement',m=>m.records[0].triangles++],['top boundary outside data',m=>m.records[0].topVertexCount=m.records[0].vertices+3],['skirt disagreement',m=>m.records[0].skirtTriangles++],['unaligned region start',m=>m.records[0].tileRegions[0].startVertex=1],['region beyond top',m=>m.records[0].tileRegions[0].endVertex=m.records[0].topVertexCount+3],['missing top region coverage',m=>m.records[0].tileRegions=[]],['nonfinite origin',m=>m.records[0].tileRegions[0].origin=[null,0]],['invalid origin shape',m=>m.records[0].tileRegions[0].origin=[0]]];
 for(const [label,mutate]of changes)rejects(()=>decode(rewrite(raw,mutate)),label);
 const tiny={...r.data,positions:r.data.positions.slice(0,3),normals:r.data.normals.slice(0,3),uvs:r.data.uvs.slice(0,2),lmuvs:r.data.lmuvs.slice(0,2),triangles:1/3,topVertexCount:0,skirtTriangles:1/3,tileRegions:[]};rejects(()=>decode(DemonBakeEncode({model:'maps/bounded.bsp',bspSha256:'s'},[{...r,data:tiny}])),'self-consistent fractional triangle topology');
 const {meta,start}=metadata(raw),badIndex=raw.slice();new DataView(badIndex.buffer).setUint32(start+meta.records[0].unique*40,meta.records[0].unique,true);rejects(()=>decode(badIndex),'index outside packed vertices');const badValue=raw.slice();new DataView(badValue.buffer).setUint32(start,0x7fc00001,true);rejects(()=>decode(badValue),'nonfinite packed position');
});
let serial=0;
function fixture(){const name='maps/prepared-displacement-public-'+(++serial)+'.bsp',storage=new Uint8Array(64);for(let i=0;i<storage.length;i++)storage[i]=(i*13+serial)%251;const source=storage.subarray(11,31),surface=makeSurface(),r=record(surface),raw=DemonBakeEncode({model:name,bspSha256:sha(source)},[r]);DEMON_BAKES[name]=[{bspSha256:sha(source),file:'newer/displacement/public-'+serial+'.gz',sha256:'compressed-fixture',rawSha256:sha(raw)}];COM_AddPack({data:storage.buffer,files:[{name,filepos:11,filelen:20}]});return{name,source,storage,surface,raw,model:{name},cleanup(){R_DemonBakeRelease();delete DEMON_BAKES[name];}};}
Deno.test('prepared transport shares exact native byte subviews and validates surface settings/height before publishing reusable geometry',async()=>{
 const f=fixture();let requests=0;try{const entry=R_DemonBakePrefetch(f.name,f.source,async()=>{requests++;return ab(f.raw);});same(R_DemonBakePrefetch(f.name,new Uint8Array(f.storage.buffer,11,20)),entry,'same underlying source range shares transport despite a fresh view object');same(R_DemonBakePrepare(f.model,[f.surface]),entry,'public COM source resolves to prefetched native identity');same(R_DemonBakeSurface(f.surface).data,null,'transport cannot publish early geometry');await entry.promise;same(entry.status,'ready','validated source/payload decode completes');R_DemonBakePrepare(f.model,[f.surface]);same(R_DemonBakeSurface(f.surface).status,'loading','height validation remains independently pending');await until(()=>R_DemonBakeSurface(f.surface).status!=='loading','height hash completes');const state=R_DemonBakeSurface(f.surface);same(state.status,'ready','actual recipe/signature/height agree');const expected=R_DemonSurfaceData(f.surface);for(const key of ['positions','normals','uvs','lmuvs'])check(bytes(state.data[key]).equals(bytes(expected[key])),'prepared '+key+' exactly equals existing public generator');R_DemonBakePrepare(f.model,[f.surface]);same(R_DemonBakeSurface(f.surface).data,state.data,'repeated valid preparation reuses exact decoded arrays');same(requests,1,'one actual load');check(R_IntroReadinessChecks({demon:{enabled:true,pending:1}}).pending.includes('sculpted surfaces'),'decoded data never bypasses real scene readiness');}finally{f.cleanup();}
});
Deno.test('different source bytes at the same filename and subviews never borrow prepared geometry, while known corruption is an explicit blocking error',async()=>{
 const f=fixture();try{let called=0;const unrelated=f.storage.subarray(12,32),other=R_DemonBakePrefetch(f.name,unrelated,async()=>{called++;return ab(f.raw);});await other.promise;same(other.status,'unprepared','same name with other actual bytes uses generator fallback');same(called,0,'unprepared custom BSP never fetches incompatible payload');const corrupt=R_DemonBakePrefetch(f.name,f.source,async()=>{const out=f.raw.slice();out[out.length-1]^=1;return ab(out);});await corrupt.promise;same(corrupt.status,'error','known source corrupt payload is not relabeled unprepared');check(corrupt.error.includes('checksum'),'checksum diagnostic retained');R_DemonBakePrepare(f.model,[f.surface]);same(R_DemonBakeSurface(f.surface).status,'error','surface keeps known prepared failure authority');same(R_DemonBakeSurface(f.surface).data,null,'corruption cannot publish any prepared geometry');check(R_IntroReadinessChecks({demon:{enabled:true,pending:1}}).pending.includes('sculpted surfaces'),'failure does not fabricate completed sculpt readiness');}finally{f.cleanup();}
});
Deno.test('changed recipes, native polygon signatures and height bytes cannot inherit a previously validated prepared surface',async()=>{
 for(const change of ['recipe-in-place','geometry','height']){const f=fixture();try{const entry=R_DemonBakePrefetch(f.name,f.source,async()=>ab(f.raw));await entry.promise;R_DemonBakePrepare(f.model,[f.surface]);await until(()=>R_DemonBakeSurface(f.surface).status==='ready','initial valid field ready');if(change==='recipe-in-place')fieldOf(f.surface).displacement.depth=5;else if(change==='geometry')f.surface.polys.verts[0]+=1;else{const old=fieldOf(f.surface);f.surface.texinfo.texture.gl_texture.userData.newerHeight={...old,data:old.data.slice()};fieldOf(f.surface).data[0]=.9;}R_DemonBakePrepare(f.model,[f.surface]);await until(()=>R_DemonBakeSurface(f.surface).status!=='loading','changed source reaches terminal decision');same(R_DemonBakeSurface(f.surface).status,'error',change+' cannot silently reuse incompatible recipe/geometry/height');same(R_DemonBakeSurface(f.surface).data,null,change+' leaves only original native backing');}finally{f.cleanup();}}
});
Deno.test('late obsolete field hash completion cannot overwrite a replacement field decision, and evicted active transports still finish safely',async()=>{
 const f=fixture(),others=[];let release;try{const entry=R_DemonBakePrefetch(f.name,f.source,()=>new Promise(r=>release=()=>r(ab(f.raw))));await until(()=>!!release,'actual deferred load started');same(R_DemonBakePrepare(f.model,[f.surface]),entry,'actual current world pins in-flight transport');for(let i=0;i<3;i++){const next=fixture();others.push(next);const e=R_DemonBakePrefetch(next.name,next.source,async()=>ab(next.raw));await e.promise;}release();await entry.promise;same(entry.status,'ready','caller-held active entry completes after bounded cache eviction');
  // A fresh model needs its currently indexed transport after eviction; finish
  // that normal load before testing two concurrently scheduled field hashes.
  const active=R_DemonBakePrefetch(f.name,COM_FindFile(f.name).data,async()=>ab(f.raw));await active.promise;R_DemonBakePrepare(f.model,[f.surface]);const old=fieldOf(f.surface);f.surface.texinfo.texture.gl_texture.userData.newerHeight={...old,data:old.data.slice()};fieldOf(f.surface).data[1]=.99;R_DemonBakePrepare(f.model,[f.surface]);await until(()=>R_DemonBakeSurface(f.surface).status!=='loading','latest replacement hash completes');same(R_DemonBakeSurface(f.surface).status,'error','late old valid hash never reinstalls old field');same(R_DemonBakeSurface(f.surface).data,null,'latest rejected height remains native backing');
 }finally{f.cleanup();others.forEach(o=>o.cleanup());}
});
Deno.test('prepared transport deadline aborts its actual request and late fulfillment cannot promote the errored entry to ready',async()=>{
 const f=fixture(),original=globalThis.setTimeout;let expire,timer,release,signal;
 globalThis.setTimeout=(callback,ms,...args)=>{if(ms===10000){expire=callback;timer=original(()=>{},100000);return timer;}return original(callback,ms,...args);};
 try{const entry=R_DemonBakePrefetch(f.name,f.source,(_url,options)=>{signal=options.signal;return new Promise(r=>release=()=>r(ab(f.raw)));});await until(()=>!!release,'real request reaches timeout fixture');check(!signal.aborted,'request initially active');expire();await entry.promise;same(entry.status,'error','deadline cannot become ready/native-generation fallback');same(signal.aborted,true,'bounded loader aborts its real signal');check(entry.error.includes('timed out'),'timeout diagnostics retained');release();for(let i=0;i<5;i++)await turn();same(entry.status,'error','late response cannot resurrect timed-out generation');same(entry.data,null,'late geometry never published');}finally{globalThis.setTimeout=original;clearTimeout(timer);f.cleanup();}
});
Deno.test('reused native model objects rebind prepared authority when COM source bytes change at the same map name',async()=>{
 const f=fixture();f.model.bspSourceBytes=f.source;try{const entry=R_DemonBakePrefetch(f.name,f.source,async()=>ab(f.raw));await entry.promise;R_DemonBakePrepare(f.model,[f.surface]);await until(()=>R_DemonBakeSurface(f.surface).status==='ready','first model source ready');const replacement=f.storage.slice();replacement[11]^=127;COM_AddPack({data:replacement.buffer,files:[{name:f.name,filepos:11,filelen:20}]});
  // Native Mod_ClearAll/Mod_FindName reuse the model object across a reload;
  // source identity, not JavaScript model identity, owns prepared authority.
  same(R_DemonBakePrepare(f.model,[f.surface]),entry,'current model stays bound to loaded bytes even when lookup route changes');f.model.bspSourceBytes=COM_FindFile(f.name).data;const second=R_DemonBakePrepare(f.model,[f.surface]);await second.promise;R_DemonBakePrepare(f.model,[f.surface]);same(second.status,'unprepared','same-named custom BSP is recognized on reused model');same(R_DemonBakeSurface(f.surface).status,'unprepared','old validated surface decision cannot outlive its source');same(R_DemonBakeSurface(f.surface).data,null,'old campaign geometry cannot be returned for replacement source');
 }finally{f.cleanup();}
});
Deno.test('bounded eviction cancels unadmitted prefetch while copied identical content shares one validated decode',async()=>{
 const f=fixture(),others=[];let release,signal;try{const entry=R_DemonBakePrefetch(f.name,f.source,(_url,o)=>{signal=o.signal;return new Promise(r=>release=()=>r(ab(f.raw)));});await until(()=>!!release,'unadmitted transport starts');for(let i=0;i<3;i++){const other=fixture();others.push(other);await R_DemonBakePrefetch(other.name,other.source,async()=>ab(other.raw)).promise;}await entry.promise;same(entry.status,'error','LRU evicts unpinned work rather than unlimited background loads');same(signal.aborted,true,'eviction aborts actual request signal');check(entry.error.includes('evicted'),'eviction has explicit diagnostic');release();await turn();same(entry.data,null,'late evicted response never publishes old decode');
  let calls=0;const reload=R_DemonBakePrefetch(f.name,f.source,async()=>{calls++;return ab(f.raw);});await reload.promise;const copy=R_DemonBakePrefetch(f.name,f.source.slice(),async()=>{calls++;return ab(f.raw);});await copy.promise;same(copy.status,'ready','copied identical native bytes validate successfully');same(calls,1,'canonical content identity shares decoded transport across different buffers');same(copy.data,reload.data,'canonical arrays share exact decode identity');
 }finally{f.cleanup();others.forEach(o=>o.cleanup());}
});
