import * as THREE from 'three';
import {DemonBakeEncode,DemonBakeDecode,DemonFieldSettings,DemonSurfaceSignature} from '../src/demon_bake_format.js';
import {R_DemonSurfaceData} from '../src/r_demonrelief.js';
import {expandAttribute,compactGeometry,assertPointParity} from './helpers/compact_geometry_oracle.mjs';
const check=(v,m)=>{if(!v)throw Error(m);},same=(a,b,m)=>check(a===b,`${m}: ${a} != ${b}`),bytes=a=>Buffer.from(a.buffer,a.byteOffset,a.byteLength);
function fixture(){const field={width:2,height:2,data:new Float32Array([0,.2,.8,1]),sampling:'clamp',displacement:{depth:4,step:2}},surface={flags:0,plane:{normal:[0,0,1]},texinfo:{texture:{name:'dem4_1',width:64,height:128,gl_texture:{userData:{newerHeight:field}}},vecs:[[8,0,0,0],[0,16,0,0]]},polys:{numverts:3,verts:new Float32Array([0,0,0,0,0,0,0,8,0,0,1,0,1,0,0,8,0,0,1,0,1]),next:null}},data=R_DemonSurfaceData(surface);for(const name of ['positions','normals','uvs','lmuvs'])data[name][0]=-0;const signature=DemonSurfaceSignature(surface),raw=DemonBakeEncode({model:'maps/compact-test.bsp',bspSha256:'native-source'},[{signature,fieldSha256:'height',settings:DemonFieldSettings(field),data}]);return{data,raw,signature,decode:compact=>DemonBakeDecode(raw.buffer,'maps/compact-test.bsp','native-source',{compact}).records.get(signature).data};}
Deno.test('compact decoder keeps all four Float32 attributes and negative-zero bits exact while compatibility arrays allocate once only on explicit request',()=>{
 const f=fixture(),rawBefore=Buffer.from(f.raw),data=f.decode(true),expanded=f.decode(false);same(data.materializedAttributes,0,'decode does not allocate expanded arrays');same(data.interleaved.buffer,f.raw.buffer,'tuple views retain original whole payload');same(data.indices.buffer,f.raw.buffer,'index view retains same payload');same(data.payloadBytes,f.raw.byteLength,'retained accounting includes header and all packed bytes');same(data.gpuBytes,data.interleaved.byteLength+data.indices.byteLength,'GPU byte count distinct from retained payload');check(data.gpuBytes<f.data.positions.byteLength+f.data.normals.byteLength+f.data.uvs.byteLength+f.data.lmuvs.byteLength,'fixture actually has compact reuse');
 const names=['positions','normals','uvs','lmuvs'];for(let i=0;i<names.length;i++){const name=names[i],first=data[name];check(bytes(first).equals(bytes(expanded[name]))&&bytes(first).equals(bytes(f.data[name])),name+' exact original expanded byte order');check(Object.is(first[0],-0),name+' signed zero retained');same(data.materializedAttributes,i+1,name+' getter allocates one compatibility array');same(data[name],first,name+' getter caches requested array');same(data.materializedAttributes,i+1,name+' reread does not allocate');}check(Buffer.from(f.raw).equals(rawBefore),'compatibility materialization never changes packed authority');
 const invalid=f.raw.slice(),view=new DataView(invalid.buffer),headerLength=view.getUint32(4,true),meta=JSON.parse(new TextDecoder().decode(invalid.subarray(8,8+headerLength))),start=(8+headerLength+3)&~3,record=meta.records[0];view.setUint32(start+record.offset+record.unique*40,record.unique,true);let rejected=false;try{DemonBakeDecode(invalid.buffer,'maps/compact-test.bsp','native-source',{compact:true});}catch{rejected=true;}check(rejected,'compact mode retains strict packed index validation');
});
Deno.test('indexed compact geometry preserves triangle/raycast order, attributes and point chunks without touching compatibility getters',()=>{
 const f=fixture(),data=f.decode(true),compact=compactGeometry(data),expanded=new THREE.BufferGeometry();expanded.setAttribute('position',new THREE.BufferAttribute(f.data.positions,3));expanded.setAttribute('normal',new THREE.BufferAttribute(f.data.normals,3));expanded.setAttribute('uv',new THREE.BufferAttribute(f.data.uvs,2));expanded.setAttribute('uv1',new THREE.BufferAttribute(f.data.lmuvs,2));expanded.computeBoundingBox();expanded.computeBoundingSphere();const material=new THREE.MeshBasicMaterial({side:THREE.DoubleSide}),a=new THREE.Mesh(compact,material),b=new THREE.Mesh(expanded,material);a.updateMatrixWorld();b.updateMatrixWorld();
 try{for(const [attribute,name]of [['position','positions'],['normal','normals'],['uv','uvs'],['uv1','lmuvs']])check(bytes(expandAttribute(compact,attribute)).equals(bytes(f.data[name])),attribute+' exact indexed expansion');let nonempty=0;for(const [x,y]of [[1.3,1.8],[3.1,.8],[.5,5.2]]){const ray=new THREE.Raycaster(new THREE.Vector3(x,y,20),new THREE.Vector3(0,0,-1),0,40),describe=mesh=>ray.intersectObject(mesh).map(h=>({face:h.faceIndex,distance:h.distance,point:h.point.toArray(),uv:h.uv?.toArray(),normal:h.normal?.toArray()})),expected=describe(b),actual=describe(a);if(expected.length)nonempty++;same(JSON.stringify(actual),JSON.stringify(expected),'actual Three raycast preserves original hit/triangle/UV/normal order');}same(nonempty,3,'all raycast probes have positive actual intersections');assertPointParity(compact,expanded,'compact versus original nonindexed');same(data.materializedAttributes,0,'geometry, raycasts, bounds and shadows never invoke compatibility getters');
  const replacement=compactGeometry(data);check(replacement.attributes.position.data!==compact.attributes.position.data&&replacement.index!==compact.index,'rebuild owns independent Three attribute wrappers');compact.dispose();check(bytes(expandAttribute(replacement,'position')).equals(bytes(f.data.positions)),'disposing first geometry preserves shared immutable CPU tuples');same(data.materializedAttributes,0,'dispose/rebuild still does not expand');replacement.dispose();
 }finally{compact.dispose();expanded.dispose();material.dispose();}
});
