// Bounded, actual-browser OPFS proof. No game/main import, RAF, renderer,
// storage shim, cache clearing or private runtime mutation is used here.
const NAMESPACE='quaked-public-opfs-trial',TRIAL_VERSION=1,LIMIT_MS=20000;
const $=id=>document.getElementById(id),params=new URL(location.href).searchParams;
const proof=params.get('proof')||globalThis.crypto?.randomUUID?.()||'unsupported',pageID=globalThis.crypto?.randomUUID?.()||'unsupported',mode=params.get('phase')==='verify'?'verify':'write';
const creator=params.get('creator'),expectedOrigin=params.get('origin');let expected=null;
try{expected=params.has('expected')?JSON.parse(params.get('expected')):null;}catch{}
const receipt={trial:NAMESPACE,version:TRIAL_VERSION,proof,pageID,mode,origin:location.origin,creatorPageID:creator,started:new Date().toISOString(),limits:{actionTimeoutMS:LIMIT_MS,physicalBrowserRestartTested:false,gameRendererReadinessTested:false,storageBackend:'native browser OPFS',lockingBackend:'native browser Web Locks'},actions:[],errors:[]};
window.displacementStoreTrialReport=receipt;
$('origin').textContent=location.origin;$('proof').textContent=proof;$('page-id').textContent=pageID;
const freshURL=new URL(location.href);freshURL.search='';freshURL.hash='';$('new-proof').href=freshURL.href;
if(!params.has('proof')&&proof!=='unsupported'){const own=new URL(location.href);own.searchParams.set('proof',proof);own.searchParams.set('phase','write');history.replaceState(null,'',own);}
$('instructions').textContent=mode==='verify'?'This is a new-page check. Its generator throws on any cache miss. Click Verify disk reuse, then optionally check distinct input/version identities.':'Cold means this randomly named trial key is absent. After a successful write, open the verification link in a new page and click Verify disk reuse there.';
let store,api,format,relief,sources,baseResult=null,current=null;
const fail=(v,message)=>{if(!v)throw Error(message);};
function publish(){receipt.summary={completedActions:receipt.actions.length,allCompletedActionsPassed:receipt.actions.length>0&&receipt.actions.every(a=>a.status==='PASS')&&receipt.errors.length===0,coldKeyWritten:receipt.actions.some(a=>a.label==='Cold-key write and readback'&&a.status==='PASS'),freshPageDiskVerified:receipt.actions.some(a=>a.label==='Fresh-page disk reuse with generator trap'&&a.status==='PASS'),inputAndVersionRekeysVerified:receipt.actions.some(a=>a.label==='Changed input and version identities'&&a.status==='PASS'),physicalBrowserRestartTested:false};window.displacementStoreTrialReport=receipt;$('report').textContent=JSON.stringify(receipt,null,2);$('save').disabled=false;}
function status(text,state='idle'){$('status').textContent=text;$('status').dataset.state=state;}
function line(text){const li=document.createElement('li');li.textContent=text;$('checks').append(li);}
function buttons(){const idle=!current,ready=!!store;$('write').disabled=!(idle&&ready&&mode==='write');$('verify').disabled=!(idle&&ready&&mode==='verify');$('rekey').disabled=!(idle&&ready&&baseResult);$('cancel').disabled=idle;}
async function sourceHashes(hashAPI=api){const paths=['../src/newer/assets/displacement_store.js','../src/newer/assets/demon_bake_format.js','../src/newer/render/r_demonrelief.js','./displacement_store_trial.js'],result={};for(const path of paths){const url=new URL(path,import.meta.url);url.searchParams.set('opfsProof',proof);const response=await fetch(url,{cache:'no-store'});if(!response.ok)throw Error('Source read failed: '+url.pathname);result[url.pathname]=await hashAPI.DisplacementHash(await response.arrayBuffer());}return result;}
async function input(variant='base'){
 const generatorVersion=relief.DEMON_GENERATOR_VERSION+(variant==='version'?':public-version-2':''),depth=variant==='input'?5:4,model='maps/public-opfs-'+proof+'.bsp',source=new TextEncoder().encode(NAMESPACE+':'+proof),bspSha256=await api.DisplacementHash(source),field={width:2,height:2,sampling:'clamp',data:new Float32Array([.1,.3,.6,.9]),displacement:{depth,step:2,smoothing:0}},surface={flags:0,plane:{normal:[0,0,1],dist:0},texinfo:{texture:{name:'dem4_1',width:64,height:128,gl_texture:{userData:{newerHeight:field}}},vecs:[[8,0,0,0],[0,16,0,0]]},polys:{numverts:3,verts:new Float32Array([0,0,0,0,0,.1,.2,0,8,0,0,1,.1,.3,8,0,0,1,0,.2,.2]),next:null}},settings=format.DemonFieldSettings(field),signature=format.DemonSurfaceSignature(surface),fieldSha256=await api.DisplacementHash(field.data);
 const key=await api.DisplacementKey([NAMESPACE,TRIAL_VERSION,proof,generatorVersion,format.DEMON_BAKE_VERSION,model,bspSha256,signature,settings,fieldSha256]);return{variant,key,model,bspSha256,fieldSha256,settings,signature,generatorVersion,surface};
}
function decoder(info){return raw=>{const decoded=format.DemonBakeDecode(raw,info.model,info.bspSha256);fail(decoded.meta.trial===NAMESPACE&&decoded.meta.proof===proof&&decoded.meta.cacheKey===info.key,'Decoded file belongs to a different trial/key');fail(decoded.meta.generatorVersion===info.generatorVersion&&decoded.records.size===1,'Decoded generator version/coverage mismatch');const record=decoded.records.get(info.signature);fail(record&&record.settings===info.settings&&record.fieldSha256===info.fieldSha256,'Decoded surface inputs mismatch');return decoded;};}
function generate(info){const data=relief.R_DemonSurfaceData(info.surface);fail(data&&data.triangles>0,'Actual procedural generator returned no geometry');return format.DemonBakeEncode({model:info.model,bspSha256:info.bspSha256,trial:NAMESPACE,proof,cacheKey:info.key,generatorVersion:info.generatorVersion},[{signature:info.signature,settings:info.settings,fieldSha256:info.fieldSha256,data}]);}
async function describe(info,result){const data=result.data.records.get(info.signature).data,attributeHashes={};for(const name of ['positions','normals','uvs','lmuvs'])attributeHashes[name]=await api.DisplacementHash(data[name]);const root=await navigator.storage.getDirectory(),directory=await root.getDirectoryHandle('quaked-displacement-v1'),manifestFile=await(await directory.getFileHandle(info.key+'.json')).getFile(),payloadFile=await(await directory.getFileHandle(result.manifest.payloadSha256+'.gz')).getFile();fail(payloadFile.size===result.manifest.compressedBytes,'Actual closed OPFS payload size differs from manifest');fail(await api.DisplacementHash(await payloadFile.arrayBuffer())===result.manifest.payloadSha256,'Independent actual OPFS file checksum mismatch');
 return{key:info.key,source:result.source,persistence:result.persistence,generatorVersion:info.generatorVersion,formatVersion:format.DEMON_BAKE_VERSION,settings:info.settings,bspSha256:info.bspSha256,fieldSha256:info.fieldSha256,triangles:data.triangles,attributeHashes,manifest:result.manifest,files:{manifest:{name:info.key+'.json',bytes:manifestFile.size,lastModified:manifestFile.lastModified},payload:{name:result.manifest.payloadSha256+'.gz',bytes:payloadFile.size,lastModified:payloadFile.lastModified}}};}
function draw(data){const canvas=$('geometry'),ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);const p=data.positions,project=(x,y,z)=>[160+(x-y)*13,184-(x+y)*6-z*15];for(let i=0;i<p.length;i+=9){const z=(p[i+2]+p[i+5]+p[i+8])/3,shade=Math.max(55,Math.min(235,80+z*30));ctx.beginPath();for(let k=0;k<3;k++){const point=project(p[i+k*3],p[i+k*3+1],p[i+k*3+2]);if(k)ctx.lineTo(...point);else ctx.moveTo(...point);}ctx.closePath();ctx.fillStyle=`rgb(${shade},${shade},${shade})`;ctx.fill();ctx.strokeStyle='#698199';ctx.lineWidth=.4;ctx.stroke();}$('geometry-caption').textContent=`Decoded cache geometry: ${data.triangles} triangles, including ${data.skirtTriangles} closed-edge triangles.`;}
async function ensure(info,operation,forbidGeneration){let calls=0;const result=await store.ensure(info.key,{signal:operation.controller.signal,decode:decoder(info),generate:()=>{calls++;if(forbidGeneration)throw Error('Fresh-page cache miss: generation trap fired');return generate(info);},onPhase:phase=>{operation.phases.push({phase,ms:performance.now()-operation.start});if(current===operation)status(operation.label+' · '+phase,'running');}});return{result,calls};}
function verificationLink(summary){const url=new URL(location.href);url.search='';url.searchParams.set('proof',proof);url.searchParams.set('phase','verify');url.searchParams.set('creator',pageID);url.searchParams.set('origin',location.origin);url.searchParams.set('expected',JSON.stringify({key:summary.key,rawSha256:summary.manifest.rawSha256,attributeHashes:summary.attributeHashes,sourceHashes:sources}));$('new-page').href=url.href;$('new-page').hidden=false;receipt.verificationURL=url.href;}
async function run(label,work){if(current)return;const operation={label,start:performance.now(),controller:new AbortController(),phases:[]};current=operation;buttons();let timeout;const timedOut=new Promise((_,reject)=>{timeout=setTimeout(()=>{operation.controller.abort();reject(Error('Bounded action timed out after20seconds'));},LIMIT_MS);});try{const details=await Promise.race([work(operation),timedOut]);receipt.actions.push({label,status:'PASS',elapsedMS:performance.now()-operation.start,phases:operation.phases,...details});status(label+' · PASS','pass');line(label+' — PASS');}catch(error){receipt.actions.push({label,status:'FAIL',elapsedMS:performance.now()-operation.start,phases:operation.phases,error:String(error.message||error)});receipt.errors.push({label,name:error.name,message:String(error.message||error)});status(label+' · '+String(error.message||error),'fail');line(label+' — FAIL: '+String(error.message||error));}finally{clearTimeout(timeout);current=null;buttons();publish();}}
$('write').addEventListener('click',()=>run('Cold-key write and readback',async operation=>{const info=await input();fail(await store.read(info.key,decoder(info),operation.controller.signal)===null,'This proof key already exists; Start a fresh proof for a cold write');const {result,calls}=await ensure(info,operation,false);fail(result.source==='generated-and-stored'&&calls===1,'Cold write did not perform exactly one committed generation');const summary=await describe(info,result);baseResult={info,result,summary};draw(result.data.records.get(info.signature).data);verificationLink(summary);return{coldKey:true,generatorCalls:calls,...summary};}));
$('verify').addEventListener('click',()=>run('Fresh-page disk reuse with generator trap',async operation=>{fail(expected&&creator&&expectedOrigin,'Use the verification link from a successful write page');fail(creator!==pageID,'Verification requires a different page instance');fail(location.origin===expectedOrigin,'Verification moved to another storage origin');fail(JSON.stringify(sources)===JSON.stringify(expected.sourceHashes),'Producer source changed between the two page checks');const info=await input();fail(info.key===expected.key,'Current inputs no longer select the recorded key');const {result,calls}=await ensure(info,operation,true);fail(result.source==='disk'&&calls===0,'Fresh page failed to reuse disk with zero generation');const summary=await describe(info,result);fail(summary.manifest.rawSha256===expected.rawSha256,'Fresh-page bytes differ from recorded first-page bytes');for(const [name,hash]of Object.entries(expected.attributeHashes))fail(summary.attributeHashes[name]===hash,'Fresh-page '+name+' bytes differ');baseResult={info,result,summary};draw(result.data.records.get(info.signature).data);return{sameOrigin:true,freshPage:true,creatorPageID:creator,generatorCalls:calls,physicalBrowserRestartTested:false,...summary};}));
$('rekey').addEventListener('click',()=>run('Changed input and version identities',async operation=>{fail(baseResult,'Complete a base write or verification first');const records=[];for(const variant of ['input','version']){const info=await input(variant);fail(info.key!==baseResult.info.key,'Changed '+variant+' retained original key');fail(!records.some(r=>r.key===info.key),'Input and version changes selected the same key');const prior=await store.read(info.key,decoder(info),operation.controller.signal),{result,calls}=await ensure(info,operation,false);fail(calls===(prior?0:1),'Unexpected generation count for '+variant);const summary=await describe(info,result);if(variant==='input')fail(summary.attributeHashes.positions!==baseResult.summary.attributeHashes.positions,'Depth change did not alter actual geometry');else for(const name of Object.keys(summary.attributeHashes))fail(summary.attributeHashes[name]===baseResult.summary.attributeHashes[name],'Version-only key change altered deterministic '+name);records.push({variant,previouslyPresent:!!prior,generatorCalls:calls,...summary});}return{baseKey:baseResult.info.key,records};}));
$('cancel').addEventListener('click',()=>current?.controller.abort());
$('save').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(receipt,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`quaked-opfs-${proof}-${mode}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
let initializationTimer;
try{fail(globalThis.isSecureContext&&navigator.storage?.getDirectory&&navigator.locks?.request&&globalThis.crypto?.subtle&&globalThis.CompressionStream&&globalThis.DecompressionStream,'This origin lacks required secure OPFS/Web-Locks/compression APIs');fail(/^[0-9a-f-]{36}$/i.test(proof),'Invalid trial identifier');const dependency=path=>{const url=new URL(path,import.meta.url);url.searchParams.set('opfsProof',proof);return url.href;};const initialized=await Promise.race([(async()=>{const modules=await Promise.all([import(dependency('../src/newer/assets/displacement_store.js')),import(dependency('../src/newer/assets/demon_bake_format.js')),import(dependency('../src/newer/render/r_demonrelief.js'))]);return{modules,hashes:await sourceHashes(modules[0])};})(),new Promise((_,reject)=>{initializationTimer=setTimeout(()=>reject(Error('Initialization timed out after20seconds')),LIMIT_MS);})]);[api,format,relief]=initialized.modules;sources=initialized.hashes;receipt.sourceHashes=sources;receipt.environment={secureContext:isSecureContext,userAgent:navigator.userAgent,opfs:true,webLocks:true};store=new api.DisplacementStore();status(mode==='verify'?'Ready to verify from this new page.':'Ready to create a fresh test key.');buttons();publish();}catch(error){receipt.errors.push({label:'Initialization',name:error.name,message:String(error.message||error)});status(String(error.message||error),'fail');publish();}finally{clearTimeout(initializationTimer);}
