// (look names are the artwork's own, from the character's point of view: head_right/eyes_right look toward the screen's left)
// Independent public controller contracts. All times are game seconds; no
// wall-clock sleeps, renderer, input mocks or production-state inspection.
import { FaceState } from '../src/face_state.js';
const check=(value,label)=>{if(!value)throw new Error(label);};
const same=(actual,expected,label)=>check(actual===expected,`${label}: ${actual} != ${expected}`);
const create=(random=()=>0)=>new FaceState({random});
const sample=(state,time,extra={})=>state.frame({time,health:100,...extra});
const lookIndex={head_right:0,eyes_right:1,front:2,eyes_left:3,head_left:4};

Deno.test('impact angle boundaries use five ordered poses and immediate expressions with adjacent-only reaction movement',()=>{
 const cases=[[-180,'front'],[-165,'front'],[-164.999,'head_right'],[-45.001,'head_right'],[-45,'eyes_right'],[-15.001,'eyes_right'],[-15,'front'],[0,'front'],[15,'front'],[15.001,'eyes_left'],[45,'eyes_left'],[45.001,'head_left'],[164.999,'head_left'],[165,'front'],[180,'front'],[null,'front']];
 for(const[angle,expected]of cases){const state=create();state.reset(0);state.damage({time:0,healthLoss:1,angle});const immediate=sample(state,0);same(immediate.expression,'pain','damage expression appears in the same frame');same(immediate.look,'front','expression does not skip pose traversal');let previous=immediate.look;for(const time of[.04,.08,.12,.16]){const next=sample(state,time);check(Math.abs(lookIndex[next.look]-lookIndex[previous])<=1,'every rendered reaction step is adjacent');previous=next.look;}same(previous,expected,'signed right-relative angle '+angle);}
 const state=create();state.reset(0);state.damage({time:0,healthLoss:1,angle:90});same(sample(state,.039).look,'front','reaction waits forty milliseconds');same(sample(state,.04).look,'eyes_left','first reaction step');same(sample(state,.08).look,'head_left','second reaction step');state.damage({time:.1,healthLoss:2,angle:-90});same(sample(state,.1).look,'head_left','opposite reaction never teleports');const visited=[.14,.18,.22,.26].map(t=>sample(state,t).look);same(visited.join(','),'eyes_left,front,eyes_right,head_right','opposite head traverses every neighboring pose');const delayed=create();delayed.reset(0);delayed.damage({time:0,healthLoss:1,angle:90});sample(delayed,0);same(sample(delayed,.5).look,'eyes_left','a delayed rendered frame still crosses only one neighbor');same(sample(delayed,.501).look,'eyes_left','large elapsed time does not queue immediate skipped poses');same(sample(delayed,.54).look,'head_left','next adjacent pose waits its real interval');
});

Deno.test('two-hundred millisecond damage direction arbitration picks greatest damage and latest tie without delaying pain',()=>{
 const state=create();state.reset(0);state.damage({time:0,healthLoss:5,amount:30,angle:-90});sample(state,0);sample(state,.04);sample(state,.08);
 state.damage({time:.1,healthLoss:2,amount:10,angle:90});same(sample(state,.1).expression,'pain','smaller impact still starts pain immediately');state.damage({time:.15,healthLoss:2,amount:15,angle:90});same(sample(state,.18).look,'head_right','smaller accumulated directional total cannot take direction');
 state.damage({time:.19,healthLoss:2,amount:6,angle:90});sample(state,.19);for(const t of[.23,.27,.31,.35])sample(state,t);same(sample(state,.36).look,'head_left','accumulated right pellets beat the larger individual left hit within window');
 state.damage({time:.401,healthLoss:1,amount:1,angle:-90});sample(state,.401);for(const t of[.441,.481,.521,.561])sample(state,t);same(sample(state,.57).look,'head_right','expired dominance cannot suppress a new small direction');const tie=create();tie.reset(0);tie.damage({time:0,healthLoss:1,amount:20,angle:-90});sample(tie,0);sample(tie,.04);sample(tie,.08);tie.damage({time:.1,healthLoss:1,amount:10,angle:90});sample(tie,.1);tie.damage({time:.19,healthLoss:1,amount:10,angle:90});sample(tie,.19);for(const t of[.23,.27,.31,.35])sample(tie,t);same(sample(tie,.36).look,'head_left','latest hit wins exactly equal directional totals');
});

Deno.test('direction holds one second; pain lasts point-two seconds and heavy shock uses actual health loss above twenty without small-hit refresh',()=>{
 const state=create();state.reset(0);state.damage({time:0,healthLoss:20,amount:100,angle:90});sample(state,0);sample(state,.04);sample(state,.08);same(sample(state,.199).expression,'pain','twenty health loss remains pain');same(sample(state,.201).expression,'normal','pain ends after point-two seconds');same(sample(state,.999).look,'head_left','impact direction held for one second');sample(state,1);same(sample(state,1.08).look,'eyes_left','return traverses adjacent normal-speed step');same(sample(state,1.16).look,'front','normal return finishes through front');
 const heavy=create();heavy.reset(0);heavy.damage({time:0,healthLoss:21,amount:21,angle:-90});same(sample(heavy,0).expression,'shocked','strictly over twenty actual health is heavy');heavy.damage({time:.7,healthLoss:2,amount:80,angle:90});same(sample(heavy,.7).expression,'shocked','small health hit cannot replace active shock');same(sample(heavy,.999).expression,'shocked','shock retains its original full second');same(sample(heavy,1.001).expression,'normal','small hit cannot extend original shock');
});

Deno.test('idle glances are bounded eye-only events independent of movement and return through the front',()=>{
 for(const random of[()=>0,()=>.999999]){const a=create(random),b=create(random);a.reset(0);b.reset(0);let onset=null,end=null;for(let tick=0;tick<=400;tick++){const time=tick/100,x=sample(a,time),y=sample(b,time,{moving:tick%2===0});same(x.look,y.look,'movement does not drive idle animation');check(['eyes_right','front','eyes_left'].includes(x.look),'idle never turns whole head');if(x.look!=='front'&&onset===null)onset=time;if(onset!==null&&x.look==='front'&&end===null)end=time;}check(onset!==null&&onset>=1.5&&onset<=3.09,'idle begins in requested interval plus adjacent transition');check(end!==null&&end-onset>=.29&&end-onset<=.69,'eye glance returns within hold plus adjacent transition');}
});

Deno.test('focused firing requires two seconds of real fresh shot cadence, stops after point-three, and ignores attack without actual shots',()=>{
 const dry=create();dry.reset(0);for(let t=0;t<4;t+=.1)check(sample(dry,t,{attacking:true}).expression!=='focused_determined','unusable held attack never fabricates firing');
 const state=create();state.reset(0);for(let i=0;i<=19;i++){const t=i*.1;state.shot({time:t,cadence:.1});check(sample(state,t,{attacking:true}).expression!=='focused_determined','no focus before sustained two seconds');}state.shot({time:2,cadence:.1});same(sample(state,2,{attacking:true}).expression,'focused_determined','actual sustained fire becomes focused at two seconds');same(sample(state,2.1,{attacking:false}).expression,'focused_determined','release retains brief focused tail');for(const t of[2.15,2.25,2.35,2.399,2.401,2.45,2.59]){const x=sample(state,t,{attacking:false});same(x.expression,t<2.4?'focused_determined':'normal','focused tail ends point-three after observed stop');same(x.look,'front','idle eye activity suppressed immediately after fire stops');}
 const sporadic=create();sporadic.reset(0);for(const t of[0,1,2,3]){sporadic.shot({time:t,cadence:.1});check(sample(sporadic,t,{attacking:true}).expression!=='focused_determined','widely separated real shots do not count as continuous fire');}
});

Deno.test('reward grin lasts two seconds without recentering, powers coexist with each health band, and death freezes then respawn resets',()=>{
 const state=create();state.reset(0);state.damage({time:0,healthLoss:1,angle:90});sample(state,0);sample(state,.04);sample(state,.08);state.reward(.3);same(sample(state,.3).expression,'mischievous_excited','reward immediately grins');same(sample(state,.3).look,'head_left','reward does not recenter recent direction');same(sample(state,2.299).expression,'mischievous_excited','grin lasts exactly requested two seconds');same(sample(state,2.301).expression,'normal','reward expires without queued later celebrations');
 for(const hp of[100,91,90,81,80,71,70,61,60,51,50,41,40,31,30,21,20,11,10,1]){const x=sample(state,3,{health:hp,strength:true,invulnerability:true,invisibility:true});same(x.health,Math.min(10,Math.floor((100-hp)/10)+1),'health band '+hp);check(x.strength&&x.invulnerability&&x.invisibility,'all power layers coexist with health '+hp);same(x.healthPercent,hp,'health percent retained');}
 const dying=create();dying.reset(0);dying.damage({time:0,healthLoss:1,angle:-90});sample(dying,0);sample(dying,.04);sample(dying,.08);const death=sample(dying,.1,{health:0});check(death.dead,'zero health enters death');same(death.look,'head_right','death freezes current head');same(death.expression,'focused_determined','v4.4 death uses focused expression');same(death.eyeState,'dead','death holds supplied closed eyes');dying.damage({time:.3,healthLoss:30,angle:90});dying.reward(.4);dying.shot({time:.5,cadence:.1});for(const t of[.6,1,3,10])same(sample(dying,t,{health:0}).look,death.look,'dead state never animates to a later event');const respawn=sample(dying,11,{health:100});check(!respawn.dead,'positive health exits death');same(respawn.look,'front','respawn resets direction');same(respawn.expression,'normal','respawn removes old reactions');same(respawn.health,1,'respawn restores healthy overlay selection');
});

Deno.test('reaction priorities override grin and focus while all expression deadlines continue independently',()=>{
 const state=create();state.reset(0);for(let i=0;i<=20;i++){state.shot({time:i*.1,cadence:.1});sample(state,i*.1,{attacking:true});}same(sample(state,2,{attacking:true}).expression,'focused_determined','actual sustained focus control');state.reward(2.01);same(sample(state,2.01,{attacking:true}).expression,'mischievous_excited','reward grin overrides ongoing focus');state.damage({time:2.02,healthLoss:1,angle:0});same(sample(state,2.02,{attacking:true}).expression,'pain','immediate pain overrides grin');state.damage({time:2.05,healthLoss:21,angle:0});same(sample(state,2.05,{attacking:true}).expression,'shocked','heavy shock overrides other expressions');
 for(let i=21;i<=42;i++){const t=i*.1;state.shot({time:t,cadence:.1});same(sample(state,t,{attacking:true}).expression,t<3.05?'shocked':t<4.01?'mischievous_excited':'focused_determined','independent priority and expiry at '+t);}
 const expired=create();expired.reset(0);expired.reward(0);expired.damage({time:.1,healthLoss:21,angle:0});sample(expired,.1);expired.damage({time:1,healthLoss:21,angle:0});sample(expired,1);same(sample(expired,2.001).expression,'normal','celebration that expires under reactions is never queued for later');
});
Deno.test('same-direction pellets do not restart adjacent steps and repeated rewards replace their deadline rather than queue',()=>{
 const state=create();state.reset(0);state.damage({time:0,healthLoss:1,angle:90});sample(state,0);state.damage({time:.02,healthLoss:1,angle:90});same(sample(state,.02).look,'front','early repeated hit waits original step');same(sample(state,.04).look,'eyes_left','same target does not restart forty-ms clock');state.damage({time:.06,healthLoss:1,angle:90});same(sample(state,.06).look,'eyes_left','second same-target hit retains current pose');same(sample(state,.08).look,'head_left','second original step is not delayed');state.reward(.1);sample(state,.1);state.reward(1);same(sample(state,2.99).expression,'mischievous_excited','second reward sets its own two-second deadline');same(sample(state,3.001).expression,'normal','rewards never accumulate queued duration');
});
Deno.test('paused game time freezes reactions and pose progress; backward clocks reset old state safely',()=>{
 const state=create();state.reset(0);state.damage({time:0,healthLoss:21,angle:90});sample(state,0);const paused=sample(state,.1);for(let i=0;i<20;i++)same(JSON.stringify(sample(state,.1)),JSON.stringify(paused),'same game time never advances pose or reaction deadlines');const restored=sample(state,-.5);same(restored.look,'front','clock restoration resets front');same(restored.expression,'normal','future damage reaction cannot leak into restored clock');same(sample(state,.999).look,'front','idle delay restarts from restored time');
});
Deno.test('queued observations retain true impact windows and expired event deadlines without rewinding display time',()=>{
 const state=create();state.reset(10);state.damage({time:9.7,receivedTime:10,impactTime:100,healthLoss:1,amount:30,angle:-90});state.damage({time:9.95,receivedTime:10,impactTime:100.25,healthLoss:1,amount:1,angle:90});same(sample(state,10).expression,'pain','recent queued event retains remaining pain time');same(sample(state,10.04).look,'eyes_left','events received together still use actual impact separation');same(sample(state,10.08).look,'head_left','old dominant hit outside real200ms cannot win');same(sample(state,10.151).expression,'normal','queued pain expires by original mapped event time');
 state.reward(1,10.16);same(sample(state,10.16).expression,'normal','old queued celebration expires instead of replaying');same(sample(state,10.16).look,'head_left','old event receipt never rewinds and resets live pose');state.shot({time:1,receivedTime:10.17,cadence:.1});check(sample(state,10.17,{attacking:true}).expression!=='focused_determined','old queued shot cannot fabricate fresh sustained fire');
});
