// Real Canvas2D compositor with controlled image completion/failure. A missing
// water atlas or interior mask must never publish a completed water portrait.
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {validatePlayerFaceManifest} from '../src/playerface_manifest.js';
const canvas=await import(process.env.QUAKED_CANVAS_MODULE||'/Users/bri/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/@napi-rs/canvas/index.js'),manifest=JSON.parse(readFileSync(new URL('../newer/hud/playerface/manifest.json',import.meta.url)));
let serial=0;const flush=async()=>{for(let i=0;i<20;i++)await Promise.resolve();};
async function fixture(run){const descriptors=Object.fromEntries(['Image','document'].map(key=>[key,Object.getOwnPropertyDescriptor(globalThis,key)])),oldFetch=globalThis.fetch,requests=[];class ControlledImage extends canvas.Image{set src(value){this.url=value;if(value)requests.push(this);}get src(){return this.url;}deliver(){super.src=new URL(String(this.url).split('?')[0]).pathname;}}
 Object.defineProperty(globalThis,'Image',{configurable:true,value:ControlledImage});Object.defineProperty(globalThis,'document',{configurable:true,value:{createElement:()=>canvas.createCanvas(96,96)}});globalThis.fetch=async()=>({ok:true,json:async()=>manifest});try{await run(await import('../src/r_playerface.js?v44-readiness-'+ ++serial),requests);}finally{globalThis.fetch=oldFetch;for(const key of['Image','document'])if(descriptors[key])Object.defineProperty(globalThis,key,descriptors[key]);else delete globalThis[key];}}
const state={expression:'normal',look:'front',health:5,eyeState:'open',strength:true,invulnerability:true,invisibility:true,waterPercent:60,waterOpacity:50};
Deno.test('v4.4 preload starts every referenced source once and remains unready while the final mask is missing',()=>fixture(async(face,requests)=>{
 const work=face.R_PlayerFacePreload();assert.equal(face.R_PlayerFacePreload(),work);await flush();assert.equal(requests.length,270);assert.equal(new Set(requests.map(r=>r.url)).size,270);const last=requests.find(r=>r.url.includes('/water_mask_helmet_front.png'));assert.ok(last);for(const image of requests.filter(r=>r!==last))image.deliver();await Promise.all(requests.filter(r=>r!==last).map(image=>image.decode()));assert.equal(face.R_PlayerFaceStatus().settled,false);assert.equal(face.R_PlayerFaceCompose(state).complete,false,'last mask remains genuine readiness dependency');last.deliver();await work;assert.equal(face.R_PlayerFaceStatus().state,'ready');assert.equal(face.R_PlayerFaceCompose(state).complete,true);const count=requests.length;await face.R_PlayerFacePreload();assert.equal(requests.length,count,'warm readiness reuses loaded resources');
}));
for(const missing of['water_shared_atlas','water_mask_helmet_front'])Deno.test('missing '+missing+' settles fallback and late callbacks never cache incomplete water',()=>fixture(async(face,requests)=>{
 const work=face.R_PlayerFacePreload();await flush();const target=requests.find(r=>r.url.includes('/'+missing+'.png'));assert.ok(target);const late=target.onload;for(const image of requests.filter(r=>r!==target))image.deliver();target.onerror(new Error('controlled missing source'));await work;assert.equal(face.R_PlayerFaceStatus().state,'fallback');assert.ok(face.R_PlayerFaceStatus().errors.includes(missing));const wet=face.R_PlayerFaceCompose(state);assert.equal(wet.complete,false);assert.ok(wet.missing.includes('water'));assert.equal(face.R_PlayerFaceCompose({...state,waterPercent:0}).complete,true,'unaffected dry face remains complete');assert.equal(face.R_PlayerFaceCompose({...state,waterOpacity:0}).complete,true,'fully clear water requests no missing layer');late();await flush();assert.equal(face.R_PlayerFaceCompose(state).complete,false,'late success cannot publish failed atlas/mask');const count=requests.length;await face.R_PlayerFacePreload();assert.equal(requests.length,count,'terminal failure initiates no retry wave');
}));
Deno.test('v4.4 validator rejects malformed mandatory health eye power water and layer registrations',()=>{
 assert.equal(validatePlayerFaceManifest(manifest),manifest);const mutations=[m=>delete m.health.stages,m=>m.health.stages.pop(),m=>m.health.stages[0].default_percent=NaN,m=>delete m.eye_states,m=>m.eye_states.dead=null,m=>delete m.power_modes.purple,m=>m.water.frames[0].asset=null,m=>m.water.targets.helmet_front.mask_asset=null,m=>m.water.targets.helmet_front.rect[2]=0,m=>m.assets[0].source_rect[2]=1e9,m=>m.assets[0].source='absent',m=>m.assets[0]={...m.assets[0],parts:[{asset:m.assets[0].id}]},m=>m.poses[0].closure_layers.dead=null,m=>m.poses[0].equipment_layers.diving_suit=null,m=>m.assets[0].available=false];for(const[caseIndex,mutate]of mutations.entries()){const changed=structuredClone(manifest);mutate(changed);assert.throws(()=>validatePlayerFaceManifest(changed),/invalid v4.4.0 face manifest/,'malformed mandatory registration '+caseIndex);}
});
Deno.test('every canonical pose identity rejects renamed IDs or mismatched look expression and head direction before publishing',async()=>{
 const mutations={id:pose=>{pose.id='unknown_'+pose.id;},look:pose=>{pose.look=pose.look==='front'?'eyes_left':'front';},expression:pose=>{pose.expression=pose.expression==='normal'?'pain':'normal';},head_direction:pose=>{pose.head_direction=pose.head_direction==='front'?'left':'front';}};
 for(let poseIndex=0;poseIndex<manifest.poses.length;poseIndex++)for(const[field,mutate]of Object.entries(mutations)){const changed=structuredClone(manifest);mutate(changed.poses[poseIndex]);assert.equal(changed.poses.length,25,'malformed fixture preserves pose count');assert.equal(new Set(changed.poses.map(pose=>pose.id)).size,25,'malformed fixture preserves unique IDs');assert.throws(()=>validatePlayerFaceManifest(changed),/invalid v4.4.0 face manifest/,manifest.poses[poseIndex].id+' mismatched '+field);}
 for(const[field,mutate]of Object.entries(mutations))await fixture(async(face,requests)=>{const changed=structuredClone(manifest);mutate(changed.poses[0]);globalThis.fetch=async()=>({ok:true,json:async()=>changed});await face.R_PlayerFacePreload();assert.equal(face.R_PlayerFaceStatus().state,'fallback',field+' mismatch cannot publish ready state');assert.equal(face.R_PlayerFaceStatus().settled,true,field+' invalid schema settles bounded fallback');assert.equal(requests.length,0,field+' invalid schema starts no image wave');assert.equal(face.R_PlayerFaceCompose(state).complete,false,field+' invalid schema cannot produce a completed face');});
});
