// Independent public/native controls for the six exit-corridor fixtures.
// Literal geometry/helper facts were read from bundled E1M1 before the change.
// Renderer endpoints record real pipeline calls; this is not a GPU/image test.
import * as THREE from 'three';
import {createHash} from 'node:crypto';
import {memberSearch,readMember,isolatedPack} from '../tools/pak_members.mjs';
import {COM_AddPack,COM_FindFile} from '../src/engine/common/pak.js';
import {Mod_Init,Mod_ForName,Mod_PointInLeaf} from '../src/engine/render/gl_model.js';
import {VID_SetPalette,vid} from '../src/engine/render/vid.js';
import {GL_BuildLightmaps} from '../src/engine/render/gl_rsurf.js';
import {R_ParseEntityLump} from '../src/newer/render/gl_portal.js';
import {cl} from '../src/engine/client/client.js';
import * as post from '../src/newer/render/gl_post.js';
import * as height from '../src/newer/render/r_heightshadows.js';
import * as anim from '../src/newer/render/r_anim.js';
import * as vars from '../src/engine/common/cvar.js';
import {R_KnownFixtureSource,R_ExitFixturePairs,R_LightCone,R_LightConeFactor} from '../src/newer/render/r_fixturelights.js';

const check=(v,m)=>{if(!v)throw Error(m);},same=(a,b,m)=>check(a===b,`${m}: ${a} != ${b}`),near=(a,b,m,e=1e-9)=>check(Math.abs(a-b)<=e,`${m}: ${a} != ${b}`),vector=(a,b,m)=>{same(a.length,b.length,m+' length');a.forEach((v,i)=>near(v,b[i],m+' component'+i));},sha=b=>createHash('sha256').update(b).digest('hex');
const BSP_SHA='7b7061ec63c3e8ecb9c0e0a8075f18823efea6578666d57d601c191bcaf16c26';
const FIXTURES=[
 {face:2763,center:[1312,1648,-304],helper:[1312,1648,-392],light:220,floor:-432},
 {face:2795,center:[1312,1520,-304],helper:[1312,1520,-392],light:170,floor:-432},
 {face:2852,center:[1312,1392,-272],helper:[1312,1392,-352],light:170,floor:-416},
 {face:2867,center:[1312,1264,-208],helper:[1312,1264,-288],light:170,floor:-352},
 {face:3023,center:[1312,1136,-144],helper:[1312,1136,-232],light:300,floor:-288},
 {face:3050,center:[1312,960,-144],helper:[1312,960,-208],light:300,floor:-280}
];
const expectedClusters=[[1312,1648,-314],[1312,1456,-298],[1312,1264,-218],[1312,1048,-154]];
let nativePromise;
async function native(){if(!nativePromise)nativePromise=(async()=>{
 const entries=await memberSearch([new URL('../pak0.pak',import.meta.url).pathname]),palette=await readMember(entries.get('gfx/palette.lmp')),bytes=await readMember(entries.get('maps/e1m1.bsp'));same(sha(bytes),BSP_SHA,'actual bundled BSP SHA');COM_AddPack(isolatedPack('gfx/palette.lmp',palette));COM_AddPack(isolatedPack('maps/e1m1.bsp',bytes));VID_SetPalette(COM_FindFile('gfx/palette.lmp').data);vid.fullbright=224;Mod_Init();const model=Mod_ForName('maps/e1m1.bsp',true);cl.worldmodel=model;cl.model_precache[1]=model;cl.model_precache[2]=null;GL_BuildLightmaps();same(sha(model.bspSourceBytes),BSP_SHA,'public model loaded same native bytes');return{model,entities:R_ParseEntityLump(model.entities)};
 })();return nativePromise;}
function points(surface){const p=surface.polys;return Array.from({length:p.numverts},(_,i)=>[0,1,2].map(k=>p.verts instanceof Float32Array?p.verts[i*7+k]:p.verts[i][k]));}
function bounds(surface){const p=points(surface);return[...Array.from({length:3},(_,a)=>Math.min(...p.map(v=>v[a]))),...Array.from({length:3},(_,a)=>Math.max(...p.map(v=>v[a])))];}
function info(surface){const b=bounds(surface);return{center:[0,1,2].map(a=>(b[a]+b[a+3])/2)};}
const callbacks={info,bounds,leaf:Mod_PointInLeaf};
function nativeBytes(model){return{source:sha(model.bspSourceBytes),entities:model.entities,faces:FIXTURES.map(f=>{const s=model.surfaces[f.face];return{plane:Array.from(s.plane.normal),flags:s.flags,styles:Array.from(s.styles),polys:Array.from(s.polys.verts),pixels:sha(new Uint8Array(s.texinfo.texture.gl_texture.image.data.buffer,s.texinfo.texture.gl_texture.image.data.byteOffset,s.texinfo.texture.gl_texture.image.data.byteLength))};})};}
function sourceSnapshot(l){return{pos:Array.from(l.pos),classname:l.classname,texture:l.texture,emitter:l.emitter,power:l.power,style:l.style,radius:l.radius,color:Array.from(l.color),flicker:l.flicker};}
const equalJSON=(a,b,m)=>same(JSON.stringify(a),JSON.stringify(b),m);

Deno.test('actual native E1M1 collector moves exactly six existing helpers, preserves authored radiance/style and removes only their four duplicate emission clusters',async()=>{
 const {model,entities}=await native(),before=nativeBytes(model),fallback=post.R_BuildWorldLights({...model,name:'maps/unknown-fixture-source.bsp'}),nativeEntities=fallback.filter(l=>l.classname),actual=post.R_BuildWorldLights(model),fixtures=actual.filter(l=>l.fixture);
 same(R_KnownFixtureSource(model),true,'source admission positive');same(fixtures.length,6,'exact six existing sources matched');same(actual.filter(l=>l.classname).length,nativeEntities.length,'no additional native/entity lamps');same(actual.length,fallback.length-4,'only four former combined surface clusters suppressed');
 for(const fact of FIXTURES){const s=model.surfaces[fact.face],lamp=fixtures.find(l=>l.fixture.face===fact.face),entity=entities.find(e=>e.classname==='light'&&e.origin?.split(/\s+/).map(Number).join()===fact.helper.join());check(lamp&&entity,'native face/helper pair '+fact.face);same(s.texinfo.texture.name,'tlight01','native material');vector(info(s).center,fact.center,'literal native panel center');const b=bounds(s);same(b[3]-b[0],32,'native width');same(b[4]-b[1],32,'native depth');vector(lamp.fixture.authoredPosition,fact.helper,'original helper provenance');vector(lamp.pos,[fact.center[0],fact.center[1],fact.center[2]-10],'ten-unit physical source offset');vector(lamp.direction,[0,0,-1],'outward signed direction');same(lamp.emitter,0,'helper is not promoted into doubled flame radiance');near(lamp.power,fact.light/300,'authored power');same(lamp.style,Number(entity.style||0),'authored style');same(lamp.style,0,'native fixture style literal');const old=nativeEntities.find(l=>l.pos.join()===fact.helper.join()&&l.classname==='light');vector(lamp.color,old.color,'authored color unchanged');same(lamp.flicker,old.flicker,'no invented flicker');same(Mod_PointInLeaf(lamp.pos,model).contents,-1,'real source in BSP air');same(lamp.leaf,Mod_PointInLeaf(lamp.pos,model),'selection/cube leaf tracks moved source');check(R_LightCone(lamp.direction,lamp.cone),'valid directional shape');}
 const omitted=fallback.filter(l=>l.texture==='tlight01'&&expectedClusters.some(p=>p.join()===l.pos.join()));same(omitted.length,4,'positive original cluster controls');for(const p of expectedClusters)check(!actual.some(l=>l.texture==='tlight01'&&l.pos.join()===p.join()),'matched procedural emitter removed '+p);
 const targetHelpers=new Set(FIXTURES.map(f=>f.helper.join()));for(const old of fallback){if(omitted.includes(old)||old.classname==='light'&&targetHelpers.has(old.pos.join()))continue;const retained=actual.find(l=>l.classname===old.classname&&l.texture===old.texture&&l.pos.join()===old.pos.join());check(retained,'unmatched source retained');equalJSON(sourceSnapshot(retained),sourceSnapshot(old),'unmatched source attributes unchanged');}
 equalJSON(nativeBytes(model),before,'native BSP, polygons, lightmap styles, entity text and original pigment unchanged');console.log('FIXTURE_NATIVE_SOURCES '+JSON.stringify({bspSha256:BSP_SHA,fixtures:fixtures.map(sourceSnapshot),removedClusters:omitted.map(sourceSnapshot),oldCount:fallback.length,newCount:actual.length}));
});

Deno.test('fixture pairing rejects unknown source/map, missing or ambiguous helpers, incomplete geometry and solid air gaps without changing native inputs',async()=>{
 const {model,entities}=await native(),plain=post.R_BuildWorldLights({...model,name:'maps/no-fixture-contract.bsp'}).filter(l=>l.classname),before=JSON.stringify(plain.map(sourceSnapshot)),pairs=R_ExitFixturePairs(model,entities,plain,callbacks);same(pairs.length,6,'native pure-classifier positive');same(new Set(pairs.map(p=>p.helper)).size,6,'one-to-one helper identity');
 const changed=model.bspSourceBytes.slice();changed[changed.length-1]^=1;for(const m of [{...model,name:'maps/e1m2.bsp'},{...model,bspSourceBytes:changed},{...model,bspSourceBytes:null}]){same(R_ExitFixturePairs(m,entities,plain,callbacks).length,0,'wrong identity cannot infer lamp changes');check(!post.R_BuildWorldLights(m).some(l=>l.fixture),'public collector also rejects unsupported identity');}
 const original=pairs[0].helper,ambiguous=[...plain,{...original,pos:original.pos.slice()}];same(R_ExitFixturePairs(model,entities,ambiguous,callbacks).length,0,'duplicate same-XY helper rejects all six');same(R_ExitFixturePairs(model,entities,plain.filter(l=>l!==original),callbacks).length,0,'missing helper rejects entire association');same(R_ExitFixturePairs(model,entities,plain,{...callbacks,leaf:()=>({contents:-2})}).length,0,'nonair source segment rejects association');
 for(const kind of ['upward','material','width']){const surfaces=model.surfaces.slice(),old=surfaces[FIXTURES[0].face];surfaces[FIXTURES[0].face]=kind==='upward'?{...old,flags:old.flags^2}:kind==='material'?{...old,texinfo:{...old.texinfo,texture:{...old.texinfo.texture,name:'other-lamp'}}}:{...old,polys:{...old.polys,verts:old.polys.verts.slice()}};if(kind==='width')for(let i=0;i<surfaces[FIXTURES[0].face].polys.numverts;i++)surfaces[FIXTURES[0].face].polys.verts[i*7]=1312+(surfaces[FIXTURES[0].face].polys.verts[i*7]-1312)*1.25;same(R_ExitFixturePairs({...model,surfaces},entities,plain,callbacks).length,0,kind+' means incomplete supported six-panel geometry');}
 same(JSON.stringify(plain.map(sourceSnapshot)),before,'read-only classifier never edits supplied helper objects');post.R_BuildWorldLights(model);
});

Deno.test('cone response obeys an independent angular oracle, handles behind/outside receivers and keeps invalid or absent shapes isotropic',()=>{
 const source=[17,-31,53],direction=[0,0,-4],cone=[Math.cos(Math.PI/10),Math.cos(32*Math.PI/180)],saved=JSON.stringify({source,direction,cone}),shape=R_LightCone(direction,cone);vector(shape.direction,[0,0,-1],'direction normalized');
 for(const [cosine,expected]of [[1,1],[cone[0],1],[(cone[0]+cone[1])/2,.5],[cone[1],0],[0,0],[-1,0]]){const ray=[Math.sqrt(Math.max(0,1-cosine*cosine)),0,-cosine],receiver=source.map((v,i)=>v+ray[i]*120);near(R_LightConeFactor(receiver,source,direction,cone),expected,'angular pool oracle cosine'+cosine,1e-10);}same(R_LightConeFactor(source,source,direction,cone),0,'source singularity contributes no undefined ray');same(JSON.stringify({source,direction,cone}),saved,'cone inputs unchanged');
 for(const [d,c]of [[null,null],[[0,0,0],cone],[[NaN,0,-1],cone],[direction,[.8,.9]],[direction,[1,-.1]],[direction,[1,1]],[direction,[1,NaN]],[direction,[1,.8,.7]],[[0,0,-1,NaN],cone],[direction,{}]]){same(R_LightCone(d,c),null,'invalid shape rejected safely');same(R_LightConeFactor([19,-31,43],source,d,c),1,'invalid direction cannot darken an ordinary point source');}
});

function camera(eye=[1312,1280,-320],direction=[0,-1,.1]){const c=new THREE.PerspectiveCamera(75,1.6,4,4096);c.up.set(0,0,1);c.position.fromArray(eye);c.lookAt(...eye.map((v,i)=>v+direction[i]));c.updateMatrixWorld();return c;}
Deno.test('public selection preserves eight physical slots and fixture membership under camera rotation without changing helper radiance',async()=>{
 const {model}=await native(),lights=post.R_BuildWorldLights(model),styles=new Array(64).fill(264),frame=73;for(const leaf of model.leafs)leaf.visframe=frame;const baseline=post.R_SelectWorldLights(camera().matrixWorldInverse,frame,styles,[],0),ids=baseline.map(l=>l.source);same(post.MAX_VOLUME_LIGHTS,8,'existing point-source budget');same(baseline.length,8,'nonvacuous saturated native source selection');check(baseline.filter(l=>l.source.fixture).length>=2,'actual corridor fixtures selected');
 for(const direction of [[1,0,0],[0,1,0],[-1,-1,.3]]){const selected=post.R_SelectWorldLights(camera(undefined,direction).matrixWorldInverse,frame,styles,[],0);same(selected.length,8,'rotation retains eight slots');check(selected.every(l=>ids.includes(l.source)),'same eye rotation retains identities');for(const l of selected){const before=baseline.find(b=>b.source===l.source);near(l.score,before.score,'ranking independent of camera orientation');vector(l.color,before.color,'source radiance invariant');}}
 const lamp=baseline.filter(l=>l.source.fixture).sort((a,b)=>b.score-a.score)[0].source,oldStyle=lamp.style;try{lamp.style=7;styles[7]=132;const dim=post.R_SelectWorldLights(camera().matrixWorldInverse,frame,styles,[],0).find(l=>l.source===lamp);check(dim,'native style control remains selected');const full=baseline.find(l=>l.source===lamp);dim.color.forEach((v,i)=>near(v,full.color[i]*.5,'authored style scales radiance exactly'));}finally{lamp.style=oldStyle;}
});

function renderer(){let target=null,face=0,mip=0,vp=new THREE.Vector4(0,0,320,200),sc=vp.clone(),test=false,color=new THREE.Color(),alpha=1;const r={draws:[],autoClear:true,xr:{enabled:false},capabilities:{isWebGL2:true},extensions:{has:()=>true},getRenderTarget:()=>target,getActiveCubeFace:()=>face,getActiveMipmapLevel:()=>mip,setRenderTarget:(t,f=0,m=0)=>{target=t;face=f;mip=m;},getViewport:v=>v.copy(vp),setViewport:(...v)=>v[0]?.isVector4?vp.copy(v[0]):vp.set(...v),getScissor:v=>v.copy(sc),setScissor:(...v)=>v[0]?.isVector4?sc.copy(v[0]):sc.set(...v),getScissorTest:()=>test,setScissorTest:v=>test=v,getClearColor:v=>v.copy(color),getClearAlpha:()=>alpha,setClearColor:(c,a)=>{color.set(c);alpha=a;},clear(){},render:(scene,camera)=>r.draws.push({scene,camera,target,face,material:scene.children[0]?.material})};return r;}
const controls=[post.r_hdr,post.r_pointshadows,post.r_bloom,post.r_volumetric,post.r_dynres,anim.r_newer_lighting,anim.r_newer_normals,anim.r_newer_water,height.r_heightshadows];
async function pipeline(fn){for(const c of controls)if(!vars.Cvar_FindVar(c.name))vars.Cvar_RegisterVariable(c);const old=controls.map(c=>c.string),r=renderer();try{controls.forEach(c=>vars.Cvar_SetValue(c.name,1));for(const name of ['r_bloom','r_volumetric','r_dynres','r_newer_water'])vars.Cvar_SetValue(name,0);anim.R_AnimSetClassicPass(false);await fn(r);}finally{post.R_PostBegin(r,false,320,200);height.R_HeightShadowScope(false);controls.forEach((c,i)=>vars.Cvar_Set(c.name,old[i]));anim.R_AnimSetClassicPass(false);anim.R_AnimSetNewer(false);anim.R_AnimSetLighting(false);}}
Deno.test('public pre-HDR snapshot freezes cone direction/order through actual cube, height and composite endpoints and resets unused or isotropic slots',()=>pipeline(async r=>{
 const {model}=await native();post.R_BuildWorldLights(model);const frame=97,styles=new Array(64).fill(264);for(const leaf of model.leafs)leaf.visframe=frame;vars.Cvar_SetValue('r_newer_normals',0);post.R_BuildSunOccluder(model);vars.Cvar_SetValue('r_newer_normals',1);const c=camera(),scene=new THREE.Scene();post.R_PostBegin(r,true,320,200);const before=post.R_PointShadowStatus(),snapshot=post.R_PostLightsFrame(r,scene,c,frame,styles,[],1,false),saved=snapshot.lights.map(l=>({source:l.source,world:l.worldPos.slice(),direction:Array.from(l.direction),view:Array.from(l.viewDirection),cone:Array.from(l.cone)}));same(snapshot.lights.length,8,'frozen budget unchanged');check(saved.some(l=>l.source.fixture),'fixture included in actual frame');same(post.R_PointShadowStatus().captures-before.captures,1,'ordinary static frame retains one-cube budget');same(post.R_PointShadowStatus().faceRenders-before.faceRenders,6,'cube retains six physical shadow faces');
 for(let i=0;i<saved.length;i++){vector(height.heightShadowUniforms.uHeightPointWorld.value[i].toArray().slice(0,3),saved[i].world,'height world source same slot');vector(height.heightShadowUniforms.uHeightPointDirection.value[i].toArray(),saved[i].direction,'height direction same world slot');vector(height.heightShadowUniforms.uHeightPointCone.value[i].toArray(),saved[i].cone,'height cone same slot');const expected=new THREE.Vector3(...saved[i].direction).transformDirection(c.matrixWorldInverse);vector(saved[i].view,saved[i].direction.some(Boolean)?expected.toArray():[0,0,0],'camera-space direction uses actual rotation');}
 const mutable=snapshot.lights.find(l=>l.source.fixture).source,oldDirection=Array.from(mutable.direction),oldCone=Array.from(mutable.cone);try{mutable.direction[0]=1;mutable.direction[2]=0;mutable.cone[0]=.99;post.R_PostFinish(r,scene,c,{lx:0,ly:0,lw:320,lh:200},frame,styles,[],1,1,false);const material=r.draws.at(-1).material;check(material?.uniforms.uLightDirection,'actual composite receives directional uniform');for(let i=0;i<saved.length;i++){vector(material.uniforms.uLightDirection.value[i].toArray(),saved[i].view,'compositor retains frozen view direction');vector(material.uniforms.uLightCone.value[i].toArray(),saved[i].cone,'compositor retains frozen cone');vector(height.heightShadowUniforms.uHeightPointDirection.value[i].toArray(),saved[i].direction,'mutable source cannot alter already rendered height metadata');}}
 finally{mutable.direction=oldDirection;mutable.cone=oldCone;}
 const ordinaryLeaf={contents:-1,visframe:frame};post.R_BuildWorldLights({nodes:[ordinaryLeaf],entities:'{ "classname" "light" "origin" "1312 1264 -250" }',surfaces:[]});const isotropic=post.R_PostLightsFrame(r,scene,c,frame,styles,[],2,false);same(isotropic.lights.length,1,'next ordinary point source keeps its own slot');vector(isotropic.lights[0].direction,[0,0,0],'ordinary snapshot clears old cone direction');vector(isotropic.lights[0].cone,[1,1],'ordinary snapshot uses isotropic fallback');post.R_PostFinish(r,scene,c,{lx:0,ly:0,lw:320,lh:200},frame,styles,[],2,1,false);vector(r.draws.at(-1).material.uniforms.uLightDirection.value[0].toArray(),[0,0,0],'actual compositor also resets reused directional slot');same(post.R_PointShadowStatus().maxSlots,8,'directionality does not allocate a ninth cube slot');
 const point={position:[1,2,3],range:100,color:[1,1,1],direction:[0,0,-1],cone:[.95,.85]};height.R_HeightShadowFrame({points:Array.from({length:12},()=>point)});same(height.heightShadowUniforms.uHeightCount.value,8,'height writer retains exactly eight existing point slots');point.direction[2]=1;point.cone[0]=.99;vector(height.heightShadowUniforms.uHeightPointDirection.value[0].toArray(),[0,0,-1],'height inputs copied');height.R_HeightShadowFrame({points:[{position:[1,2,3],range:100,color:[1,1,1]}]});same(height.heightShadowUniforms.uHeightCount.value,1,'new frame shrinks active count');for(let i=0;i<8;i++){vector(height.heightShadowUniforms.uHeightPointDirection.value[i].toArray(),[0,0,0],'isotropic/unused direction clears');vector(height.heightShadowUniforms.uHeightPointCone.value[i].toArray(),[1,1],'isotropic/unused cone clears');if(i>0)same(height.heightShadowUniforms.uHeightPointWorld.value[i].w,0,'unused range clears');}height.R_HeightShadowFrame(null);same(height.heightShadowUniforms.uHeightCount.value,0,'null frame resets all slots');
}));
