import {fileURLToPath} from 'node:url';
import './glass_materials_test.js';
import {readFileSync,writeFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import {createHash} from 'node:crypto';
import {R_GenerateNormalData} from '../src/newer/render/gl_normals.js';
const require=createRequire(import.meta.url),{createCanvas,loadImage}=require('/Users/bri/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/@napi-rs/canvas');
const root=fileURLToPath(new URL('../newer/textures/',import.meta.url)),reviews=JSON.parse(readFileSync(root+'glass/region-review.json')),proof=JSON.parse(readFileSync(root+'glass/region-proof.json')),own=Object.fromEntries(reviews.filter(v=>v.reviewId>=72).map(v=>[String(v.reviewId),v.regionReview]));
const check=(v,m)=>{if(!v)throw Error(m)},sha=b=>createHash('sha256').update(b).digest('hex');
async function decode(file){const image=await loadImage(root+file),canvas=createCanvas(image.width,image.height),context=canvas.getContext('2d');context.drawImage(image,0,0);return{width:image.width,height:image.height,data:new Uint8Array(context.getImageData(0,0,image.width,image.height).data)}}
function contained(shape,x,y){if(shape.type==='rect'){const [a,b,c,d]=shape.bounds;return x>=a&&x<=c&&y>=b&&y<=d}if(shape.type==='ellipse'){const [a,b]=shape.center,[rx,ry]=shape.radius;return ((x-a)/rx)**2+((y-b)/ry)**2<=1}let inside=false;const p=shape.points;for(let i=0,j=p.length-1;i<p.length;j=i++){const [xi,yi]=p[i],[xj,yj]=p[j];if((yi>y)!==(yj>y)&&x<(xj-xi)*(y-yi)/(yj-yi)+xi)inside=!inside}return inside}
const decoded=new Map();
Deno.test('independent actual PNG decode restores canonical ordinary normals outside every reviewed pane across all 130 materials',async()=>{
 check(reviews.length===130,'entire reviewed material corpus included');const receipt=[];
 for(const material of reviews){const p=proof.find(x=>x.reviewId===material.reviewId);check(p,'installed source proof record '+material.reviewId);const f=material.outputs,diff=await decode(f.diffuse.file),normal=await decode(f.normal.file),height=await decode(f.height.file),gloss=await decode(f.gloss.file);check([normal,height,gloss].every(x=>x.width===diff.width&&x.height===diff.height),'source dimensions match '+material.reviewId);const base=R_GenerateNormalData(diff.data,diff.width,diff.height),combined=new Uint8Array(base.length);let outside=0,panes=0,lead=0;
  for(let i=0;i<diff.width*diff.height;i++){const j=i*4,r=gloss.data[j],g=gloss.data[j+1];combined.set(normal.data.subarray(j,j+3),j);combined[j+3]=height.data[j];check(normal.data[j+3]===255&&height.data[j+3]===255&&gloss.data[j+3]===255,'opaque decoded source prevents premultiplication corruption '+material.reviewId);if(r){panes++;check(g===255,'no glass specular outside reviewed opening '+material.reviewId);check(Math.max(diff.data[j],diff.data[j+1],diff.data[j+2])/255>.22,'dark lead never receives glass normal/specular '+material.reviewId)}else{outside++;for(let c=0;c<4;c++)check(combined[j+c]===base[j+c],'canonical public normal RGBA restored outside glass '+material.reviewId+' pixel '+i+' channel '+c);if(g)lead++}if(!material.regionReview.glass)check(r===0&&g===0,'whole opaque/control texture receives no mask '+material.reviewId)}
  check(sha(combined)===p.assembledNormalSha256,'actual decoded assembled data matches installed proof '+material.reviewId);check(sha(base)===p.baselineNormalSha256,'independently generated public baseline matches installed source proof '+material.reviewId);check(sha(readFileSync(root+f.diffuse.file))===material.outputs.diffuse.sha256,'owner diffuse unchanged '+material.reviewId);decoded.set(material.reviewId,{diff,gloss,panes,outside});receipt.push({reviewId:material.reviewId,name:material.name,panes,outside,lead,canonicalOutsideExact:true,assembledSHA256:sha(combined)});
 }
 writeFileSync(process.env.QUAKED_GLASS_REGION_RECEIPT||'/private/tmp/quaked-glass-region-asset-receipt.json',JSON.stringify({source:'actual PNG canvas decode and public R_GenerateNormalData',materials:receipt},null,2));
});
Deno.test('independent visually reviewed 58 materials constrain aperture G to pane openings and reject whole-texture masks',()=>{
 check(decoded.size===130,'actual asset pass completed');for(const [id,review]of Object.entries(own)){const {diff,gloss}=decoded.get(Number(id));let active=0,excluded=0;for(let y=0;y<diff.height;y++)for(let x=0;x<diff.width;x++){const g=gloss.data[(y*diff.width+x)*4+1];if(!g){excluded++;continue}active++;check(review.glass,'negative visual classification cannot carry glass aperture '+id);let permitted=false;for(let dy=-2;dy<=2;dy++)for(let dx=-2;dx<=2;dx++)if(review.shapes.some(s=>contained(s,(x+dx)/diff.width,(y+dy)/diff.height)))permitted=true;check(permitted,'actual aperture G cannot extend into visually excluded frame/wall '+id+' pixel '+x+','+y)}if(review.glass){check(active>0,'identified pane has real aperture '+id);check(excluded>0,'whole texture forbidden: outside frame or margin must remain excluded '+id)}else check(active===0,'opaque/no-glass control has zero aperture '+id)}
});
