// Independent public held framing checks with actual imported poses and native
// view/bob calculation. CPU clip-space checks report geometric visibility;
// owner visual acceptance and raster occlusion remain separate browser checks.
import * as THREE from 'three';
import {readFileSync} from 'node:fs';
import * as pak from '../src/engine/common/pak.js';
import {VID_SetPalette} from '../src/vid.js';
import {Mod_Init,Mod_ForName} from '../src/gl_model.js';
import * as main from '../src/gl_rmain.js';
import * as weapons from '../src/r_weapons.js';
import * as anim from '../src/r_anim.js';
import * as vars from '../src/engine/common/cvar.js';
import * as view from '../src/view.js';
import {r_hdr} from '../src/gl_post.js';
import {cl,cls,cl_entities} from '../src/client.js';
import {r_refdef,entity_t} from '../src/render.js';
import {STAT_HEALTH,STAT_WEAPON,STAT_WEAPONFRAME} from '../src/engine/common/quakedef.js';
import {cl_simvel,set_cl_simonground} from '../src/cl_pred.js';
import {set_host_frametime} from '../src/engine/server/host.js';
const check=(value,message)=>{if(!value)throw Error(message);},same=(a,b,message)=>check(a===b,`${message}: ${a} != ${b}`),near=(a,b,message,tolerance=1e-5)=>check(Math.abs(a-b)<=tolerance,`${message}: ${a} != ${b}`);
const read=path=>readFileSync(new URL('../'+path,import.meta.url)),oldFetch=globalThis.fetch,oldLoad=THREE.TextureLoader.prototype.load;
globalThis.fetch=async path=>{try{return{ok:true,json:async()=>JSON.parse(read(String(path).split('?')[0]))};}catch{return{ok:false};}};
THREE.TextureLoader.prototype.load=function(path,done){const texture=new THREE.DataTexture(new Uint8Array([160,100,60,255]),1,1);queueMicrotask(()=>done(texture));return texture;};
const raw=read('pak0.pak');pak.COM_AddPack(pak.COM_LoadPackFile('held-framing-native',raw.buffer.slice(raw.byteOffset,raw.byteOffset+raw.length)));VID_SetPalette(pak.COM_FindFile('gfx/palette.lmp').data);Mod_Init();main.R_Init();view.V_Init();
for(const variable of[r_hdr,weapons.r_newer_weapons])if(!vars.Cvar_FindVar(variable.name))vars.Cvar_RegisterVariable(variable);
vars.Cvar_SetValue('r_hdr',1);weapons.r_newer_weapons.value=1;anim.R_AnimSetNewer(true);anim.r_lerpmodels.value=0;anim.R_AnimSetClassicPass(false);
const manifest=await weapons.R_WeaponsLoad();await Promise.all(Object.keys(manifest.models).map(key=>weapons.R_WeaponLoad(key)));
globalThis.fetch=oldFetch;THREE.TextureLoader.prototype.load=oldLoad;
cl.worldmodel={nodes:[{contents:-1}],lightdata:new Uint8Array([0])};cl.time=1;cl.oldtime=1;cl.maxclients=1;cl.viewentity=1;cl.stats[STAT_HEALTH]=100;cl.items=0;cl.intermission=0;cl.viewheight=22;cl.onground=true;cls.demoplayback=true;cl_entities[1]=new entity_t();cl_entities[1].origin.set([0,0,0]);
r_refdef.vrect.width=1280;r_refdef.vrect.height=800;r_refdef.fov_x=90;r_refdef.fov_y=2*Math.atan(800/1280)*180/Math.PI;
function place(key,angles=[0,0,0]){cl.viewent.model=Mod_ForName('progs/'+key+'.mdl',true);cl.viewent.origin.set([10,-40,24]);cl.viewent.angles.set(angles);cl.viewent.frame=0;r_refdef.vieworg.set(cl.viewent.origin);r_refdef.viewangles.set(angles);main.R_SetupGL();}
Deno.test('ready manifest publishes held-only pullbacks and keeps prior baked fitting untouched',()=>{
 same(Object.keys(manifest.models).length,14,'fourteen replacement roles (thirteen, and the basic shotgun drop g_shot1 of card [12])');same(weapons.R_WeaponHeldPullback('progs/v_rock2.mdl'),.5,'Rocket half-unit camera pullback');same(weapons.R_WeaponHeldPullback('progs/v_nail2.mdl'),1,'SNG one-unit camera pullback');same(weapons.R_WeaponHeldPullback('progs/v_nail2.mdl')/weapons.R_WeaponHeldPullback('progs/v_rock2.mdl'),2,'SNG delta is exactly twice Rocket');
 for(const key of Object.keys(manifest.models).filter(key=>!['v_rock2','v_nail2'].includes(key)))same(weapons.R_WeaponHeldPullback('progs/'+key+'.mdl'),0,'other held/pickup role unchanged '+key);same(weapons.R_WeaponHeldPullback('progs/v_axe.mdl'),0,'native-only fallback stays unchanged');same(JSON.stringify(manifest.models.v_rock2.viewOffset),'[-3,0,0]','prior Rocket baked translation retained');same(JSON.stringify(manifest.models.v_nail2.viewTranslation),'[-7,0,0]','prior SNG baked translation retained');same(manifest.models.v_nail2.pitchUpDegrees,8,'prior SNG baked pitch retained');
});
Deno.test('actual held draw applies exact camera-backward deltas at varied orientations once per frame',()=>{
 for(const key of['v_rock2','v_nail2'])for(const angles of[[0,0,0],[15,90,0],[-30,190,20]]){place(key,angles);const asset=weapons.R_WeaponAsset('progs/'+key+'.mdl'),amount=asset.cameraPullback,origin=Array.from(cl.viewent.origin),poses=asset.templates.map(t=>Array.from(t.posAttr.array).join());asset.cameraPullback=0;main.R_DrawViewModel();const base=cl.viewent._aliasMesh.position.clone();asset.cameraPullback=amount;main.R_DrawViewModel();const mesh=cl.viewent._aliasMesh,delta=mesh.position.clone().sub(base),direction=main.camera.getWorldDirection(new THREE.Vector3()).multiplyScalar(-amount);near(delta.distanceTo(direction),0,key+' camera-axis delta');near(delta.length(),amount,key+' exact magnitude');const expected=mesh.position.clone();for(let i=0;i<10;i++){main.R_DrawViewModel();near(mesh.position.distanceTo(expected),0,key+' repeated frame cannot accumulate pullback');}same(Array.from(cl.viewent.origin).join(),origin.join(),'render adjustment never mutates native entity');asset.templates.forEach((t,i)=>same(Array.from(t.posAttr.array).join(),poses[i],'all baked pose coordinates remain unchanged'));}
});
Deno.test('Classic disabled replacements and fallback never acquire held pullback',()=>{
 for(const key of['v_rock2','v_nail2','v_shot','v_axe']){place(key);anim.R_AnimSetClassicPass(true);main.R_DrawViewModel();near(cl.viewent._aliasMesh.position.distanceTo(new THREE.Vector3(...cl.viewent.origin)),0,'Classic native mesh remains at native origin');same(weapons.R_WeaponHeldPullback('progs/'+key+'.mdl'),0,'Classic getter suppressed');anim.R_AnimSetClassicPass(false);weapons.r_newer_weapons.value=0;main.R_DrawViewModel();near(cl.viewent._aliasMesh.position.distanceTo(new THREE.Vector3(...cl.viewent.origin)),0,'disabled replacement remains at native origin');weapons.r_newer_weapons.value=1;}
});
function clipPolygon(poly,plane){const out=[];for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length],da=plane(a),db=plane(b);if(da>=0)out.push(a);if((da<0)!==(db<0)){const t=da/(da-db);out.push(a.map((v,k)=>v+(b[k]-v)*t));}}return out;}
function clipping(mesh){mesh.updateMatrixWorld(true);const viewMatrix=new THREE.Matrix4().multiplyMatrices(main.camera.matrixWorldInverse,mesh.matrixWorld),project=new THREE.Matrix4().multiplyMatrices(main.camera.projectionMatrix,viewMatrix),positions=mesh.geometry.getAttribute('position'),points=[],depths=[];for(let i=0;i<positions.count;i++){const local=new THREE.Vector3().fromBufferAttribute(positions,i);depths.push(-local.clone().applyMatrix4(viewMatrix).z);const c=new THREE.Vector4(local.x,local.y,local.z,1).applyMatrix4(project);points.push(c.toArray());}const index=mesh.geometry.index.array;let visibleNearCut=0;for(let i=0;i<index.length;i+=3){let poly=[points[index[i]],points[index[i+1]],points[index[i+2]]];for(const plane of[p=>p[3]-1e-7,p=>p[0]+p[3],p=>p[3]-p[0],p=>p[1]+p[3],p=>p[3]-p[1]]){poly=clipPolygon(poly,plane);if(poly.length<3)break;}if(poly.length>=3&&poly.some(p=>p[2]+p[3]<-1e-6))visibleNearCut++;}return{minDepth:Math.min(...depths),near:main.camera.near,visibleNearCut};}
Deno.test('actual native bob and all imported held poses retain visible near-plane clearance',()=>{
 const rows=[];set_cl_simonground(0);cl.nodrift=true;cl.punchangle.fill(0);cl.viewangles.fill(0);cl.model_precache[1]=null;cl.stats[STAT_WEAPON]=1;set_host_frametime(.6/36);
 for(const key of['v_rock2','v_nail2'])for(const fov of[75,90,110]){r_refdef.fov_x=fov;r_refdef.fov_y=2*Math.atan(Math.tan(fov*Math.PI/360)*800/1280)*180/Math.PI;const model=Mod_ForName('progs/'+key+'.mdl',true),asset=weapons.R_WeaponAsset(model.name);cl.model_precache[1]=model;const row={key,fov,samples:0,minDepth:Infinity,visibleNearCut:0,worst:null};for(const pitch of[-45,0,45])for(const speed of[0,200,320]){cl.viewangles.set([pitch,37,0]);cl_simvel.set([speed,0,0]);cl.velocity.set([speed,0,0]);for(let pose=0;pose<asset.templates.length;pose++)for(let sample=0;sample<36;sample++){cl.time+=.6/36;cl.oldtime=cl.time-.6/36;cl.stats[STAT_WEAPONFRAME]=pose;view.V_CalcRefdef();main.R_SetupGL();main.R_DrawViewModel();const value=clipping(cl.viewent._aliasMesh);row.samples++;if(pitch===0&&speed===0&&sample===0&&pose===0)row.stationaryDepth=value.minDepth;if(value.minDepth<row.minDepth){row.minDepth=value.minDepth;row.worst={pitch,speed,sample,pose,...value};}row.visibleNearCut=Math.max(row.visibleNearCut,value.visibleNearCut);}}rows.push(row);console.log('HELD_FRAMING_CLIP '+JSON.stringify(row));}
 console.log('HELD_FRAMING_CLIP_SUMMARY '+JSON.stringify(rows));check(rows.every(row=>row.visibleNearCut===0),'no imported triangles intersect near plane inside current display frustum');
});

Deno.test('public asset loader rejects malformed or pickup pullback metadata and waits for ready geometry',async()=>{
 const fetchBefore=globalThis.fetch,loadBefore=THREE.TextureLoader.prototype.load;const miniature={sources:{fixture:{maps:{diffuse:'diffuse.png'}}},models:{v_negative:{source:'fixture',cameraPullback:-1},v_string:{source:'fixture',cameraPullback:'1'},v_null:{source:'fixture',cameraPullback:null},v_infinite:{source:'fixture',cameraPullback:Infinity},g_rogue:{source:'fixture',cameraPullback:3},v_pending:{source:'fixture',cameraPullback:1.25},v_failed:{source:'fixture',cameraPullback:1.25}}},geometry={poses:[[0,0,0,1,0,0,0,1,0]],uv:[0,0,1,0,0,1],indices:[0,1,2]};let release;
 globalThis.fetch=async path=>{if(String(path).endsWith('index.json'))return{ok:true,json:async()=>miniature};if(String(path).endsWith('v_failed.json'))return{ok:false};if(String(path).endsWith('v_pending.json'))return new Promise(resolve=>release=()=>resolve({ok:true,json:async()=>geometry}));return{ok:true,json:async()=>geometry};};THREE.TextureLoader.prototype.load=function(url,done){const texture=new THREE.Texture();queueMicrotask(()=>done(texture));return texture;};
 try{const isolated=await import('../src/r_weapons.js?held-framing-metadata');await isolated.R_WeaponsLoad();const pending=isolated.R_WeaponLoad('v_pending');for(let i=0;i<8;i++)await Promise.resolve();same(isolated.R_WeaponHeldPullback('progs/v_pending.mdl'),0,'pending geometry cannot shift native fallback');check(release,'real geometry request pending');release();await pending;same(isolated.R_WeaponHeldPullback('progs/v_pending.mdl'),1.25,'valid held metadata appears only with ready asset');for(const key of['v_negative','v_string','v_null','v_infinite','g_rogue','v_failed']){await isolated.R_WeaponLoad(key);same(isolated.R_WeaponHeldPullback('progs/'+key+'.mdl'),0,'invalid or unsupported metadata cannot shift '+key);}check(isolated.R_WeaponStatus().failures.v_failed,'controlled geometry failure remains diagnosed');for(const material of isolated.R_WeaponMaterials())material.dispose();for(const texture of isolated.R_WeaponTextures())texture.dispose();
 }finally{globalThis.fetch=fetchBefore;THREE.TextureLoader.prototype.load=loadBefore;}
});
