// Supplied main-sheet pixels through the existing public PNG loader, followed
// by real menu command/keyboard/touch routing in the authored title order.
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import * as draw from '../src/gl_draw.js';
import * as menu from '../src/menu.js';
import * as cmd from '../src/engine/common/cmd.js';
import * as keys from '../src/keys.js';
const canvasAPI=await import(process.env.QUAKED_CANVAS_MODULE||'/Users/bri/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/@napi-rs/canvas/index.js');
const check=(v,m)=>{if(!v)throw Error(m);},same=(a,b,m)=>check(a===b,`${m}: ${a} != ${b}`),bytes=readFileSync(new URL('../newer/ui/mainmenu-bestiarium.png',import.meta.url)),image=await canvasAPI.loadImage(bytes);let sheet;
Deno.test('supplied seven-row main menu remains byte-identical and uses the existing native-pitch PNG loader',async()=>{
 same(createHash('sha256').update(bytes).digest('hex'),'4f75a11764e91096a9cf21f147b989b4864a64efef7f0fdd23fa215e9ed6dd8e','original supplied sheet bytes');same(image.width,1536,'source width');same(image.height,1024,'source height');const before={Image:Object.getOwnPropertyDescriptor(globalThis,'Image'),document:Object.getOwnPropertyDescriptor(globalThis,'document')};let requested=null;Object.defineProperty(globalThis,'Image',{configurable:true,value:class{constructor(){Object.defineProperty(image,'src',{configurable:true,set(url){requested=url;queueMicrotask(()=>image.onload());}});return image;}}});Object.defineProperty(globalThis,'document',{configurable:true,value:{createElement:tag=>{same(tag,'canvas','existing loader only allocates drawing canvases');return canvasAPI.createCanvas(1,1);}}});try{sheet=await draw.Draw_CachePicFromPNG('gfx/mainmenu_ext.lmp','newer/ui/mainmenu-bestiarium.png',{displayHeight:140});same(requested,'newer/ui/mainmenu-bestiarium.png','exact author image loaded');same(sheet.height,140,'seven20-pixel native cursor rows');same(sheet.width,210,'source aspect preserved at native-pitch height');same(draw.Draw_CachePic('gfx/mainmenu_ext.lmp'),sheet,'public cache exposes actual decoded picture');const expected=canvasAPI.createCanvas(210,140),ctx=expected.getContext('2d');ctx.imageSmoothingEnabled=false;ctx.drawImage(image,0,0,1536,1024,0,0,210,140);const a=sheet.canvas.getContext('2d').getImageData(0,0,210,140).data,b=ctx.getImageData(0,0,210,140).data;check(a.every((v,i)=>v===b[i]),'native display bitmap is exactly the supplied sheet at nearest-pixel scale');for(let row=0;row<7;row++){let visible=0;for(let y=row*20;y<(row+1)*20;y++)for(let x=0;x<210;x++){const i=(y*210+x)*4;if(a[i+3]&&a[i]+a[i+1]+a[i+2]>40)visible++;}check(visible>100,'every authored action row has nonempty glyph pixels '+row);}const main=readFileSync(new URL('../main.js',import.meta.url),'utf8');check(/Draw_CachePicFromPNG\(\s*'gfx\/mainmenu_ext\.lmp',\s*'newer\/ui\/mainmenu-bestiarium\.png',\s*\{\s*displayHeight:\s*140\s*\}/.test(main),'real startup uses same loader/options');}finally{for(const[k,d]of Object.entries(before))if(d)Object.defineProperty(globalThis,k,d);else delete globalThis[k];}
});
Deno.test('actual main menu artwork and fallback follow title order and every keyboard/touch action matches its authored row',()=>{
 check(sheet,'actual sheet positive control loaded');const prior={window:Object.getOwnPropertyDescriptor(globalThis,'window'),document:Object.getOwnPropertyDescriptor(globalThis,'document')};globalThis.window={devicePixelRatio:1,innerWidth:640,innerHeight:400};globalThis.document={fullscreenElement:null};try{let dest=keys.key_game,art=true;const server={active:false},client={state:0,demonum:-1,demoplayback:false},pictures=[],subpictures=[],chars=[];cmd.Cbuf_Init();cmd.Cmd_Init();menu.M_Init();menu.M_SetExternals({key_dest_set:v=>dest=v,key_dest_get:()=>dest,cls:client,sv:server,svs:{maxclients:1},Draw_CachePic:path=>path==='gfx/mainmenu_ext.lmp'?(art?sheet:null):{width:16,height:24,path},Draw_TransPic:(x,y,p)=>pictures.push({x,y,p}),Draw_SubPic:(x,y,p,sy,sh)=>subpictures.push({x,y,p,sy,sh}),Draw_Pic:()=>{},Draw_Character:(x,y,c)=>chars.push({x,y,c}),Draw_FadeScreen:()=>{},S_LocalSound:()=>{},host_time_get:()=>0,IN_RequestPointerLock:()=>{}});const titles=[['SINGLE PLAYER',menu.m_singleplayer],['MULTIPLAYER',menu.m_multiplayer],['BESTIARIUM',menu.m_bestiary],['OPTIONS',menu.m_options],['CREDITS',menu.m_credits],['QUIT',menu.m_quit]],dx=(draw.Draw_GetVirtualWidth()-320)>>1,dy=(draw.Draw_GetVirtualHeight()-200)>>1;const render=()=>{pictures.length=subpictures.length=chars.length=0;menu.M_Draw();};
 for(const inGame of[false,true]){server.active=inGame;client.state=inGame?2:0;const actions=inGame?[['CONTINUE',menu.m_none],...titles]:titles;for(const available of[true,false]){art=available;cmd.Cmd_ExecuteString('menu_main');render();if(available){if(inGame)check(pictures.some(p=>p.p===sheet),'in-game draws complete sheet with Continue');else{const crop=subpictures.find(p=>p.p===sheet);check(crop,'out-of-game draws actual supplied subpicture');const native=sheet.canvas.getContext('2d').getImageData(0,0,210,140).data;check(native[(20*210+71)*4+3]>=128,'positive control: Continue descender extends into native row20');same(crop.sy,21,'crop removes significant Continue descender while retaining first Single Player strokes');same(crop.sh,119,'all remaining authored rows reach original sheet bottom');check(native[(21*210+7)*4+3]>0,'first retained row contains actual Single Player pixels');}}else{for(let row=0;row<actions.length;row++){const text=chars.filter(c=>c.y===37+dy+row*20).map(c=>String.fromCharCode(c.c&127)).join('');same(text,actions[row][0],'fallback title follows supplied order');}}
 for(let row=0;row<actions.length;row++){const[title,state]=actions[row];cmd.Cmd_ExecuteString('menu_main');render();const dot=pictures.find(p=>p.p.path?.includes('menudot'));check(dot,'real cursor is visible');let current=(dot.y-32-dy)/20;same(current,Math.floor(current),'native cursor lies on authored pitch');for(let n=0;n<(row-current+actions.length)%actions.length;n++)menu.M_Keydown(keys.K_DOWNARROW);menu.M_Keydown(keys.K_ENTER);same(menu.m_state,state,'keyboard selects '+title);if(title==='CONTINUE')same(dest,keys.key_game,'Continue returns native input');cmd.Cmd_ExecuteString('menu_main');const w=draw.Draw_GetVirtualWidth(),h=draw.Draw_GetVirtualHeight();menu.M_TouchInput(100+(w-320)/2,42+row*20+(h-200)/2,w,h);same(menu.m_state,state,'touch selects '+title);}
 }}client.demoplayback=true;server.active=true;client.state=2;art=true;cmd.Cmd_ExecuteString('menu_main');render();check(subpictures.some(p=>p.p===sheet&&p.sy===21),'demo playback never offers Continue even with connected client');menu.M_Keydown(keys.K_ESCAPE);same(menu.m_state,menu.m_none,'Escape still closes main menu');}finally{for(const[k,d]of Object.entries(prior))if(d)Object.defineProperty(globalThis,k,d);else delete globalThis[k];}
});
