import '../src/engine/render/gl_rsurf.js';
import * as THREE from 'three';
import * as post from '../src/newer/render/gl_post.js';
import * as main from '../src/engine/render/gl_rmain.js';
import * as mode from '../src/newer/mode.js';
import * as vars from '../src/engine/common/cvar.js';
import {r_flashlight} from '../src/newer/render/r_flashlight.js';
import {r_newer_weapons} from '../src/newer/render/r_weapons.js';
import {COM_LoadPackFile,COM_AddPack,COM_FindFile} from '../src/engine/common/pak.js';
import {Mod_Init,Mod_ForName} from '../src/engine/render/gl_model.js';
import {VID_SetPalette} from '../src/engine/render/vid.js';
import {cl,cl_dlights} from '../src/engine/client/client.js';
import {r_refdef,entity_t} from '../src/engine/render/render.js';
import {R_DrawAliasModel} from '../src/engine/render/gl_mesh.js';
import {R_CloneAliasMaterial} from '../src/newer/render/r_newerskins.js';
import {weaponSurface,WeaponSurfaceState} from '../src/newer/render/r_weapon_surface.js';
import '../src/newer/install.js'; // Newer Game plugs into the engine's hooks (src/engine/common/hooks.js)
const W=480,H=320,report=document.querySelector('#report'),button=document.querySelector('#run'),errors=[],owned=[];let renderer,draws=0,composite=null;
const options=[post.r_hdr,post.r_newbright,post.r_newcontrast,post.r_dynres,post.r_bloom,post.r_volumetric,post.r_bounce,post.r_pointshadows,mode.r_newer_lighting,mode.r_newer_normals,mode.r_newer_water,mode.r_newer_shadows,r_newer_weapons,r_flashlight];
const bodyVertexSnapshot=new WeakMap();
function face(points){return{flags:0,texinfo:{texture:{name:'diagnostic_stone'}},polys:{numverts:points.length,verts:new Float32Array(points.flatMap(p=>[...p,0,0,0,0]))}};}
const farFloor=face([[-128,-128,-128],[128,-128,-128],[128,128,-128],[-128,128,-128]]);
function world(color=null,blocker=false,sun=false,lightPosition=[80,-60,48]){const entities='{ "classname" "worldspawn" "_sun_mangle" "0 -70" }'+(color?`\n{ "classname" "light" "origin" "${lightPosition.join(' ')}" "light" "600" "_color" "${color.join(' ')}" }`:'');const surfaces=[farFloor];if(blocker)surfaces.push(face([[60,-96,-32],[60,-96,96],[60,-20,96],[60,-20,-32]]));const m={nodes:[{contents:-1,visframe:1}],entities,surfaces,lightdata:new Uint8Array([0])};post.R_BuildWorldLights(m);post.R_BuildSunOccluder(m);return m;}
function capture(rt=renderer.getRenderTarget()){const normal=new Uint16Array(W*H*4),albedo=new Uint8Array(W*H*4),hdr=new Uint16Array(W*H*4);renderer.readRenderTargetPixels(rt,0,0,W,H,hdr,undefined,0);renderer.readRenderTargetPixels(rt,0,0,W,H,normal,undefined,1);renderer.readRenderTargetPixels(rt,0,0,W,H,albedo,undefined,2);return{rt,hdr,normal:Float32Array.from(normal,THREE.DataUtils.fromHalfFloat),albedo};}
function picture(label){const figure=document.createElement('figure'),img=document.createElement('img'),caption=document.createElement('figcaption');img.src=renderer.domElement.toDataURL();caption.textContent=label;figure.append(img,caption);document.querySelector('#views').append(figure);}
const decodeSRGB=v=>v<=.04045?v/12.92:Math.pow((v+.055)/1.055,2.4),encodeSRGB=v=>v<=.0031308?v*12.92:1.055*Math.pow(v,1/2.4)-.055;
function differences(a,b){let changed=0,maximum=0,sum=0;for(let i=0;i<a.screen.length;i++){if(i%4===3)continue;const d=Math.abs(a.screen[i]-b.screen[i]);if(d)changed++;maximum=Math.max(maximum,d);sum+=d;}return{changed,maximum,sum};}
function measured(image,held){let pixels=0,sum=[0,0,0],maximum=0;for(let i=0;i<W*H;i++){const a=image.normal[i*4+3],tag=image.albedo[i*4+3]/255;if(held?a>=-2:!(a>0&&tag>.05&&tag<.1))continue;pixels++;for(let k=0;k<3;k++){sum[k]+=image.screen[i*4+k];maximum=Math.max(maximum,image.screen[i*4+k]);}}return{pixels,mean:sum.map(v=>v/Math.max(1,pixels)),maximum};}
function setupCamera(){r_refdef.vrect.width=W;r_refdef.vrect.height=H;r_refdef.fov_y=60;r_refdef.fov_x=85;r_refdef.vieworg.set([0,-64,24]);r_refdef.viewangles.set([0,90,0]);main.R_SetupGL();}
let nativeHeld,ordinary;
function draw(label,{color=null,blocker=false,sun=false,held=true,dlights=[],translucent=false,reuseWorld=null,lightPosition=[80,-60,48]}={}){
 cl.time=10;for(const d of cl_dlights){d.radius=0;d.die=0;}const m=reuseWorld||world(color,blocker,sun,lightPosition);cl.worldmodel=m;setupCamera();post.R_PostBegin(renderer,true,W,H);
 if(ordinary?._aliasMesh)ordinary._aliasMesh.visible=false;if(cl.viewent._aliasMesh)cl.viewent._aliasMesh.visible=false;
 let mesh;if(held){cl.viewent.model=nativeHeld;cl.viewent.origin.set(r_refdef.vieworg);cl.viewent.angles.set([0,90,0]);cl.viewent.frame=0;cl.stats[0]=100;cl.items=0;main.R_DrawViewModel();mesh=cl.viewent._aliasMesh;}else{ordinary.origin.set([0,-15,12]);ordinary.angles.set([0,90,0]);mesh=R_DrawAliasModel(ordinary,ordinary.model.cache.data,new Float32Array(256).fill(1),0);if(mesh.parent!==main.scene)main.scene.add(mesh);mesh._quakeOwner=ordinary;mesh.userData.quakeViewmodel=false;mesh.layers.enable(post.SUN_SHADOW_LAYER);}
 if(!mesh)throw Error('Native alias failed to draw');const originalMaterial=mesh.material;if(translucent){mesh.material=R_CloneAliasMaterial(originalMaterial);mesh.material.transparent=true;mesh.material.opacity=.45;mesh.material.needsUpdate=true;}mesh.visible=true;mesh.updateMatrixWorld(true);if(!bodyVertexSnapshot.has(mesh.geometry))bodyVertexSnapshot.set(mesh.geometry,{position:mesh.geometry.attributes.position.array.slice(),uv:mesh.geometry.attributes.uv.array.slice()});
 const frame=post.R_PostLightsFrame(renderer,main.scene,main.camera,1,new Array(64).fill(264),dlights,10,sun);post.R_PostBind(renderer);renderer.clear();renderer.render(main.scene,main.camera);draws++;const image=capture();
 const original=renderer.render;renderer.render=function(scene,camera){const material=scene.children[0]?.material;if(material?.uniforms?.uLighting&&material?.uniforms?.tNormal)composite=material;return original.call(this,scene,camera);};try{post.R_PostFinish(renderer,main.scene,main.camera,{lx:0,ly:0,lw:W,lh:H},1,new Array(64).fill(264),dlights,10,1,sun);}finally{renderer.render=original;}
 if(translucent){const repaired=capture(image.rt);image.repairColorChanges=image.hdr.reduce((n,v,i)=>n+(v!==repaired.hdr[i]),0);image.normal=repaired.normal;image.albedo=repaired.albedo;const temp=mesh.material;mesh.material=originalMaterial;temp.dispose();}
 image.screen=new Uint8Array(W*H*4);const gl=renderer.getContext();gl.readPixels(0,0,W,H,gl.RGBA,gl.UNSIGNED_BYTE,image.screen);image.glError=gl.getError();image.metrics=measured(image,held);image.frame=frame;image.world=m;image.shadow=post.R_PointShadowStatus();image.mesh=mesh;image.matrix=mesh.matrixWorld.clone();image.camera=main.camera.clone();image.camera.matrixWorld.copy(main.camera.matrixWorld);image.camera.matrixWorldInverse.copy(main.camera.matrixWorldInverse);picture(label);return image;
}
function receiverOracle(image){
 if(!composite)throw Error('Actual compositor program was not captured');const source=composite.fragmentShader,at=source.lastIndexOf('void main()');if(at<0)throw Error('Actual compositor entry missing');
 const target=new THREE.WebGLRenderTarget(W,H,{type:THREE.FloatType,depthBuffer:false,minFilter:THREE.NearestFilter,magFilter:THREE.NearestFilter}),geometry=new THREE.PlaneGeometry(2,2),material=new THREE.ShaderMaterial({uniforms:composite.uniforms,vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position.xy,0.,1.);}',fragmentShader:source.slice(0,at)+'void main(){gl_FragColor=vec4(viewPosAt(vUv),1.);}',depthTest:false,depthWrite:false});material.onBeforeCompile=()=>{};const scene=new THREE.Scene();scene.add(new THREE.Mesh(geometry,material));renderer.setRenderTarget(target);renderer.render(scene,new THREE.OrthographicCamera(-1,1,1,-1,0,2));draws++;const decoded=new Float32Array(W*H*4);renderer.readRenderTargetPixels(target,0,0,W,H,decoded);
 const caster=new THREE.Raycaster(),p0=new THREE.Vector3(),p1=new THREE.Vector3(),p2=new THREE.Vector3(),bary=new THREE.Vector3(),local=new THREE.Vector3(),normal=new THREE.Vector3(),worldNormal=new THREE.Matrix3().getNormalMatrix(image.matrix),normalView=new THREE.Matrix3().getNormalMatrix(image.camera.matrixWorldInverse),inverse=image.matrix.clone().invert();let samples=0,depthError=0,positionError=0,normalError=0,clippedFirstHits=0,worstSample=null;
 for(let y=3;y<H;y+=4)for(let x=3;x<W;x+=4){const i=(y*W+x)*4,a=image.normal[i+3];if(a>=-2)continue;caster.setFromCamera(new THREE.Vector2((x+.5)/W*2-1,(y+.5)/H*2-1),image.camera);const hits=caster.intersectObject(image.mesh,false),hitDepths=hits.map(h=>-h.point.clone().applyMatrix4(image.camera.matrixWorldInverse).z);const index=hitDepths.findIndex(d=>d>=image.camera.near&&d<=image.camera.far),hit=hits[index];if(!hit)continue;if(index>0)clippedFirstHits++;const view=hit.point.clone().applyMatrix4(image.camera.matrixWorldInverse),distance=-view.z,error=Math.abs((-a-2)-distance);if(error>depthError)worstSample={pixel:[x,y],packetDepth:-a-2,hitDepths,selected:index};depthError=Math.max(depthError,error);positionError=Math.max(positionError,Math.hypot(decoded[i]-view.x,decoded[i+1]-view.y,decoded[i+2]-view.z));
  local.copy(hit.point).applyMatrix4(inverse);p0.fromBufferAttribute(image.mesh.geometry.attributes.position,hit.face.a);p1.fromBufferAttribute(image.mesh.geometry.attributes.position,hit.face.b);p2.fromBufferAttribute(image.mesh.geometry.attributes.position,hit.face.c);THREE.Triangle.getBarycoord(local,p0,p1,p2,bary);const n=image.mesh.geometry.attributes.normal;normal.set(0,0,0);for(const[index,weight]of[[hit.face.a,bary.x],[hit.face.b,bary.y],[hit.face.c,bary.z]])normal.addScaledVector(new THREE.Vector3().fromBufferAttribute(n,index),weight);normal.applyMatrix3(worldNormal).applyMatrix3(normalView).normalize();normalError=Math.max(normalError,normal.distanceTo(new THREE.Vector3(image.normal[i]*2-1,image.normal[i+1]*2-1,image.normal[i+2]*2-1).normalize()));samples++;
 }
 const glError=renderer.getContext().getError();material.dispose();geometry.dispose();target.dispose();return{samples,depthError,positionError,normalError,clippedFirstHits,worstSample,glError};
}



function linearSceneProbe(image){const marker='c = max( c * uExposure, 0.0 );';if(!composite.fragmentShader.includes(marker))throw Error('Actual production exposure boundary absent');const target=new THREE.WebGLRenderTarget(W,H,{type:THREE.FloatType,depthBuffer:false}),geo=new THREE.PlaneGeometry(2,2),mat=new THREE.ShaderMaterial({uniforms:composite.uniforms,vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position.xy,0.,1.);}',fragmentShader:composite.fragmentShader.replace(marker,'gl_FragColor=vec4(c,1.);return;'),depthTest:false,depthWrite:false});mat.onBeforeCompile=()=>{};const scene=new THREE.Scene();scene.add(new THREE.Mesh(geo,mat));renderer.setRenderTarget(target);renderer.render(scene,new THREE.OrthographicCamera(-1,1,1,-1,0,2));draws++;const data=new Float32Array(W*H*4);renderer.readRenderTargetPixels(target,0,0,W,H,data);const glError=renderer.getContext().getError();mat.dispose();geo.dispose();target.dispose();renderer.setRenderTarget(null);return{data,glError};}

function reflectiveLight(image){const ray=new THREE.Raycaster(),shadow=new THREE.Raycaster(),nmat=new THREE.Matrix3().getNormalMatrix(image.camera.matrixWorld);for(let y=4;y<H-4;y+=2)for(let x=4;x<W-4;x+=2){const i=(y*W+x)*4;if(image.normal[i+3]>=-2||[-4,4,-W*4,W*4].some(o=>image.normal[i+o*4+3]>=-2))continue;ray.setFromCamera(new THREE.Vector2((x+.5)/W*2-1,(y+.5)/H*2-1),image.camera);const hit=ray.intersectObject(image.mesh,false).find(h=>-h.point.clone().applyMatrix4(image.camera.matrixWorldInverse).z>=image.camera.near);if(!hit)continue;const N=new THREE.Vector3(image.normal[i]*2-1,image.normal[i+1]*2-1,image.normal[i+2]*2-1).normalize().applyMatrix3(nmat).normalize(),V=image.camera.position.clone().sub(hit.point).normalize();if(N.dot(V)<0)N.negate();if(N.dot(V)<.3)continue;const L=N.clone().multiplyScalar(2*N.dot(V)).sub(V).normalize(),position=hit.point.clone().addScaledVector(L,70);shadow.set(position,L.clone().negate());shadow.far=69;const blocked=shadow.intersectObject(image.mesh,false)[0];if(!blocked)return{position:position.toArray(),pixel:[x,y],ndv:N.dot(V)};}throw Error('No unoccluded reflective native surface sample found');}
function lightProbe(image,held=true){const src=composite.fragmentShader,at=src.lastIndexOf('void main()'),target=new THREE.WebGLRenderTarget(W,H,{type:THREE.FloatType,depthBuffer:false}),geo=new THREE.PlaneGeometry(2,2),mat=new THREE.ShaderMaterial({uniforms:composite.uniforms,vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position.xy,0.,1.);}',fragmentShader:src.slice(0,at)+`void main(){vec3 P=viewPosAt(vUv),N=normalize(texture2D(tNormal,vUv).rgb*2.-1.);if(dot(N,P)>0.)N=-N;vec3 a=texture2D(tAlbedo,vUv).rgb,L=pointSurfaceIncident(P,N,0);gl_FragColor=vec4(max(a.r,max(a.g,a.b)),max(L.r,max(L.g,L.b)),pointSurfaceVisibility(P,N,0,.1),max(dot(N,normalize(uLightPos[0].xyz-P)),0.));}`,depthTest:false,depthWrite:false});mat.onBeforeCompile=()=>{};const scene=new THREE.Scene();scene.add(new THREE.Mesh(geo,mat));renderer.setRenderTarget(target);renderer.render(scene,new THREE.OrthographicCamera(-1,1,1,-1,0,2));draws++;const data=new Float32Array(W*H*4);renderer.readRenderTargetPixels(target,0,0,W,H,data);let samples=0,litFacing=0,litReached=0,mean=[0,0,0,0],maximum=[0,0,0,0];for(let i=0;i<W*H;i++){const alpha=image.normal[i*4+3],tag=image.albedo[i*4+3]/255;if(held?alpha>=-2:!(alpha>0&&tag>.05&&tag<.1))continue;samples++;for(let k=0;k<4;k++){mean[k]+=data[i*4+k];maximum[k]=Math.max(maximum[k],data[i*4+k]);}if(data[i*4+3]>.1)litFacing++;if(data[i*4+1]*data[i*4+2]>.001)litReached++;}mean=mean.map(v=>v/Math.max(samples,1));const glError=renderer.getContext().getError();mat.dispose();geo.dispose();target.dispose();renderer.setRenderTarget(null);return{channels:['linearAlbedoMaximum','incidentMaximum','worldVisibility','NdotL'],samples,litFacing,litReached,mean,maximum,glError};}

function visibilityOracle(image){
 const src=composite.fragmentShader,at=src.lastIndexOf('void main()'),target=new THREE.WebGLRenderTarget(W,H,{type:THREE.FloatType,depthBuffer:false,minFilter:THREE.NearestFilter,magFilter:THREE.NearestFilter}),geo=new THREE.PlaneGeometry(2,2),mat=new THREE.ShaderMaterial({uniforms:composite.uniforms,vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position.xy,0.,1.);}',fragmentShader:src.slice(0,at)+`void main(){vec3 P=viewPosAt(vUv),N=normalize(texture2D(tNormal,vUv).rgb*2.-1.);if(dot(N,P)>0.)N=-N;vec3 pw=(uViewInv*vec4(P+N*1.58,1.)).xyz;gl_FragColor=vec4(pointSurfaceVisibility(P,N,0,.1),max(dot(N,normalize(uLightPos[0].xyz-P)),0.),nearSunVisibility(pw),max(dot(N,uSunDirV),0.));}`,depthTest:false,depthWrite:false});mat.onBeforeCompile=()=>{};const scene=new THREE.Scene();scene.add(new THREE.Mesh(geo,mat));renderer.setRenderTarget(target);renderer.render(scene,new THREE.OrthographicCamera(-1,1,1,-1,0,2));draws++;const pixels=new Float32Array(W*H*4);renderer.readRenderTargetPixels(target,0,0,W,H,pixels);const caster=new THREE.Raycaster(),shadowRay=new THREE.Raycaster(),probeMaterial=new THREE.MeshBasicMaterial({side:THREE.DoubleSide}),probe=new THREE.Mesh(image.mesh.geometry,probeMaterial);probe.matrixAutoUpdate=false;probe.matrix.copy(image.matrix);probe.updateMatrixWorld(true);const light=new THREE.Vector3(...image.frame.lights[0].worldPos),normalMatrix=new THREE.Matrix3().getNormalMatrix(image.camera.matrixWorld);let lit=0,blocked=0,verifiedLit=0,verifiedBlocked=0;const witnesses=[];
 for(let y=1;y<H;y+=2)for(let x=1;x<W;x+=2){const i=(y*W+x)*4;if(image.normal[i+3]>=-2||pixels[i+1]<.15)continue;caster.setFromCamera(new THREE.Vector2((x+.5)/W*2-1,(y+.5)/H*2-1),image.camera);const hit=caster.intersectObject(probe,false).find(h=>{const d=-h.point.clone().applyMatrix4(image.camera.matrixWorldInverse).z;return d>=image.camera.near&&d<=image.camera.far;});if(!hit)continue;const normal=new THREE.Vector3(image.normal[i]*2-1,image.normal[i+1]*2-1,image.normal[i+2]*2-1).normalize().applyMatrix3(normalMatrix).normalize(),receiver=hit.point.clone().addScaledVector(normal,.1),delta=receiver.clone().sub(light),distance=delta.length();shadowRay.set(light,delta.normalize());shadowRay.near=0;shadowRay.far=distance+.1;const first=shadowRay.intersectObject(probe,false)[0],gap=first?distance-first.distance:0;
 if(gap>1.5){blocked++;if(pixels[i]<=.4){verifiedBlocked++;if(witnesses.length<6)witnesses.push({pixel:[x,y],gap,visibility:pixels[i]});}}else if(gap<.15){lit++;if(pixels[i]>=.8)verifiedLit++;}
 }
 const glError=renderer.getContext().getError();probeMaterial.dispose();mat.dispose();geo.dispose();target.dispose();renderer.setRenderTarget(null);return{lit,blocked,verifiedLit,verifiedBlocked,witnesses,glError};
}
function dynamicCaster(){const material=new THREE.MeshBasicMaterial({color:0}),geometry=new THREE.BoxGeometry(4,76,128),mesh=new THREE.Mesh(geometry,material);mesh._quakeOwner={model:{name:'progs/player.mdl'},_aliasMesh:mesh};mesh.layers.set(post.SUN_SHADOW_LAYER);main.scene.add(mesh);return mesh;}

async function run(){button.disabled=true;document.querySelector('#views').replaceChildren();const checks=[],check=(passed,name,data={})=>checks.push({passed,name,...data});draws=0;const surfaceSaved=weaponSurface.snapshot();weaponSurface.restore(new WeaponSurfaceState().snapshot(),10);try{
 const dark=draw('Held weapon: no incident light');check(dark.metrics.pixels>250,'actual held receiver coverage',dark.metrics);check(dark.metrics.maximum<=1,'non-emissive held body remains dark without baked or dynamic light',dark.metrics);const oracle=receiverOracle(dark);check(oracle.samples>30&&oracle.depthError<.08&&oracle.positionError<.12&&oracle.normalError<.025&&oracle.glError===0,'compressed display depth retains actual model position and interpolated normal',oracle);
 const red=draw('Held weapon: red point source',{color:[1,0,0]}),blue=draw('Held weapon: blue point source',{color:[0,0,1]}),blocked=draw('Held weapon: same source behind opaque world blocker',{color:[1,0,0],blocker:true});check(red.metrics.mean[0]>5&&red.metrics.mean[0]>red.metrics.mean[2]*4,'held body receives real red point lighting',red.metrics);check(blue.metrics.mean[2]>3&&blue.metrics.mean[2]>blue.metrics.mean[0]*4,'held body receives real blue point lighting',blue.metrics);const frustum=new THREE.Frustum().setFromProjectionMatrix(new THREE.Matrix4().multiplyMatrices(main.camera.projectionMatrix,main.camera.matrixWorldInverse));check(!frustum.intersectsBox(new THREE.Box3(new THREE.Vector3(60,-96,-32),new THREE.Vector3(60,-20,96))),'physical blocker is outside the viewing frustum');check(blocked.metrics.mean[0]<red.metrics.mean[0]*.35,'off-screen world geometry shadows the real point source',{lit:red.metrics,blocked:blocked.metrics,shadow:post.R_PointShadowStatus()});
 const selfImage=draw('Native held self-shadow witness',{color:[1,1,1]});const heldLightProbe=lightProbe(selfImage);const self=visibilityOracle(selfImage);check(self.blocked>2&&self.lit>10&&self.verifiedBlocked>2&&self.verifiedLit>10&&self.glError===0,'native posed weapon casts its own point shadow on independently ray-confirmed visible surfaces',{...self,heldLightProbe});
 const pickupDark=draw('Native pickup: dark control',{held:false}),pickup=draw('Native pickup: colored source',{held:false,color:[0,0,1]});const pickupProbe=lightProbe(pickup,false),pickupLinear=linearSceneProbe(pickup);check(pickup.metrics.pixels>250&&pickupDark.metrics.maximum===0&&pickup.metrics.mean[0]===0&&pickup.metrics.mean[1]===0&&pickup.metrics.mean[2]>0&&pickup.metrics.maximum>=10&&pickupProbe.litFacing>20&&pickupProbe.litReached>20,'native dark pickup responds only to the real blue source without an arbitrary pigment brightness floor',{dark:pickupDark.metrics,lit:pickup.metrics,lightProbe:pickupProbe});const pickupSource=pickup.frame.lights[0].source;pickupSource.color[2]*=2;const pickupDouble=draw('Native dark pickup: same blue source doubled',{held:false,color:[0,0,1],reuseWorld:pickup.world}),doubleLinear=linearSceneProbe(pickupDouble);pickupSource.color[2]/=2;let positiveSamples=0,maximumRelativeError=0,firstEnergy=0,doubleEnergy=0;for(let i=0;i<W*H;i++){if(pickup.normal[i*4+3]<=0||pickup.albedo[i*4+3]/255<=.05||pickup.albedo[i*4+3]/255>=.1)continue;const original=pickupLinear.data[i*4+2],doubled=doubleLinear.data[i*4+2];if(original>1e-6){positiveSamples++;maximumRelativeError=Math.max(maximumRelativeError,Math.abs(doubled-2*original)/(2*original));firstEnergy+=original;doubleEnergy+=doubled;}}check(positiveSamples>20&&doubleEnergy>firstEnergy&&maximumRelativeError<.005&&pickupLinear.glError===0&&doubleLinear.glError===0,'actual pre-exposure compositor radiance doubles with the same source at fixed native pigment and geometry',{positiveSamples,firstEnergy,doubleEnergy,maximumRelativeError,glErrors:[pickupLinear.glError,doubleLinear.glError]});
 const translucent=draw('Authored translucent held receiver',{color:[0,0,1],translucent:true});const transparentOracle=receiverOracle(translucent);let coverageSamples=0,coverageError=0;for(let i=0;i<W*H;i++)if(blue.normal[i*4+3]<-2&&translucent.normal[i*4+3]<-2){for(let k=0;k<3;k++)coverageError=Math.max(coverageError,Math.abs(translucent.albedo[i*4+k]-255*encodeSRGB(decodeSRGB(blue.albedo[i*4+k]/255)*.45)));coverageSamples++;}check(coverageSamples>250&&coverageError<2,'transparent actor albedo retains authored color coverage',{samples:coverageSamples,maximumByteError:coverageError});check(translucent.metrics.pixels>250&&translucent.metrics.mean[2]>1&&translucent.repairColorChanges===0&&transparentOracle.samples>30&&transparentOracle.depthError<.08&&transparentOracle.positionError<.12&&transparentOracle.normalError<.025&&transparentOracle.glError===0,'transparent physical alias repairs unblended packets without touching authored color0',{metrics:translucent.metrics,color0Changes:translucent.repairColorChanges,oracle:transparentOracle});
 const sun=draw('Held weapon: directional sunlight',{sun:true});check(Math.max(...sun.metrics.mean)>3,'held body receives directional light',sun.metrics);
 const actor=dynamicCaster();actor.position.set(60,-58,32);actor.updateMatrixWorld(true);const actorBlocked=draw('Moving actor blocks point source',{color:[1,0,0]});actor.position.set(160,-58,32);actor.updateMatrixWorld(true);const actorMoved=draw('Same actor and light after moving out of beam',{color:[1,0,0],reuseWorld:actorBlocked.world});check(actorBlocked.shadow.pointDynamicMeshes>=2&&actorMoved.frame.lights[0].source===actorBlocked.frame.lights[0].source&&actorBlocked.metrics.mean[0]<actorMoved.metrics.mean[0]*.35&&actorMoved.metrics.mean[0]>3,'moving physical actor refreshes the same point-light shadow',{blocked:actorBlocked.metrics,moved:actorMoved.metrics,shadow:actorMoved.shadow});actor.geometry.dispose();actor.geometry=new THREE.BoxGeometry(80,80,4);actor.position.set(16,-40,60);actor.updateMatrixWorld(true);const sunBlocked=draw('Near directional actor shadow',{sun:true});actor.position.set(200,-40,60);actor.updateMatrixWorld(true);const sunMoved=draw('Near directional light after actor moves away',{sun:true,reuseWorld:sunBlocked.world});check(sunBlocked.shadow.sunReady&&sunBlocked.shadow.sunDynamicMeshes>=2&&sunMoved.metrics.mean[0]>3&&sunBlocked.metrics.mean[0]<sunMoved.metrics.mean[0]*.5,'near directional atlas resolves moving physical actor shadow on held geometry',{blocked:sunBlocked.metrics,moved:sunMoved.metrics,shadow:sunMoved.shadow});actor.removeFromParent();actor.geometry.dispose();actor.material.dispose();
 const explosion={origin:new Float32Array([80,-60,48]),radius:600,die:11,minlight:0};const flash=draw('Held weapon: live explosion',{dlights:[explosion]}),flashBlocked=draw('Held weapon: explosion behind world geometry',{dlights:[explosion],blocker:true});check(flash.metrics.mean[0]>3&&flash.metrics.mean[0]>flash.metrics.mean[2],'live explosion contributes its actual warm radiance',flash.metrics);check(flashBlocked.metrics.mean[0]<flash.metrics.mean[0]*.35,'explosion source uses real world shadow visibility',{lit:flash.metrics,blocked:flashBlocked.metrics});
 const clean=draw('Held weapon: clean under white light',{color:[1,1,1]}),pickupClean=draw('Pickup: clean white control',{held:false,color:[1,1,1]});weaponSurface.add(.6);const bloody=draw('Held weapon: persistent blood',{color:[1,1,1]}),pickupBloody=draw('Pickup: unchanged by player blood',{held:false,color:[1,1,1]});const stain=differences(clean,bloody);check(stain.changed>30,'actual cached held shader displays blood',stain);const isolated=differences(pickupClean,pickupBloody);check(isolated.changed===0,'world pickup never shares held coating',isolated);weaponSurface.frame(10000,-1);const aged=draw('Held weapon: same blood after long elapsed game time',{color:[1,1,1]});const persistent=differences(bloody,aged);check(persistent.changed===0,'blood has no age-driven fading in actual shader',persistent);weaponSurface.frame(10001,-3);const washed=draw('Held weapon: washed while in water',{color:[1,1,1]});const wash=differences(clean,washed);check(wash.changed===0,'water restores original native pigment exactly',wash);const specular=reflectiveLight(washed),filmClean=draw('Held weapon: dry specular-angle control',{color:[1,1,1],lightPosition:specular.position});weaponSurface.frame(10002,-1);const wet=draw('Held weapon: wet shine after emergence',{color:[1,1,1],lightPosition:specular.position});const film=differences(filmClean,wet);check(film.changed>0,'emerging film contributes actual lit specular response',{...film,specular});weaponSurface.frame(10006,-1);const dried=draw('Held weapon: naturally dry',{color:[1,1,1],lightPosition:specular.position});const dry=differences(filmClean,dried);check(dry.changed===0,'natural drying restores exact dry appearance',dry);
 for(const mesh of[cl.viewent._aliasMesh,ordinary._aliasMesh]){const g=mesh.geometry,old=bodyVertexSnapshot.get(g);check(old.position.every((v,i)=>v===g.attributes.position.array[i])&&old.uv.every((v,i)=>v===g.attributes.uv.array[i]),'native model positions and UVs remain unchanged',{model:mesh===cl.viewent._aliasMesh?'held':'pickup'});}

 check([dark,red,blue,blocked,selfImage,actorBlocked,actorMoved,sunBlocked,sunMoved,pickupDark,pickup,pickupDouble,translucent,sun,flash,flashBlocked,clean,pickupClean,bloody,pickupBloody,aged,washed,filmClean,wet,dried].every(x=>x.glError===0)&&errors.length===0,'actual alias and compositor programs compile without GL errors',{errors});check(renderer.getContext().getParameter(renderer.getContext().DEPTH_RANGE).join()==='0,1','real held callback restores default depth range');
 }catch(error){checks.push({passed:false,name:String(error),stack:error.stack});}finally{weaponSurface.restore(surfaceSaved,10);renderer.setRenderTarget(null);button.disabled=false;}
 const result={status:checks.every(c=>c.passed)?'PASS':'FAIL',draws,checks,scope:'Actual native held/pickup geometry and production scene/compositor; neutral presentation brightness/contrast1 isolates physical response. Independent ray oracle. Transparent color-coverage oracle uses the actual SRGB attachment transfer function. Actual point/explosion world occlusion, directional sunlight, persistent blood, water washing and wet drying. Dark native pickup uses spectral purity plus exact pre-exposure source-radiance doubling, not a shared display-brightness floor. Moving actor point/near-sun shadows and independently ray-confirmed native self-shadow samples. Native save/load remains separate integration coverage.'};window.modelLightingResult=result;report.textContent=JSON.stringify(result,null,2);return result;
}
try{main.R_Init();for(const c of options)if(!vars.Cvar_FindVar(c.name))vars.Cvar_RegisterVariable(c);for(const[k,v]of Object.entries({r_hdr:1,r_newbright:1,r_newcontrast:1,r_dynres:0,r_bloom:0,r_volumetric:0,r_bounce:0,r_pointshadows:1,r_newer_lighting:1,r_newer_normals:0,r_newer_water:0,r_newer_shadows:1,r_newer_weapons:0,r_flashlight:0}))vars.Cvar_SetTemporary(k,String(v));
 const response=await fetch(new URL('../games/shareware/pak0.pak',import.meta.url));if(!response.ok)throw Error('Native pack unavailable');COM_AddPack(COM_LoadPackFile('pak0.pak',await response.arrayBuffer()));VID_SetPalette(COM_FindFile('gfx/palette.lmp').data);Mod_Init();nativeHeld=Mod_ForName('progs/v_shot.mdl',true);ordinary=new entity_t();ordinary.model=Mod_ForName('progs/g_shot.mdl',true);
 renderer=new THREE.WebGLRenderer({antialias:false,preserveDrawingBuffer:true});renderer.setPixelRatio(1);renderer.setSize(W,H);renderer.setClearColor(0,0);renderer.autoClear=false;renderer.debug.onShaderError=(gl,p,v,f)=>errors.push({program:gl.getProgramInfoLog(p),vertex:gl.getShaderInfoLog(v),fragment:gl.getShaderInfoLog(f)});button.addEventListener('click',run);button.disabled=false;report.textContent='Ready. Run checks after the production implementation is ready.';
}catch(error){report.textContent=String(error.stack||error);window.modelLightingResult={status:'FAIL',error:String(error)};}
window.addEventListener('pagehide',()=>{for(const c of options)vars.Cvar_RestoreTemporary(c.name);renderer?.dispose();});
