const panel=document.querySelector('section'),errors=[];for(const t of ['mousedown','mouseup','keydown','keyup','pointerdown','pointerup'])panel.addEventListener(t,e=>e.stopPropagation());window.addEventListener('error',e=>errors.push(e.message));window.addEventListener('unhandledrejection',e=>errors.push(String(e.reason)));
await import('../main.js');while(!window.Cbuf_AddText)await new Promise(r=>setTimeout(r,50));
const cmd=await import('../src/cmd.js'),menu=await import('../src/menu.js'),draw=await import('../src/gl_draw.js'),vars=await import('../src/cvar.js');
const {cl,cls}=await import('../src/client.js'),{sv}=await import('../src/server.js'),{SV_Move,SV_LinkEdict,MOVE_NOMONSTERS}=await import('../src/world.js'),{Mod_PointInLeaf}=await import('../src/gl_model.js');
const loading=await import('../src/r_demoloading.js'),post=await import('../src/gl_post.js'),weapons=await import('../src/r_weapons.js'),surface=await import('../src/r_weapon_surface.js'),parts=await import('../src/r_part.js'),lens=await import('../src/r_screendrops.js');
let ready=false,token=0,exitPosition=[128,1008,-199.95],held=2,measure=null;
const touch=(x,y)=>{const w=draw.Draw_GetVirtualWidth(),h=draw.Draw_GetVirtualHeight();menu.M_TouchInput(x+(w-320)/2,y+(h-200)/2,w,h);};
function start(){const previous=sv.edicts?.[1],id=++token;ready=false;cmd.Cmd_ExecuteString('menu_singleplayer');touch(100,122);touch(100,88);document.querySelector('#status').textContent='Loading through the normal Newer Level Select…';const until=performance.now()+180000,timer=setInterval(()=>{if(id!==token||performance.now()>until){clearInterval(timer);return;}if(sv.edicts?.[1]===previous||cls.signon!==4||cls.demoplayback||loading.R_IntroLoadingHolding()||cl.worldmodel?.name!=='maps/e1m1.bsp')return;clearInterval(timer);ready=true;sv.edicts[1].v.flags|=64|128;cmd.Cbuf_AddText('give 2\ngive 7\ngive s 100\ngive r 100\nimpulse 2\n');document.querySelector('#status').textContent='Real weapon ready. Use Outdoor light, blood spray, then submerge and emerge.';},100);}
function place(origin,angles=[0,90,0]){if(!ready)return false;const p=sv.edicts[1],fit=SV_Move(origin,p.v.mins,p.v.maxs,origin,MOVE_NOMONSTERS,p);if(fit.startsolid||fit.allsolid)return false;p.v.origin=origin;p.v.velocity=[0,0,0];p.v.movetype=0;p.v.angles=angles;p.v.v_angle=angles;p.v.fixangle=1;cl.viewangles.set(angles);SV_LinkEdict(p,false);return true;}
document.querySelector('#start').onclick=start;
document.querySelector('#outside').onclick=()=>{if(place(exitPosition,[0,90,0]))document.querySelector('#status').textContent='Outdoor receiver: posed gun and world share the real light and shadow sources.';};
document.querySelector('#blood').onclick=()=>{if(!ready)return;const eye=window.camera.position,p=eye.toArray();p[0]+=12;parts.R_RunParticleEffect(p,[0,0,0],73,40);lens.R_ScreenDropsClear();document.querySelector('#status').textContent='Native nearby blood event. Lens cleared only for inspection; gun/body blood remains.';};
document.querySelector('#water').onclick=()=>{if(!ready)return;for(const leaf of cl.worldmodel.leafs){if(leaf.contents!==-3)continue;const b=leaf.minmaxs,eye=[0,1,2].map(k=>(b[k]+b[k+3])/2);if(Mod_PointInLeaf(eye,cl.worldmodel).contents!==-3)continue;if(place([eye[0],eye[1],eye[2]-22])){document.querySelector('#status').textContent='Actual BSP water at the eye washes the surface.';return;}}document.querySelector('#status').textContent='No hull-safe water centre found; swim into the courtyard pool manually.';};
document.querySelector('#emerge').onclick=()=>{if(place(exitPosition,[0,90,0]))document.querySelector('#status').textContent='Wet surface emerges; extra shine naturally dries in four game seconds.';};
document.querySelector('#switch').onclick=()=>{held=held===2?7:2;cmd.Cbuf_AddText('impulse '+held+'\n');};document.querySelector('#save').onclick=()=>cmd.Cbuf_AddText('save surface-trial\n');document.querySelector('#load').onclick=()=>cmd.Cbuf_AddText('load surface-trial\n');document.querySelector('#hide').onclick=()=>panel.hidden=true;document.addEventListener('keydown',e=>{if(e.key==='Escape'&&panel.hidden){panel.hidden=false;e.preventDefault();e.stopImmediatePropagation();}},true);
document.querySelector('#measure').onclick=async()=>{if(!ready)return;const old=vars.Cvar_VariableValue('r_pointshadows'),results=[];try{for(const on of[0,1]){vars.Cvar_SetValue('r_pointshadows',on);let last=null,frames=[];for(let i=0;i<50;i++){const t=await new Promise(requestAnimationFrame);if(last!==null&&i>10)frames.push(t-last);last=t;}results.push({shadows:on,samples:frames.length,meanMs:frames.reduce((a,b)=>a+b,0)/frames.length,canvas:[window.renderer.domElement.width,window.renderer.domElement.height],atlas:post.R_PointShadowStatus()});}measure=results;}finally{vars.Cvar_SetValue('r_pointshadows',old);}};
setInterval(()=>{if(!sv.edicts?.[1])return;const p=sv.edicts[1],state=surface.weaponSurface.snapshot();document.querySelector('#report').textContent=JSON.stringify({ready,map:sv.name,signon:cls.signon,loading:loading.R_DemoLoadingStatus(),position:Array.from(p.v.origin),eye:window.camera?.position.toArray(),eyeContents:window.camera?Mod_PointInLeaf(window.camera.position.toArray(),cl.worldmodel).contents:null,surface:state,weapon:cl.viewent.model?.name,heldReceiver:cl.viewent._aliasMesh?.material.userData,assets:weapons.R_WeaponStatus(),shadows:post.R_PointShadowStatus(),measure,glError:window.renderer.getContext().getError(),errors},null,2);},250);
await new Promise(requestAnimationFrame);await new Promise(requestAnimationFrame);start();
