// Public native alias/viewmodel paths and real material compiler contracts.
// GPU radiance, visibility and physical receiver positions are checked by the
// finite model_lighting_gpu_trial, not inferred from these compiler checks.
import * as THREE from 'three';
import {readFileSync} from 'node:fs';
import * as pak from '../src/engine/common/pak.js';
import {VID_SetPalette} from '../src/engine/render/vid.js';
import {Mod_Init,Mod_ForName} from '../src/engine/render/gl_model.js';
import * as main from '../src/engine/render/gl_rmain.js';
import {R_DrawAliasModel} from '../src/engine/render/gl_mesh.js';
import {R_TranslatePlayerSkin,R_GetPlayerSkinTexture} from '../src/engine/render/gl_rmisc.js';
import * as skins from '../src/newer/render/r_newerskins.js';
import * as post from '../src/newer/render/gl_post.js';
import * as mode from '../src/newer/mode.js';
import * as vars from '../src/engine/common/cvar.js';
import {r_newer_weapons} from '../src/newer/render/r_weapons.js';
import {weaponSurface,WeaponSurfaceState,R_ActiveWeaponSurface,R_PlayerBodySurface,R_WeaponSurfaceContext,R_PlayerSurfaceBlood,R_WeaponSurfaceBloodAt,R_WeaponSurfaceFrame} from '../src/newer/render/r_weapon_surface.js';
import * as common from '../src/engine/common/common.js';
import {V_ParseDamage} from '../src/engine/client/view.js';
import {R_InitParticles,R_SetParticleExternals,R_ClearParticles,R_RunParticleEffect} from '../src/engine/render/r_part.js';
import {cls,cl,cl_entities,cl_visedicts,cl_dlights,set_cl_numvisedicts} from '../src/engine/client/client.js';
import {r_refdef,entity_t} from '../src/engine/render/render.js';
const check=(v,m)=>{if(!v)throw Error(m);},same=(a,b,m)=>check(a===b,`${m}: ${a} != ${b}`);
const b=readFileSync(new URL('../pak0.pak',import.meta.url));pak.COM_AddPack(pak.COM_LoadPackFile('pak0.pak',b.buffer.slice(b.byteOffset,b.byteOffset+b.length)));VID_SetPalette(pak.COM_FindFile('gfx/palette.lmp').data);Mod_Init();main.R_Init();
const controls=[post.r_hdr,post.r_dynres,post.r_bloom,post.r_volumetric,post.r_bounce,mode.r_newer_lighting,mode.r_newer_normals,mode.r_newer_enemies,r_newer_weapons];for(const c of controls)if(!vars.Cvar_FindVar(c.name))vars.Cvar_RegisterVariable(c);
function compile(m){const s={uniforms:{},vertexShader:THREE.ShaderLib.basic.vertexShader,fragmentShader:THREE.ShaderLib.basic.fragmentShader};m.onBeforeCompile(s);return s;}
function mock(){let target=null;return{capabilities:{isWebGL2:true},extensions:{has:()=>true},getRenderTarget:()=>target,setRenderTarget:t=>target=t};}
function fixture(fn){const saved=controls.map(c=>c.string),coating=weaponSurface.snapshot(),oldWorld=cl.worldmodel;try{for(const c of controls)vars.Cvar_SetTemporary(c.name,'0');for(const name of['r_hdr','r_newer_lighting'])vars.Cvar_SetTemporary(name,'1');mode.R_AnimSetClassicPass(false);post.R_PostBegin(mock(),true,128,128);cl.worldmodel={nodes:[{contents:-1}],lightdata:new Uint8Array([0])};cl.time=1;cl.maxclients=1;cl.viewentity=1;cl.stats[0]=100;cl.items=0;for(const d of cl_dlights){d.radius=0;d.die=0;}weaponSurface.restore(new WeaponSurfaceState().snapshot(),1);r_refdef.vrect.width=640;r_refdef.vrect.height=400;r_refdef.fov_y=60;r_refdef.fov_x=85;r_refdef.vieworg.set([0,-64,24]);r_refdef.viewangles.set([0,90,0]);main.R_SetupGL();fn();}finally{mode.R_AnimSetClassicPass(false);post.R_PostShutdown();controls.forEach((c,i)=>vars.Cvar_Set(c.name,saved[i]));weaponSurface.restore(coating,1);cl.worldmodel=oldWorld;for(const d of cl_dlights){d.radius=0;d.die=0;}set_cl_numvisedicts(0);}}
Deno.test('actual opaque held clone keeps physical receiver metadata and only applies compressed display depth to the main camera',()=>fixture(()=>{
 cl.viewent.model=Mod_ForName('progs/v_shot.mdl',true);cl.viewent.origin.set(r_refdef.vieworg);cl.viewent.angles.set([0,90,0]);main.R_DrawViewModel();const mesh=cl.viewent._aliasMesh,material=mesh.material,source=compile(material);
 check(mesh.parent===main.scene,'actual native held mesh is in renderer scene');same(material.transparent,false,'opaque gun is not forced into transparent MRT blending');same(material.userData.quakeViewmodel,true,'actual draw path tags held receiver');same(material.userData.quakePlayerSurface,true,'actual held clone owns player coating scope');check(source.fragmentShader.includes('-vQrView.z-2.'),'held normal packet retains physical distance with distinct negative marker');check(source.fragmentShader.includes('uHeldVisionTag')&&skins.R_HeldVisionTag.value===.08,'held actor tag (a uniform: .08, or .065 in the Unseen World) is distinct from world carving data');same(source.uniforms.uActorCoatOn.value,1,'held material enables player coating');
 const calls=[],renderer={getContext:()=>({depthRange:(a,b)=>calls.push([a,b])})};mesh.onBeforeRender(renderer,main.scene,main.camera);mesh.onAfterRender(renderer,main.scene,main.camera);same(JSON.stringify(calls),'[[0,0.3],[0,1]]','actual main-view callbacks retain display depth hack and restore state');calls.length=0;const shadowCamera=new THREE.PerspectiveCamera();mesh.onBeforeRender(renderer,main.scene,shadowCamera);mesh.onAfterRender(renderer,main.scene,shadowCamera);same(calls.length,0,'shadow/receiver cameras never inherit held display-depth compression');
 const enhanced=material;mode.R_AnimSetClassicPass(true);main.R_DrawViewModel();const classic=mesh.material;check(classic!==enhanced,'Classic has a separate owned held material');same(compile(classic).uniforms.uActorCoatOn.value,0,'Classic suppresses coating');mode.R_AnimSetClassicPass(false);main.R_DrawViewModel();same(mesh.material,enhanced,'returning from Classic reuses exact enhanced clone');
}));
Deno.test('native pickups, native player colormap and imported alias materials all carry real receiver data without sharing held coating state',()=>fixture(()=>{
 const pickup=new entity_t();pickup.model=Mod_ForName('progs/g_shot.mdl',true);pickup._entityIndex=2;const original=R_DrawAliasModel(pickup,pickup.model.cache.data,new Float32Array(256).fill(1),0),native=compile(original.material);check(native.fragmentShader.includes('vQrView.z')&&native.fragmentShader.includes('0.06'),'native fallback pickup is a real model-lighting receiver');same(native.uniforms.uActorCoatOn.value,0,'world pickup does not inherit player blood');
 const player=new entity_t();player.model=Mod_ForName('progs/player.mdl',true);player._entityIndex=1;player.colormap={};cl_entities[1]=player;cl.scores=[{colors:0x36}];R_TranslatePlayerSkin(0);check(R_GetPlayerSkinTexture(0),'actual native player palette translation exists');cl_visedicts[0]=player;set_cl_numvisedicts(1);main.R_DrawEntitiesOnList();const playerShader=compile(player._aliasMesh.material);same(player._aliasMesh.material.map,R_GetPlayerSkinTexture(0),'player colormap retains its actual translated texture');check(playerShader.fragmentShader.includes('0.08')&&playerShader.fragmentShader.includes('vQrView.z'),'local player body receives coating tag and physical model normal');same(playerShader.uniforms.uActorCoatOn.value,1,'local player body owns coating');
 const diffuse=new THREE.DataTexture(new Uint8Array([120,90,60,255]),1,1),base=skins.R_AssetAliasMaterial({diffuse},'independent-model-receiver'),held=skins.R_CloneAliasMaterial(base);held.userData.quakeViewmodel=true;held.userData.quakePlayerSurface=true;const b=compile(base),h=compile(held);weaponSurface.add(.6);const repaired=skins.R_CloneAliasMaterial(held);repaired.userData.quakeReceiverOnly=true;check(repaired.customProgramCacheKey()!==held.customProgramCacheKey(),'data repair has a distinct compiled program from the opaque held color pass');check(compile(repaired).fragmentShader.includes('qrAlbedo*qrCoverage'),'repair writes coverage-weighted physical albedo');repaired.dispose();same(b.uniforms.uActorCoatOn.value,0,'shared imported base remains uncoated');same(h.uniforms.uActorCoatOn.value,1,'held clone independently enables same public coating state');check(b.uniforms.uActorCoatOn!==h.uniforms.uActorCoatOn,'coating scope holders are per compiled material');check(h.uniforms.uActorBloodSpots.value===weaponSurface.spots,'cached program observes persistent vector array');const originalPixels=diffuse.image.data.slice();weaponSurface.frame(2,-3);check(h.uniforms.uActorBloodSpots.value.every(s=>s.w===0),'water clears the existing cached shader vectors in place');check(originalPixels.every((v,i)=>v===diffuse.image.data[i]),'coating never repaints source pixels');same(b.uniforms.uActorCoatOn.value,0,'washing held material cannot activate pickup coating');held.dispose();base.dispose();diffuse.dispose();
}));
Deno.test('the held weapon material reads the drawn weapon coating and the chase-camera body material reads the body coating',()=>fixture(()=>{
 const diffuse=new THREE.DataTexture(new Uint8Array([120,90,60,255]),1,1),base=skins.R_AssetAliasMaterial({diffuse},'coat-routing'),held=skins.R_CloneAliasMaterial(base),body=skins.R_CloneAliasMaterial(base);
 held.userData.quakeViewmodel=true;held.userData.quakePlayerSurface=true;body.userData.quakePlayerSurface=true;
 const h=compile(held),b=compile(body),model=cl.viewent.model;
 try{cl.viewent.model={name:'progs/v_shot.mdl'};same(h.uniforms.uActorBloodSpots.value,R_ActiveWeaponSurface().spots,'held material reads the drawn weapon');same(b.uniforms.uActorBloodSpots.value,R_PlayerBodySurface().spots,'body material reads the body');check(R_ActiveWeaponSurface().spots!==R_PlayerBodySurface().spots,'they are different coatings');
  cl.viewent.model={name:'progs/v_nail.mdl'};same(h.uniforms.uActorBloodSpots.value,R_ActiveWeaponSurface().spots,'a weapon switch moves the held material to that weapon');same(b.uniforms.uActorBloodSpots.value,R_PlayerBodySurface().spots,'the body material stays on the body');}
 finally{cl.viewent.model=model;held.dispose();body.dispose();base.dispose();}
}));
Deno.test('enhanced alias CPU colors contain baked light only so a live explosion is not added as unshadowed grayscale before deferred lighting',()=>fixture(()=>{
 const e=new entity_t();e.model=Mod_ForName('progs/g_shot.mdl',true);e._entityIndex=2;e.origin.set([0,0,0]);cl_visedicts[0]=e;set_cl_numvisedicts(1);main.R_DrawEntitiesOnList();const before=e._aliasColorArray.slice(),positions=e._aliasMesh.geometry.attributes.position.array.slice(),uv=e._aliasMesh.geometry.attributes.uv.array.slice();check(before.every(v=>v===0),'black native baked-light control');const d=cl_dlights[0];d.origin.set([0,0,16]);d.radius=350;d.die=cl.time+.5;main.R_DrawEntitiesOnList();check(before.every((v,i)=>v===e._aliasColorArray[i]),'actual enhanced draw does not inject dynamic light into baked vertex colors');check(positions.every((v,i)=>v===e._aliasMesh.geometry.attributes.position.array[i])&&uv.every((v,i)=>v===e._aliasMesh.geometry.attributes.uv.array[i]),'model geometry and native UVs unchanged by lighting');mode.R_AnimSetClassicPass(true);main.R_DrawEntitiesOnList();check(e._aliasColorArray.some(v=>v>0),'Classic preserves its native dynamic vertex-light behavior');mode.R_AnimSetClassicPass(false);
}));

Deno.test('surface blood persists indefinitely and water alone washes; wet film dries on unpaused game time',()=>{
 const state=new WeaponSurfaceState(),array=state.spots,vectors=array.slice();check(state.spots.every(s=>s.x===0&&s.y===0&&s.z===0&&s.w===0),'new coating state has twelve genuinely empty slots, including Vector4.w');state.add(.25);same(state.spots.filter(s=>s.w>0).length,3,'first blood event seeds exactly three previously empty UV spots');const contactState=new WeaponSurfaceState();contactState.add(.2,[.31,.73]);same(contactState.spots[0].x,.31,'optional UV retains exact contact U');same(contactState.spots[0].y,.73,'optional UV retains exact contact V');check(contactState.spots.filter(s=>s.w>0).every(s=>Math.abs(s.x-.31)<=.04&&Math.abs(s.y-.73)<=.04),'secondary splats cluster within bounded contact jitter');const edgeState=new WeaponSurfaceState();edgeState.add(.2,[-.1,1.1]);check(edgeState.spots.filter(s=>s.w>0).every(s=>s.x>=0&&s.x<=1&&s.y>=0&&s.y<=1),'edge contacts keep all UVs within finite skin bounds');check(state.spots.filter(s=>s.w>0).every(s=>s.x>.05&&s.y>.05&&s.z>=.055),'fresh blood seeds real skin coordinates and visible radii');state.frame(1,-1);const blood=JSON.stringify(state.snapshot());state.frame(10000,-1);same(JSON.stringify(state.snapshot()),blood,'elapsed time never fades blood');state.frame(10001,-4);same(JSON.stringify(state.snapshot()),blood,'slime does not silently wash owner blood');state.frame(10002,-5);same(JSON.stringify(state.snapshot()),blood,'lava does not silently wash owner blood');
 for(let i=0;i<20;i++)state.add(.1);same(state.spots.length,12,'bounded twelve spots');check(state.spots.every(s=>s.w>0&&s.w<=1&&s.z<=.22),'full slots augment without disappearing');state.frame(10003,-3);same(state.blood,0,'water removes blood');check(state.spots.every(s=>s.w===0),'water clears actual shader slots');same(state.wet,0,'underwater film absent');state.frame(10004,-1);same(state.wet,1,'emergence starts a full wet film');state.frame(10006,-1,true);same(state.wet,1,'paused clock movement cannot dry film');state.frame(10007,-1);same(state.wet,.75,'one unpaused second dries one quarter');state.frame(1,-1);same(state.wet,.75,'map clock reset never consumes elapsed time from another map');state.frame(4,-1);same(state.wet,0,'four accumulated seconds naturally dry film');same(state.spots,array,'cached array identity preserved');check(vectors.every((v,i)=>v===state.spots[i]),'cached vector identities preserved');
});
Deno.test('public native damage and blood particle events coat only enabled, nearby, visible surfaces',()=>fixture(()=>{
 const old=common.net_message;R_WeaponSurfaceContext(true,[0,0,0],()=>true);try{
  const packet=(armor,blood)=>{const msg={};common.SZ_Alloc(msg,32);common.MSG_WriteByte(msg,armor);common.MSG_WriteByte(msg,blood);for(const v of[4,0,0])common.MSG_WriteCoord(msg,v);common.COM_SetNetMessage(msg);common.MSG_BeginReading();V_ParseDamage();};
  cl.viewent.model=Mod_ForName('progs/v_shot.mdl',true);cl.viewent.origin.set(r_refdef.vieworg);cl.viewent.angles.set([0,90,0]);main.R_DrawViewModel();const held=cl.viewent._aliasMesh;held.updateMatrixWorld(true);const positions=held.geometry.attributes.position.array.slice(),nativeUVs=held.geometry.attributes.uv.array.slice(),eye=new THREE.Vector3(...r_refdef.vieworg),centre=new THREE.Box3().setFromObject(held).getCenter(new THREE.Vector3()),ray=new THREE.Raycaster(eye,centre.clone().sub(eye).normalize(),0,eye.distanceTo(centre)+100),contact=ray.intersectObject(held,false)[0];check(contact?.uv,'posed native weapon has an independently measured damage ray contact');const program=compile(held.material);main.R_SetupFrame();packet(20,0);same(weaponSurface.blood,0,'armor-only actual native damage does not invent blood');packet(0,10);check(weaponSurface.blood>0,'native damage packet reaches coating');same(weaponSurface.spots[0].x,contact.uv.x,'actual renderer frame sends ray-hit U to native damage coating');same(weaponSurface.spots[0].y,contact.uv.y,'actual renderer frame sends ray-hit V to native damage coating');check(program.uniforms.uActorBloodSpots.value===weaponSurface.spots&&program.uniforms.uActorBloodSpots.value[0].w>0,'already compiled held shader sees the exact new contact splat');check(positions.every((v,i)=>v===held.geometry.attributes.position.array[i])&&nativeUVs.every((v,i)=>v===held.geometry.attributes.uv.array[i]),'contact placement retains every original native vertex and UV');weaponSurface.frame(2,-3);R_WeaponSurfaceContext(false,[0,0,0],()=>true);packet(0,10);same(weaponSurface.blood,0,'disabled surface context preserves Classic damage behavior');
  const contacts=[];R_WeaponSurfaceContext(true,[0,0,0],()=>true,point=>{contacts.push([...point]);return [.31,.73];});R_InitParticles();R_SetParticleExternals({cl});R_ClearParticles();R_RunParticleEffect([8,0,0],[1,0,0],0,12);same(weaponSurface.blood,0,'nonblood particle event does not coat');R_RunParticleEffect([8,0,0],[1,0,0],73,12);check(weaponSurface.blood>0,'actual native blood particle event coats a nearby visible weapon');same(JSON.stringify(contacts),JSON.stringify([[8,0,0]]),'actual blood-particle origin is forwarded to contact lookup once');same(weaponSurface.spots[0].x,.31,'blood particle anchors actual contact U');same(weaponSurface.spots[0].y,.73,'blood particle anchors actual contact V');weaponSurface.frame(3,-3);R_RunParticleEffect([73,0,0],[1,0,0],73,12);same(weaponSurface.blood,0,'distant blood cannot coat');R_WeaponSurfaceContext(true,[0,0,0],()=>false);R_RunParticleEffect([8,0,0],[1,0,0],73,12);same(weaponSurface.blood,0,'world occlusion visibility rejection prevents coating');
 }finally{common.COM_SetNetMessage(old);R_WeaponSurfaceContext(false,null,null);R_ClearParticles();}
}));
Deno.test('surface snapshot restores in place across clocks and malformed data is atomic; demos cannot wash live custody',()=>fixture(()=>{
 const live=weaponSurface,oldDemo=cls.demoplayback,oldModel=cl.viewent.model;cl.viewent.model={name:'progs/v_shot.mdl'};R_WeaponSurfaceContext(true,[0,0,0],()=>true);try{cls.demoplayback=false;live.add(.4);live.frame(100,-1);const saved=JSON.parse(JSON.stringify(live.snapshot())),array=live.spots;live.frame(101,-3);check(live.restore(saved,1),'saved surface snapshot accepted after level clock reset');same(JSON.stringify(live.snapshot()),JSON.stringify(saved),'entire blood layout restored exactly');same(live.spots,array,'restore updates cached shader state in place');const malformed=JSON.parse(JSON.stringify(saved));malformed.spots[5][2]=NaN;check(!live.restore(malformed,2),'malformed data rejected');same(JSON.stringify(live.snapshot()),JSON.stringify(saved),'failed restoration cannot partially alter state');
 cls.demoplayback=true;const demo=R_ActiveWeaponSurface();check(demo!==live.state(),'demo surface custody is isolated');R_PlayerSurfaceBlood(10);R_WeaponSurfaceFrame(2,-3);same(JSON.stringify(live.snapshot()),JSON.stringify(saved),'demo water and blood leave saved live blood untouched');cls.demoplayback=false;same(R_ActiveWeaponSurface(),live.state(),'returning from demo restores exact live state');}finally{cls.demoplayback=oldDemo;cl.viewent.model=oldModel;R_WeaponSurfaceContext(false,null,null);}
}));
Deno.test('public HDR target keeps normal and actor packets unmultisampled with all four attachments even when micro normals are disabled',()=>fixture(()=>{
 const renderer=mock();vars.Cvar_SetTemporary('r_newer_normals','0');vars.Cvar_SetTemporary('r_newer_lighting','1');check(post.R_PostBegin(renderer,true,96,64),'lighting-only deferred frame admitted');post.R_PostBind(renderer);const target=renderer.getRenderTarget();check(target?.isWebGLRenderTarget,'actual production target allocated');same(target.samples,0,'categorical actor tags and physical normal distance must never be MSAA coverage-averaged');same(target.textures.length,4,'transparent physical receiver repair retains four production attachments without micro normals');
}));
