import {fileURLToPath} from 'node:url';
// Independent donor binary decoder and public renderer checks. Paths below are
// supplied by the implementation's retained provenance after installation.
import {readFileSync,writeFileSync,openSync,readSync,closeSync,fstatSync} from 'node:fs';
import {inflateRawSync} from 'node:zlib';
import {createHash} from 'node:crypto';
import {r_avertexnormals} from '../src/engine/common/anorm_dots.js';
import * as THREE from 'three';
import {createRequire} from 'node:module';
import {COM_AddPack,COM_LoadPackFile} from '../src/engine/common/pak.js';
import {Mod_Init,Mod_ForName,Mod_Extradata} from '../src/engine/render/gl_model.js';
import {VID_SetPalette,vid} from '../src/engine/render/vid.js';
import {R_DrawAliasModel,GL_DrawAliasFrame} from '../src/engine/render/gl_mesh.js';
import * as weapons from '../src/newer/render/r_weapons.js';
import * as anim from '../src/newer/render/r_anim.js';
import * as mode from '../src/newer/mode.js';
import * as vars from '../src/engine/common/cvar.js';
import {r_hdr} from '../src/newer/render/gl_post.js';
const check=(v,m)=>{if(!v)throw Error(m)},near=(a,b,m,e=2e-5)=>check(Number.isFinite(a)&&Math.abs(a-b)<=e,`${m}: ${a} != ${b}`),hash=b=>createHash('sha256').update(b).digest('hex');
const root=fileURLToPath(new URL('../',import.meta.url)),proof=JSON.parse(readFileSync(root+'newer/weapons/nailgun/provenance.json')),entries=archive(proof.archive),manifest=JSON.parse(readFileSync(root+'newer/weapons/index.json'));
const donorHeld=mdl(entries.get('progs/v_nail.mdl')),donorPickup=md3(entries.get('progs/g_nail.mdl')),converted=Object.fromEntries(['v_nail','g_nail'].map(k=>[k,JSON.parse(readFileSync(root+'newer/weapons/'+k+'.json'))]));
const require=createRequire(import.meta.url),{createCanvas,loadImage}=require('/Users/bri/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/@napi-rs/canvas');
const same=(a,b,m)=>check(a===b,`${m}: ${a} != ${b}`),equal=(a,b,m)=>same(Buffer.from(a).toString('hex'),Buffer.from(b).toString('hex'),m);
function tga(b){check(b[1]===0&&b[2]===2,'uncompressed RGB donor TGA');const w=b.readUInt16LE(12),h=b.readUInt16LE(14),channels=b[16]/8;check(channels===3||channels===4,'24/32bit TGA');const data=new Uint8Array(w*h*4),start=18+b[0];for(let y=0;y<h;y++)for(let x=0;x<w;x++){const sx=b[17]&16?w-1-x:x,sy=b[17]&32?y:h-1-y,q=start+(sy*w+sx)*channels,j=(y*w+x)*4;data.set([b[q+2],b[q+1],b[q],255],j)}return{width:w,height:h,data}}
async function png(data){const image=await loadImage(data),canvas=createCanvas(image.width,image.height),ctx=canvas.getContext('2d');ctx.drawImage(image,0,0);return{width:image.width,height:image.height,data:new Uint8Array(ctx.getImageData(0,0,image.width,image.height).data)}}

Deno.test('independent donor MDL6 and MD3 decoding proves every emitted pose, vertex normal, UV seam and triangle preserves source shape',()=>{
 same(donorHeld.vertices,727,'held source vertices');same(donorHeld.tris,681,'held source triangles');same(donorHeld.poses.length,9,'all source animation poses');same(donorPickup.frames,1,'pickup source frame');same(donorPickup.surfaces.length,1,'one pickup surface');same(donorPickup.surfaces[0].vertices,499,'pickup source vertices');same(donorPickup.surfaces[0].tris,444,'pickup source triangles');same(donorPickup.surfaces[0].shaders[0],'g_nail.tga','actual MD3 shader identity');
 for(const role of ['v_nail','g_nail']){const output=converted[role],record=proof.models[role],source=role==='v_nail'?donorHeld:donorPickup.surfaces[0],mapping=record.sourceVertexForEmitted,count=mapping.length;const shapes=source.poses;
  same(output.poses.length,shapes.length,role+' no collapsed/repeated source poses');same(JSON.stringify(output.transform),JSON.stringify({scale:[1,1,1],offset:[0,0,0]}),role+' identity source coordinates');same(output.fitKind,'source-quake-coordinates',role+' identity fit policy');check(!output.rotor,role+' no invented rotor metadata');same(output.indices.length,source.tris*3,role+' full topology');same(hash(entries.get(record.archiveEntry)),record.sourceSHA256,role+' retained source binary identity');
  for(let frame=0;frame<shapes.length;frame++){same(output.poses[frame].length,count*3,role+' complete emitted pose');for(let v=0;v<count;v++)for(let axis=0;axis<3;axis++){near(output.poses[frame][v*3+axis],shapes[frame].positions[mapping[v]][axis],role+' exact position '+frame+':'+v+':'+axis);near(output.normals[frame][v*3+axis],shapes[frame].normals[mapping[v]][axis],role+' source vertex normal '+frame+':'+v+':'+axis)}}
  for(let v=0;v<count;v++){const id=mapping[v],seam=record.seamVariants?.find(x=>x.emitted===v),expected=role==='v_nail'?[(source.st[id].s+(seam.backSeam?source.width/2:0)+.5)/source.width,(source.st[id].t+.5)/source.height]:source.uv[id];if(seam?.backSeam)check(source.st[id].seam!==0,'only actual MDL seam gets duplicate UV');near(output.uv[v*2],expected[0],role+' source U '+v);near(output.uv[v*2+1],expected[1],role+' source V '+v)}
  let inward=0,outward=0;for(let t=0;t<source.tris;t++){const raw=role==='v_nail'?source.triangles[t].vertices:source.triangles[t],actual=output.indices.slice(t*3,t*3+3).map(v=>mapping[v]),expected=record.reverseWinding?[raw[0],raw[2],raw[1]]:raw;check(actual.every((v,i)=>v===expected[i]),role+' source triangle preserved with only winding conversion '+t);const [a,b,c]=output.indices.slice(t*3,t*3+3),P=i=>output.poses[0].slice(i*3,i*3+3),A=P(a),B=P(b),C=P(c),u=B.map((x,i)=>x-A[i]),v=C.map((x,i)=>x-A[i]),cross=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]],N=[0,1,2].map(i=>(output.normals[0][a*3+i]+output.normals[0][b*3+i]+output.normals[0][c*3+i])/3),dot=cross.reduce((s,x,i)=>s+x*N[i],0);if(dot>1e-8)outward++;if(dot< -1e-8)inward++}check(outward>inward,role+' converted CCW faces agree with retained source normals');
 }
});

Deno.test('independent atlas decode proves held skin exact bytes and pickup TGA diffuse/normal top-row sampling without incompatible held normal',async()=>{
 equal(readFileSync(root+'newer/weapons/nailgun/diffuse.png'),entries.get('progs/v_nail.mdl_0.png'),'held supplied PNG copied directly');const held=await png(entries.get('progs/v_nail.mdl_0.png'));same(held.width,512,'held skin width');same(held.height,512,'held skin height');check(!manifest.sources.nailgun.maps.normal,'incompatible alternate held normal atlas not bound');
 for(const [kind,name]of [['diffuse','textures/g_nail.tga'],['normal','textures/g_nail_norm.tga']]){const source=tga(entries.get(name)),actual=await png(readFileSync(root+'newer/weapons/nailgun_pickup/'+kind+'.png'));same(actual.width,source.width,kind+' source atlas width');same(actual.height,source.height,kind+' source atlas height');equal(actual.data,source.data,kind+' exact decoded RGB and original top-row orientation')}
 same(manifest.sources.nailgun.textureFlipY,false,'held UV no additional flip');same(manifest.sources.nailgun_pickup.textureFlipY,false,'pickup UV no additional flip');
});

Deno.test('independent real weapon load and native alias draw preserve all ordinary nailgun poses, Classic, toggle and pickup identity',async()=>{
 const oldFetch=globalThis.fetch,oldLoad=THREE.TextureLoader.prototype.load,controls=[r_hdr,weapons.r_newer_weapons,anim.r_lerpmodels],saved=controls.map(v=>v.string),classic=mode.R_ClassicPassActive();for(const v of controls)if(!vars.Cvar_FindVar(v.name))vars.Cvar_RegisterVariable(v);
 globalThis.fetch=async path=>({ok:true,json:async()=>JSON.parse(readFileSync(root+String(path)))});THREE.TextureLoader.prototype.load=function(path,done,progress,error){const texture=new THREE.Texture();texture._testSource=String(path);png(readFileSync(root+String(path))).then(pic=>{texture.image=pic;done(texture)},error);return texture};
 const nativePack=readFileSync(root+'games/shareware/pak0.pak');COM_AddPack(COM_LoadPackFile('ordinary-nailgun-native-test',nativePack.buffer.slice(nativePack.byteOffset,nativePack.byteOffset+nativePack.length)));const o=nativePack.readInt32LE(4),end=o+nativePack.readInt32LE(8);let palette;for(let p=o;p<end;p+=64)if(nativePack.toString('ascii',p,p+56).split('\0')[0]==='gfx/palette.lmp'){const start=nativePack.readInt32LE(p+56);palette=nativePack.subarray(start,start+768)}VID_SetPalette(palette);vid.fullbright=224;Mod_Init();
 try{vars.Cvar_SetValue('r_hdr',1);vars.Cvar_SetValue('r_newer_weapons',1);vars.Cvar_SetValue('r_lerpmodels',0);mode.R_AnimSetClassicPass(false);const assets=Object.fromEntries(await Promise.all(['v_nail','g_nail'].map(async role=>[role,await weapons.R_WeaponLoad(role)])));for(const role of ['v_nail','g_nail']){const asset=assets[role],model=Mod_ForName('progs/'+role+'.mdl',true),header=Mod_Extradata(model),entity={model,frame:0,skinnum:0,origin:[11,22,33],angles:[0,41,0]};check(asset,role+' actual public asset loader succeeds');check(!asset.rotor,role+' no rotor at loader boundary');same(asset.templates.length,converted[role].poses.length,role+' source pose count at runtime');check(asset.material.map._testSource.endsWith(manifest.models[role].source+'/diffuse.png'),role+' own source atlas bound');same(asset.material.map.flipY,false,role+' sampler keeps UV orientation');for(let pose=0;pose<header.numposes;pose++){entity.frame=pose;const mesh=R_DrawAliasModel(entity,header,new Float32Array(162).fill(1),.75),template=asset.templates[pose];same(mesh.geometry.getAttribute('position'),template.posAttr,role+' source pose selected 1:1 '+pose);same(mesh.geometry.getAttribute('normal'),template.normalAttr,role+' authored source normals draw');same(mesh.geometry.getAttribute('uv'),template.uvAttr,role+' supplied source UV draw');for(let k=0;k<converted[role].poses[pose].length;k++)near(template.posAttr.array[k],converted[role].poses[pose][k],role+' source identity reaches actual runtime');same(mesh.position.x,11,'native entity X preserved');same(mesh.position.y,22,'native entity Y preserved');same(mesh.position.z,33,'native entity Z preserved');check(!weapons.R_WeaponRotorFrame(asset,entity,pose,null,123),'ordinary nailgun never creates a supernail rotor frame');
    mode.R_AnimSetClassicPass(true);const original=R_DrawAliasModel(entity,header,new Float32Array(162).fill(1),.75),native=GL_DrawAliasFrame(header,pose);same(original.geometry.getAttribute('position'),native.posAttr,role+' Classic native pose');check((Array.isArray(header.gl_texturenum[0])?header.gl_texturenum[0]:[header.gl_texturenum[0]]).includes(original.material.map),role+' Classic native skin group');mode.R_AnimSetClassicPass(false);vars.Cvar_SetValue('r_newer_weapons',0);same(R_DrawAliasModel(entity,header,new Float32Array(162).fill(1),.75).geometry.getAttribute('position'),native.posAttr,role+' disabled switch native pose');vars.Cvar_SetValue('r_newer_weapons',1);
   }same(model.name,'progs/'+role+'.mdl',role+' gameplay identity remains native')}
 }finally{globalThis.fetch=oldFetch;THREE.TextureLoader.prototype.load=oldLoad;controls.forEach((v,i)=>vars.Cvar_Set(v.name,saved[i]));mode.R_AnimSetClassicPass(classic)}
});

Deno.test('independent ordinary nailgun addition preserves every previously imported weapon geometry and texture including Super Nailgun',()=>{
 const previous=JSON.parse(readFileSync(new URL('./fixtures/nailgun-prior-assets.json',import.meta.url)));let count=0;for(const [file,expected]of Object.entries(previous)){if(!/\.(?:json|png|jpg|jpeg|webp|tga)$/.test(file)||file.endsWith('/index.json'))continue;same(hash(readFileSync(root+file)),expected,'previous weapon bytes preserved '+file);count++}check(count>10,'substantial previous geometry and texture coverage');
 const old=JSON.parse(readFileSync(new URL('./fixtures/nailgun-prior-manifest.json',import.meta.url)));for(const [key,value]of Object.entries(old.models))same(JSON.stringify(manifest.models[key]),JSON.stringify(value),'existing role contract preserved '+key);for(const [key,value]of Object.entries(old.sources))same(JSON.stringify(manifest.sources[key]),JSON.stringify(value),'existing source contract preserved '+key);
 writeFileSync(process.env.QUAKED_NAILGUN_RECEIPT||'/private/tmp/quaked-nailgun-source-receipt.json',JSON.stringify({sourceArchive:proof.archive,models:{v_nail:{poses:donorHeld.poses.length,sourceVertices:donorHeld.vertices,triangles:donorHeld.tris},g_nail:{poses:donorPickup.frames,vertices:donorPickup.surfaces[0].vertices,triangles:donorPickup.surfaces[0].tris}},priorAssetsChecked:count,heldSourceSHA256:hash(entries.get('progs/v_nail.mdl')),pickupSourceSHA256:hash(entries.get('progs/g_nail.mdl')),heldJSONSHA256:hash(readFileSync(root+'newer/weapons/v_nail.json')),pickupJSONSHA256:hash(readFileSync(root+'newer/weapons/g_nail.json'))},null,2));
});
export function archive(path){const fd=openSync(path,'r');try{const range=(position,size)=>{const data=Buffer.alloc(size);let got=0;while(got<size){const n=readSync(fd,data,got,size-got,position+got);check(n>0,'short donor archive range');got+=n}return data},size=fstatSync(fd).size,tailStart=Math.max(0,size-65557),tail=range(tailStart,size-tailStart);let end=tail.length-22;while(end>=0&&tail.readUInt32LE(end)!==0x06054b50)end--;check(end>=0,'ZIP directory');const directory=range(tail.readUInt32LE(end+16),tail.readUInt32LE(end+12)),entries=new Map();let p=0;for(let i=0;i<tail.readUInt16LE(end+10);i++){check(directory.readUInt32LE(p)===0x02014b50,'ZIP central header');const method=directory.readUInt16LE(p+10),compressedSize=directory.readUInt32LE(p+20),nl=directory.readUInt16LE(p+28),el=directory.readUInt16LE(p+30),cl=directory.readUInt16LE(p+32),name=directory.toString('utf8',p+46,p+46+nl),local=directory.readUInt32LE(p+42);if(/^(?:progs\/[vg]_nail\.mdl|progs\/v_nail\.mdl_0\.png|textures\/g_nail(?:_norm)?\.tga)$/.test(name)){const h=range(local,30),start=local+30+h.readUInt16LE(26)+h.readUInt16LE(28),compressed=range(start,compressedSize);check(method===0||method===8,'ZIP stored/deflate only');entries.set(name,method===8?inflateRawSync(compressed):compressed)}p+=46+nl+el+cl}return entries}finally{closeSync(fd)}}
export function mdl(b){check(b.toString('ascii',0,4)==='IDPO'&&b.readInt32LE(4)===6,'donor MDL6');const scale=[8,12,16].map(o=>b.readFloatLE(o)),origin=[20,24,28].map(o=>b.readFloatLE(o)),skins=b.readInt32LE(48),width=b.readInt32LE(52),height=b.readInt32LE(56),vertices=b.readInt32LE(60),tris=b.readInt32LE(64),frames=b.readInt32LE(68);let p=84;const skin=[];for(let i=0;i<skins;i++){check(b.readInt32LE(p)===0,'single donor skins');p+=4;skin.push(b.subarray(p,p+width*height));p+=width*height}const st=Array.from({length:vertices},(_,i)=>({seam:b.readInt32LE(p+i*12),s:b.readInt32LE(p+i*12+4),t:b.readInt32LE(p+i*12+8)}));p+=vertices*12;const triangles=Array.from({length:tris},(_,i)=>({front:b.readInt32LE(p+i*16),vertices:[4,8,12].map(o=>b.readInt32LE(p+i*16+o))}));p+=tris*16;const poses=[];for(let i=0;i<frames;i++){check(b.readInt32LE(p)===0,'single donor frame');const name=b.toString('ascii',p+12,p+28).split('\0')[0];p+=28;const positions=[],normals=[],raw=[];for(let v=0;v<vertices;v++){const q=p+v*4,xyz=[b[q],b[q+1],b[q+2]],normalIndex=b[q+3];check(normalIndex<162,'source normal index in canonical table');raw.push({v:xyz,lightnormalindex:normalIndex});positions.push(xyz.map((x,j)=>x*scale[j]+origin[j]));normals.push([...r_avertexnormals[normalIndex]])}p+=vertices*4;poses.push({name,positions,normals,raw})}return{width,height,vertices,tris,frames,st,triangles,poses,skin,scale,origin,end:p}}
export function md3(b){check(b.toString('ascii',0,4)==='IDP3'&&b.readInt32LE(4)===15,'donor MD3 v15');const frames=b.readInt32LE(76),count=b.readInt32LE(84),surfaces=[];let p=b.readInt32LE(100);for(let s=0;s<count;s++){check(b.toString('ascii',p,p+4)==='IDP3','MD3 surface magic');const nframes=b.readInt32LE(p+72),shaders=b.readInt32LE(p+76),vertices=b.readInt32LE(p+80),tris=b.readInt32LE(p+84),triAt=p+b.readInt32LE(p+88),shaderAt=p+b.readInt32LE(p+92),uvAt=p+b.readInt32LE(p+96),xyzAt=p+b.readInt32LE(p+100),poses=[];const triangles=Array.from({length:tris},(_,i)=>[0,4,8].map(o=>b.readInt32LE(triAt+i*12+o))),uv=Array.from({length:vertices},(_,i)=>[b.readFloatLE(uvAt+i*8),b.readFloatLE(uvAt+i*8+4)]);for(let f=0;f<nframes;f++){const positions=[],normals=[];for(let v=0;v<vertices;v++){const q=xyzAt+(f*vertices+v)*8,packed=b.readUInt16LE(q+6),latitude=(packed>>8)*Math.PI*2/256,longitude=(packed&255)*Math.PI*2/256;positions.push([0,2,4].map(o=>b.readInt16LE(q+o)/64));normals.push([Math.cos(latitude)*Math.sin(longitude),Math.sin(latitude)*Math.sin(longitude),Math.cos(longitude)])}poses.push({positions,normals})}surfaces.push({name:b.toString('ascii',p+4,p+68).split('\0')[0],shaders:Array.from({length:shaders},(_,i)=>b.toString('ascii',shaderAt+i*68,shaderAt+i*68+64).split('\0')[0]),vertices,tris,uv,triangles,poses});p+=b.readInt32LE(p+104)}return{frames,surfaces}}
