// Actual current-model role, real Three textures and real gzip transport.
import * as THREE from 'three';
import {gzipSync} from 'node:zlib';
import {createHash} from 'node:crypto';
import {R_NewerNormalsPrepare,R_NewerNormalsStatus} from '../src/newer/render/r_newertextures.js';
import {NormalInputs,NormalInputKey,NormalGenerate,R_NormalPrepared} from '../src/newer/assets/normal_prepare.js';
import {NormalBakeEncode} from '../src/newer/assets/normal_bake_format.js';
import {NORMAL_BAKES} from '../src/newer/assets/normal_bakes.js';
import * as mode from '../src/newer/mode.js';
const check=(v,m)=>{if(!v)throw Error(m);},same=(a,b,m)=>check(a===b,`${m}: ${a} != ${b}`);
Deno.test('actual surface normal role covers native and offscreen brush textures, excludes sky/water, and waits for replacement art before preparing',async()=>{
 const make=(name,seed)=>({name,gl_texture:new THREE.DataTexture(Uint8Array.from({length:256},(_,i)=>(i*23+seed)%256),8,8)}),native=make('brick-public',21),brush=make('brush-public',83),sky=make('sky-public',44),water=make('*water-public',55),entries=[native,brush,sky,water],model={textures:[native,sky,water],texinfo:[{texture:native},{texture:brush}]},oldFetch=globalThis.fetch,registered=[],files=new Map();let requests=0;
 try{for(const t of [native,brush]){const input=NormalInputs(t.gl_texture),key=await NormalInputKey(input),raw=NormalBakeEncode(key,8,8,NormalGenerate(input)),file='newer/normal-public-'+registered.length+'.gz';registered.push({key,prior:NORMAL_BAKES[key]});NORMAL_BAKES[key]={file,sha256:'fixture',rawSha256:createHash('sha256').update(raw).digest('hex')};files.set(file,gzipSync(raw));}
  globalThis.fetch=async url=>{requests++;const bytes=files.get(String(url).split('?')[0]);check(bytes,'actual role fetches only registered normals');return new Response(bytes);};
  native.gl_texture.userData.newerPending=true;R_NewerNormalsPrepare(model);same(R_NormalPrepared(native.gl_texture),undefined,'pending authored replacement prevents obsolete native job');same(R_NormalPrepared(sky.gl_texture),undefined,'sky excluded');same(R_NormalPrepared(water.gl_texture),undefined,'water excluded');await R_NormalPrepared(brush.gl_texture).promise;let status=R_NewerNormalsStatus(model);same(status.pending,1,'current pending pigment prevents premature role completion');same(status.ready,1,'offscreen brush normals actually prepared');same(status.shipped,1,'known brush source counted');same(requests,1,'only eligible settled art fetched');
  native.gl_texture.userData.newerPending=false;R_NewerNormalsPrepare(model);await R_NormalPrepared(native.gl_texture).promise;status=R_NewerNormalsStatus(model);same(status.ready,2,'world plus texinfo-only brush retained without duplicate');same(status.pending,0,'both completed');same(status.shipped,2,'both actual sources shipped');same(status.generated,0,'no runtime generation');same(status.settled,true,'ready after actual source decode');
  native.gl_texture.userData.newerPending=true;const previous=R_NormalPrepared(native.gl_texture);R_NewerNormalsPrepare(model);same(R_NormalPrepared(native.gl_texture),previous,'pending replacement starts no obsolete work');same(requests,2,'pending replacement performs no unnecessary transport');same(R_NewerNormalsStatus(model).pending,1,'old ready normal must not qualify pending replacement art');native.gl_texture.userData.newerPending=false;
 }finally{globalThis.fetch=oldFetch;for(const r of registered){if(r.prior)NORMAL_BAKES[r.key]=r.prior;else delete NORMAL_BAKES[r.key];}for(const t of entries)t.gl_texture.dispose();}
});

Deno.test('custom actor art can load with normals disabled without starting a normal job, then enabling normals prepares the retained art',async()=>{
 const old={fetch:globalThis.fetch,window:Object.getOwnPropertyDescriptor(globalThis,'window'),document:Object.getOwnPropertyDescriptor(globalThis,'document'),load:THREE.TextureLoader.prototype.load,newer:mode.R_IsNewer(),classic:mode.R_ClassicPassActive(),enemies:mode.r_newer_enemies.value,normals:mode.r_newer_normals.value},pixels=Uint8Array.from({length:256},(_,i)=>(i*29+31)%256),donor=new THREE.DataTexture(pixels,8,8),companion=new THREE.DataTexture(pixels,8,8);companion.userData.newerHeight={width:8,height:8,derive:true,strength:.65,cap:.55};const input=NormalInputs(companion),key=await NormalInputKey(input),raw=NormalBakeEncode(key,8,8,NormalGenerate(input)),prior=NORMAL_BAKES[key];NORMAL_BAKES[key]={file:'newer/actor-normal-public.gz',sha256:'fixture',rawSha256:createHash('sha256').update(raw).digest('hex')};let skins,requests=0;const loads=[];
 try{globalThis.fetch=async url=>{requests++;check(String(url).includes('actor-normal-public.gz'),'only known actor normal transport');return new Response(gzipSync(raw));};Object.defineProperty(globalThis,'window',{configurable:true,value:{}});Object.defineProperty(globalThis,'document',{configurable:true,value:{}});THREE.TextureLoader.prototype.load=function(url,done){loads.push({url,done});return new THREE.Texture();};mode.R_AnimSetClassicPass(false);mode.R_AnimSetNewer(true);mode.r_newer_enemies.value=1;mode.r_newer_normals.value=0;
  skins=await import('../src/newer/render/r_newerskins.js?public-normal-role-toggle');skins.R_NewerSetIndex({version:'normal-role-public',models:{dog:[{dir:'public-dog',maps:{diffuse:'dog.png'}}]}});const model={name:'progs/dog.mdl',cache:{data:{numskins:0,gl_texturenum:[]}}};await skins.R_NewerSkinsPrepare([model]);same(loads.length,1,'custom pigment request remains enabled');loads[0].done(donor);await new Promise(r=>setTimeout(r,30));same(requests,0,'normals-off never starts preparation or transport');same(skins.R_NewerSkinsStatus([model]).pending,0,'custom pigment finishes independently');
  mode.r_newer_normals.value=1;await skins.R_NewerSkinsPrepare([model]);const deadline=performance.now()+2000;while(skins.R_NewerSkinsStatus([model]).normals?.shipped!==1&&performance.now()<deadline)await new Promise(r=>setTimeout(r,5));const status=skins.R_NewerSkinsStatus([model]);same(status.normals.shipped,1,'normal toggle prepares previously loaded custom art from shipped data');same(status.normals.generated,0,'no runtime generation');same(status.normals.pending,0,'actual normal job settled');same(requests,1,'one exact normal source load');
 }finally{skins?.R_NewerSkinsShutdown();globalThis.fetch=old.fetch;THREE.TextureLoader.prototype.load=old.load;for(const name of ['window','document'])if(old[name])Object.defineProperty(globalThis,name,old[name]);else delete globalThis[name];mode.R_AnimSetNewer(old.newer);mode.R_AnimSetClassicPass(old.classic);mode.r_newer_enemies.value=old.enemies;mode.r_newer_normals.value=old.normals;if(prior)NORMAL_BAKES[key]=prior;else delete NORMAL_BAKES[key];donor.dispose();companion.dispose();}
});
