import * as THREE from 'three';
import * as fs from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createHash} from 'node:crypto';
import {NormalBakeEncode,NormalBakeDecode} from '../src/newer/assets/normal_bake_format.js';
import {NormalInputs,NormalInputKey,NormalGenerate,R_NormalPrepare,R_NormalPrepared,R_NormalPreparationNeeded} from '../src/newer/assets/normal_prepare.js';
import {NORMAL_BAKES} from '../src/newer/assets/normal_bakes.js';
import {R_HeightFromRGBA,R_MultiScaleHeight,R_NormalsFromHeight,R_NormalsFromCraftedHeight} from '../src/newer/render/gl_normals.js';
import {DisplacementStore} from '../src/newer/assets/displacement_store.js';
import {nativeStorage,recordingLocks} from './helpers/opfs_native_fixture.mjs';
import {GL_RegisterTexture,GL_UnregisterTexture,GL_SetForceLinear,GL_TextureLinear,gl_texturemode} from '../src/engine/render/glquake.js';
import {R_NewerNormalsPrepare} from '../src/newer/render/r_newertextures.js';
const check=(v,m)=>{if(!v)throw Error(m);},same=(a,b,m)=>check(a===b,`${m}: ${a} != ${b}`),bytes=v=>Buffer.from(v.buffer,v.byteOffset,v.byteLength),equal=(a,b,m)=>check(bytes(a).equals(bytes(b)),m),ab=a=>a.buffer.slice(a.byteOffset,a.byteOffset+a.byteLength),sha=b=>createHash('sha256').update(b).digest('hex');
function texture(crafted=false){const t=new THREE.DataTexture(Uint8Array.from({length:8*8*4},(_,i)=>(i*19+23)%256),8,8);t._fullbright=new THREE.DataTexture(new Uint8Array(8*8*4),8,8);if(crafted)t.userData.newerHeight={width:8,height:8,strength:2,cap:1.8,data:Float32Array.from({length:64},(_,i)=>((i*11)%61)/60),edgeSource:{width:10,height:10,data:Float32Array.from({length:100},(_,i)=>((i*13)%97)/96),offset:[1,1]}};return t;}
function rejects(fn,label){let error;try{fn();}catch(e){error=e;}check(error instanceof Error,label+' rejected');}
function rewrite(raw,change){const len=new DataView(raw.buffer,raw.byteOffset,raw.byteLength).getUint32(0,true),start=(4+len+3)&~3,meta=JSON.parse(new TextDecoder().decode(raw.subarray(4,4+len)));change(meta);const h=new TextEncoder().encode(JSON.stringify(meta)),next=(4+h.length+3)&~3,out=new Uint8Array(next+raw.length-start);new DataView(out.buffer).setUint32(0,h.length,true);out.set(h,4);out.set(raw.subarray(start),next);return out;}
async function fixture(fn){const root=await fs.mkdtemp(join(tmpdir(),'quaked-normal-prepare-')),storage=nativeStorage(root),disk=new DisplacementStore(storage,recordingLocks());try{return await fn({root,storage,disk,files:async()=>{try{return(await fs.readdir(join(root,'quaked-displacement-v1'))).filter(n=>n.endsWith('.json'));}catch(e){if(e.code==='ENOENT')return[];throw e;}}});}finally{await fs.rm(root,{recursive:true,force:true});}}
async function until(fn,label){for(let i=0;i<300&&!fn();i++)await new Promise(r=>setTimeout(r,2));check(fn(),label);}

Deno.test('normal input capture is an independent snapshot and full SHA includes previously unsampled pixel bytes and every authored source',async()=>{
 const t=texture(true),input=NormalInputs(t),key=await NormalInputKey(input),snapshot=structuredClone(input);t.image.data[4]^=127;t._fullbright.image.data[4]=255;t.userData.newerHeight.data[4]=.91;t.userData.newerHeight.edgeSource.data[4]=.93;t.userData.newerHeight.edgeSource.offset[0]=3;
 equal(input.rgba,snapshot.rgba,'RGBA captured immutably');equal(input.fullbright,snapshot.fullbright,'fullbright captured immutably');equal(input.scalar,snapshot.scalar,'scalar captured immutably');equal(input.edge.data,snapshot.edge.data,'reference scalar captured immutably');same(JSON.stringify(input.edge.offset),JSON.stringify(snapshot.edge.offset),'edge source offset captured immutably');same(await NormalInputKey(input),key,'later source edits cannot mutate captured identity');
 for(const [label,change]of [['byte4',v=>v.rgba[4]^=1],['fullbright',v=>v.fullbright[4]=1],['scalar',v=>v.scalar[4]=.8],['reference',v=>v.edge.data[4]=.7],['offset',v=>v.edge.offset[0]++],['strength',v=>v.strength+=.1],['cap',v=>v.cap+=.1],['derive',v=>v.derive=true],['authored',v=>v.authored=new Uint8Array(256).fill(128)]]){const altered=structuredClone(snapshot);change(altered);check(await NormalInputKey(altered)!==key,label+' changes full durable identity');}
 const a=texture(),b=texture();b.image.data[4]^=1;check(await NormalInputKey(NormalInputs(a))!==await NormalInputKey(NormalInputs(b)),'byte4 formerly missed by stepped FNV cannot collide');for(const x of [t,a,b]){x.dispose();x._fullbright.dispose();}
});
Deno.test('prepared normal codec and generator preserve exact legacy fallback, crafted and reference bytes while rejecting corrupt identity or scalar coverage',()=>{
 for(const crafted of [false,true]){const t=texture(crafted),i=NormalInputs(t),result=NormalGenerate(i),expectedScalar=crafted?i.scalar:R_MultiScaleHeight(R_HeightFromRGBA(i.rgba,8,8,i.fullbright),8,8),expectedPixels=crafted?R_NormalsFromCraftedHeight(expectedScalar,8,8,i.strength,i.cap,i.edge):R_NormalsFromHeight(expectedScalar,8,8);equal(result.scalar,expectedScalar,'legacy scalar parity');equal(result.pixels,expectedPixels,'legacy normal byte parity');if(crafted)equal(result.reference,R_NormalsFromCraftedHeight(i.edge.data,10,10,0),'legacy reference normals exact');
  const raw=NormalBakeEncode('key',8,8,result),decoded=NormalBakeDecode(ab(raw),'key',8,8);equal(decoded.pixels,result.pixels,'encoded normal bytes');equal(decoded.scalar,result.scalar,'encoded scalar Float32 bits');if(result.reference)equal(decoded.reference,result.reference,'encoded reference bytes');same(decoded.referenceWidth,crafted?10:0,'reference dimensions retained');
  rejects(()=>NormalBakeDecode(ab(raw),'other',8,8),'source key');rejects(()=>NormalBakeDecode(ab(raw),'key',4,16),'dimensions');rejects(()=>NormalBakeDecode(ab(raw.slice(0,-1)),'key',8,8),'truncated coverage');for(const change of [h=>h.version='old',h=>h.referenceWidth=1.5,h=>h.referenceHeight=0,h=>h.width=2049]){if(!crafted&&String(change).includes('referenceHeight'))continue;rejects(()=>NormalBakeDecode(ab(rewrite(raw,change)),'key',8,8),'header corruption');}
  const bad=raw.slice(),start=(4+new DataView(raw.buffer).getUint32(0,true)+3)&~3;new DataView(bad.buffer).setFloat32(start+256,NaN,true);rejects(()=>NormalBakeDecode(ab(bad),'key',8,8),'nonfinite scalar');t.dispose();t._fullbright.dispose();
 }
 const t=texture(true),i=NormalInputs(t);i.authored=Uint8Array.from({length:256},(_,n)=>n);equal(NormalGenerate(i).pixels,i.authored,'authored donor normals retain every byte');t.dispose();t._fullbright.dispose();
});
Deno.test('normal readiness follows closed-file readback, emits one update, and another texture/module reuses exact disk output without generation',()=>fixture(async f=>{
 const t=texture(true);let updates=0,generated=0,held=false,release;t.addEventListener('newertextureupdated',()=>updates++);const pause=new Promise(r=>release=r);f.storage.hooks.beforeClose=async name=>{if(name.endsWith('.json')){held=true;await pause;}};const work=R_NormalPrepare(t,{disk:f.disk,generate:i=>{generated++;return NormalGenerate(i);}});same(R_NormalPrepared(t),work,'public active work identity');same(R_NormalPrepare(t,{disk:f.disk}),work,'same immutable texture shares one job');await until(()=>held,'real manifest close');same(work.status,'loading','no early ready after generator');same(updates,0,'no renderer update before persistence');release();await work.promise;same(work.status,'ready','real durable completion');same(work.source,'generated-and-stored','cold result stored');same(generated,1,'one generator');same(updates,1,'one completed renderer event');delete f.storage.hooks.beforeClose;
 const api=await import('../src/newer/assets/normal_prepare.js?public-normal-reopen='+Date.now()),other=texture(true),reused=api.R_NormalPrepare(other,{disk:new DisplacementStore(nativeStorage(f.root),recordingLocks()),generate:()=>{throw Error('Stored normals must bypass generator');}});await reused.promise;same(reused.status,'ready','fresh module/texture disk hit');same(reused.source,'disk','actual disk source');for(const k of ['pixels','scalar','reference'])equal(reused.data[k],work.data[k],'disk exact '+k);same((await f.files()).length,1,'one complete durable record');
 t.dispose();same(work.status,'cancelled','disposing ready texture relinquishes old job');same(R_NormalPrepared(t),undefined,'disposed weak-key entry removed');t.image.data[4]^=1;const replacement=R_NormalPrepare(t,{disk:f.disk,generate:i=>{generated++;return NormalGenerate(i);}});check(replacement!==work,'art reload owns a fresh job even when native texture object is reused');await replacement.promise;same(replacement.status,'ready','reloaded image prepares successfully');same(replacement.source,'generated-and-stored','changed art receives new source identity');same(generated,2,'reloaded art generates once');same(updates,2,'one new update without old listener double dispatch');same((await f.files()).length,2,'both durable source versions retained');t.dispose();other.dispose();t._fullbright.dispose();other._fullbright.dispose();
}));
Deno.test('normal disposal cancels pending storage and shipped decode without ready events, and failed known payload never generates',()=>fixture(async f=>{
 const t=texture();let release,held=false,updates=0;const pause=new Promise(r=>release=r);t.addEventListener('newertextureupdated',()=>updates++);f.storage.hooks.beforeClose=async name=>{if(name.endsWith('.gz')){held=true;await pause;}};const work=R_NormalPrepare(t,{disk:f.disk});await until(()=>held,'storage write held');t.dispose();release();await work.promise;same(work.status,'cancelled','disposed job stays cancelled');same(work.data,null,'disposed job has no output');same(R_NormalPrepared(t),undefined,'cache ownership removed');same(updates,0,'no stale ready event');same((await f.files()).length,0,'cancel before manifest is not completed persistence');delete f.storage.hooks.beforeClose;t._fullbright.dispose();
 for(const kind of ['valid','corrupt','cancel']){const tex=texture(true);tex.image.data[0]^={valid:17,corrupt:39,cancel:61}[kind];const input=NormalInputs(tex),key=await NormalInputKey(input),raw=NormalBakeEncode(key,8,8,NormalGenerate(input));NORMAL_BAKES[key]={file:'public-normal.gz',rawSha256:sha(raw),sha256:'fixture'};let fallback=0,finish;try{const w=R_NormalPrepare(tex,{disk:{ensure(){fallback++;throw Error('Known must not fall through to disk');}},generate(){fallback++;throw Error('Known must not generate');},loader:async()=>{if(kind==='cancel')await new Promise(r=>finish=r);return ab(kind==='corrupt'?raw.slice(0,-1):raw);}});if(kind==='cancel'){await until(()=>!!finish,'known load held');tex.dispose();finish();}await w.promise;same(w.status,kind==='valid'?'ready':kind==='cancel'?'cancelled':'error',kind+' known authority');same(fallback,0,kind+' no regeneration');if(kind==='corrupt')check(w.error.includes('checksum'),'known corruption remains explicit');}finally{delete NORMAL_BAKES[key];tex.dispose();tex._fullbright.dispose();}}
}));
Deno.test('different full-byte normal sources create new records and unavailable storage remains an error rather than synchronous fallback',()=>fixture(async f=>{
 for(const variant of ['original','byte4','scalar','offset']){const t=texture(true);if(variant==='byte4')t.image.data[4]^=1;if(variant==='scalar')t.userData.newerHeight.data[4]=.51;if(variant==='offset')t.userData.newerHeight.edgeSource.offset[0]=2;const w=R_NormalPrepare(t,{disk:f.disk});await w.promise;same(w.status,'ready',variant+' persisted');same(w.source,'generated-and-stored',variant+' distinct full source');t.dispose();t._fullbright.dispose();}same((await f.files()).length,4,'four separately validated identities');
 const bad=texture();const w=R_NormalPrepare(bad,{disk:new DisplacementStore(null,null)});await w.promise;same(w.status,'error','unavailable persistence explicit');check(w.error.includes('unavailable'),'filesystem diagnostic retained');same(w.data,null,'not falsely ready');bad.dispose();bad._fullbright.dispose();
}));

Deno.test('malformed crafted reference inputs cannot silently generate a valid-looking cached normal image',()=>{
 for(const [label,change]of [['nonfinite offset',f=>f.edgeSource.offset[0]=NaN],['infinite offset',f=>f.edgeSource.offset[1]=Infinity],['string offset',f=>f.edgeSource.offset[0]='1'],['nonfinite reference scalar',f=>f.edgeSource.data[4]=NaN],['out-of-range reference scalar',f=>f.edgeSource.data[4]=1.5],['authored byte coverage',f=>f.authoredNormal={width:8,height:8,data:new Uint8Array(255)}]]){const t=texture(true);change(t.userData.newerHeight);try{rejects(()=>NormalGenerate(NormalInputs(t)),label);}finally{t.dispose();t._fullbright.dispose();}}
});

Deno.test('same-object byte edits with Three upload hints and direct recipe edits invalidate public normal preparation',()=>fixture(async f=>{
 const missing=[];for(const [label,edit]of [['scalar',t=>{t.userData.newerHeight.data[4]=.73;t.needsUpdate=true;}],['pixels',t=>{t.image.data[4]^=3;t.needsUpdate=true;}],['strength',t=>t.userData.newerHeight.strength=2.5],['edge scalar',t=>{t.userData.newerHeight.edgeSource.data[4]=.87;t.needsUpdate=true;}],['edge offset',t=>t.userData.newerHeight.edgeSource.offset[0]=2]]){const t=texture(true);const before=R_NormalPrepare(t,{disk:f.disk});await before.promise;same(before.status,'ready','initial '+label);same(R_NormalPreparationNeeded(t),false,'unchanged source not scheduled');edit(t);if(!R_NormalPreparationNeeded(t))missing.push(label);const after=R_NormalPrepare(t,{disk:f.disk});check(after!==before,label+' direct public prepare replaces stale work');await after.promise;same(after.status,'ready',label+' current source ready');const expected=NormalGenerate(NormalInputs(t));equal(after.data.pixels,expected.pixels,label+' current pixels');equal(after.data.scalar,expected.scalar,label+' current scalar');equal(after.data.reference,expected.reference,label+' current reference');t.dispose();t._fullbright.dispose();}same(JSON.stringify(missing),'[]','renderer-facing invalidation detects every in-place source edit');
}));

Deno.test('a source edit during persisted normal preparation publishes only the latest snapshot and preserves its readback requirement',()=>fixture(async f=>{
 const t=texture(true);t.image.data[0]^=71;let held=false,release,events=0;const pause=new Promise(r=>release=r);f.storage.hooks.beforeClose=async name=>{if(name.endsWith('.json')&&!held){held=true;await pause;}};t.addEventListener('newertextureupdated',()=>events++);const first=R_NormalPrepare(t,{disk:f.disk});try{await until(()=>held,'first source manifest hold');t.image.data[4]^=23;t.userData.newerHeight.data[4]=.77;t.userData.newerHeight.strength=1.3;t.userData.newerHeight.edgeSource.offset[0]=2;const expected=NormalGenerate(NormalInputs(t));release();await first.promise;const latest=R_NormalPrepared(t);check(latest!==first,'old snapshot replaced before publication');same(latest.status,'ready','replacement actually persisted');same(events,1,'obsolete snapshot never emitted a ready event');for(const k of ['pixels','scalar','reference'])equal(latest.data[k],expected[k],'published current '+k);same((await f.files()).length,2,'old completed source and current source keep distinct immutable files');}finally{release();t.dispose();t._fullbright.dispose();}
}));

Deno.test('distinct normal textures share one shipped transport, one consumer cancellation cannot harm another, and reference dimensions remain authoritative',async()=>{
 const a=texture(true),b=texture(true);a.image.data[0]^=93;b.image.data[0]^=93;const input=NormalInputs(a),key=await NormalInputKey(input),raw=NormalBakeEncode(key,8,8,NormalGenerate(input)),prior=NORMAL_BAKES[key];NORMAL_BAKES[key]={file:'shared-public-normal.gz',sha256:'fixture',rawSha256:sha(raw)};let calls=0,release,signal;const loader=async(_s,s)=>{calls++;signal=s;await new Promise(r=>release=r);return ab(raw);};
 try{const x=R_NormalPrepare(a,{loader}),y=R_NormalPrepare(b,{loader});await until(()=>!!release,'shared transport started');a.dispose();same(signal.aborted,false,'remaining consumer owns shared request');release();await Promise.all([x.promise,y.promise]);same(x.status,'cancelled','cancelled consumer stays cancelled');same(y.status,'ready','live consumer receives validated data');same(calls,1,'distinct images same full source download only once');const c=texture(true);c.image.data[0]^=93;try{const z=R_NormalPrepare(c,{loader:()=>{throw Error('Retained validated transport must be reused');}});await z.promise;same(z.status,'ready','subsequent image reuses retained transport');equal(z.data.pixels,y.data.pixels,'shared exact output');}finally{c.dispose();c._fullbright.dispose();}}
 finally{release?.();a.dispose();b.dispose();a._fullbright.dispose();b._fullbright.dispose();if(prior)NORMAL_BAKES[key]=prior;else delete NORMAL_BAKES[key];}
 const t=texture(true);t.image.data[0]^=117;const i=NormalInputs(t),k=await NormalInputKey(i),generated=NormalGenerate(i),wrong=NormalBakeEncode(k,8,8,{...generated,reference:null,referenceWidth:0,referenceHeight:0});NORMAL_BAKES[k]={file:'reference-coverage-public.gz',sha256:'test',rawSha256:sha(wrong)};try{const w=R_NormalPrepare(t,{loader:async()=>ab(wrong)});await w.promise;same(w.status,'error','self-consistent wrong reference coverage rejected');check(w.error.includes('reference coverage'),'precise mismatch retained');same(w.data,null,'wrong reference never published');}finally{t.dispose();t._fullbright.dispose();delete NORMAL_BAKES[k];}
});

Deno.test('actual Classic/HDR filtering switches do not rescan unchanged normal inputs, while pixel upload hints and recipe edits still prepare',()=>fixture(async f=>{
 const t=texture(true),model={textures:[{name:'normal-sampler-public',gl_texture:t}]},oldMode=gl_texturemode.value;gl_texturemode.value=0;const oldForce=GL_TextureLinear();let generated=0,scans=0;
 try{const first=R_NormalPrepare(t,{disk:f.disk,generate:i=>{generated++;return NormalGenerate(i);}});await first.promise;same(first.status,'ready','real normal input prepared');GL_RegisterTexture(t);GL_RegisterTexture(t._fullbright);GL_SetForceLinear(false);const version=t.version,samplerUpdates=t.userData.normalSamplerUpdates||0;
  t.image.data.every=()=>{scans++;throw Error('Sampler-only change scanned pigment pixels');};t._fullbright.image.data.every=()=>{scans++;throw Error('Sampler-only change scanned fullbright pixels');};
  for(const force of [true,false,true,false]){GL_SetForceLinear(force);same(t.magFilter,force?THREE.LinearFilter:THREE.NearestFilter,'actual GPU filter changes');same(R_NormalPreparationNeeded(t),false,'sampler refresh is not a pixel revision');R_NewerNormalsPrepare(model);same(R_NormalPrepared(t),first,'per-frame model role retains same prepared work');}same(t.version,version+4,'four actual Three GPU upload revisions occur');same(t.userData.normalSamplerUpdates,samplerUpdates+4,'all four sampler revisions tracked');same(scans,0,'real role/selector never reads unchanged pixel arrays');same(generated,1,'no new normal generation');delete t.image.data.every;delete t._fullbright.image.data.every;
  t.image.data[4]^=7;t.needsUpdate=true;same(R_NormalPreparationNeeded(t),true,'real byte upload remains detectable');const changed=R_NormalPrepare(t,{disk:f.disk,generate:i=>{generated++;return NormalGenerate(i);}});await changed.promise;check(changed!==first&&changed.status==='ready','changed actual pigment has separate ready work');same(generated,2,'changed pixels prepare once');t.userData.newerHeight.strength=2.7;same(R_NormalPreparationNeeded(t),true,'recipe metadata independently detected');const recipe=R_NormalPrepare(t,{disk:f.disk,generate:i=>{generated++;return NormalGenerate(i);}});await recipe.promise;same(recipe.status,'ready','new recipe prepared');same(generated,3,'recipe prepares once');
  t.needsUpdate=true;same(R_NormalPreparationNeeded(t),true,'unclassified upload requests one explicit comparison');same(R_NormalPrepare(t,{disk:f.disk}),recipe,'explicit identical input comparison retains work');same(R_NormalPreparationNeeded(t),false,'confirmed identical input updates cheap revision baseline');
 }finally{delete t.image.data.every;delete t._fullbright.image.data.every;GL_UnregisterTexture(t);GL_UnregisterTexture(t._fullbright);GL_SetForceLinear(oldForce);gl_texturemode.value=oldMode;t.dispose();t._fullbright.dispose();}
}));
