// Public optional-asset deadlines and complete/incomplete compositor state.
// Canvas and image transport are controlled endpoints; browser pixel correctness
// is verified separately by player_face_trial.
import {readFileSync} from 'node:fs';
const manifest=JSON.parse(readFileSync(new URL('../newer/hud/playerface/manifest.json',import.meta.url),'utf8'));
const sources=new Set(manifest.assets.map(a=>a.source).filter(Boolean));
const check=(v,m)=>{if(!v)throw Error(m);},same=(a,b,m)=>check(a===b,`${m}: ${a} != ${b}`);
const flush=async()=>{for(let i=0;i<30;i++)await Promise.resolve();};
async function fixture(fn){const old={fetch:globalThis.fetch,setTimeout:globalThis.setTimeout,clearTimeout:globalThis.clearTimeout,Image:Object.getOwnPropertyDescriptor(globalThis,'Image'),document:Object.getOwnPropertyDescriptor(globalThis,'document')},images=[],timers=new Map();let serial=0;globalThis.setTimeout=(fn,ms)=>{same(ms,30000,'face requests have bounded thirty-second deadlines');const id=++serial;timers.set(id,fn);return id;};globalThis.clearTimeout=id=>timers.delete(id);const context=()=>({drawImage(){},save(){},restore(){},translate(){},scale(){},rotate(){},beginPath(){},moveTo(){},lineTo(){},closePath(){},clip(){},fill(){},fillRect(){}});Object.defineProperty(globalThis,'document',{configurable:true,value:{createElement:()=>({width:0,height:0,getContext:context})}});Object.defineProperty(globalThis,'Image',{configurable:true,value:class{constructor(){this.width=this.height=96;images.push(this);}set src(value){this.url=value;}}});globalThis.fetch=async()=>({ok:true,json:async()=>manifest});try{await fn({images,timers,expire:()=>{for(const fn of [...timers.values()])fn();}});}finally{globalThis.fetch=old.fetch;globalThis.setTimeout=old.setTimeout;globalThis.clearTimeout=old.clearTimeout;for(const key of['Image','document'])if(old[key])Object.defineProperty(globalThis,key,old[key]);else delete globalThis[key];}}
Deno.test('real face manifest starts every unique donor image once and settles only after the complete bounded batch',()=>fixture(async env=>{
 const face=await import('../src/newer/ui/r_playerface.js?public-batch'),promise=face.R_PlayerFacePreload();same(face.R_PlayerFacePreload(),promise,'batch promise shared');await flush();same(env.images.length,sources.size,'all exact installed donor sources requested once');check(!face.R_PlayerFaceStatus().settled,'pending images keep face unready');same(face.R_PlayerFaceCompose({expression:'normal',look:'front',health:1}).complete,false,'no incomplete portrait claims readiness');for(const image of env.images.slice(0,-1))image.onload();await flush();check(!face.R_PlayerFaceStatus().settled,'last source remains a real readiness dependency');env.images.at(-1).onload();await promise;same(face.R_PlayerFaceStatus().state,'ready','all donor sources ready');check(face.R_PlayerFaceCompose({expression:'normal',look:'front',health:10,strength:true,invulnerability:true,invisibility:true}).complete,'all requested injury and power layers compose');same(env.timers.size,0,'all deadlines cleared');
}));
Deno.test('failed or timed-out donor sources settle as fallback and late callbacks cannot resurrect incomplete portraits',()=>fixture(async env=>{
 const face=await import('../src/newer/ui/r_playerface.js?public-timeout'),promise=face.R_PlayerFacePreload();await flush();const base=env.images.find(image=>image.url.includes('/bases.png')),late=base.onload;check(base,'real canonical base request exists');env.expire();await promise;const status=face.R_PlayerFaceStatus();same(status.state,'fallback','bounded transport failure is terminal fallback');check(status.settled&&status.errors.includes('bases'),'source failure remains visible');same(status.errors.length,sources.size,'every stalled source has terminal evidence');same(face.R_PlayerFaceCompose({expression:'normal',look:'front',health:1}).complete,false,'missing canonical head cannot produce a completed portrait');late();await flush();same(face.R_PlayerFaceCompose({expression:'normal',look:'front',health:1}).complete,false,'late callback cannot populate timed-out cache');same(env.timers.size,0,'timeout paths release all timers');const count=env.images.length;await face.R_PlayerFacePreload();same(env.images.length,count,'failed optional batch never initiates a retry wave');
}));
Deno.test('stalled or invalid face manifests settle and late manifest completion cannot start an image wave',()=>fixture(async env=>{
 let release;globalThis.fetch=()=>new Promise(resolve=>release=resolve);const face=await import('../src/newer/ui/r_playerface.js?public-stalled-manifest'),promise=face.R_PlayerFacePreload();await flush();env.expire();await promise;check(face.R_PlayerFaceStatus().settled&&face.R_PlayerFaceStatus().state==='fallback','stalled manifest terminates readiness');release({ok:true,json:async()=>manifest});await flush();same(env.images.length,0,'late manifest cannot start source downloads');globalThis.fetch=async()=>({ok:true,json:async()=>({cell_size:96,poses:[],assets:[]})});const invalid=await import('../src/newer/ui/r_playerface.js?public-invalid-manifest');await invalid.R_PlayerFacePreload();same(invalid.R_PlayerFaceStatus().state,'fallback','invalid donor structure is explicit fallback');same(env.images.length,0,'invalid manifest never fabricates image requests');same(env.timers.size,0,'manifest deadlines released');
}));
