import '../src/gl_rsurf.js';
import {FaceState} from '../src/face_state.js';
import {R_PlayerFacePreload,R_PlayerFaceStatus,R_PlayerFaceCompose,R_PlayerFaceLayer} from '../src/r_playerface.js';
const $=id=>document.getElementById(id),state=new FaceState({random:()=>.25});let time=0,manifest;
const pixels=canvas=>canvas.getContext('2d').getImageData(0,0,96,96).data;
const differ=(a,b)=>{let n=0;for(let i=0;i<a.length;i++)if(a[i]!==b[i])n++;return n;};
function settings(){return{time,health:Number($('health').value),attacking:$('attack').checked,strength:$('strength').checked,invulnerability:$('invulnerability').checked,invisibility:$('invisibility').checked};}
function show(){const snapshot=state.frame(settings()),result=R_PlayerFaceCompose(snapshot),ctx=$('portrait').getContext('2d');ctx.clearRect(0,0,96,96);ctx.imageSmoothingEnabled=false;if(result.canvas)ctx.drawImage(result.canvas,0,0);$('state').textContent=JSON.stringify({time,...snapshot,complete:result.complete,missing:result.missing,layers:result.selection?.layers},null,2);return snapshot;}
for(const button of document.querySelectorAll('[data-step]'))button.onclick=()=>{time+=Number(button.dataset.step);show();};
for(const button of document.querySelectorAll('[data-event]'))button.onclick=()=>{const event=button.dataset.event;if(event==='reset'){time=0;state.reset(0);$('health').value=100;}else if(event==='reward')state.reward(time);else if(event==='shot')state.shot({time,cadence:.1});else{const healthLoss=event==='heavy'?21:5;state.damage({time,healthLoss,angle:event==='left'?-90:event==='right'?90:0});$('health').value=Math.max(0,Number($('health').value)-healthLoss);}show();};
for(const input of document.querySelectorAll('input'))input.onchange=show;
$('fire').onclick=()=>{$('attack').checked=true;for(let i=0;i<22;i++){if(i)time+=.1;state.shot({time,cadence:.1});state.frame(settings());}show();};
function imageFigure(canvas,label){const fig=document.createElement('figure'),copy=document.createElement('canvas'),caption=document.createElement('figcaption');copy.width=copy.height=96;copy.getContext('2d').drawImage(canvas,0,0);caption.textContent=label;fig.append(copy,caption);$('gallery').append(fig);}
function inside(point,polygon){let result=false;for(let i=0,j=polygon.length-1;i<polygon.length;j=i++){const a=polygon[i],b=polygon[j];if((a[1]>point[1])!==(b[1]>point[1])&&point[0]<(b[0]-a[0])*(point[1]-a[1])/(b[1]-a[1])+a[0])result=!result;}return result;}
function nearPolygon(point,poly){if(inside(point,poly))return true;for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length],dx=b[0]-a[0],dy=b[1]-a[1],t=Math.max(0,Math.min(1,((point[0]-a[0])*dx+(point[1]-a[1])*dy)/(dx*dx+dy*dy||1)));if(Math.hypot(point[0]-a[0]-t*dx,point[1]-a[1]-t*dy)<=1)return true;}return false;}
async function run(){const checks=[],check=(passed,name,extra={})=>checks.push({passed,name,...extra});$('checks').disabled=true;$('gallery').replaceChildren();try{
 const status=R_PlayerFaceStatus();check(status.settled&&status.errors.length===0,'all installed donor assets settled successfully',status);let count=0,nonempty=0,missing=[],wrong=[];
 for(const pose of manifest.poses){for(const health of Array.from({length:10},(_,i)=>i+1))for(const mask of Array.from({length:8},(_,i)=>i)){const value={look:pose.look,expression:pose.expression,health,healthPercent:100-(health-1)*10,strength:!!(mask&1),invulnerability:!!(mask&2),invisibility:!!(mask&4)},out=R_PlayerFaceCompose(value);count++;if(!out.complete)missing.push({pose:pose.id,health,mask,missing:out.missing});if(out.canvas?.width!==96||out.canvas?.height!==96)wrong.push(pose.id);if(out.canvas&&pixels(out.canvas).some((v,i)=>i%4===3&&v>0))nonempty++;const sel=out.selection;if(sel?.pose.id!==pose.id||sel.health!==health||sel.layers.base!==pose.base_asset||!!sel.layers.blood!==(health>1)||sel.effect!==((mask&3)===3?'mixed':mask&1?'purple':mask&2?'yellow':null)||!!sel.layers.mask!==!!(mask&4)||sel.layers.blood?.asset!==(health>1?pose.blood_layers[health-2].asset:undefined))wrong.push({pose:pose.id,health,mask,selection:sel});if(health===10&&mask===7)imageFigure(out.canvas,pose.id+' · H10 · all powers');}}
 check(count===2000&&nonempty===2000&&missing.length===0&&wrong.length===0,'all2000 expression/pose/health/power combinations retain exact registered donor layers',{count,nonempty,missing,wrong});
 const power=[];for(let mask=0;mask<8;mask++){const out=R_PlayerFaceCompose({look:'front',expression:'normal',health:8,strength:!!(mask&1),invulnerability:!!(mask&2),invisibility:!!(mask&4)});power.push({mask,effect:out.selection.effect,blood:!!out.selection.layers.blood,invisible:!!out.selection.layers.mask,complete:out.complete});}check(power.every(x=>x.complete&&x.blood&&x.invisible===!!(x.mask&4)&&x.effect===((x.mask&3)===3?'mixed':x.mask&1?'purple':x.mask&2?'yellow':null)),'eight power combinations coexist with the same injury stage', {power});
 const gaze=[];for(const expression of manifest.expressions){const front=R_PlayerFaceCompose({look:'front',expression,health:1});for(const look of['eyes_left','eyes_right']){const out=R_PlayerFaceCompose({look,expression,health:1}),a=pixels(front.canvas),b=pixels(out.canvas),polygons=out.selection.pose.eye_openings;let changed=0,outside=0;for(let i=0;i<96*96;i++){if([0,1,2,3].every(k=>a[i*4+k]===b[i*4+k]))continue;changed++;if(!polygons.some(p=>nearPolygon([i%96+.5,Math.floor(i/96)+.5],p)))outside++;}gaze.push({expression,look,changed,outside,canonicalBase:out.selection.layers.base===front.selection.layers.base});}}check(gaze.every(x=>x.canonicalBase&&x.changed>0&&x.outside===0),'eye glances reuse canonical head and alter only registered eye openings (one-pixel antialias boundary)',{gaze});
 const blood=[];for(const expression of manifest.expressions){const pose=manifest.poses.find(p=>p.expression===expression&&p.look==='front'),out=R_PlayerFaceCompose({look:'front',expression,health:10}),healthy=R_PlayerFaceCompose({look:'front',expression,health:1}),layer=R_PlayerFaceLayer(pose.blood_layers[8].asset,pose.id);const ctx=document.createElement('canvas').getContext('2d');ctx.canvas.width=ctx.canvas.height=96;ctx.drawImage(healthy.canvas,0,0);ctx.drawImage(layer.canvas,0,0);blood.push({expression,exact:differ(pixels(ctx.canvas),pixels(out.canvas))===0,changed:differ(pixels(healthy.canvas),pixels(out.canvas)),complete:layer.complete});imageFigure(layer.canvas,expression+' · supplied H10 blood only');}check(blood.every(x=>x.exact&&x.changed>0&&x.complete),'health selects one complete registered donor decal with no added blood generation',{blood});
 for(const look of['head_left','head_right']){const pose=manifest.poses.find(p=>p.expression==='normal'&&p.look===look),blood=R_PlayerFaceLayer(pose.blood_layers[8].asset,pose.id);imageFigure(blood.canvas,'normal '+look+' · supplied H10 blood only');}
 const timing=new FaceState({random:()=>0});timing.reset(0);timing.damage({time:0,healthLoss:21,angle:90});const samples=[0,.04,.08,.2,.999,1.001].map(t=>timing.frame({time:t,health:79}));check(samples[0].expression==='shocked'&&samples[0].look==='front'&&samples[1].look==='eyes_right'&&samples[2].look==='head_right'&&samples[4].expression==='shocked'&&samples[5].expression==='normal','real public controller drives neighboring poses and immediate shock independently of canvas',{samples});
 }catch(error){checks.push({passed:false,name:String(error),stack:error.stack});}finally{$('checks').disabled=false;}const result={status:checks.every(c=>c.passed)?'PASS':'FAIL',checks,scope:'Actual installed donor canvas composition and public controller. No game loop. Anatomical nose clearance is shown for owner visual review, not inferred from an invented pixel mask; native event adapter integration is separate.'};window.playerFaceResult=result;$('report').textContent=JSON.stringify(result,null,2);show();return result;}
try{manifest=await(await fetch('../newer/hud/playerface/manifest.json')).json();await R_PlayerFacePreload();$('checks').disabled=false;$('checks').onclick=run;$('report').textContent='Ready. Run bounded checks to populate all poses and isolated blood layers.';show();}catch(error){$('report').textContent=String(error.stack||error);window.playerFaceResult={status:'FAIL',error:String(error)};}
