// Public power-vision lifecycle and MRT contracts with real Three objects.
// A recording renderer exercises actual pass scheduling; GPU pixel semantics
// are checked separately by the finite powervision_semantics_trial.html.
import assert from 'node:assert/strict';
import * as THREE from 'three';
import * as vision from '../src/r_powervision.js';
import { PowerVisionMode } from '../src/powervision_state.js';
import * as post from '../src/gl_post.js';
import * as anim from '../src/r_anim.js';
import * as skins from '../src/r_newerskins.js';
import * as view from '../src/view.js';
import { Cvar_FindVar, Cvar_RegisterVariable } from '../src/cvar.js';
if(!Cvar_FindVar(post.r_hdr.name))Cvar_RegisterVariable(post.r_hdr);
import { cl, CSHIFT_POWERUP, CSHIFT_DAMAGE, CSHIFT_BONUS, CSHIFT_CONTENTS } from '../src/client.js';
import { IT_INVISIBILITY, IT_INVULNERABILITY, IT_QUAD, IT_SUIT, STAT_HEALTH } from '../src/quakedef.js';
function fixture(run) {
 vision.R_PowerVisionReset(true);
 const camera=new THREE.PerspectiveCamera(75,640/360,4,4096); camera.updateMatrixWorld();
 const source=new THREE.Texture(),hdr={width:640,height:360,depthTexture:new THREE.Texture(),textures:[source,new THREE.Texture(),new THREE.Texture()]};
 const client={items:IT_INVISIBILITY,stats:[],time:10,worldmodel:{},viewentity:1};client.stats[STAT_HEALTH]=100;
 const caller=new THREE.WebGLRenderTarget(8,8),calls=[];let target=caller,fail=0;
 const renderer={getRenderTarget:()=>target,setRenderTarget:value=>{target=value;},render(scene){const material=scene.children[0].material,u=material.uniforms;calls.push({target,material,source:u.tScene.value,current:u.tCurrent.value,history:u.tHistory.value,depth:u.tDepth.value,normal:u.tNormal.value,albedo:u.tAlbedo.value,valid:u.uValid.value,delta:u.uDelta.value,near:u.uNear.value,far:u.uFar.value,previous:u.uPreviousViewProjection.value.clone()});if(fail&&calls.length===fail)throw Error('controlled vision pass failure');}};
 const api={camera,source,hdr,client,caller,calls,renderer,render:()=>vision.R_PowerVisionRender(renderer,source,hdr,camera,PowerVisionMode(client,true),client),set failAt(value){fail=value;}};
 try{run(api);}finally{vision.R_PowerVisionReset(true);caller.dispose();source.dispose();hdr.depthTexture.dispose();hdr.textures.slice(1).forEach(t=>t.dispose());}
}
Deno.test('public vision follows native expiry and renders paused views without repeated history feedback',()=>fixture(f=>{
 const snapshot=JSON.stringify(f.client),first=f.render();assert.equal(f.calls.length,2);assert.equal(f.calls[1].valid,0);assert.equal(f.calls[0].source,f.source);assert.equal(f.calls[0].depth,f.hdr.depthTexture);assert.equal(f.calls[0].normal,f.hdr.textures[1]);assert.equal(f.calls[0].albedo,f.hdr.textures[2]);assert.equal(f.calls[0].near,4);assert.equal(f.calls[0].far,4096);assert.equal(f.renderer.getRenderTarget(),f.caller);assert.equal(JSON.stringify(f.client),snapshot,'rendering does not mutate native state');
 const paused=f.render();assert.notEqual(paused,first,'paused frame still renders current picture');assert.equal(f.calls.length,4);assert.equal(f.calls[3].valid,0,'pause disables history feedback');assert.equal(f.calls[3].delta,0);f.camera.position.x=1;f.camera.updateMatrixWorld();f.render();assert.equal(f.calls.at(-1).valid,0,'paused camera movement keeps current view without feedback');const pausedCurrent=f.calls.at(-1).target.texture;f.client.time+=.016;const second=f.render();assert.notEqual(second,pausedCurrent);assert.equal(f.calls.length,8);assert.equal(f.calls[7].history,pausedCurrent,'history consumes previous completed frame');assert.equal(f.calls[7].valid,1);
 f.client.items|=IT_INVULNERABILITY;f.client.time+=.016;f.render();assert.equal(f.calls.length,10,'ring wins while both native bits remain');f.client.items&=~IT_INVISIBILITY;f.client.time+=.016;const demon=f.render();assert.equal(f.calls.length,11,'ring expiry resumes one-pass Demon');assert.equal(vision.R_PowerVisionStatus().mode,2);assert.equal(f.calls[10].valid,0,'no ring history applied to Demon');assert.equal(demon,f.calls[10].target.texture);
 f.client.items=0;assert.equal(f.render(),f.source,'native expiry returns original composite');assert.equal(f.calls.length,11,'expired mode performs no pass');assert.equal(vision.R_PowerVisionStatus().mode,0);f.client.items=IT_INVISIBILITY;f.render();assert.equal(f.calls.at(-1).valid,0,'renewed item cannot resurrect stale history');
}));
Deno.test('public vision clears temporal history across map view camera time and framebuffer changes',()=>fixture(f=>{
 f.render();for(const alter of[()=>{f.client.worldmodel={};},()=>{f.client.viewentity++;},()=>{f.camera.position.x+=100;f.camera.updateMatrixWorld();},()=>{f.camera.rotateY(Math.PI);f.camera.updateMatrixWorld();},()=>{f.client.time-=5;},()=>{f.client.time+=1;},()=>{f.camera.fov=95;f.camera.updateProjectionMatrix();}]){f.client.time+=.016;alter();f.render();assert.equal(f.calls.at(-1).valid,0,'discontinuity rejects history');}
 const oldTargets=new Set(f.calls.map(c=>c.target)),materials=new Set(f.calls.map(c=>c.material));let disposed=0;for(const object of [...oldTargets,...materials])object.addEventListener('dispose',()=>disposed++);
 f.hdr.width=320;f.hdr.height=180;f.client.time+=.016;f.render();assert.equal(f.calls.at(-1).valid,0);assert.equal(vision.R_PowerVisionStatus().width,320);assert.ok(disposed>=oldTargets.size+materials.size,'resize disposes observed previous targets and materials');assert.equal(f.renderer.getRenderTarget(),f.caller);
}));
Deno.test('failed history rendering restores caller target and never promotes an incomplete history target',()=>fixture(f=>{
 const completed=f.render();f.client.time+=.016;f.failAt=4;assert.throws(()=>f.render(),/controlled vision pass failure/);assert.equal(f.renderer.getRenderTarget(),f.caller,'exception restores caller target');f.failAt=0;f.client.time+=.016;f.render();assert.equal(f.calls.at(-1).history,completed,'next successful frame reads last completed history, not failed target');
}));
function nativeFixture(run){
 const vars=[post.r_hdr,anim.r_newer_lighting,anim.r_newer_normals,anim.r_newer_water],values=vars.map(v=>v.value),old={items:cl.items,health:cl.stats[STAT_HEALTH],intermission:cl.intermission,newer:anim.R_IsNewer(),classic:anim.R_ClassicPassActive(),lighting:anim.R_NewerLightingActive(),hdrString:post.r_hdr.string,shifts:cl.cshifts.map(s=>({percent:s.percent,destcolor:Array.from(s.destcolor)})),prev:cl.prev_cshifts.map(s=>({percent:s.percent,destcolor:Array.from(s.destcolor)}))};
 const renderer={capabilities:{isWebGL2:true},extensions:{has:()=>true},setRenderTarget:target=>{renderer.target=target;}};
 post.r_hdr.value=1;post.r_hdr.string='1';anim.r_newer_lighting.value=anim.r_newer_normals.value=anim.r_newer_water.value=0;cl.stats[STAT_HEALTH]=100;cl.intermission=0;anim.R_AnimSetClassicPass(false);
 try{run(renderer);}finally{post.R_PostShutdown();vars.forEach((v,i)=>v.value=values[i]);post.r_hdr.string=old.hdrString;cl.items=old.items;cl.stats[STAT_HEALTH]=old.health;cl.intermission=old.intermission;for(const key of['shifts','prev'])old[key].forEach((s,i)=>{const out=(key==='shifts'?cl.cshifts:cl.prev_cshifts)[i];out.percent=s.percent;out.destcolor.set?s.destcolor.forEach((v,j)=>out.destcolor[j]=v):out.destcolor=s.destcolor;});anim.R_AnimSetClassicPass(old.classic);anim.R_AnimSetNewer(old.newer);anim.R_AnimSetLighting(old.lighting);}
}
Deno.test('public HDR admission allocates unfiltered semantic MRT only while native vision is active with other features off',()=>nativeFixture(renderer=>{
 cl.items=0;assert.equal(post.R_PostBegin(renderer,true,640,360),false);for(const item of[IT_INVISIBILITY,IT_INVULNERABILITY]){cl.items=item;assert.equal(post.R_PostBegin(renderer,true,640,360),true,'vision independently admits shared post pipeline');post.R_PostBind(renderer);assert.equal(renderer.target.textures.length,4,'vision has actual pigment and receiver attachments');assert.equal(renderer.target.samples,0,'receiver tags cannot be multisample averaged');for(const index of[1,2]){assert.equal(renderer.target.textures[index].minFilter,THREE.NearestFilter);assert.equal(renderer.target.textures[index].magFilter,THREE.NearestFilter);}assert.equal(renderer.target.textures[2].type,THREE.UnsignedByteType);}
 cl.items=0;assert.equal(post.R_PostBegin(renderer,true,640,360),false,'native expiry immediately exits otherwise idle pipeline');cl.items=IT_INVISIBILITY;assert.equal(post.R_PostBegin(renderer,false,640,360),false,'Classic mode refuses vision pipeline');assert.equal(vision.R_PowerVisionStatus().mode,0);cl.stats[STAT_HEALTH]=0;assert.equal(post.R_PostBegin(renderer,true,640,360),false,'death disables vision admission');cl.stats[STAT_HEALTH]=100;cl.intermission=1;assert.equal(post.R_PostBegin(renderer,true,640,360),false,'intermission disables vision admission');
}));
Deno.test('public palette update suppresses only active vision tint and retains native Quad Suit and other cshifts',()=>nativeFixture(renderer=>{
 for(const shift of cl.cshifts)shift.percent=0;
 for(const [item,nativePercent] of[[IT_INVISIBILITY,100],[IT_INVULNERABILITY,30]]){cl.items=item;post.R_PostBegin(renderer,false,640,360);view.V_UpdatePalette();assert.equal(cl.cshifts[CSHIFT_POWERUP].percent,nativePercent,'Classic native item tint preserved');post.R_PostBegin(renderer,true,640,360);view.V_UpdatePalette();assert.equal(cl.cshifts[CSHIFT_POWERUP].percent,0,'active supplied vision replaces old full-screen tint');}
 for(const [item,percent]of[[IT_QUAD,30],[IT_SUIT,20]]){cl.items=IT_INVISIBILITY|item;post.R_PostBegin(renderer,true,640,360);view.V_UpdatePalette();assert.equal(cl.cshifts[CSHIFT_POWERUP].percent,percent,'higher-priority native tint retained');}
 cl.cshifts[CSHIFT_CONTENTS].percent=80;cl.cshifts[CSHIFT_DAMAGE].percent=90;cl.cshifts[CSHIFT_BONUS].percent=40;cl.items=IT_INVISIBILITY;view.V_UpdatePalette();assert.equal(cl.cshifts[CSHIFT_CONTENTS].percent,80,'liquid tint remains');assert.ok(cl.cshifts[CSHIFT_DAMAGE].percent>0,'damage tint remains');assert.ok(cl.cshifts[CSHIFT_BONUS].percent>0,'pickup tint remains');cl.items=0;view.V_UpdatePalette();assert.equal(cl.cshifts[CSHIFT_POWERUP].percent,0,'expiry restores untinted native state');
}));
function compiled(material){const shader={uniforms:{},vertexShader:'#include <project_vertex>',fragmentShader:'void main() {\n#include <map_fragment>\n#include <opaque_fragment>\n#include <colorspace_fragment>\n}'};material.onBeforeCompile(shader);return shader;}
Deno.test('native enemy material exports vision subject and true-depth packets with relief off and preserves held and pickup semantics',()=>nativeFixture(renderer=>{
 const texture=new THREE.DataTexture(new Uint8Array(64).fill(128),4,4);skins.R_NewerSetIndex({models:{}});cl.items=IT_INVISIBILITY;post.R_PostBegin(renderer,true,640,360);
 try{const enemy=skins.R_EnemyAliasMaterial(texture,'progs/dog.mdl',true);assert.ok(enemy,'native subject remains tagged when normals option is off');assert.equal(enemy.map,texture,'vision keeps native diffuse ownership');const shader=compiled(enemy);assert.match(shader.fragmentShader,/gAlbedo = vec4\( qrAlbedo, 0\.065 \)/);assert.match(shader.fragmentShader,/gNormal = vec4\(qrN\*0\.5\+0\.5,vQrView.z\)/);assert.equal(shader.uniforms.uSkinDetail.value,0,'vision does not enable disabled relief');
 const held=skins.R_CloneAliasMaterial(enemy);held.userData.quakeViewmodel=true;held.userData.quakePlayerSurface=true;const heldShader=compiled(held);assert.match(heldShader.fragmentShader,/gAlbedo = vec4\( qrAlbedo, 0\.08 \)/);assert.match(heldShader.fragmentShader,/-vQrView.z-2\./,'held packet stores true view distance independently of compressed hardware depth');
 const pickup=skins.R_AssetAliasMaterial({diffuse:texture},'pickup');assert.match(compiled(pickup).fragmentShader,/gAlbedo = vec4\( qrAlbedo, 0\.06 \)/,'pickups are not enemy subjects');held.dispose();pickup.dispose();cl.items=0;assert.equal(skins.R_EnemyAliasMaterial(texture,'progs/dog.mdl',true),null,'native expiry returns normal material selection with relief off');anim.R_AnimSetClassicPass(true);cl.items=IT_INVISIBILITY;assert.equal(skins.R_EnemyAliasMaterial(texture,'progs/dog.mdl',true),null,'Classic pass refuses native vision wrapper');
 }finally{skins.R_NewerSkinsShutdown();texture.dispose();}
}));

Deno.test('native vision wrapper can acquire relief after normals are enabled without replacing native diffuse',()=>nativeFixture(renderer=>{
 const descriptor=Object.getOwnPropertyDescriptor(globalThis,'window'),texture=new THREE.DataTexture(new Uint8Array(64).fill(128),4,4),model={name:'progs/dog.mdl'};
 Object.defineProperty(globalThis,'window',{configurable:true,value:{}});skins.R_NewerSetIndex({models:{}});cl.items=IT_INVISIBILITY;post.R_PostBegin(renderer,true,640,360);
 try{const material=skins.R_EnemyAliasMaterial(texture,model.name,true);assert.ok(material);assert.equal(skins.R_NewerSkinsStatus([model]).normals.pending,0,'normals-off browser wrapper starts no expensive normal work');anim.r_newer_normals.value=1;assert.equal(skins.R_EnemyAliasMaterial(texture,model.name,true),material,'toggle reuses existing material');assert.equal(skins.R_NewerSkinsStatus([model]).normals.pending,1,'cached wrapper starts missing relief preparation');assert.equal(material.map,texture,'native diffuse remains original');skins.R_EnemyAliasMaterial(texture,model.name,true);assert.equal(skins.R_NewerSkinsStatus([model]).normals.pending,1,'subsequent draws do not duplicate relief work');
 }finally{skins.R_NewerSkinsShutdown();texture.dispose();if(descriptor)Object.defineProperty(globalThis,'window',descriptor);else delete globalThis.window;}
}));
Deno.test('actual post finish feeds vision the completed linear composite and presents its output before expiry restores native composition',()=>nativeFixture(renderer=>{
 const oldTime=cl.time,passes=[];const camera=new THREE.PerspectiveCamera(75,640/360,4,4096),scene=new THREE.Scene();camera.updateMatrixWorld();renderer.getRenderTarget=()=>renderer.target;renderer.setViewport=()=>{};renderer.setScissorTest=()=>{};renderer.render=scene=>{const material=scene.children[0].material;passes.push({target:renderer.target,material,scene:material.uniforms.tScene?.value,composite:material.uniforms.tComposite?.value,current:material.uniforms.tCurrent?.value});};
 const finish=()=>post.R_PostFinish(renderer,scene,camera,{lx:0,ly:0,lw:640,lh:360},0,[],[],cl.time,1,false);
 try{cl.time=10;cl.items=IT_INVISIBILITY;assert.equal(post.R_PostBegin(renderer,true,640,360),true);post.R_PostBind(renderer);const hdr=renderer.target;finish();assert.equal(passes.length,4,'linear composite, Unseen, history and final presentation');assert.equal(passes[0].scene,hdr.textures[0],'post composite reads rendered world color');assert.equal(passes[1].scene,passes[0].target.texture,'vision reads completed composite');assert.equal(passes[2].current,passes[1].target.texture,'history reads completed Unseen pass');assert.equal(passes[3].composite,passes[2].target.texture,'final presentation reads completed history');assert.equal(passes[3].target,null,'output returns to display');
 cl.items=0;cl.time+=.016;anim.r_newer_normals.value=1;passes.length=0;assert.equal(post.R_PostBegin(renderer,true,640,360),true,'independent relief keeps shared post active after item expiry');finish();assert.equal(vision.R_PowerVisionStatus().mode,0,'native expiry clears history through real post path');assert.equal(passes.length,1,'expired vision adds no extra passes');assert.equal(passes[0].target,null,'normal composite goes straight to display');
 }finally{cl.time=oldTime;}
}));
Deno.test('half-float-only advertised post capability uses packed byte optical targets through Demon and Ring',()=>nativeFixture(renderer=>{
 const oldTime=cl.time,camera=new THREE.PerspectiveCamera(75,640/360,4,4096),scene=new THREE.Scene(),passes=[];camera.updateMatrixWorld();renderer.extensions.has=name=>name==='EXT_color_buffer_half_float';renderer.getRenderTarget=()=>renderer.target;renderer.setViewport=()=>{};renderer.setScissorTest=()=>{};renderer.render=scene=>passes.push({target:renderer.target,material:scene.children[0].material});
 try{for(const [item,mode,expectedPasses]of[[IT_INVULNERABILITY,2,3],[IT_INVISIBILITY,1,4]]){cl.items=item;cl.time=(cl.time||1)+.016;passes.length=0;assert.equal(post.R_PostBegin(renderer,true,640,360),true,'half-float capability still admits native vision');post.R_PostBind(renderer);post.R_PostFinish(renderer,scene,camera,{lx:0,ly:0,lw:640,lh:360},0,[],[],cl.time,1,false);assert.equal(passes.length,expectedPasses,'only required current mode passes run');const coordinates=passes[0].target.textures[1];assert.equal(coordinates.type,THREE.UnsignedByteType,'composite coordinates use four byte channels');assert.equal(coordinates.minFilter,THREE.NearestFilter);assert.equal(coordinates.userData.visionEncoded,true);assert.equal(passes[1].material.uniforms.tVisionCoordinates.value,coordinates,'actual vision receives compositor optical field');assert.equal(passes[1].material.uniforms.uVisionCoordinates.value,2,'actual vision enables packed decoder');for(const pass of passes)for(const texture of pass.target?.textures||[])assert.notEqual(texture.type,THREE.FloatType,'vision render path requires no float32 color attachment');if(mode===1){const history=passes[2].target;assert.equal(history.textures.length,2);assert.equal(history.textures[1].type,THREE.UnsignedByteType);assert.equal(history.textures[1].userData.visionEncoded,true,'Ring history retains packed optical coordinates');}}
 }finally{cl.time=oldTime;}
}));
