// Independent native QC death/remains and atomic inventory-custody tests.
// Owner override: the axe is NOT dropped, despite the supplied demo's README.
import { readFileSync } from 'node:fs';
import * as THREE from 'three';
import * as pak from '../src/engine/common/pak.js';
import { VID_SetPalette } from '../src/engine/render/vid.js';
import { Mod_Init } from '../src/engine/render/gl_model.js';
import { PR_InitBuiltins } from '../src/engine/progs/pr_cmds.js';
import { PR_ExecuteProgram } from '../src/engine/progs/pr_exec.js';
import * as progs from '../src/engine/progs/progs.js';
import { ED_FindFunction, ED_NewString, ED_Write, ED_ParseEdict, ED_Alloc, ED_Free, GetEdictFieldValue } from '../src/engine/progs/pr_edict.js';
import { OFS_PARM0 } from '../src/engine/progs/pr_comp.js';
import { sv, svs, client_t, FL_MONSTER, FL_ONGROUND } from '../src/engine/server/server.js';
import { SV_SpawnServer, SV_CheckForNewClients, SV_SaveSpawnparms, SV_ClearCarriedPowerups, SV_WriteClientdataToMessage } from '../src/engine/server/sv_main.js';
import { SV_RunTriggerTouch, SV_LinkEdict, SV_Move, MOVE_NOMONSTERS } from '../src/engine/server/world.js';
import { SV_Physics, SV_Physics_Client, SV_Physics_Toss, SV_SetPlayer, SV_SetFrametime, SV_PushEntity, sv_gravity } from '../src/engine/server/sv_phys.js';
import * as travel from '../src/newer/gameplay/sv_seamless.js';
import * as respawn from '../src/newer/gameplay/sv_respawn.js';
import {Respawn_DropAmmo} from '../src/newer/gameplay/respawn_record.js';
import * as vars from '../src/engine/common/cvar.js';
import { Cbuf_Init, Cbuf_Execute, Cmd_AddCommand, Cmd_ExecuteString, src_command } from '../src/engine/common/cmd.js';
import { SZ_Alloc, SZ_Clear, sizebuf_t, COM_SetNetMessage } from '../src/engine/common/common.js';
import { CL_ParseServerMessage } from '../src/engine/client/cl_parse.js';
import { r_hdr } from '../src/newer/render/gl_post.js';
import { skill } from '../src/engine/server/host.js';
import { R_AnimSetClassicPass } from '../src/newer/mode.js';
import { cls, cl, cl_entities, set_cl_numvisedicts, ca_disconnected, ca_connected, ca_dedicated } from '../src/engine/client/client.js';
import * as Q from '../src/engine/common/quakedef.js';
import { R_LevelEntities } from '../src/newer/render/r_levelents.js';
import { NET_Init, NET_Close } from '../src/engine/net/net_main.js';
import { Loop_Connect, Loop_CheckNewConnections } from '../src/engine/net/net_loop.js';
import { V_Init, V_CalcRefdef } from '../src/engine/client/view.js';
import * as render from '../src/engine/render/gl_rmain.js';
import { r_refdef, entity_t } from '../src/engine/render/render.js';
import { R_DrawAliasModel } from '../src/engine/render/gl_mesh.js';
import { Host_InitCommands } from '../src/engine/server/host_cmd.js';
import { Respawn_Sample } from '../src/newer/ui/respawn_motion.js';
const check=(v,m)=>{if(!v)throw Error(m);},same=(a,b,m)=>check(a===b,`${m}: ${a} != ${b}`),near=(a,b,m,e=1e-4)=>check(Math.abs(a-b)<e,`${m}: ${a} != ${b}`);
const pools=['ammo_shells','ammo_nails','ammo_rockets','ammo_cells'], weapons=[1,2,4,8,16,32,64],powerFields=['invisible_finished','invincible_finished','super_damage_finished','radsuit_finished','invisible_time','invincible_time','super_time','rad_time'];
const text=i=>progs.PR_GetString(i),fn=n=>{const f=ED_FindFunction(n);check(f,'native function '+n);return progs.pr_functions.indexOf(f);};
function field(e,n,value){const s=GetEdictFieldValue(e,n);check(s,'native field '+n);if(value!==undefined)s.accessor.setFloat(s.ofs,value);return s.accessor.getFloat(s.ofs);}
function call(e,n){progs.pr_global_struct.self=progs.EDICT_TO_PROG(e);progs.pr_global_struct.time=sv.time;PR_ExecuteProgram(typeof n==='string'?fn(n):n);}
const bytes=readFileSync(new URL('../pak0.pak',import.meta.url));pak.COM_AddPack(pak.COM_LoadPackFile('pak0.pak',bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.length)));VID_SetPalette(pak.COM_FindFile('gfx/palette.lmp').data);Mod_Init();PR_InitBuiltins();Cbuf_Init();
for(const c of[r_hdr,skill,sv_gravity,travel.sv_seamless])if(!vars.Cvar_FindVar(c.name))vars.Cvar_RegisterVariable(c);
respawn.sv_respawnguard.value=0; // the guard monster (respawn_guard_native_test.js) is not part of this test
let restarts=0;Cmd_AddCommand('restart',()=>restarts++);
function spawn(map='e1m1',reset=true,enhanced=true){if(reset){travel.SV_SeamlessReset();svs.maxclients=1;svs.clients=[new client_t()];SZ_Alloc(svs.clients[0].message,32768);}cls.state=ca_disconnected;cls.demoplayback=false;vars.Cvar_SetValue('r_hdr',enhanced?1:0);vars.Cvar_SetValue('skill',1);vars.Cvar_SetValue('sv_seamless',1);R_AnimSetClassicPass(false);sv.active=false;SV_SpawnServer(map);const p=svs.clients[0].edict;call(p,progs.pr_global_struct.SetNewParms);call(p,progs.pr_global_struct.ClientConnect);call(p,progs.pr_global_struct.PutClientInServer);svs.clients[0].active=true;svs.clients[0].spawned=true;check(p.v.health===100&&p._respawnStart&&(enhanced?!!p._respawn:!p._respawn),'actual native spawn captures checkpoint and admits coordinator only in Newer');return p;}
const drops=()=>sv.edicts.filter(e=>e&&!e.free&&e._respawnDrop);
const totals=p=>pools.map((a,i)=>p.v[a]+drops().reduce((sum,e)=>sum+Respawn_DropAmmo(e._respawnDrop)[i],0));
function inventory(p,ammo=[19,61,7,13],bits=127|Q.IT_AXE){p.v.items=bits;p.v.weapon=bits&Q.IT_SHOTGUN?Q.IT_SHOTGUN:Q.IT_AXE;pools.forEach((a,i)=>p.v[a]=ammo[i]);call(p,'W_SetCurrentAmmo');}
function kill(p,command=false){if(command)call(p,'ClientKill');else{const world=sv.edicts[0];progs.pr_globals_int[OFS_PARM0]=progs.EDICT_TO_PROG(p);progs.pr_globals_int[OFS_PARM0+3]=progs.EDICT_TO_PROG(world);progs.pr_globals_int[OFS_PARM0+6]=progs.EDICT_TO_PROG(world);progs.pr_globals_float[OFS_PARM0+9]=200;call(p,'T_Damage');}check(p._respawn?.sequence,'native lethal outcome starts sequence');return p._respawn.sequence;}
function at(p,time){sv.time=time;progs.pr_global_struct.time=time;SV_SetFrametime(.01);SV_Physics_Client(p,1);}
function finish(p){const s=p._respawn.sequence,cut=s.at+.22+s.turn/2+1e-6,end=s.at+.22+s.turn+.001;if(sv.time<cut)at(p,cut);check(s.respawned,'native physics reaches contact');if(sv.time<end)at(p,end);check(!p._respawn.sequence,'native physics finishes sequence');}


function settle(list){SV_SetFrametime(.02);for(let frame=0;frame<250&&list.some(e=>!e.free&&!(e.v.flags&FL_ONGROUND));frame++){sv.time+=.02;progs.pr_global_struct.time=sv.time;for(const e of list)if(!e.free)SV_Physics_Toss(e);}check(list.every(e=>!e.free&&(e.v.flags&FL_ONGROUND)),'actual native toss collision settles every drop');for(const e of list){const fit=SV_Move(e.v.origin,e.v.mins,e.v.maxs,e.v.origin,MOVE_NOMONSTERS,e);check(!fit.startsolid&&!fit.allsolid,'settled native drop remains outside BSP solids');}}
function recover(p,e){const was=e._respawnDrop;check(was,'live payload before recovery');const prior=totals(p).join();p.v.origin=[e.v.origin[0]+512,e.v.origin[1],e.v.origin[2]+20];SV_LinkEdict(p,false);SV_RunTriggerTouch(p,e);check(!e.free&&e._respawnDrop===was,'public touch rejects remote pickup without spatial overlap');same(totals(p).join(),prior,'rejected distant touch conserves all ammo');p.v.origin=[e.v.origin[0],e.v.origin[1],e.v.origin[2]+20];SV_LinkEdict(p,false);SV_RunTriggerTouch(p,e);check(e.free&&!e._respawnDrop,'actual public trigger atomically consumes contacted payload');return was;}
function recoverByMovement(p,e){
 let direction=null;for(const d of [[1,0],[-1,0],[0,1],[0,-1]]){const start=[e.v.origin[0]+d[0]*32,e.v.origin[1]+d[1]*32,e.v.origin[2]+20],end=[e.v.origin[0]+d[0]*16,e.v.origin[1]+d[1]*16,e.v.origin[2]+20];const a=SV_Move(start,p.v.mins,p.v.maxs,start,MOVE_NOMONSTERS,p),b=SV_Move(end,p.v.mins,p.v.maxs,end,MOVE_NOMONSTERS,p);if(!a.startsolid&&!b.startsolid){direction=d;p.v.origin=start;break;}}
 check(direction,'native pickup has a reachable player-hull approach');SV_LinkEdict(p,false);const tr=SV_PushEntity(p,[-direction[0]*16,-direction[1]*16,0]);check(!tr.startsolid&&e.free&&!e._respawnDrop,'real native movement and area-link touching recover the pickup');
}
function encoded(e){const lines=[];ED_Write(lines,e);return lines.join('\n');}
function restore(e,text){ED_ParseEdict(text.slice(text.indexOf('{')+1),e);SV_LinkEdict(e,false);}


function cross(p,c){const t=c.transform;p.v.origin=t.center.map((v,i)=>v-t.through[i]*32);p.v.velocity=t.through.map(v=>v*120);SV_LinkEdict(p,false);travel.SV_SeamlessFrame();for(let step=0;step<18&&!travel.SV_SeamlessPending();step++){const tr=SV_PushEntity(p,t.through.map(v=>v*4));check(!tr.startsolid,'native player approach stays outside solids');sv.time+=.1;travel.SV_SeamlessFrame();check(tr.fraction===1||travel.SV_SeamlessPending(),'native hull reaches actual passage threshold');}same(travel.SV_SeamlessPending()?.map,c.map,'native movement queues requested map');}

const remains=()=>sv.edicts.filter(e=>e&&!e.free&&e._respawnRemains);
const signature=e=>({record:JSON.stringify(e._respawnRemains),model:text(e.v.model),frame:e.v.frame,skin:e.v.skin,colormap:e.v.colormap,origin:Array.from(e.v.origin),angles:Array.from(e.v.angles)});
function assertSignature(e,old,label){same(JSON.stringify(e._respawnRemains),old.record,label+' metadata');same(text(e.v.model),old.model,label+' model');same(e.v.frame,old.frame,label+' native pose');same(e.v.skin,old.skin,label+' skin');same(e.v.colormap,old.colormap,label+' colormap');old.origin.forEach((v,i)=>near(e.v.origin[i],v,label+' location',.001));old.angles.forEach((v,i)=>near(e.v.angles[i],v,label+' angles',.001));same(sv.model_precache[e.v.modelindex],old.model,label+' valid native precache index');}
function animateRemains(seconds=4){SV_SetFrametime(.02);for(let i=0;i<Math.ceil(seconds/.02);i++){sv.time+=.02;progs.pr_global_struct.time=sv.time;for(const e of remains())SV_Physics_Toss(e);}}

Deno.test('native starting shotgun remains beside a persistent death body and is recoverable after the actual axe-only respawn',()=>{
 const p=spawn();same(p.v.items&(127|Q.IT_AXE),Q.IT_SHOTGUN|Q.IT_AXE,'native initial ownership includes starting shotgun and axe');same(p.v.ammo_shells,25,'native initial shell allotment');const originalModel=text(p.v.model),skin=p.v.skin,bodyQueue=new Set(sv.edicts.filter(e=>e&&!e.free&&text(e.v.classname)==='bodyque').map(e=>e.index));kill(p,true);const body=remains();same(body.length,1,'one body from one native kill command');same(body[0]._respawnRemains.kind,'body','native nongib death produces body');check(body[0].index>1&&!bodyQueue.has(body[0].index),'persistent body is independent of four reusable native body slots');same(text(body[0].v.model),originalModel,'native player model retained');same(body[0].v.skin,skin,'native player skin retained');check(!body[0]._respawn,'corpse does not inherit a live respawn coordinator');
 const weapons=drops();same(weapons.length,1,'initial shotgun produces exactly one drop');same(weapons[0]._respawnDrop.weapon,Q.IT_SHOTGUN,'starting shotgun ownership is recoverable');same(Respawn_DropAmmo(weapons[0]._respawnDrop).join(),'25,0,0,0','starting shells are neither erased nor replenished');same(text(weapons[0].v.model),'progs/g_shot.mdl','actual native pickup model');finish(p);same(p.v.items,Q.IT_AXE,'actual respawn owns only axe');same(pools.map(a=>p.v[a]).join(),'0,0,0,0','actual respawn has no hidden stock refill');check(!body[0].free,'original body remains after contact');settle(weapons);recoverByMovement(p,weapons[0]);same(p.v.items&(127|Q.IT_AXE),Q.IT_SHOTGUN|Q.IT_AXE,'native movement recovers original shotgun');same(p.v.ammo_shells,25,'native movement recovers exact original shells');same(remains().length,1,'pickup recovery does not consume the death body');same(p.v.weapon,Q.IT_SHOTGUN,'recovered starting shotgun is actually selected');same(text(p.v.weaponmodel),'progs/v_shot.mdl','native shotgun viewmodel is equipped');same(p.v.currentammo,25,'native selected-ammo display is exact');call(p,'W_FireShotgun');same(p.v.ammo_shells,24,'recovered shotgun fires through real QC without a hidden refill');
 const oldIds=new Set(remains().map(e=>e._respawnRemains.id));p.v.health=10;p.v.armorvalue=0;p.v.armortype=0;const world=sv.edicts[0];progs.pr_globals_int[OFS_PARM0]=progs.EDICT_TO_PROG(p);progs.pr_globals_int[OFS_PARM0+3]=progs.EDICT_TO_PROG(world);progs.pr_globals_int[OFS_PARM0+6]=progs.EDICT_TO_PROG(world);progs.pr_globals_float[OFS_PARM0+9]=25;call(p,'T_Damage');check(p._respawn.sequence,'real low-overkill lethal damage starts coordinator');const animated=remains().find(e=>!oldIds.has(e._respawnRemains.id));check(animated&&animated._respawnRemains.kind==='body','low overkill retains native nongib body');const initialFrame=animated.v.frame;same(animated.v.deadflag,1,'native nongib body begins in dying state');check(animated.v.think>0&&animated.v.nextthink>0,'native death animation thinker remains scheduled');finish(p);animateRemains(2);same(animated.v.deadflag,2,'native corpse thinker reaches real PlayerDead completion');check(animated.v.frame!==initialFrame,'native death animation advances to a later authored frame');check(!animated.free,'completed animated body remains in world');const oldBodies=new Set(remains().map(e=>e._respawnRemains.id));same(p.v.weapon,Q.IT_AXE,'post-contact control really holds native axe');p.v.health=10;progs.pr_globals_int[OFS_PARM0]=progs.EDICT_TO_PROG(p);progs.pr_globals_int[OFS_PARM0+3]=progs.EDICT_TO_PROG(world);progs.pr_globals_int[OFS_PARM0+6]=progs.EDICT_TO_PROG(world);progs.pr_globals_float[OFS_PARM0+9]=25;call(p,'T_Damage');const axeBody=remains().find(e=>!oldBodies.has(e._respawnRemains.id));check(axeBody&&axeBody._respawnRemains.kind==='body','native axe-only lethal hit retains body');finish(p);animateRemains(2);same(axeBody.v.deadflag,2,'axe body completes native death state');same(axeBody.v.frame,49,'held axe chooses native axe-death final frame49');
});

Deno.test('six native body deaths and a gib death remain independent beyond body-queue reuse and all original gib expiry deadlines',()=>{
 const p=spawn(),preserved=[];for(let cycle=0;cycle<6;cycle++){const before=remains().length;kill(p,true);same(remains().length,before+1,'one additional body per death '+cycle);finish(p);animateRemains(3);const body=remains().find(e=>!preserved.some(old=>JSON.parse(old.record).id===e._respawnRemains.id));check(body&&body._respawnRemains.kind==='body','new native body exists '+cycle);preserved.push(signature(body));for(const old of preserved){const found=remains().find(e=>JSON.stringify(e._respawnRemains)===old.record);check(found,'older body is not recycled');assertSignature(found,old,'body after later death '+cycle);}}
 const previous=new Set(remains().map(e=>e._respawnRemains.id));kill(p,false);const gibbed=remains().filter(e=>!previous.has(e._respawnRemains.id));same(gibbed.filter(e=>e._respawnRemains.kind==='head').length,1,'native lethal gib event retains one real player head');for(const model of['progs/gib1.mdl','progs/gib2.mdl','progs/gib3.mdl'])check(gibbed.some(e=>text(e.v.model)===model),'actual native gib retained '+model);check(gibbed.every(e=>e.index!==1&&e.v.think===0&&e.v.nextthink<=0),'owned gibs and detached head have no native removal timer');finish(p);animateRemains(8);const all=remains().map(signature),ids=new Set(all.map(e=>JSON.parse(e.record).id));same(ids.size,all.length,'every retained corpse or gib has unique identity');sv.time+=100000;SV_SetFrametime(.02);for(const e of remains())SV_Physics_Toss(e);same(remains().length,all.length,'nothing expires after arbitrarily later level time');for(const old of all){const e=remains().find(e=>JSON.stringify(e._respawnRemains)===old.record);check(e,'retained identity beyond native expiry');assertSignature(e,old,'long-lived remains');}console.log('RESPAWN_PERSISTENT_NATIVE_REMAINS '+JSON.stringify({bodyDeaths:6,gibModels:gibbed.map(e=>text(e.v.model)),retained:all.length,uniqueIds:ids.size}));
});

Deno.test('axe-only ammunition uses one native backpack carrying all four pools, atomically rejects overflow and recovers without weapon grants or refills',()=>{
 const p=spawn(),ammo=[301,407,211,509];inventory(p,ammo,Q.IT_AXE);kill(p,true);const list=drops();same(list.length,1,'all orphan ammunition is one world backpack');const backpack=list[0];same(backpack._respawnDrop.version,2,'multi-pool payload uses explicit version');same(backpack._respawnDrop.weapon,0,'backpack cannot grant an unowned ranged weapon');same(text(backpack.v.model),'progs/backpack.mdl','actual native backpack model');same(Respawn_DropAmmo(backpack._respawnDrop).join(),ammo.join(),'exact four-family payload');same(totals(p).join(),ammo.join(),'world plus player ammunition conserved');finish(p);same(p.v.items,Q.IT_AXE,'respawn remains axe-only');settle([backpack]);pools.forEach((name,i)=>p.v[name]=[7,16777216,11,13][i]);const before=pools.map(name=>p.v[name]),record=JSON.stringify(backpack._respawnDrop);p.v.origin=[backpack.v.origin[0],backpack.v.origin[1],backpack.v.origin[2]+20];SV_LinkEdict(p,false);SV_RunTriggerTouch(p,backpack);same(pools.map(name=>p.v[name]).join(),before.join(),'one overflowing family rejects the entire transfer');check(!backpack.free&&JSON.stringify(backpack._respawnDrop)===record,'rejected backpack remains intact');p.v.ammo_nails=0;recover(p,backpack);same(pools.map(name=>p.v[name]).join(),[308,407,222,522].join(),'all four pools recover exactly with existing inventory');same(p.v.items,Q.IT_AXE,'ammo-only recovery never grants shotgun or other weapons');const recovered=pools.map(name=>p.v[name]).join();SV_RunTriggerTouch(p,backpack);same(pools.map(name=>p.v[name]).join(),recovered,'consumed backpack cannot transfer twice');
 inventory(p,[0,0,0,0],Q.IT_AXE);kill(p,true);finish(p);same(drops().length,0,'empty axe-only death does not invent an empty pickup');
});

Deno.test('native entity save records preserve persistent remains and both legacy weapon and multi-pool backpack payloads',()=>{
 const p=spawn();kill(p,true);const liveRecord=JSON.parse(JSON.stringify(p._respawn)),probe=ED_Alloc();for(const value of[undefined,true,false,'true',1,null]){const record=JSON.parse(JSON.stringify(liveRecord));if(value===undefined)delete record.sequence.remainsRetained;else record.sequence.remainsRetained=value;restore(probe,'{\n"classname" "player_corpse"\n"_clockwise_player" "'+encodeURIComponent(JSON.stringify(record))+'"\n}');same(!!probe._respawn,value===undefined||typeof value==='boolean','optional remains transaction marker accepts only absent/boolean metadata');}for(const kind of['body','head','gib','weapon']){restore(probe,'{\n"classname" "player_corpse"\n"_clockwise_remains" "'+encodeURIComponent(JSON.stringify({version:1,id:'independent-kind',kind,born:sv.time}))+'"\n}');same(!!probe._respawnRemains,kind!=='weapon','only explicit body/head/gib metadata kinds accepted');}restore(probe,'{\n"classname" "dropped_weapon"\n"_clockwise_drop" "'+encodeURIComponent(JSON.stringify({version:2,id:'invalid-pool',weapon:0,pools:[1,2,-1,4],born:sv.time}))+'"\n}');same(probe._respawnDrop,null,'negative multi-pool metadata never becomes collectible');ED_Free(probe);finish(p);animateRemains(3);inventory(p,[11,22,33,44],Q.IT_AXE);kill(p,false);finish(p);animateRemains(8);settle(drops());const bodies=remains().map(e=>({e,old:signature(e),saved:encoded(e)})),payloads=drops().map(e=>({e,record:JSON.stringify(e._respawnDrop),saved:encoded(e)}));check(payloads.some(e=>e.e._respawnDrop.version===1)&&payloads.some(e=>e.e._respawnDrop.version===2),'fixture retains original shotgun plus later ammo backpack');
 for(const item of bodies){check(item.saved.includes('_clockwise_remains'),'native ED_Write includes remains ownership');restore(item.e,item.saved);assertSignature(item.e,item.old,'ED roundtrip remains');}
 for(const item of payloads){restore(item.e,item.saved);same(JSON.stringify(item.e._respawnDrop),item.record,'legacy and multi-pool records roundtrip exactly');}
 same(remains().length,bodies.length,'save restoration duplicates no body or gib');same(drops().length,payloads.length,'save restoration duplicates no payload');
});

Deno.test('native seamless departure preview and return retain every persistent corpse and gib without replaying a death',()=>{
 let p=spawn('e1m2');kill(p,true);finish(p);animateRemains(3);kill(p,false);finish(p);animateRemains(8);const records=remains().map(signature),deathCount=p._respawn.deaths;check(records.length>=5,'fixture includes actual body, head and three native gibs');cross(p,travel.SV_SeamlessCrossings().find(c=>c.map==='e1m3'));const snapshot=travel.SV_LevelSnapshotEntities('e1m2'),saved=snapshot.filter(e=>e._clockwise_remains);same(saved.length,records.length,'snapshot retains every persistent remains record');const visible=R_LevelEntities(sv.worldmodel.entities,snapshot,sv.worldmodel.submodels,1);for(const old of records)check(visible.some(e=>e.model===old.model&&e.frame===old.frame&&e.origin.every((v,i)=>Math.abs(v-old.origin[i])<.001)),'actual portal entity parser retains native posed remains '+old.model);
 SV_SaveSpawnparms();p=spawn('e1m3',false);travel.SV_SeamlessPlacePlayer(p);travel.SV_SeamlessHolding(1);sv.time+=5;const back=travel.SV_SeamlessCrossings().find(c=>c.back&&c.map==='e1m2');check(back,'native inverse passage exists');cross(p,back);SV_SaveSpawnparms();p=spawn('e1m2',false);travel.SV_SeamlessPlacePlayer(p);travel.SV_SeamlessHolding(1);same(remains().length,records.length,'return restores exactly the unexpired remains');for(const old of records){const e=remains().find(e=>JSON.stringify(e._respawnRemains)===old.record);check(e,'return preserves exact corpse/gib identity');assertSignature(e,old,'native seamless return');}same(p._respawn.deaths,deathCount,'travel does not replay death transaction');travel.SV_SeamlessReset();
});
Deno.test('actual Host save/load restores persistent death remains and native model resources in Newer and Classic',async()=>{
 const descriptor=Object.getOwnPropertyDescriptor(globalThis,'localStorage'),storage=new Map();Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{setItem:(k,v)=>storage.set(k,String(v)),getItem:k=>storage.get(k)??null,removeItem:k=>storage.delete(k)}});const oldSocket=cls.netcon,owned=[];
 try{Host_InitCommands();let p=spawn();kill(p,true);finish(p);animateRemains(3);inventory(p,[17,23,5,9],Q.IT_AXE);kill(p,false);finish(p);animateRemains(8);settle(drops());const expected=remains().map(signature),payloads=drops().map(e=>JSON.stringify(e._respawnDrop));cl.intermission=0;cl.levelname='independent persistent remains';Cmd_ExecuteString('save independent_persistent_remains',src_command);check([...storage.values()].some(text=>text.includes('_clockwise_remains')&&text.includes('_clockwise_drop')),'actual host save records remains and world inventory together');
 svs.maxclientslimit=1;NET_Init();SZ_Alloc(cls.message,8192);const client=Loop_Connect('local'),server=Loop_CheckNewConnections();owned.push(client,server);cls.netcon=client;cls.state=ca_connected;svs.clients[0].netconnection=server;
 for(const enhanced of[true,false]){vars.Cvar_SetValue('r_hdr',enhanced?1:0);Cmd_ExecuteString('load independent_persistent_remains',src_command);await Promise.resolve();check(sv.active&&sv.loadgame,'actual native host load completed');same(remains().length,expected.length,'host restores every corpse and gib exactly once');for(const old of expected){const e=remains().find(e=>JSON.stringify(e._respawnRemains)===old.record);check(e,'host retains exact remains identity');assertSignature(e,old,'host load '+(enhanced?'Newer':'Classic'));check(sv.models[e.v.modelindex]?.cache?.data,'real native model data available for restored remains');}same(drops().map(e=>JSON.stringify(e._respawnDrop)).sort().join(),payloads.slice().sort().join(),'host preserves scalar weapon and four-pool backpack metadata');SV_CheckForNewClients();const active=svs.clients[0];check(active.active&&active.netconnection,'actual paired client accepted after load');owned.push(cls.netcon,active.netconnection);const header=new TextDecoder('latin1').decode(active.message.data.subarray(0,active.message.cursize));for(const model of new Set(expected.map(e=>e.model)))check(header.includes(model),'connection header announces restored remains model '+model);}
 }finally{for(const socket of new Set(owned))if(socket&&!socket.disconnected)NET_Close(socket);cls.netcon=oldSocket;cls.state=ca_disconnected;sv.active=false;for(const c of svs.clients)c.active=false;vars.Cvar_SetValue('r_hdr',1);if(descriptor)Object.defineProperty(globalThis,'localStorage',descriptor);else delete globalThis.localStorage;Cbuf_Init();}
});

Deno.test('native death reserves corpse plus every weapon slot atomically before relinquishing any inventory',()=>{
 const capacity=()=>Q.MAX_EDICTS-sv.num_edicts+sv.edicts.slice(svs.maxclients+1,sv.num_edicts).filter(e=>e.free&&(e.freetime<2||sv.time-e.freetime>.5)).length;
 const occupy=remaining=>{const owned=[];while(capacity()>remaining){owned.push(ED_Alloc());check(owned.length<=Q.MAX_EDICTS,'bounded native capacity fixture');}same(capacity(),remaining,'exact available native entity capacity');return owned;};
 let p=spawn();inventory(p);p.v.items|=Q.IT_QUAD|Q.IT_KEY1;field(p,'super_damage_finished',sv.time+100);const dummies=occupy(7),before=new Uint8Array(p._fieldBuffer).slice(),record=JSON.stringify(p._respawn),live=sv.edicts.slice(0,sv.num_edicts).filter(e=>!e.free).map(e=>e.index).join();let failure=null;try{call(p,'ClientKill');}catch(error){failure=error;}
 check(failure&&String(failure).includes('no free edicts'),'one missing corpse-plus-weapons slot reaches actual native allocator failure');check(before.every((v,i)=>v===new Uint8Array(p._fieldBuffer)[i]),'failed death preserves every native player field including weapons ammo powers and health');same(JSON.stringify(p._respawn),record,'failed allocation does not commit death or custody metadata');same(drops().length,0,'failed allocation leaves no collectible partial drops');same(remains().length,0,'failed allocation leaves no persistent corpse');same(sv.edicts.slice(0,sv.num_edicts).filter(e=>!e.free).map(e=>e.index).join(),live,'all partial drops and reserved corpse slots are released');sv.time+=1;same(capacity(),7,'all seven available slots recover after native reuse quarantine');for(const e of dummies)ED_Free(e);
 p=spawn();inventory(p);occupy(8);kill(p,true);same(drops().length,7,'exact corpse-plus-seven-weapons capacity succeeds');same(remains().length,1,'successful death uses its already-reserved body');same(capacity(),0,'no hidden extra corpse allocation occurs after inventory commit');same(pools.map(a=>p.v[a]).join(),'0,0,0,0','successful transaction moves exact ammo into world');same(totals(p).join(),'19,61,7,13','exact-capacity success still conserves all shared ammo');
});
