import * as fs from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {spawn} from 'node:child_process';
import {createHash} from 'node:crypto';
import * as THREE from 'three';
import {RockPrepareTiles} from '../src/rockfield_prepare.js';
import {RockBakeSource,RockBakeCoverage,R_RockBakePrefetch} from '../src/newer/assets/r_rockbakes.js';
import {RockBakeConfig,RockBakeEncode,RockBakeDecode,RockBakeTileCoordinates,ROCK_BAKE_SIDE} from '../src/newer/assets/rockfield_bake_format.js';
import {createField,generateTile} from '../src/newer/assets/rockfield.js';
import {ROCK_BAKES} from '../src/newer/assets/rockfield_bakes.js';
import {PREPARED_CORPUS} from '../src/prepared_corpus.js';
import {DisplacementStore} from '../src/newer/assets/displacement_store.js';
import {nativeStorage,recordingLocks} from './helpers/opfs_native_fixture.mjs';
import {rockCharts,rockModel,nativeRockWorkers} from './helpers/rock_prepare_fixture.mjs';
const check=(v,m)=>{if(!v)throw Error(m);},same=(a,b,m)=>check(a===b,`${m}: ${a} != ${b}`),sha=a=>createHash('sha256').update(a).digest('hex'),ab=a=>a.buffer.slice(a.byteOffset,a.byteOffset+a.byteLength),hashData=s=>sha(new Uint8Array(s.entry.data.data.buffer));
async function fixture(fn){const root=await fs.mkdtemp(join(tmpdir(),'quaked-rock-prepare-')),storage=nativeStorage(root),disk=new DisplacementStore(storage,recordingLocks());try{return await fn({root,storage,disk,files:async()=>{try{return(await fs.readdir(join(root,'quaked-displacement-v1'))).filter(n=>n.endsWith('.json'));}catch(e){if(e.code==='ENOENT')return[];throw e;}}});}finally{await fs.rm(root,{recursive:true,force:true});}}
// These are readiness milestones, not a sub-second product benchmark. Real
// worker-thread startup varies with host load; retain an explicit finite bound.
async function until(fn,label,detail=()=>null){const deadline=performance.now()+10000;while(!fn()&&performance.now()<deadline)await new Promise(r=>setTimeout(r,5));check(fn(),label+' '+JSON.stringify(detail()));}
async function rejected(p,label){let error;try{await p;}catch(e){error=e;}check(error instanceof Error,label+' rejects');return error;}
function reject(fn,label){let error;try{fn();}catch(e){error=e;}check(error instanceof Error,label+' rejects');}

Deno.test('complete rock preparation uses at most two real workers and covers negative/offscreen brush coordinates with exact GPU half values',async()=>{
 const charts=rockCharts(),before=JSON.stringify(charts),workers=nativeRockWorkers(),tiles=await RockPrepareTiles(charts,{workerFactory:workers.factory}),coords=charts.flatMap(c=>RockBakeTileCoordinates(c).map(([x,y])=>({x,y,seed:c.seed})));same(tiles.length,18,'both nine-tile halos included');same(workers.stats.workers,2,'two actual workers');same(workers.stats.peak,2,'bounded concurrent generator jobs');same(workers.stats.completed,18,'every required coordinate completed');same(workers.stats.terminated,2,'both generator workers terminated');same(JSON.stringify(workers.stats.jobs.map(({x,y,seed})=>({x,y,seed}))),JSON.stringify(coords),'all original chart/coordinate jobs retained in deterministic order');
 for(const i of [0,9,17]){const c=charts[i<9?0:1],p=coords[i],expected=Uint16Array.from(generateTile(createField(RockBakeConfig(c)),p.x,p.y).data,THREE.DataUtils.toHalfFloat);same(Buffer.compare(Buffer.from(tiles[i].buffer),Buffer.from(expected.buffer)),0,'actual worker HALF bytes match independent same public generator '+i);}same(JSON.stringify(charts),before,'source charts unchanged');
});
Deno.test('named complete rock fields commit before ready and fresh module/process reuse disk with zero workers',()=>fixture(async f=>{
 const charts=rockCharts(),model=rockModel(),workers=nativeRockWorkers();let held=false,release;const pause=new Promise(r=>release=r);f.storage.hooks.beforeClose=async name=>{if(name.endsWith('.json')){held=true;await pause;}};const source=new RockBakeSource(model,charts,undefined,{store:f.disk,workerFactory:workers.factory});
 try{await until(()=>held,'manifest close reached',()=>({status:source.status,phase:source.entry?.phase,error:source.entry?.error,workers:workers.stats}));same(source.status,'loading','generation complete still not ready before durable manifest closes');same(source.tile(charts[1],-21,36),null,'offscreen field cannot publish ahead of commit');release();await source.entry.promise;same(source.status,'ready','closed files/readback completed');same(source.entry.source,'generated-and-stored','first visit generated and committed');same(source.entry.data.charts.size,2,'both charts persisted');check(source.tile(charts[1],-21,36),'offscreen brush center available');same(workers.stats.completed,18,'complete map generated once');const expected=hashData(source);delete f.storage.hooks.beforeClose;source.dispose();
  const fresh=await import('../src/newer/assets/r_rockbakes.js?rock-public-reopen='+Date.now()),again=new fresh.RockBakeSource(rockModel(),rockCharts(),undefined,{store:new DisplacementStore(nativeStorage(f.root),recordingLocks()),workerFactory:()=>{throw Error('Fresh module must not generate');}});try{await again.entry.promise;same(again.status,'ready','fresh module ready');same(again.entry.source,'disk','fresh module source is actual closed files');same(hashData(again),expected,'all persisted half values exact');}finally{again.dispose();}
  const child=spawn(process.execPath,[new URL('./helpers/rock_prepare_child.mjs',import.meta.url).pathname,f.root],{env:process.env,stdio:['ignore','pipe','pipe']});let out='',err='';child.stdout.on('data',b=>out+=b);child.stderr.on('data',b=>err+=b);const code=await new Promise((resolve,reject)=>{child.on('error',reject);child.on('exit',resolve);});same(code,0,'fresh-process reuse '+err);const proof=JSON.parse(out.split('\n').find(s=>s.startsWith('ROCK_DISK_CHILD ')).slice(16));same(proof.source,'disk','new process actual disk');same(proof.workers,0,'new process worker trap untouched');same(proof.sha256,expected,'new process exact complete half payload');check(proof.pid!==process.pid,'distinct lifetime');console.log('ROCK_PERSISTENCE_PROOF '+JSON.stringify({...proof,parentPID:process.pid,tiles:18}));
 }finally{release();source.dispose();}
}));
Deno.test('rock source, model name, full coordinate membership, seed, axes and settings each rekey durable identity',()=>fixture(async f=>{
 const base=rockCharts();base.splice(1);const variants=[['base',()=>{}],['copy',()=>{}],['source',(m)=>m.bspSourceBytes[0]++],['name',m=>m.name+='-renamed'],['coordinate',(_m,c)=>c[0].surfaces[0].bounds=[6,-8,6,-8]],['seed',(_m,c)=>c[0].seed++],['axis',(_m,c)=>c[0].tangent=[0,1,0]],['settings',(_m,c)=>c[0].config.featureSize+=1],['membership',(_m,c)=>c.push(rockCharts()[1])]];let expected=0;
 for(const [label,change]of variants){const m=rockModel(),c=structuredClone(base);change(m,c);const workers=nativeRockWorkers(),source=new RockBakeSource(m,c,undefined,{store:f.disk,workerFactory:workers.factory});try{await source.entry.promise;same(source.status,'ready',label+' complete');same(source.entry.source,label==='copy'?'disk':'generated-and-stored',label+' selects intended authority');if(label!=='copy')expected++;same((await f.files()).length,expected,label+' distinct persisted identity');}finally{source.dispose();}}
}));
Deno.test('rock cancellation and malformed worker data never publish partial coverage, and disposal prevents late committed publication',async()=>{
 const charts=rockCharts().slice(0,1);for(const kind of ['identity','width','coordinate','sample','worker-error']){let terminated=0;const promise=RockPrepareTiles(charts,{workerFactory:()=>({terminate(){terminated++;},postMessage(job){queueMicrotask(()=>{if(kind==='worker-error'){this.onerror(Error('controlled generator failure'));return;}const result={width:ROCK_BAKE_SIDE,tileX:job.x,tileY:job.y,data:new Float32Array(ROCK_BAKE_SIDE**2).fill(.5)};if(kind==='width')result.width--;if(kind==='coordinate')result.tileX++;if(kind==='sample')result.data[12]=NaN;this.onmessage({data:{id:job.id+(kind==='identity'?1:0),result}});});}})});await rejected(promise,kind);same(terminated,2,kind+' terminates both owned workers');}
 const controller=new AbortController();let count=0;const pending=RockPrepareTiles(charts,{signal:controller.signal,workerFactory:()=>({postMessage(){},terminate(){count++;}})});controller.abort();await rejected(pending,'cancelled workers');same(count,2,'cancel terminates both outstanding jobs');
 await fixture(async f=>{let held=false,release;const pause=new Promise(r=>release=r);f.storage.hooks.beforeClose=async name=>{if(name.endsWith('.gz')){held=true;await pause;}};const source=new RockBakeSource(rockModel(),charts,undefined,{store:f.disk,workerFactory:nativeRockWorkers().factory}),work=source.entry;await until(()=>held,'actual payload close held');source.dispose();release();await work.promise;same(source.entry,null,'disposed source never restored');same(source.tile(charts[0],0,0),null,'late persistence cannot publish stale tile');same((await f.files()).length,0,'cancelled pre-manifest work is not completed cache');});
});
Deno.test('exact bundled rock coverage failures are errors without filesystem or worker fallback while anonymous controls remain supported',async()=>{
 const charts=rockCharts().slice(0,1),tiles=RockBakeTileCoordinates(charts[0]).map(()=>new Uint16Array(ROCK_BAKE_SIDE**2).fill(0x3800));
 for(const variant of ['valid','missing','corrupt','coverage']){const model=rockModel();model.name+='-'+variant;const hash=sha(model.bspSourceBytes),raw=RockBakeEncode(model.name,charts,tiles,{bspSha256:hash});PREPARED_CORPUS[model.name]=[hash];if(variant!=='missing')ROCK_BAKES[model.name]=[{bspSha256:hash,file:'public-rock.gz',sha256:'test',rawSha256:sha(raw)}];let fallback=0;const ask=variant==='coverage'?[{...charts[0],surfaces:[{bounds:[9,9,9,9]}]}]:charts,source=new RockBakeSource(model,ask,async()=>variant==='corrupt'?ab(raw.slice(0,-2)):ab(raw),{store:{ensure(){fallback++;throw Error('Bundled must not fall through to filesystem');}},workerFactory:()=>{fallback++;throw Error('Bundled must not generate');}});
  try{await source.entry.promise;same(source.status,variant==='valid'?'ready':'error',variant+' exact bundled decision');same(fallback,0,variant+' never generates/relabels corrupted authority');if(variant==='valid'){same(source.entry.source,'shipped','validated bundled source');const entry=source.transport;same(entry.pins,1,'source owns one transport pin');source.dispose();same(entry.pins,0,'first disposal releases pin');source.dispose();same(entry.pins,0,'second disposal cannot create permanently pinned negative count');}else check(source.entry.error,'failure diagnostic retained');}finally{source.dispose();delete ROCK_BAKES[model.name];delete PREPARED_CORPUS[model.name];}}
 const decoded=RockBakeDecode(ab(RockBakeEncode('anonymous-fixture',charts,tiles)),'anonymous-fixture');same(RockBakeCoverage(decoded,charts),decoded,'complete exact coverage positive');reject(()=>RockBakeCoverage(decoded,[...charts,...charts]),'extra chart');decoded.charts.values().next().value.delete('0,0');reject(()=>RockBakeCoverage(decoded,charts),'missing coordinate');const anonymous=new RockBakeSource('anonymous-unregistered',charts);same(anonymous.status,'fallback','legacy unnamed fixture still falls back');anonymous.dispose();same(R_RockBakePrefetch('anonymous-unregistered'),null,'no invented bundled work');
});
