import {createHash} from 'node:crypto';
import {RockBakeSource,R_RockBakePrefetch} from '../src/newer/assets/r_rockbakes.js';
import {RockBakeEncode,RockBakeTileCoordinates,ROCK_BAKE_SIDE} from '../src/newer/assets/rockfield_bake_format.js';
import {ROCK_BAKES} from '../src/newer/assets/rockfield_bakes.js';
import {rockCharts} from './helpers/rock_prepare_fixture.mjs';
const check=(v,m)=>{if(!v)throw Error(m);},same=(a,b,m)=>check(a===b,`${m}: ${a} != ${b}`),sha=b=>createHash('sha256').update(b).digest('hex'),ab=b=>b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength);let serial=0;
async function until(fn,label){const end=performance.now()+2000;while(!fn()&&performance.now()<end)await new Promise(r=>setTimeout(r,0));check(fn(),label);}
async function fixture(fn){const name='maps/public-rock-retry-'+ ++serial+'.bsp',bytes=new Uint8Array([19,31,53,serial]),charts=rockCharts().slice(0,1),raw=RockBakeEncode(name,charts,RockBakeTileCoordinates(charts[0]).map(()=>new Uint16Array(ROCK_BAKE_SIDE**2).fill(0x3800)),{bspSha256:sha(bytes)}),spec={bspSha256:sha(bytes),file:'public-rock-retry-'+serial+'.gz',sha256:'fixture',rawSha256:sha(raw)},timers=[],oldSet=globalThis.setTimeout,oldClear=globalThis.clearTimeout;ROCK_BAKES[name]=[spec];
 globalThis.setTimeout=(fn,ms,...args)=>{if(ms!==5000&&ms!==10000)return oldSet(fn,ms,...args);const timer={fn,ms,cleared:false,handle:oldSet(()=>{},60000)};timers.push(timer);return timer.handle;};globalThis.clearTimeout=h=>{const timer=timers.find(t=>t.handle===h);if(timer)timer.cleared=true;return oldClear(h);};
 try{return await fn({name,bytes,model:{name,bspSourceBytes:bytes},charts,raw,spec,timers});}finally{globalThis.setTimeout=oldSet;globalThis.clearTimeout=oldClear;for(const t of timers)oldClear(t.handle);delete ROCK_BAKES[name];}
}
Deno.test('named rock timeout retries once with a bounded longer deadline and late first completion cannot replace verified retry data',()=>fixture(async f=>{
 let calls=0,late,firstSignal;const source=new RockBakeSource(f.model,f.charts,async(_url,{signal})=>{calls++;if(calls===1){firstSignal=signal;return new Promise(r=>late=()=>r(ab(f.raw)));}return ab(f.raw);}),work=source.entry,first=source.transport;
 try{await until(()=>calls===1,'initial actual request');same(first.pins,1,'initial source pin');f.timers[0].fn();await work.promise;same(calls,2,'exactly one retry');same(source.status,'ready','retry validates source and complete coverage');same(firstSignal.aborted,true,'initial timed-out request aborted');same(first.pins,0,'old failed pin relinquished');same(source.transport.pins,1,'replacement pin owned exactly once');same(f.timers.map(t=>t.ms).join(),'5000,10000','both attempts bounded');late();await new Promise(r=>setTimeout(r,0));same(first.status,'error','late first success cannot publish');same(source.status,'ready','validated retry remains authority');check(source.tile(f.charts[0],0,0),'real prepared tile available');}
 finally{late?.();const current=source.transport;source.dispose();source.dispose();same(current?.pins,0,'idempotent release owns no residual retry pin');}
}));
Deno.test('second rock timeout is terminal for the current owner, while checksum and malformed-codec corruption are never retried',async()=>{
 await fixture(async f=>{let calls=0;const source=new RockBakeSource(f.model,f.charts,(_url,{signal})=>{calls++;return calls===1?new Promise((_resolve,reject)=>signal.addEventListener('abort',()=>reject(Error('Request cancelled by signal')),{once:true})):Promise.resolve(ab(f.raw));});try{await until(()=>calls===1,'generic-abort request');f.timers[0].fn();await source.entry.promise;same(source.status,'ready','explicit timer expiry remains retryable despite generic abort message');same(calls,2,'generic loader abort does not suppress one bounded timeout retry');}finally{source.dispose();}});
 await fixture(async f=>{let calls=0;const releases=[],source=new RockBakeSource(f.model,f.charts,()=>{calls++;return new Promise(r=>releases.push(()=>r(ab(f.raw))));});try{await until(()=>calls===1,'first request');f.timers[0].fn();await until(()=>calls===2,'bounded retry starts');f.timers[1].fn();await source.entry.promise;same(source.status,'error','second timeout stays explicit blocker');await new Promise(r=>setTimeout(r,0));same(calls,2,'no unbounded automatic retry loop');same(source.tile(f.charts[0],0,0),null,'no false prepared data');}finally{source.dispose();releases.forEach(r=>r());}});
 for(const kind of ['checksum','malformed-json'])await fixture(async f=>{let raw=f.raw;if(kind==='checksum'){raw=raw.slice();raw[raw.length-1]^=1;}else{const text=new TextEncoder().encode('network'),start=4+text.length+(text.length&1);raw=new Uint8Array(start);new DataView(raw.buffer).setUint32(0,text.length,true);raw.set(text,4);f.spec.rawSha256=sha(raw);}let calls=0;const source=new RockBakeSource(f.model,f.charts,async()=>{calls++;return ab(raw);});try{await source.entry.promise;same(source.status,'error',kind+' rejected');same(calls,1,kind+' is data corruption, not transient network failure');check(source.entry.error,'original diagnostic retained');}finally{source.dispose();}});
});
Deno.test('two current rock sources share one retry and transfer both pins without retaining the failed pinned request',()=>fixture(async f=>{
 let calls=0,late;const loader=()=>{calls++;return calls===1?new Promise(r=>late=()=>r(ab(f.raw))):Promise.resolve(ab(f.raw));},a=new RockBakeSource(f.model,f.charts,loader),b=new RockBakeSource(f.model,f.charts,loader),first=a.transport;
 try{same(b.transport,first,'both sources share initial transport');same(first.pins,2,'two actual owners');await until(()=>calls===1,'shared request started');f.timers[0].fn();await Promise.all([a.entry.promise,b.entry.promise]);same(calls,2,'exactly one shared replacement request');same(a.status,'ready','first source retries successfully');same(b.status,'ready','second source retries successfully');same(a.transport,b.transport,'both retain same verified replacement');same(first.pins,0,'both failed pins released');same(a.transport.pins,2,'replacement has exactly two owners');same(a.tile(f.charts[0],0,0),b.tile(f.charts[0],0,0),'both share exact immutable decoded tile');const replacement=a.transport;a.dispose();same(replacement.pins,1,'other source remains pinned');b.dispose();same(replacement.pins,0,'last owner releases replacement');}
 finally{late?.();a.dispose();b.dispose();}
}));
Deno.test('disposing a rock source while either attempt waits cannot launch another retry, repin a transport, or publish late data',async()=>{
 for(const stage of ['initial','retry'])await fixture(async f=>{let calls=0;const finish=[],source=new RockBakeSource(f.model,f.charts,()=>{calls++;return new Promise(r=>finish.push(()=>r(ab(f.raw))));}),work=source.entry;await until(()=>calls===1,'initial request entered');if(stage==='retry'){f.timers[0].fn();await until(()=>calls===2,'retry request entered');}const pending=source.transport;source.dispose();same(pending.pins,0,stage+' release immediately unpins');for(const timer of f.timers)if(!timer.cleared)timer.fn();finish.forEach(r=>r());await work.promise;same(source.entry,null,stage+' late continuation cannot restore owner');same(source.transport,null,stage+' late continuation cannot retain transport');same(pending.pins,0,stage+' no async repin');same(calls,stage==='initial'?1:2,stage+' no additional request');same(source.tile(f.charts[0],0,0),null,stage+' no stale tile publication');});
});

Deno.test('public null teardown and anonymous renderer worlds never enter named-source transport or durable preparation',()=>{
 for(const model of [null,undefined,{}, {bspSourceBytes:new Uint8Array([1,2,3])}]){same(R_RockBakePrefetch(model),null,'unnamed prefetch has no native filename lookup');const source=new RockBakeSource(model,[],()=>{throw Error('Anonymous helper cannot fetch');},{store:{ensure(){throw Error('Anonymous helper cannot own durable identity');}}});same(source.status,'fallback','anonymous helper retains normal fallback');same(source.entry,null,'no fabricated source work');source.dispose();source.dispose();same(source.transport,null,'idempotent teardown keeps no pin');}
});
