import '../src/engine/render/gl_rsurf.js';
import * as THREE from 'three';
import * as rock from '../src/newer/render/r_rockfield.js';
import * as band from '../src/newer/render/r_rockshader.js';
import { R_RockCoordinates } from '../src/newer/render/r_rocksurfaces.js';
import * as post from '../src/newer/render/gl_post.js';
import * as height from '../src/newer/render/r_heightshadows.js';
import * as mode from '../src/newer/mode.js';
import * as vars from '../src/engine/common/cvar.js';
import { DrawGLPoly, createQuakeLightmapMaterial } from '../src/engine/render/gl_rsurf.js';
import '../src/newer/install.js'; // Newer Game plugs into the engine's hooks (src/engine/common/hooks.js)
const W=384,H=384,report=document.querySelector('#report'),owned=[],checks=[],errors=[];let draws=0;
const check=(passed,name,data={})=>checks.push({passed,name,...data});
const face=(name,rect,phase=0)=>{const[x0,x1,z0,z1]=rect;return{flags:0,plane:{normal:[0,-1,0],dist:0},texinfo:{texture:{name,width:64,height:64}},polys:{numverts:4,verts:new Float32Array([[x0,z0],[x0,z1],[x1,z1],[x1,z0]].flatMap(([x,z])=>[x,0,z,x/64+phase,z/64-phase,.5,.5]))}};};
async function decoded(path){const response=await fetch(new URL('../newer/textures/'+path,import.meta.url));if(!response.ok)throw Error('Installed asset unavailable '+path);const bitmap=await createImageBitmap(await response.blob()),canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;const context=canvas.getContext('2d',{willReadFrequently:true});context.drawImage(bitmap,0,0);const data=context.getImageData(0,0,canvas.width,canvas.height).data;bitmap.close();return{data:new Uint8Array(data),width:canvas.width,height:canvas.height};}
const stats=(a,b,channels=3,tolerance=1)=>{let sum=0,maximum=0,changed=0,n=0;for(let i=0;i<a.length;i+=4)for(let c=0;c<channels;c++){const d=Math.abs(a[i+c]-b[i+c]);sum+=d;maximum=Math.max(maximum,d);if(d>tolerance)changed++;n++;}return{mean:sum/n,maximum,changedFraction:changed/n};};
const decodeShadow=(bytes,i)=>{const word=bytes[i]+bytes[i+1]*256+bytes[i+2]*65536+bytes[i+3]*16777216,kind=Math.floor(word/1073741824);return kind===1||kind===2?(word%8)/7:1;};
try{
 for(const c of [post.r_hdr,post.r_dynres,post.r_bloom,post.r_volumetric,post.r_bounce,mode.r_newer_lighting,mode.r_newer_normals,mode.r_newer_water,height.r_heightshadows])if(!vars.Cvar_FindVar(c.name))vars.Cvar_RegisterVariable(c);
 for(const[k,v]of Object.entries({r_hdr:1,r_dynres:0,r_bloom:0,r_volumetric:0,r_bounce:0,r_newer_lighting:1,r_newer_normals:1,r_newer_water:0,r_heightshadows:1}))vars.Cvar_SetValue(k,v);
 const [pigment,scalar,index]=await Promise.all([decoded('bricka2_2.webp'),decoded('normals/bricka2_2.webp'),fetch(new URL('../newer/textures/index.json',import.meta.url)).then(r=>r.json())]);
 const originalPigment=pigment.data.slice(),originalScalar=scalar.data.slice(),texture=new THREE.DataTexture(pigment.data,pigment.width,pigment.height);owned.push(texture);texture.colorSpace=THREE.SRGBColorSpace;texture.wrapS=texture.wrapT=THREE.RepeatWrapping;texture.minFilter=THREE.LinearMipmapLinearFilter;texture.magFilter=THREE.LinearFilter;texture.generateMipmaps=true;texture.anisotropy=16;texture.userData.newerPicture=true;
 const descriptor=index.normals.bricka2_2;texture.userData.newerHeight={...descriptor,data:Float32Array.from({length:scalar.width*scalar.height},(_,i)=>scalar.data[i*4]/255),width:scalar.width,height:scalar.height};texture.needsUpdate=true;
 const lm=new THREE.DataTexture(new Uint8Array([128,128,128,255]),1,1);owned.push(lm);lm.channel=1;lm.needsUpdate=true;
 const renderer=new THREE.WebGLRenderer({antialias:false,preserveDrawingBuffer:true});owned.push(renderer);renderer.setPixelRatio(1);renderer.setSize(W,H);renderer.setClearColor(0,0);renderer.debug.onShaderError=(gl,program,vertex,fragment)=>errors.push({program:gl.getProgramInfoLog(program),vertex:gl.getShaderInfoLog(vertex),fragment:gl.getShaderInfoLog(fragment)});
 const camera=new THREE.PerspectiveCamera(55,1,1,2000);camera.position.set(180,-560,110);camera.up.set(0,0,1);camera.lookAt(-16,0,-8);camera.updateMatrixWorld();let chartSeed,chartReference,attributesIntact=true;
 function draw(label,{arrangement='whole',enabled=true,classic=false,fieldOn=true,target=true}={}){
  const rectangles=arrangement==='split'?[[-256,0,-256,256],[0,256,-256,256]]:arrangement==='t-junction'?[[-256,0,-256,256],[0,256,-256,0],[0,256,0,256]]:[[-256,256,-256,256]];
  const faces=rectangles.map((r,i)=>face(target?'bricka2_2':'uwall1_2',r,i?i*3:0)),fields=rock.R_RockfieldBuild({name:'maps/start.bsp',surfaces:faces}),chart=fields.charts[0],scene=new THREE.Scene(),snapshots=[];
  if(target){if(chartSeed===undefined){chartSeed=chart.seed;chartReference=chart;}check(chart.seed===chartSeed,label+' stable map/material seed');}
  for(const f of faces){const g=DrawGLPoly(f.polys,f.plane.normal);owned.push(g);const before=Object.entries(g.attributes).map(([name,a])=>({name,attribute:a,values:a.array.slice()})),indices=g.index?.array.slice();rock.R_RockfieldGeometry(g,f);const m=createQuakeLightmapMaterial(texture,lm);owned.push(m);m.userData.rockField=true;scene.add(new THREE.Mesh(g,m));snapshots.push({g,before,indices});}
  post.R_PostBegin(renderer,true,W,H);post.classicLook.value=classic?1:0;band.rockBandWarpOn.value=enabled?1:0;rock.rockUniforms.qrRockOn.value=fieldOn?1:0;height.R_HeightShadowFrame({points:[{position:[90,-240,120],range:1024,color:[1,1,1]}],sun:{on:false},spot:{on:false}});height.R_HeightShadowScope(!classic);post.R_PostBind(renderer);renderer.render(scene,camera);draws++;
  const rt=renderer.getRenderTarget(),albedo=new Uint8Array(W*H*4),half=new Uint16Array(W*H*4),mask=new Uint8Array(W*H*4);renderer.readRenderTargetPixels(rt,0,0,W,H,albedo,undefined,2);renderer.readRenderTargetPixels(rt,0,0,W,H,half,undefined,1);renderer.readRenderTargetPixels(rt,0,0,W,H,mask,undefined,3);const normals=Float32Array.from(half,THREE.DataUtils.fromHalfFloat);let covered=0;for(let i=3;i<normals.length;i+=4)if(normals[i]>1)covered++;check(covered>20000,label+' real visible surface coverage',{covered});
  post.R_PostFinish(renderer,scene,camera,{lx:0,ly:0,lw:W,lh:H},0,[],[],0,1,false);draws++;const screen=new Uint8Array(W*H*4),gl=renderer.getContext();gl.readPixels(0,0,W,H,gl.RGBA,gl.UNSIGNED_BYTE,screen);check(gl.getError()===gl.NO_ERROR,label+' GL0');
  for(const{g,before,indices}of snapshots){for(const{name,attribute,values}of before)attributesIntact&&=g.getAttribute(name)===attribute&&values.every((v,i)=>v===attribute.array[i]);attributesIntact&&=!indices||indices.every((v,i)=>v===g.index.array[i]);}
  const figure=document.createElement('figure'),img=document.createElement('img'),caption=document.createElement('figcaption');img.src=renderer.domElement.toDataURL();caption.textContent=label;figure.append(img,caption);document.querySelector('#views').append(figure);return{albedo,normals,mask,screen};
 }
 const off=draw('Unwarped installed pigment',{enabled:false}),on=draw('Continuous warp, same installed pixels'),again=draw('Identical repeat draw'),split=draw('Split faces + integer UV phase',{arrangement:'split'}),junction=draw('T junction + integer UV phase',{arrangement:'t-junction'});
 const effect=stats(off.albedo,on.albedo);check(effect.changedFraction>.05,'actual pigment sampling changes with warp enabled',effect);check(stats(on.albedo,again.albedo,4,0).changedFraction===0,'repeat draw deterministic');
 for(const[label,other]of[['split',split],['T junction',junction]]){const a=stats(on.albedo,other.albedo),n=stats(on.normals,other.normals,3,.01),s=stats(on.screen,other.screen,3,3);let shadowError=0;for(let i=0;i<on.mask.length;i+=4)shadowError+=Math.abs(decodeShadow(on.mask,i)-decodeShadow(other.mask,i));shadowError/=W*H;check(a.mean<.35&&a.changedFraction<.02&&n.mean<.002&&s.mean<.5&&shadowError<.003,label+' perspective shader continuity across native subdivisions',{albedo:a,normals:n,screen:s,shadowMeanError:shadowError});}
 const classicOff=draw('Classic switch, warp off',{classic:true,enabled:false}),classicOn=draw('Classic switch, warp on',{classic:true});check(stats(classicOff.albedo,classicOn.albedo,4,0).changedFraction===0&&stats(classicOff.screen,classicOn.screen,4,0).changedFraction===0,'Classic retains exact original sampling');
 const fieldOff=draw('Field disabled identity',{fieldOn:false});check(stats(off.albedo,fieldOff.albedo,4,0).changedFraction===0,'field-off retains exact unwarped pigment');
 const unrelatedOff=draw('Other material control off',{target:false,enabled:false}),unrelatedOn=draw('Other material control on',{target:false});check(stats(unrelatedOff.albedo,unrelatedOn.albedo,4,0).changedFraction===0,'non-target material sampling remains exact');
 // Float readback uses the exact exported production helper. It does not
 // synthesize a picture or replace the material shader used above.
 const points=[],noiseTriples=[],continuityPairs=[],line=[];const add=p=>{points.push(p);return points.length-1;};
 for(const axis of [0,1])for(const edge of [-2,-1,0,1]){const p=axis?[.37,edge]:[edge,.37],a=p.slice(),b=p.slice();a[axis]-=.01;b[axis]+=.01;noiseTriples.push([add(a),add(p),add(b)]);}
 for(const z of [-64,-32,0,32,64])for(const x of [-64,17,64])continuityPairs.push([add(R_RockCoordinates(chartReference,[x,0,z-.001])),add(R_RockCoordinates(chartReference,[x,0,z+.001]))]);
 for(let x=-256;x<=256;x+=32)line.push(add(R_RockCoordinates(chartReference,[x,0,32])));
 const count=points.length,data=new Float32Array(count*4);points.forEach((p,i)=>data.set([...p,0,1],i*4));const pointMap=new THREE.DataTexture(data,count,1,THREE.RGBAFormat,THREE.FloatType);pointMap.needsUpdate=true;owned.push(pointMap);
 const target=new THREE.WebGLRenderTarget(count,1,{type:THREE.FloatType,minFilter:THREE.NearestFilter,magFilter:THREE.NearestFilter,depthBuffer:false});owned.push(target);const probeMaterial=new THREE.ShaderMaterial({uniforms:{uPoints:{value:pointMap},uPair:{value:new THREE.Vector2(chartSeed&65535,.2)},qrRockBandWarpOn:{value:1},qrRockOn:{value:1},uClassic:{value:0}},vertexShader:'varying vec2 vUv;varying vec2 vRockWarp;uniform vec2 uPair;void main(){vUv=uv;vRockWarp=uPair;gl_Position=vec4(position.xy,0.,1.);}',fragmentShader:'varying vec2 vUv;uniform sampler2D uPoints;uniform float qrRockOn;\n'+band.ROCK_BAND_WARP_GLSL+'\nvoid main(){vec2 p=texture2D(uPoints,vUv).xy;gl_FragColor=vec4(qrRockBandOffset(p),qrRockBandNoise(p,uint(floor(vRockWarp.x+.5))),1.);}',depthTest:false,depthWrite:false});probeMaterial.onBeforeCompile=()=>{};owned.push(probeMaterial);const probeScene=new THREE.Scene(),probeGeometry=new THREE.PlaneGeometry(2,2);owned.push(probeGeometry);probeScene.add(new THREE.Mesh(probeGeometry,probeMaterial));const probeCamera=new THREE.OrthographicCamera(-1,1,1,-1,0,2);
 const sample=()=>{renderer.setRenderTarget(target);renderer.render(probeScene,probeCamera);draws++;const a=new Float32Array(count*4);renderer.readRenderTargetPixels(target,0,0,count,1,a);return a;};const samples=sample(),repeated=sample();check(samples.every((v,i)=>v===repeated[i]),'GPU helper deterministic at negative coordinates and midlines');check(points.every((_,i)=>Math.abs(samples[i*4])<=.200001&&Math.abs(samples[i*4+1])<=.200001),'warp stays within declared native-tile amplitude');
 let maxSeam=0,maxSlope=0;for(const[a,b]of continuityPairs)maxSeam=Math.max(maxSeam,Math.abs(samples[a*4]-samples[b*4]),Math.abs(samples[a*4+1]-samples[b*4+1]));for(const[a,b,c]of noiseTriples)maxSlope=Math.max(maxSlope,Math.abs(samples[a*4+2]-samples[b*4+2])/.01,Math.abs(samples[c*4+2]-samples[b*4+2])/.01);check(maxSeam<.0001,'no warp jump at negative tile boundaries or painted midtile lines',{maxSeam});check(maxSlope<.002,'quintic noise retains smooth lattice-boundary slopes',{maxSlope});
 const vertical=line.map(i=>samples[i*4+1]),bend=Math.max(...vertical)-Math.min(...vertical);check(bend>.02,'same painted midtile fissure receives different continuous vertical offsets along the wall',{nativeTileOffsetRange:bend});
 probeMaterial.uniforms.uPair.value.x=(chartSeed+1)&65535;const otherSeed=sample();check(otherSeed.some((v,i)=>i%4<2&&Math.abs(v-samples[i])>.01),'different seed changes deterministic warp');probeMaterial.uniforms.uPair.value.x=chartSeed&65535;
 for(const gate of ['qrRockBandWarpOn','qrRockOn','uClassic']){probeMaterial.uniforms[gate].value=gate==='uClassic'?1:0;const zero=sample();check(points.every((_,i)=>zero[i*4]===0&&zero[i*4+1]===0),'production GPU helper exact off identity '+gate);probeMaterial.uniforms[gate].value=gate==='uClassic'?0:1;}
 check(attributesIntact&&originalPigment.every((v,i)=>v===pigment.data[i])&&originalScalar.every((v,i)=>v===scalar.data[i]),'original pigment height pixels and native geometry/UV attributes unchanged');check(errors.length===0&&renderer.getContext().getError()===0,'all production material and helper shaders compile cleanly',{errors});
}catch(error){checks.push({passed:false,name:String(error),stack:error.stack});}
finally{height.R_HeightShadowScope(false);post.classicLook.value=0;band.rockBandWarpOn.value=1;rock.R_RockfieldBuild(null);for(const object of owned.reverse())object.dispose?.();}
const result={status:checks.every(c=>c.passed)?'PASS':'FAIL',draws,scope:'Installed pigment/height, perspective subdivision and integer UV-phase identity; isolated warp has no resident macro pages. Does not claim fractional authored UV-phase jumps are identical.',checks};window.rockBandsResult=result;report.textContent=JSON.stringify(result,null,2);
