// Independent public chart/geometry/material checks for the START painted
// fissure correction. The GPU trial tests numeric continuity and real assets.
import * as THREE from 'three';
import * as field from '../src/r_rockfield.js';
import * as shader from '../src/r_rockshader.js';
import * as post from '../src/gl_post.js';
import * as anim from '../src/r_anim.js';
import * as vars from '../src/engine/common/cvar.js';
import { DrawGLPoly, createQuakeLightmapMaterial } from '../src/gl_rsurf.js';
const check=(x,m)=>{if(!x)throw Error(m);},same=(a,b,m)=>check(a===b,`${m}: ${a} != ${b}`);
const face=(name,x0,x1,z0,z1,phase=0)=>({flags:0,plane:{normal:[0,-1,0],dist:0},texinfo:{texture:{name,width:64,height:64}},polys:{numverts:4,verts:new Float32Array([[x0,z0],[x0,z1],[x1,z1],[x1,z0]].flatMap(([x,z])=>[x,0,z,x/64+phase,z/64-phase,.2,.3]))}});
function metadata(faces){const result=field.R_RockfieldBuild({name:'maps/start.bsp',surfaces:faces});return faces.map(f=>{const geometry=DrawGLPoly(f.polys,f.plane.normal),before=Object.fromEntries(Object.entries(geometry.attributes).map(([n,a])=>[n,{attribute:a,values:a.array.slice()}]));check(field.R_RockfieldGeometry(geometry,f),'public annotation accepts natural wall');const warp=geometry.getAttribute('rockWarp'),chart=result.bySurface.get(f);check(warp?.itemSize===2&&warp.count===geometry.attributes.position.count,'one warp metadata pair per native vertex');for(let i=0;i<warp.count;i++){same(warp.getX(i),chart.seed&65535,'exact16-bit map/material seed');check(Math.abs(warp.getY(i)-(chart.name==='bricka2_2'?.2:0))<1e-7,'only target material receives small warp amplitude');}for(const[n,a]of Object.entries(before)){same(geometry.getAttribute(n),a.attribute,'native attribute identity '+n);check(a.values.every((v,i)=>v===a.attribute.array[i]),'native attribute values '+n);}const out={seed:warp.getX(0),amplitude:warp.getY(0)};geometry.dispose();return out;});}
Deno.test('painted-band metadata stays deterministic across negative growth, disconnected bridging, BSP subdivision and native UV phase changes',()=>{
 try{const a=face('bricka2_2',-256,0,-256,256),b=face('bricka2_2',256,512,-256,256),bridge=face('bricka2_2',0,256,-256,256,11),before=metadata([a,b]),after=metadata([b,bridge,a]);check(before.every(x=>x.seed===after[0].seed),'component discovery and changed order never reseed existing pigment warp');const whole=metadata([face('bricka2_2',-256,256,-256,256)])[0],split=metadata([face('bricka2_2',-256,0,-256,256),face('bricka2_2',0,256,-256,0,-7),face('bricka2_2',0,256,0,256,13)]);check(split.every(x=>JSON.stringify(x)===JSON.stringify(whole)),'T junction and UV phase retain same world warp');for(const name of ['uwall1_2','rock4_1'])same(metadata([face(name,-256,256,-256,256)])[0].amplitude,0,'unrelated natural texture retains its original sampling policy');}finally{field.R_RockfieldBuild(null);}
});
Deno.test('real rock material routes pigment normal height emission and filtering through the same warped micro coordinates while keeping macro metrics native',()=>{
 const controls=[post.r_hdr,anim.r_newer_lighting,anim.r_newer_normals],saved=controls.map(c=>c.string);for(const c of controls){if(!vars.Cvar_FindVar(c.name))vars.Cvar_RegisterVariable(c);vars.Cvar_SetValue(c.name,1);}let target=null;const renderer={capabilities:{isWebGL2:true},extensions:{has:()=>true},getRenderTarget:()=>target,setRenderTarget:t=>target=t};
 const diffuse=new THREE.DataTexture(new Uint8Array([121,79,43,255]),1,1),lightmap=new THREE.Texture(),normal=new THREE.DataTexture(new Uint8Array([128,128,255,128]),1,1);normal.userData.heightSource=true;diffuse._normalMap=normal;const original=diffuse.image.data.slice();
 try{post.R_PostBegin(renderer,true,64,64);const material=createQuakeLightmapMaterial(diffuse,lightmap);material.userData.rockField=true;const s={uniforms:{},vertexShader:THREE.ShaderLib.lambert.vertexShader,fragmentShader:THREE.ShaderLib.lambert.fragmentShader};material.onBeforeCompile(s);const f=s.fragmentShader;check(s.uniforms.qrRockBandWarpOn===shader.rockBandWarpOn,'actual material shares public diagnostic switch');check(s.vertexShader.includes('vRockWarp=rockWarp'),'actual interpolated metadata reaches fragment shader');check(f.includes('uint(floor(vRockWarp.x+.5))'),'perspective interpolation cannot randomly truncate stable seed');check(f.includes('vec2 pUv = vMapUv + qrRockUvShift + qrRockBandOffset(qrRockQ);'),'pigment samples warp at accepted macro hit');check(f.includes('qrShadowDx=dFdx(qrRockBaseUv);qrShadowDy=dFdy(qrRockBaseUv);'),'height-shadow footprint uses warped rest coordinates');check(f.indexOf('qrShadowDx=dFdx(qrRockBaseUv);')<f.indexOf('#include <clipping_planes_fragment>'),'warped derivatives captured before clipping or discard');check(f.includes('qrPigmentDx=dFdx(qrRockBaseUv)')&&f.includes('qrHeightGradients(-vViewPosition,qrRockBaseUv,hctx.normal'),'micro filtering and physical metric follow same warped base');check(f.includes('qrHeightGradients(-vViewPosition,vMapUv,qrRockN,qrMapGradU'),'macro physical UV conversion retains original native gradients');check(f.includes('hctx.microUv=DETAIL_UV'),'micro height receives actual final POM coordinate');check(f.includes('textureGrad( map, DETAIL_UV')&&f.includes('texture2D( normalMap, DETAIL_UV )')&&f.includes('texture2D( emissiveMap, DETAIL_UV )'),'diffuse normal emission share final coordinate');for(const gate of ['qrRockBandWarpOn<=0.','qrRockOn<=0.','uClassic>=.5'])check(shader.ROCK_BAND_WARP_GLSL.includes(gate),'actual warp preserves off/Classic identity '+gate);check(!/qrRockPage|qrRockHeights|uTime/.test(shader.ROCK_BAND_WARP_GLSL),'warp depends on rest space and seed, never page residency or time');check(original.every((v,i)=>v===diffuse.image.data[i]),'material compilation never repaints original pigment');material.dispose();}finally{post.R_PostShutdown();controls.forEach((c,i)=>vars.Cvar_Set(c.name,saved[i]));diffuse.dispose();normal.dispose();lightmap.dispose();}
});
