import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {STARTUP_PACK} from '../src/startup_pack.js';
import {COM_LoadPackFile,COM_SetNewerStartupPack,COM_SetNewerPack,COM_NewerFile,COM_NewerURL} from '../src/pak.js';
const check=(v,m)=>{if(!v)throw Error(m);},same=(a,b,m)=>check(a===b,`${m}: ${a} != ${b}`),read=p=>readFileSync(new URL('../'+p,import.meta.url)),sha=b=>createHash('sha256').update(b).digest('hex'),ab=b=>b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength);
const pack=()=>COM_LoadPackFile('independent-startup-pack',ab(read(STARTUP_PACK.file)));
function direct(entries){let total=12;const files=[];for(const [name,value]of entries){const data=new TextEncoder().encode(value);files.push({name,filepos:total,filelen:data.length,bytes:data});total+=data.length;}const bytes=new Uint8Array(total);for(const f of files)bytes.set(f.bytes,f.filepos);return{data:bytes.buffer,files};}
Deno.test('startup PACK contains exactly the287 manifest-referenced canonical HUD sources with every original byte and provenance hash intact',()=>{
 const raw=read(STARTUP_PACK.file),p=pack(),hud=JSON.parse(read('newer/hud/index.json')),face=JSON.parse(read('newer/hud/playerface/manifest.json')),expected=new Set(['newer/hud/index.json','newer/hud/playerface/manifest.json']);
 for(const path of Object.values(hud.sprites))expected.add('newer/hud/'+path);for(const asset of face.assets)if(asset.source)expected.add('newer/hud/playerface/'+asset.source+'.png');same(expected.size,287,'literal expected author-source roster');same(p.files.length,288,'287source payloads plus alias index only');same(raw.length,STARTUP_PACK.bytes,'exact transport length');same(sha(raw),STARTUP_PACK.sha256,'pinned raw PACK digest');
 const provenance=JSON.parse(read('newer/startup-pack-provenance.json'));same(provenance.sources.length,287,'every source has provenance');const records=new Map(provenance.sources.map(r=>[r.path,r]));COM_SetNewerPack(null);COM_SetNewerStartupPack(p);
 try{const alias=p.files.find(f=>f.name==='startup/index.json'),manifest=JSON.parse(new TextDecoder().decode(new Uint8Array(p.data,alias.filepos,alias.filelen)));same(Object.keys(manifest.files).sort().join(),[...expected].sort().join(),'no unused blood atlas, archive, original or unrelated artwork enters aliases');for(const path of expected){const actual=COM_NewerFile(path),source=read(path);check(actual&&Buffer.from(actual.data).equals(source),path+' actual public routing retains exact source bytes');same(actual.size,source.length,path+' exact length');same(records.get(path)?.sha256,sha(source),path+' independent original-byte provenance');}same(COM_NewerFile('newer/hud/unused-blood.png'),null,'unreferenced path absent');}finally{COM_SetNewerStartupPack(null);COM_SetNewerPack(null);}
});
Deno.test('explicit full art pack retains priority over startup aliases and null reset invalidates only optional routing while loose fallback remains usable',()=>{
 const p=pack(),name='newer/hud/index.json',original=read(name);COM_SetNewerPack(null);COM_SetNewerStartupPack(p);try{const aliasURL=COM_NewerURL(name,'loose.json');check(aliasURL.startsWith('blob:'),'startup alias resolves through real pack URL');COM_SetNewerPack(direct([[name,'{"override":true}']]));same(new TextDecoder().decode(COM_NewerFile(name).data),'{"override":true}','full art pack exact entry overrides bundled default');const overrideURL=COM_NewerURL(name,'loose.json');check(overrideURL!==aliasURL,'cached alias URL cannot mask newly installed override');COM_SetNewerPack(null);check(Buffer.from(COM_NewerFile(name).data).equals(original),'removing override restores bundled original');COM_SetNewerStartupPack(null);same(COM_NewerFile(name),null,'reset removes optional aliases');same(COM_NewerURL(name,'loose.json'),'loose.json','missing optional pack retains loose fallback');}finally{COM_SetNewerStartupPack(null);COM_SetNewerPack(null);}
});
Deno.test('malformed startup aliases are rejected atomically without replacing previously valid routing',()=>{
 const p=pack(),name='newer/hud/index.json',original=read(name);COM_SetNewerStartupPack(p);
 try{for(const [logical,alias]of [['newer/hud/../outside.png','startup/0.png'],['newer/hud/./x.png','startup/0.png'],['other/secret.png','startup/0.png'],['newer/hud/good.png','../secret.png'],['newer/hud/good.png','startup/not-numeric.png'],['newer/hud/good.png','startup/99.png']]){const bad=direct([['startup/index.json',JSON.stringify({version:1,files:{[logical]:alias}})],['startup/0.png','image']]);let rejected=false;try{COM_SetNewerStartupPack(bad);}catch{rejected=true;}check(rejected,'unsafe or missing alias rejected '+logical+' -> '+alias);check(Buffer.from(COM_NewerFile(name).data).equals(original),'rejected update preserves last valid source');}for(const index of [{version:2,files:{}},{version:1},null]){let rejected=false;try{COM_SetNewerStartupPack(direct([['startup/index.json',JSON.stringify(index)]]));}catch{rejected=true;}check(rejected,'invalid alias schema rejected');}}finally{COM_SetNewerStartupPack(null);}
});
