// Public bounded BSP directory parsing and existing decoded-asset cache reuse.
// No renderer, model loader, palette setup or game is needed for prefetch.
import {readFileSync} from 'node:fs';
import * as THREE from 'three';
import {R_BspTextureNames} from '../src/r_newertextures.js';
import * as anim from '../src/r_anim.js';
import * as vars from '../src/engine/common/cvar.js';
import {r_hdr} from '../src/gl_post.js';
import * as boot from '../src/r_demoloading.js';
const check=(v,m)=>{if(!v)throw Error(m);},same=(a,b,m)=>check(a===b,`${m}: ${a} != ${b}`),flush=async()=>{for(let i=0;i<40;i++)await Promise.resolve();};
function bsp(names){const offset=128,length=4+names.length*4+names.filter(n=>n!==null).length*40,bytes=new Uint8Array(offset+length),v=new DataView(bytes.buffer);v.setInt32(0,29,true);v.setInt32(20,offset,true);v.setInt32(24,length,true);v.setInt32(offset,names.length,true);let at=4+names.length*4;names.forEach((name,i)=>{v.setInt32(offset+4+i*4,name===null?-1:at,true);if(name===null)return;bytes.set(new TextEncoder().encode(name).subarray(0,16),offset+at);v.setInt32(offset+at+16,64,true);v.setInt32(offset+at+20,64,true);at+=40;});return bytes;}
Deno.test('bounded BSP29 texture-directory prefetch handles real native views, duplicate names and unsupported directories without touching a model',()=>{
 const bytes=bsp(['bricka2_2','*water1','sky1',null,'bricka2_2','dem4_1','']),copy=bytes.slice(),container=new Uint8Array(bytes.length+26);container.set(bytes,13);same(R_BspTextureNames(container.subarray(13,13+bytes.length)).join(),'bricka2_2,dem4_1','directory offsets relative to actual nonzero-offset view; duplicate/sky/water removed');same(Buffer.from(bytes).equals(Buffer.from(copy)),true,'original directory bytes retained');
 for(const bad of [null,{},bytes.buffer,new Int8Array(bytes),bytes.subarray(0,123)])same(R_BspTextureNames(bad).length,0,'unsupported view or short header is optional empty prefetch');
 const mutate=(label,change)=>{const bad=bytes.slice();change(new DataView(bad.buffer));same(R_BspTextureNames(bad).length,0,label+' rejects entire unsafe directory');};
 mutate('wrong BSP version',v=>v.setInt32(0,30,true));mutate('header-overlap texture lump',v=>v.setInt32(20,120,true));mutate('negative length',v=>v.setInt32(24,-1,true));mutate('truncated lump',v=>v.setInt32(24,bytes.length,true));mutate('negative entry count',v=>v.setInt32(128,-1,true));mutate('excessive entry count',v=>v.setInt32(128,4097,true));mutate('directory outside lump',v=>v.setInt32(128,100,true));mutate('offset points into directory',v=>v.setInt32(132,4,true));mutate('negative entry other than native missing',v=>v.setInt32(132,-2,true));mutate('truncated texture header',v=>v.setInt32(132,bytes.length-128-39,true));
 const pack=readFileSync(new URL('../pak0.pak',import.meta.url));for(let p=pack.readInt32LE(4),end=p+pack.readInt32LE(8);p<end;p+=64){const name=pack.subarray(p,p+56).toString().split('\0')[0];if(name!=='maps/e1m3.bsp')continue;const start=pack.readInt32LE(p+56),view=pack.subarray(start,start+pack.readInt32LE(p+60)),actual=R_BspTextureNames(view),expected=[],base=view.readInt32LE(20),count=view.readInt32LE(base);for(let i=0;i<count;i++){const off=view.readInt32LE(base+4+i*4);if(off<0)continue;const n=view.subarray(base+off,base+off+16).toString().split('\0')[0];if(n&&!n.startsWith('*')&&!n.startsWith('sky')&&!expected.includes(n))expected.push(n);}check(actual.length>20,'native demo fixture has a substantial real texture directory');same(actual.join(),expected.join(),'real PAK subview matches independent native directory walk');return;}throw Error('native demo map missing');
});
async function assetsFixture(run){
 const saved={fetch:globalThis.fetch,Image:Object.getOwnPropertyDescriptor(globalThis,'Image'),document:Object.getOwnPropertyDescriptor(globalThis,'document'),classic:anim.R_ClassicPassActive()},options=[r_hdr,anim.r_newer_textures];for(const v of options)if(!vars.Cvar_FindVar(v.name))vars.Cvar_RegisterVariable(v);const values=options.map(v=>v.string),images=[],fetches=[],decoded=[],scalar=new Uint16Array([0,16384,32768,65535]);
 const manifest={version:991,textures:{prefetch_a:'diffuse.png',prefetch_alias:'diffuse.png',prefetch_good:'good.png',prefetch_bad:'bad.png'},normals:{prefetch_a:{file:'height.png',dataFile:'height.r16',sampling:'clamp',displacement:{depth:4,step:1},edgeSource:{file:'edge.png'}},prefetch_alias:{file:'height.png',dataFile:'height.r16',sampling:'clamp',displacement:{depth:4,step:1},edgeSource:{file:'edge.png'}}}};
 globalThis.fetch=async url=>{fetches.push(String(url));if(String(url).endsWith('index.json'))return{ok:true,json:async()=>manifest};if(String(url).includes('height.r16'))return{ok:true,arrayBuffer:async()=>scalar.buffer.slice(0)};throw Error('unexpected prefetch '+url);};
 Object.defineProperty(globalThis,'Image',{configurable:true,value:class{constructor(){this.width=this.height=2;images.push(this);}set src(url){this.url=String(url);}finish(fail=false){if(fail){this.onerror?.(Error('controlled missing picture'));return;}this.pixels=new Uint8ClampedArray([10,20,30,255,40,50,60,255,70,80,90,255,100,110,120,255]);this.onload?.();}}});
 Object.defineProperty(globalThis,'document',{configurable:true,value:{createElement:tag=>{same(tag,'canvas','only decoding canvas requested');let image;return{width:0,height:0,getContext:()=>({drawImage:i=>image=i,getImageData:()=>{decoded.push(image.url);return{data:image.pixels};}})};}}});
 anim.R_AnimSetClassicPass(false);vars.Cvar_SetValue('r_hdr',0);vars.Cvar_SetValue('r_newer_textures',1);boot.R_DemoLoadingBoot();boot.R_DemoLoadingWelcome();
 const native=()=>new THREE.DataTexture(new Uint8Array([1,2,3,255]),1,1);
 try{const module=await import('../src/r_newertextures.js?prefetch-public-'+Math.random());await run({module,images,fetches,decoded,scalar,native});}
 finally{for(const image of images)if(image.onload||image.onerror)image.finish(true);await flush();boot.R_DemoLoadingCancel();globalThis.fetch=saved.fetch;anim.R_AnimSetClassicPass(saved.classic);options.forEach((v,i)=>vars.Cvar_Set(v.name,values[i]));for(const [key,d]of [['Image',saved.Image],['document',saved.document]])if(d)Object.defineProperty(globalThis,key,d);else delete globalThis[key];}
}
Deno.test('named prefetch shares exact decoded pigment/height/edge/scalar caches while actual textures and startup readiness remain authoritative',()=>assetsFixture(async f=>{
 const a=f.native(),b=f.native(),nativeImage=a.image,originalPixels=a.image.data.slice(),initialVersion=a.version,model={textures:[{name:'prefetch_a',gl_texture:a},{name:'prefetch_alias',gl_texture:b}]};let updates=0;a.addEventListener('newertextureupdated',()=>updates++);
 try{
  const gate=JSON.stringify(boot.R_DemoLoadingStatus()),prefetched=f.module.R_NewerTexturesPrefetch(['prefetch_a','prefetch_a','prefetch_alias','absent']);await flush();same(f.images.length,3,'shared diffuse/height/edge requested only once per decoded file');same(f.fetches.filter(u=>u.includes('height.r16')).length,1,'saved scalar fetched once');same(a.image,nativeImage,'prefetch cannot install pixels into an actual native texture');same(a.version,initialVersion,'prefetch cannot request GPU upload');same(updates,0,'no fabricated native texture update event');same(JSON.stringify(boot.R_DemoLoadingStatus()),gate,'prefetch never modifies actual startup coordinator');
  for(const image of f.images)image.finish();await prefetched;vars.Cvar_SetValue('r_hdr',1);same(f.module.R_NewerTexturesStatus(model).pending,2,'decoded prefetch does not mark real unapplied textures ready');same(f.module.R_NewerTexturesStatus(model).ready,0,'no fake asset-ready counts');
  f.module.R_NewerTextureUpgrade('prefetch_a',a);f.module.R_NewerTextureUpgrade('prefetch_alias',b);same(f.module.R_NewerTexturesStatus(model).pending,2,'public install begins through ordinary asynchronous upgrade');await flush();same(f.module.R_NewerTexturesStatus(model).ready,2,'actual installs produce readiness');same(f.images.length,3,'actual upgrade reused each decoded picture without second decode');same(f.decoded.length,3,'each source picture decoded exactly once');same(f.fetches.filter(u=>u.includes('height.r16')).length,1,'actual upgrade reuses scalar transport');same(a.image.data,b.image.data,'unmodified diffuse bytes shared from existing decoded cache');same(a.userData.classicImage,nativeImage,'original native image identity retained');check(Buffer.from(nativeImage.data).equals(Buffer.from(originalPixels)),'original native pixel bytes unchanged');same(updates,1,'one actual update event after installation');check(a.userData.newerHeight.edgeSource&&a.userData.newerHeight.displacement,'crafted edge/sculpt features survive prefetch');
  for(let i=0;i<4;i++)same(a.userData.newerHeight.data[i],Math.fround(f.scalar[i]/65535),'actual scalar height sample '+i);same(a.userData.newerHeight.sampling,'clamp','authored height boundary retained');check(boot.R_IntroLoadingHolding(),'successful prefetch/install cannot release startup by itself');
  vars.Cvar_SetValue('r_hdr',0);const classic=f.native();f.module.R_NewerTextureUpgrade('prefetch_a',classic);await flush();same(classic.userData.newerPicture,undefined,'resident cache never enables Classic upgrade');classic.dispose();
 }finally{a.dispose();b.dispose();}
}));
Deno.test('optional prefetch failure remains a recorded native fallback and cannot conceal another actual texture still loading',()=>assetsFixture(async f=>{
 const good=f.native(),bad=f.native(),original=bad.image,model={textures:[{name:'prefetch_good',gl_texture:good},{name:'prefetch_bad',gl_texture:bad}]};
 try{const promise=f.module.R_NewerTexturesPrefetch(['prefetch_good','prefetch_bad']);await flush();vars.Cvar_SetValue('r_hdr',1);f.module.R_NewerTextureUpgrade('prefetch_good',good);f.module.R_NewerTextureUpgrade('prefetch_bad',bad);await flush();f.images.find(i=>i.url.includes('bad.png')).finish(true);await flush();let status=f.module.R_NewerTexturesStatus(model);same(status.fallback,1,'actual missing picture reaches native fallback');same(status.pending,1,'other undecoded actual texture remains pending');check(status.errors['bad.png'],'prefetch failure retained in public diagnostics');check(boot.R_IntroReadinessChecks({assets:[['textures',status]]}).pending.includes('textures'),'real collector cannot overlook other pending art');same(bad.image,original,'failed optional prefetch/upgrade retains native pixels');f.images.find(i=>i.url.includes('good.png')).finish();await promise;await flush();status=f.module.R_NewerTexturesStatus(model);same(status.ready,1,'successful source installed normally');same(status.fallback,1,'failure remains terminal fallback');same(status.pending,0,'only actual settled outcomes finish texture work');check(boot.R_IntroLoadingHolding(),'terminal texture work alone cannot fake whole renderer readiness');same(f.images.length,2,'failed prefetch not redundantly retried by actual upgrade');}finally{good.dispose();bad.dispose();}
}));
