import * as THREE from 'three';
import {readFileSync} from 'node:fs';
import * as anim from '../src/r_anim.js';
import * as boot from '../src/r_demoloading.js';
const check=(v,m)=>{if(!v)throw Error(m);},same=(a,b,m)=>check(a===b,`${m}: ${a} != ${b}`);
function bsp(text){const raw=new TextEncoder().encode(text+'\0'),bytes=new Uint8Array(124+raw.length),view=new DataView(bytes.buffer);view.setInt32(0,29,true);view.setInt32(4,124,true);view.setInt32(8,raw.length,true);bytes.set(raw,124);return bytes;}
const entities='{"classname" "worldspawn"}\n{"classname" "monster_dog" "spawnflags" "1536"}\n{"classname" "monster_knight" "spawnflags" "1280"}\n{"classname" "monster_ogre" "spawnflags" "768"}\n{"classname" "monster_shambler" "spawnflags" "1792"}';
Deno.test('early skin inspection rejects malformed BSP views and starts only actual all-skill model, head and shared-gib sets through ordinary cached loads',async()=>{
 const old={fetch:globalThis.fetch,document:Object.getOwnPropertyDescriptor(globalThis,'document'),load:THREE.TextureLoader.prototype.load,newer:anim.R_IsNewer(),classic:anim.R_ClassicPassActive(),enemies:anim.r_newer_enemies.value,normals:anim.r_newer_normals.value},requests=[],loads=[];let skins;
 const expected=['dog','h_dog','knight','h_knight','ogre','h_ogre','gib1','gib2','gib3','zom_gib'],models={};for(const key of [...expected,'shambler','h_shams','wizard'])models[key]=[{dir:key,maps:{diffuse:'skin.png'}}];models.dog.push({dir:'dog-alt',maps:{diffuse:'skin.png'}});
 globalThis.fetch=async url=>{requests.push(String(url));return{ok:true,json:async()=>({version:'public-prefetch',models})};};Object.defineProperty(globalThis,'document',{configurable:true,value:{}});THREE.TextureLoader.prototype.load=function(url,done,_progress,fail){loads.push({url:String(url),done,fail});return new THREE.Texture();};anim.R_AnimSetClassicPass(false);anim.R_AnimSetNewer(false);boot.R_DemoLoadingWelcome();
 try{skins=await import('../src/r_newerskins.js?early-native-skin-prefetch');const good=bsp(entities),before=good.slice();for(const bad of [null,{},good.buffer,good.subarray(0,123)])await skins.R_NewerSkinsPrefetchBsp(bad);for(const mutate of [v=>v.setInt32(0,30,true),v=>v.setInt32(4,120,true),v=>v.setInt32(8,-1,true),v=>v.setInt32(8,4*1024*1024+1,true),v=>v.setInt32(4,good.length,true)]){const bad=good.slice();mutate(new DataView(bad.buffer));await skins.R_NewerSkinsPrefetchBsp(bad);}same(requests.length,0,'malformed optional inspection starts no manifest or images');
  const container=new Uint8Array(good.length+18);container.set(good,9);await skins.R_NewerSkinsPrefetchBsp(container.subarray(9,9+good.length));same(requests.length,1,'one real existing skin index request');same(loads.length,11,'all three skills include their own enemies, heads and shared gibs plus actual dog variant');const keys=loads.map(l=>l.url.split('/').at(-2)).sort();same(keys.join(),[...expected,'dog-alt'].sort().join(),'exact present-model sets only, all-skill excluded shambler and unrelated wizard absent');check(Buffer.from(good).equals(Buffer.from(before)),'native BSP bytes unchanged');same(skins.R_NewerAliasMaterial({_entityIndex:1},'progs/dog.mdl',true),null,'prefetch cannot activate Classic material choice');check(boot.R_IntroLoadingHolding(),'early requests cannot finish real loading coordinator');
  const names=expected.map(n=>'progs/'+n+'.mdl');same(skins.R_NewerSkinsStatus(names).pending,11,'settled prefetch promise means requests started, not falsely ready images');await skins.R_NewerSkinsPrefetchBsp(good);same(loads.length,11,'repeated inspection shares actual set/load cache');
  anim.R_AnimSetNewer(true);anim.r_newer_enemies.value=1;anim.r_newer_normals.value=0;await skins.R_NewerSkinsPrepare(names.map(name=>({name,cache:{data:{numskins:0}}})));same(loads.length,11,'actual model-precache preparation reuses prefetch requests');
  for(const item of loads){if(item.url.includes('/dog-alt/'))item.fail();else item.done(new THREE.DataTexture(new Uint8Array(16).fill(127),2,2));}const status=skins.R_NewerSkinsStatus(names);same(status.pending,0,'only actual image outcomes finish pending');same(status.ready,10,'successful images retained');same(status.fallback,1,'failed optional variant retained as explicit native fallback');check(Object.keys(status.errors).some(k=>k.includes('dog-alt')),'failure diagnostics retained');const material=skins.R_NewerAliasMaterial({_entityIndex:3},'progs/knight.mdl',true);check(material,'actual later native draw obtains ready cached model material');same(loads.length,11,'actual draw does not reload images');anim.R_AnimSetClassicPass(true);same(skins.R_NewerAliasMaterial({_entityIndex:3},'progs/knight.mdl',true),null,'Classic still ignores prefetched custom art');check(boot.R_IntroLoadingHolding(),'terminal optional assets alone never release world gate');
 }finally{skins?.R_NewerSkinsShutdown();globalThis.fetch=old.fetch;THREE.TextureLoader.prototype.load=old.load;anim.R_AnimSetClassicPass(old.classic);anim.R_AnimSetNewer(old.newer);anim.r_newer_enemies.value=old.enemies;anim.r_newer_normals.value=old.normals;boot.R_DemoLoadingCancel();if(old.document)Object.defineProperty(globalThis,'document',old.document);else delete globalThis.document;}
});
Deno.test('actual E1M3 entity bytes prefetch exactly its19 installed authored skin maps without loading models or unrelated enemy families',async()=>{
 const read=p=>readFileSync(new URL('../'+p,import.meta.url)),pack=read('pak0.pak'),index=JSON.parse(read('newer/enemies/index.json'));let map;
 for(let p=pack.readInt32LE(4),end=p+pack.readInt32LE(8);p<end;p+=64)if(pack.subarray(p,p+56).toString().split('\0')[0]==='maps/e1m3.bsp'){const start=pack.readInt32LE(p+56);map=pack.subarray(start,start+pack.readInt32LE(p+60));break;}check(map,'actual attract BSP in native PACK');
 // Independent literal model oracle from the native entity class roster plus
 // existing head/gib families. Only these keys have installed custom artwork.
 const keys=['armor','demon','h_demon','ogre','shambler','h_shams','wizard','zom_gib','zombie'],expected=keys.flatMap(k=>index.models[k].flatMap(v=>Object.entries(v.maps).filter(([role])=>['diffuse','height','normal','luma','gloss'].includes(role)).map(([,file])=>'newer/enemies/'+v.dir+'/'+file))).sort();same(expected.length,19,'bounded native authored request roster');
 const old={load:THREE.TextureLoader.prototype.load,document:Object.getOwnPropertyDescriptor(globalThis,'document')},requests=[];let skins;
 Object.defineProperty(globalThis,'document',{configurable:true,value:{}});THREE.TextureLoader.prototype.load=function(url,done,progress,fail){requests.push({url:String(url).split('?')[0],fail});return new THREE.Texture();};
 try{skins=await import('../src/r_newerskins.js?actual-e1m3-prefetch');skins.R_NewerSetIndex(index);const before=Buffer.from(map);await skins.R_NewerSkinsPrefetchBsp(map);same(requests.map(r=>r.url).sort().join(),expected.join(),'real BSP requests every installed needed image and no knight/dog/boss/other-map set');check(Buffer.from(map).equals(before),'actual native PAK bytes unchanged');same(skins.R_NewerSkinsStatus().pending,19,'starting native transport never pretends its images decoded');await skins.R_NewerSkinsPrefetchBsp(map);same(requests.length,19,'second actual BSP inspection retains existing request cache');}
 finally{for(const request of requests)request.fail();skins?.R_NewerSkinsShutdown();THREE.TextureLoader.prototype.load=old.load;if(old.document)Object.defineProperty(globalThis,'document',old.document);else delete globalThis.document;}
});
Deno.test('both BSP2 entity directory versions positively initiate needed skin requests before any model or game exists',async()=>{
 const previous={load:THREE.TextureLoader.prototype.load,document:Object.getOwnPropertyDescriptor(globalThis,'document')};Object.defineProperty(globalThis,'document',{configurable:true,value:{}});
 try{for(const version of [0x32505342,0x42535032]){const requests=[],skins=await import('../src/r_newerskins.js?wide-prefetch-'+version);THREE.TextureLoader.prototype.load=function(url,done){requests.push(String(url));const texture=new THREE.DataTexture(new Uint8Array(16).fill(127),2,2);queueMicrotask(()=>done(texture));return texture;};skins.R_NewerSetIndex({version,models:{dog:[{dir:'wide-dog',maps:{diffuse:'dog.png'}}]}});const bytes=bsp('{"classname" "worldspawn"}\n{"classname" "monster_dog"}');new DataView(bytes.buffer).setInt32(0,version,true);try{await skins.R_NewerSkinsPrefetchBsp(bytes);same(requests.length,1,'accepted widened entity directory causes actual new image request');check(requests[0].includes('/wide-dog/dog.png'),'correct actual entity model selected');}finally{skins.R_NewerSkinsShutdown();}}}
 finally{THREE.TextureLoader.prototype.load=previous.load;if(previous.document)Object.defineProperty(globalThis,'document',previous.document);else delete globalThis.document;}
});
