// Public optional prefetch: exact BSP source chooses transport hints, while
// actual model/texture jobs and the intro coordinator retain readiness.
import * as THREE from 'three';
import {createHash} from 'node:crypto';
import {R_StartupNormalsPrefetch} from '../src/newer/assets/r_normalprefetch.js';
import {STARTUP_NORMAL_BAKES} from '../src/newer/assets/startup_normal_bakes.js';
import {NORMAL_BAKES} from '../src/newer/assets/normal_bakes.js';
import {NormalTransport} from '../src/newer/assets/normal_transport.js';
import {NormalInputs,NormalInputKey,NormalGenerate,R_NormalPrepare,R_NormalPrepared} from '../src/newer/assets/normal_prepare.js';
import {NormalBakeEncode} from '../src/newer/assets/normal_bake_format.js';
import * as intro from '../src/newer/ui/r_demoloading.js';
const check=(v,m)=>{if(!v)throw Error(m);},same=(a,b,m)=>check(a===b,`${m}: ${a} != ${b}`),sha=b=>createHash('sha256').update(b).digest('hex'),ab=b=>b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),turn=()=>new Promise(r=>setTimeout(r,0));
let serial=0;
async function fixture(fn){const name='maps/normal-prefetch-public-'+ ++serial+'.bsp',storage=new Uint8Array([9,11,21,37,53,99]),bytes=storage.subarray(1,5),keys=['normal-prefetch-'+serial+'-a','normal-prefetch-'+serial+'-b'];STARTUP_NORMAL_BAKES[name]=[{bspSha256:sha(bytes),keys}];keys.forEach((key,i)=>NORMAL_BAKES[key]={file:key+'.gz',width:8+i,height:9+i,rawSha256:'fixture-'+i});try{return await fn({name,storage,bytes,keys});}finally{delete STARTUP_NORMAL_BAKES[name];keys.forEach(k=>delete NORMAL_BAKES[k]);}}
function leases(){const calls=[];return{calls,transport(spec,key,width,height){let resolve,reject;const call={spec,key,width,height,released:0,promise:new Promise((a,b)=>{resolve=a;reject=b;}),resolve:v=>resolve(v),reject:e=>reject(e),release(){call.released++;}};calls.push(call);return call;}};}
async function until(fn,label){const end=performance.now()+2000;while(!fn()&&performance.now()<end)await turn();check(fn(),label);}

Deno.test('startup normal hints select exact bounded BSP bytes and share only the matching named byte-range request',()=>fixture(async f=>{
 const pending=leases(),p=R_StartupNormalsPrefetch(f.name,f.bytes,pending.transport);same(R_StartupNormalsPrefetch(f.name,new Uint8Array(f.storage.buffer,1,4),pending.transport),p,'fresh view of identical loaded range shares promise');await until(()=>pending.calls.length===2,'exact source selects both hints');same(pending.calls[0].key,f.keys[0],'declared key order retained');same(pending.calls[0].width,8,'actual declared width forwarded');same(pending.calls[1].height,10,'actual declared height forwarded');
 for(const bytes of [f.storage.subarray(0,4),f.storage.subarray(1,4),new Uint8Array([11,21,37,54])])same((await R_StartupNormalsPrefetch(f.name,bytes,()=>{throw Error('Other source must not prefetch');})).status,'unused','different source range/content never borrows matching map-name hints');same((await R_StartupNormalsPrefetch('maps/unregistered-normal-public.bsp',f.bytes,()=>{throw Error('Unknown must not prefetch');})).status,'unused','unregistered map leaves runtime ownership alone');same((await R_StartupNormalsPrefetch(f.name,null)).status,'unused','absent source cannot claim bundled work');
 pending.calls.forEach(c=>c.resolve({}));same((await p).status,'ready','only exact source completes');check(pending.calls.every(c=>c.released===1),'every acquired lease released exactly once');
}));

Deno.test('normal prefetch awaits every transport lease without releasing actual intro readiness or creating texture jobs',()=>fixture(async f=>{
 const recording=leases();intro.R_DemoLoadingBoot();intro.R_DemoLoadingWelcome();const before=intro.R_DemoLoadingStatus(),p=R_StartupNormalsPrefetch(f.name,f.bytes,recording.transport);let finished=false;p.then(()=>finished=true);try{await until(()=>recording.calls.length===2,'both transports');recording.calls[0].resolve({});await turn();same(finished,false,'one remaining payload still matters');check(recording.calls.every(c=>c.released===0),'leases retained through pending group');recording.calls[1].resolve({});const result=await p;same(result.samples,2,'reports actual sample count');same(result.status,'ready','completed transport status');same(intro.R_DemoLoadingStatus().phase,before.phase,'transport completion cannot alter intro phase');check(intro.R_IntroLoadingHolding(),'actual world entry remains held');check(recording.calls.every(c=>c.released===1),'complete group leases released');}finally{recording.calls.forEach(c=>c.resolve({}));intro.R_DemoLoadingCancel();}
}));

Deno.test('missing later normal metadata and rejected transports release all earlier leases and never become a false successful hint',async()=>{
 await fixture(async f=>{delete NORMAL_BAKES[f.keys[1]];const recording=leases(),p=R_StartupNormalsPrefetch(f.name,f.bytes,recording.transport),result=await p;same(result.status,'error','missing partial specification is error');check(result.error.includes('Missing startup normal'),'missing source diagnosed');same(recording.calls.length,1,'no invented transport for missing sample');same(recording.calls[0].released,1,'earlier lease released on synchronous partial failure');recording.calls[0].resolve({});});
 await fixture(async f=>{const recording=leases(),p=R_StartupNormalsPrefetch(f.name,f.bytes,recording.transport);await until(()=>recording.calls.length===2,'both error fixture requests');let finished=false;p.then(()=>finished=true);recording.calls[1].reject(Error('controlled normal transport failure'));await turn();same(finished,false,'failed group still waits for all admitted consumers');check(recording.calls.every(c=>c.released===0),'unsettled consumer ownership retained');recording.calls[0].resolve({});const result=await p;same(result.status,'error','rejected transport stays error after all consumers settle');check(result.error.includes('controlled normal'),'precise failure retained');check(recording.calls.every(c=>c.released===1),'all lease ownership released exactly once after settlement');await turn();same((await p).status,'error','other completion cannot rewrite terminal error');});
});

Deno.test('startup hints populate the real bounded normal transport cache but only later public texture preparation installs data',()=>fixture(async f=>{
 const texture=new THREE.DataTexture(Uint8Array.from({length:64},(_,i)=>(i*17+91)%256),4,4),input=NormalInputs(texture),key=await NormalInputKey(input),raw=NormalBakeEncode(key,4,4,NormalGenerate(input)),prior=NORMAL_BAKES[key];NORMAL_BAKES[key]={file:'public-startup-real-normal.gz',width:4,height:4,rawSha256:sha(raw),sha256:'fixture'};STARTUP_NORMAL_BAKES[f.name][0].keys=[key];let calls=0;
 try{const result=await R_StartupNormalsPrefetch(f.name,f.bytes,(spec,k,w,h)=>NormalTransport(spec,k,w,h,async()=>{calls++;return ab(raw);}));same(result.status,'ready','actual checked transport ready');same(calls,1,'one real decode');same(R_NormalPrepared(texture),undefined,'prefetch has not fabricated a texture job');let events=0;texture.addEventListener('newertextureupdated',()=>events++);const work=R_NormalPrepare(texture,{loader:()=>{throw Error('Prefetched source must not download again');},generate:()=>{throw Error('Shipped source must not generate');},disk:{ensure(){throw Error('Shipped source needs no filesystem lookup');}}});await work.promise;same(work.status,'ready','actual texture job validates/installs retained payload');same(work.source,'shipped','source honestly reported');same(events,1,'only real preparation notifies renderer');same(calls,1,'prefetch request reused after its lease released');}
 finally{texture.dispose();if(prior)NORMAL_BAKES[key]=prior;else delete NORMAL_BAKES[key];}
}));
