// Independent public cache contracts. Real Three geometry and real validated
// bake payloads; renderer/fetch endpoints record work without starting a GPU.
import * as THREE from 'three';
import {createHash} from 'node:crypto';
import {PointShadowAtlas} from '../src/r_pointshadows.js';
import {R_ShaderAssetStamp} from '../src/r_shaderwarm.js';
import {ROCK_BAKES} from '../src/rockfield_bakes.js';
import {RockBakeConfig,RockBakeSignature,RockBakeTileCoordinates,RockBakeEncode,RockBakeDecode,ROCK_BAKE_SIDE} from '../src/rockfield_bake_format.js';
import {RockBakeSource,RockBakeFieldSignature,RockBakeFieldIndex} from '../src/r_rockbakes.js';
import {createField,generateTile} from '../src/rockfield.js';
import {R_RockPreset} from '../src/rockfield_presets.js';
const check=(v,m)=>{if(!v)throw Error(m);},same=(a,b,m)=>check(a===b,`${m}: ${a} != ${b}`),equalBytes=(a,b,m)=>check(Buffer.from(a.buffer,a.byteOffset,a.byteLength).equals(Buffer.from(b.buffer,b.byteOffset,b.byteLength)),m);
function geometry(){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute([-16,-16,-20,16,-16,-20,16,16,-20,-16,16,-12],3));g.setIndex([0,1,2,0,2,3]);g.setAttribute('normal',new THREE.Float32BufferAttribute(new Float32Array(12).fill(1),3));g.setAttribute('uv',new THREE.Float32BufferAttribute(new Float32Array(8),2));return g;}
function renderer(){const original=new THREE.WebGLRenderTarget(32,32),r={target:original,face:2,mip:1,viewport:new THREE.Vector4(7,8,90,91),scissor:new THREE.Vector4(1,2,70,71),scissorTest:false,color:new THREE.Color(.2,.3,.4),alpha:.7,autoClear:true,xr:{enabled:true},draws:[],throwAt:Infinity};r.getRenderTarget=()=>r.target;r.getActiveCubeFace=()=>r.face;r.getActiveMipmapLevel=()=>r.mip;r.getViewport=v=>v.copy(r.viewport);r.getScissor=v=>v.copy(r.scissor);r.getScissorTest=()=>r.scissorTest;r.getClearColor=v=>v.copy(r.color);r.getClearAlpha=()=>r.alpha;r.setRenderTarget=(t,f=0,m=0)=>{r.target=t;r.face=f;r.mip=m;};r.setViewport=v=>r.viewport.copy(v);r.setScissor=v=>r.scissor.copy(v);r.setScissorTest=v=>r.scissorTest=v;r.setClearColor=(v,a=r.alpha)=>{r.color.set(v);r.alpha=a;};r.clear=()=>{};r.render=(scene,camera)=>{const poses=scene.children.map(mesh=>{mesh.onBeforeRender(r,scene,camera,mesh.geometry,mesh.material);const p=mesh.geometry.getAttribute('position');return{mesh,geometry:mesh.geometry,matrix:mesh.matrixWorld.elements.slice(),position:p.isGLBufferAttribute?null:Array.from({length:p.count},(_,i)=>[p.getX(i),p.getY(i),p.getZ(i)]).flat(),index:mesh.geometry.index&&Array.from(mesh.geometry.index.array),count:mesh.count,instances:mesh.instanceMatrix&&Array.from(mesh.instanceMatrix.array)};});r.draws.push({camera:camera.position.toArray(),far:camera.far,poses});if(r.draws.length===r.throwAt)throw Error('controlled depth capture failure');};r.dispose=()=>original.dispose();return r;}
const rendererState=r=>JSON.stringify({face:r.face,mip:r.mip,viewport:r.viewport.toArray(),scissor:r.scissor.toArray(),test:r.scissorTest,color:r.color.toArray(),alpha:r.alpha,auto:r.autoClear,xr:r.xr.enabled});
const lights=n=>Array.from({length:n},(_,i)=>({source:{},position:[i*16,12,8],far:400}));
function fixture(fn){const world=geometry(),actorGeometry=geometry(),material=new THREE.MeshBasicMaterial(),actor=new THREE.Mesh(actorGeometry,material),group=new THREE.Group(),atlas=new PointShadowAtlas(world),r=renderer();group.add(actor);group.position.set(4,5,6);group.updateMatrixWorld(true);actor.onBeforeRender=()=>{throw Error('source callback must never execute in depth capture');};try{return fn({world,actorGeometry,material,actor,group,atlas,r});}finally{atlas.dispose();world.dispose();actorGeometry.dispose();material.dispose();r.dispose();}}
const frozen={frozenPose:true};
Deno.test('frozen intro reuses unchanged actual depth bytes despite version-only uploads and radiance changes, while ordinary live behavior stays current-frame',()=>fixture(({actor,actorGeometry,material,group,atlas,r})=>{
 const sources=lights(2);sources[0].live=true;const before=rendererState(r),target=r.target;atlas.update(r,sources,[actor],frozen);same(r.draws.length,12,'first frozen pose captures both complete cubes');check(sources.every(s=>atlas.lookup(s.source).ready),'both actual cubes ready');const revision=atlas.status().pointGeometryRevision;
 for(let i=0;i<4;i++){actorGeometry.attributes.position.needsUpdate=true;actorGeometry.index.needsUpdate=true;actorGeometry.attributes.normal.array[0]+=1;actorGeometry.attributes.normal.needsUpdate=true;actorGeometry.attributes.uv.array[0]+=.1;actorGeometry.attributes.uv.needsUpdate=true;material.color.setRGB(i/4,.3,.4);sources[0].source.power=3+i;group.updateMatrixWorld(true);atlas.update(r,sources,[actor],frozen);}
 same(r.draws.length,12,'same depth pose and light origin/range incur no extra cube draws');same(atlas.status().pointGeometryRevision,revision,'irrelevant attribute/version changes do not invalidate depth');same(atlas.status().pointDynamicMeshes,1,'physical caster remains admitted while cached');same(actor.parent,group,'source parent unchanged');same(atlas.scene.children.length,atlas.chunks.length,'borrowed clones always detached');same(rendererState(r),before,'renderer state unchanged');same(r.target,target,'target unchanged');
 atlas.update(r,sources,[actor]);same(r.draws.length,24,'default gameplay still refreshes all live/dynamic cubes');atlas.update(r,sources,[actor]);same(r.draws.length,36,'ordinary repeated frame behavior unchanged');
}));
Deno.test('frozen pose changes recapture actual vertex, index, range, world matrix, visibility and instance depth data',()=>fixture(({actor,actorGeometry,group,atlas,r})=>{
 const sources=lights(2);atlas.update(r,sources,[actor],frozen);const change=(label,mutate)=>{const n=r.draws.length;mutate();atlas.update(r,sources,[actor],frozen);same(r.draws.length-n,12,label+' invalidates both selected cubes');check(sources.every(s=>atlas.lookup(s.source).ready),label+' finishes current captures');};
 change('position bytes',()=>{actorGeometry.attributes.position.array[2]+=3;actorGeometry.attributes.position.needsUpdate=true;});check(r.draws.at(-1).poses.some(p=>p.geometry===actorGeometry&&p.position[2]===-17),'recorded draw sees new native positions');
 change('index bytes',()=>{actorGeometry.index.array[2]=3;actorGeometry.index.needsUpdate=true;});change('draw range',()=>actorGeometry.setDrawRange(0,3));change('actual world matrix',()=>{group.position.x+=7;group.updateMatrixWorld(true);});
 const n=r.draws.length;actor.visible=false;atlas.update(r,sources,[actor],frozen);same(r.draws.length-n,12,'removing actor recaptures static world without its old shadow');same(atlas.status().pointDynamicMeshes,0,'hidden source excluded');actor.visible=true;atlas.update(r,sources,[actor],frozen);
 const instances=new THREE.InstancedMesh(actorGeometry,actor.material,2);instances.setMatrixAt(0,new THREE.Matrix4());instances.setMatrixAt(1,new THREE.Matrix4().makeTranslation(12,0,0));instances.updateMatrixWorld();atlas.update(r,sources,[instances],frozen);let at=r.draws.length;instances.instanceMatrix.needsUpdate=true;atlas.update(r,sources,[instances],frozen);same(r.draws.length,at,'instance version-only upload reuses identical depth');instances.instanceMatrix.array[12]=8;instances.instanceMatrix.needsUpdate=true;atlas.update(r,sources,[instances],frozen);same(r.draws.length-at,12,'changed actual instance matrix recaptures');at=r.draws.length;instances.count=1;atlas.update(r,sources,[instances],frozen);same(r.draws.length-at,12,'instance count changes actual occlusion');same(instances.geometry,actorGeometry,'instance source geometry borrowed intact');
}));
Deno.test('frozen cache keeps moved lights and returning resident slots current, retries failed captures and invalidates on new-map geometry',()=>fixture(({actor,group,atlas,r})=>{
 const sources=lights(3);sources[0].source.live=true;atlas.update(r,sources,[actor],frozen);same(r.draws.length,18,'three initial cubes');let n=r.draws.length;sources[0].position[0]+=9;sources[0].far=550;atlas.update(r,sources,[actor],frozen);same(r.draws.length-n,6,'only changed light requires recapture despite frozen actors');check(r.draws.slice(n).every(d=>d.camera[0]===9&&d.far===550),'real capture camera uses updated origin/range');
 atlas.update(r,sources.slice(0,2),[actor],frozen);group.position.y+=5;group.updateMatrixWorld(true);atlas.update(r,sources.slice(0,2),[actor],frozen);same(atlas.lookup(sources[2].source).ready,false,'unselected resident cannot retain stale actor depth');n=r.draws.length;atlas.update(r,[sources[2]],[actor],frozen);same(r.draws.length-n,6,'returning light captures current pose');
 group.position.z+=3;group.updateMatrixWorld(true);r.throwAt=r.draws.length+1;atlas.update(r,sources,[actor],frozen);check(sources.some(s=>!atlas.lookup(s.source).ready),'failed capture cannot be marked ready');r.throwAt=Infinity;atlas.update(r,sources,[actor],frozen);check(sources.every(s=>atlas.lookup(s.source).ready),'unchanged pose still retries pending failed capture');
 atlas.invalidate();same(atlas.lookup(sources[0].source).ready,false,'map invalidation drops readiness');n=r.draws.length;atlas.update(r,sources,[actor],frozen);same(r.draws.length-n,18,'fresh epoch rebuilds every required cube');const replacement=geometry();try{atlas.setGeometry(replacement);n=r.draws.length;atlas.update(r,sources,[actor],frozen);same(r.draws.length-n,18,'new world geometry cannot inherit frozen depth');}finally{replacement.dispose();}
}));
const chart=(key='coverage-original')=>({id:1,key,name:'wgrnd1_5',profile:'ground',seed:73421,config:R_RockPreset('wgrnd1_5','ground'),tangent:[1,0,0],bitangent:[0,1,0],surfaces:[{bounds:[0,0,0,0]}]});
const buffer=b=>b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),hash=b=>createHash('sha256').update(b).digest('hex');let serial=0;
async function prepared(charts,tileFn,run){const model='maps/startup-public-'+(++serial)+'.bsp',payload=RockBakeEncode(model,charts,charts.flatMap(c=>RockBakeTileCoordinates(c).map(([x,y])=>tileFn(c,x,y))));ROCK_BAKES[model]={file:'fixture-'+serial+'.rf.gz',sha256:'compressed-fixture',rawSha256:hash(payload)};let requests=0;try{return await run(model,async()=>{requests++;return buffer(payload);},()=>requests,RockBakeDecode(buffer(payload),model));}finally{delete ROCK_BAKES[model];}}
Deno.test('validated prepared field reuses exact generated HALF-U16 data across coverage-only changes without crossing seed/config/axis or model boundaries',async()=>{
 const original=chart(),generated=Uint16Array.from(generateTile(createField(RockBakeConfig(original)),0,0).data,THREE.DataUtils.toHalfFloat),constant=new Uint16Array(ROCK_BAKE_SIDE**2).fill(0x3800);
 await prepared([original],(_c,x,y)=>x===0&&y===0?generated:constant,async(model,loader,requests,decoded)=>{
  const changed={...original,key:'joined-or-split-coverage',id:17,surfaces:[{bounds:[-20,-20,30,40]}]},different=[{...changed,seed:original.seed+1},{...changed,config:{...original.config,featureSize:original.config.featureSize+1}},{...changed,tangent:[0,1,0]},{...changed,bitangent:[0,0,1]}],source=new RockBakeSource(model,[original,changed,...different],loader);
  try{await source.entry.promise;same(source.status,'ready','normal SHA/model validation completes');same(requests(),1,'one validated payload transport');check(RockBakeSignature(original)!==RockBakeSignature(changed),'coverage signature truly changed');same(RockBakeFieldSignature(original),RockBakeFieldSignature(changed),'mathematical field is still identical');equalBytes(source.tile(changed,0,0),generated,'reused bytes equal independently generated GPU HALF data');same(source.fieldHits,1,'secondary field lookup actually used');equalBytes(source.tile(original,0,0),generated,'exact chart lookup remains first');same(source.fieldHits,1,'exact lookup did not masquerade as field reuse');same(source.tile(changed,100,100),null,'unprepared new extent still requires real generator');for(const c of different)same(source.tile(c,0,0),null,'changed seed/config/axes cannot borrow old field');same(RockBakeFieldIndex(decoded),RockBakeFieldIndex(decoded),'index is cached only per validated decoded object');const unrelated=new RockBakeSource('maps/unregistered-startup-fixture.bsp',[changed],loader);try{same(unrelated.tile(changed,0,0),null,'another model cannot inherit prepared payload');}finally{unrelated.dispose();}}
  finally{source.dispose();}
 });
});
Deno.test('conflicting validated overlap poisons shared reuse permanently while exact-chart authority and nonconflicting reuse remain intact',async()=>{
 const a=chart('a'),b=chart('b'),c=chart('c'),one=new Uint16Array(ROCK_BAKE_SIDE**2).fill(0x3800),two=one.slice();two[71]=0x3801;
 await prepared([a,b,c],(entry,x,y)=>entry===b&&x===0&&y===0?two:one,async(model,loader,_requests,decoded)=>{
  const requested={...a,key:'new-component'},source=new RockBakeSource(model,[a,b,c,requested],loader);try{await source.entry.promise;const index=RockBakeFieldIndex(decoded).get(RockBakeFieldSignature(a));same(index.get('0,0'),null,'A then conflictingB then A again cannot resurrect ambiguous tile');same(source.tile(requested,0,0),null,'ambiguous secondary lookup falls back to real generation');equalBytes(source.tile(a,0,0),one,'original exact chart remains authoritative');equalBytes(source.tile(b,0,0),two,'second exact chart is not silently replaced');equalBytes(source.tile(requested,1,1),one,'nonconflicting overlap remains reusable');}finally{source.dispose();}
 });
});

Deno.test('frozen depth cache compares GPU layout and bypasses unreadable GPU-only positions without dropping physical captures',()=>fixture(({actor,actorGeometry,atlas,r})=>{
 const sources=lights(1);atlas.update(r,sources,[actor],frozen);let n=r.draws.length;
 actorGeometry.attributes.position.gpuType=THREE.IntType;atlas.update(r,sources,[actor],frozen);same(r.draws.length-n,6,'changed GPU interpretation invalidates depth');
 const storage=new THREE.InstancedInterleavedBuffer(new Float32Array([-16,-16,-20,16,-16,-20,16,16,-20,-16,16,-12]),3,1),position=new THREE.InterleavedBufferAttribute(storage,3,0);
 actorGeometry.setAttribute('position',position);atlas.update(r,sources,[actor],frozen);n=r.draws.length;storage.needsUpdate=true;atlas.update(r,sources,[actor],frozen);same(r.draws.length,n,'identical interleaved upload is reusable');storage.meshPerAttribute=2;atlas.update(r,sources,[actor],frozen);same(r.draws.length-n,6,'interleaved divisor changes depth interpretation');
 const gpuPosition=new THREE.GLBufferAttribute({},THREE.FloatType,3,4,4);actorGeometry.setAttribute('position',gpuPosition);n=r.draws.length;
 for(let i=0;i<3;i++){atlas.update(r,sources,[actor],frozen);same(atlas.lookup(sources[0].source).ready,true,'GPU-only caster still completes ordinary depth capture');same(atlas.status().pointDynamicMeshes,1,'GPU-only caster remains admitted');}
 same(r.draws.length-n,18,'unreadable CPU data bypasses optional reuse on every call');check(r.draws.slice(n).every(d=>d.poses.some(p=>p.geometry===actorGeometry&&p.position===null)),'actual borrowed draw retains original GPU geometry');same(actorGeometry.getAttribute('position'),gpuPosition,'GPU attribute identity unchanged');same(atlas.scene.children.length,atlas.chunks.length,'no attached borrowed clones after GPU-only fallback');
}));
Deno.test('shader upload stamp follows real material and texture bindings and versions independently of mesh streaming',()=>{
 const material=new THREE.MeshBasicMaterial(),texture=new THREE.DataTexture(new Uint8Array([1,2,3,255]),1,1),replacementMaterial=material.clone(),replacementTexture=texture.clone(),mesh=new THREE.Mesh(geometry(),material);
 try{
  const stamp=()=>R_ShaderAssetStamp('native-assets-ready',[material],[texture]),first=stamp(),pixels=texture.image.data.slice();
  mesh.geometry.attributes.position.array[0]+=2;mesh.geometry.attributes.position.needsUpdate=true;mesh.geometry.setDrawRange(0,3);mesh.position.x=100;mesh.updateMatrixWorld();same(stamp(),first,'geometry streaming cannot force unchanged texture/material uploads');
  material.needsUpdate=true;check(stamp()!==first,'actual material program revision invalidates stamp');const second=stamp();texture.needsUpdate=true;check(stamp()!==second,'actual texture upload revision invalidates stamp');
  check(R_ShaderAssetStamp('native-assets-ready',[replacementMaterial],[texture])!==stamp(),'equal-looking replacement material retains distinct UUID identity');check(R_ShaderAssetStamp('native-assets-ready',[material],[replacementTexture])!==stamp(),'replacement texture cannot inherit old upload readiness');check(R_ShaderAssetStamp('upgraded-assets-ready',[material],[texture])!==stamp(),'asset role/revision stays part of upload identity');
  const versions=[material.version,texture.version];for(let i=0;i<5;i++)stamp();same([material.version,texture.version].join(),versions.join(),'inspection cannot create further upload revisions');equalBytes(texture.image.data,pixels,'stamp never modifies native texture pixels');
 }finally{mesh.geometry.dispose();material.dispose();texture.dispose();replacementMaterial.dispose();replacementTexture.dispose();}
});
Deno.test('transparent DoubleSide asset identity ignores internal draw versions but preserves real shader, callback and texture-binding changes',()=>{
 const texture=new THREE.DataTexture(new Uint8Array([110,70,20,255]),1,1),second=texture.clone(),third=texture.clone(),material=new THREE.MeshBasicMaterial({map:texture,transparent:true,side:THREE.DoubleSide}),opaque=new THREE.MeshBasicMaterial(),single=new THREE.MeshBasicMaterial({transparent:true,side:THREE.FrontSide});
 try{
  const stamp=()=>R_ShaderAssetStamp('ready',[material],[]),first=stamp();
  for(let i=0;i<4;i++){material.side=THREE.BackSide;material.needsUpdate=true;material.side=THREE.FrontSide;material.needsUpdate=true;material.side=THREE.DoubleSide;}
  same(stamp(),first,'ordinary two-pass drawing changes no shader/binding semantics');
  const changed=(label,mutate)=>{const before=stamp();mutate();check(stamp()!==before,label+' must invalidate previously warmed binding');};
  changed('alpha-test shader flag',()=>material.alphaTest=.4);changed('vertex-color shader flag',()=>material.vertexColors=true);changed('custom define',()=>material.defines={PUBLIC_FOG:1});changed('existing define value',()=>material.defines.PUBLIC_FOG=2);
  changed('program cache key',()=>material.customProgramCacheKey=()=> 'public-new-program');changed('program cache key result',()=>material.customProgramCacheKey=()=> 'public-another-program');
  // The default cache key derives from onBeforeCompile source; use its actual
  // implementation to verify callbacks without a fixture-only revision flag.
  material.customProgramCacheKey=THREE.Material.prototype.customProgramCacheKey;changed('onBeforeCompile implementation',()=>material.onBeforeCompile=function publicShaderChange(shader){shader.defines.PUBLIC_CUSTOM=1;});
  changed('ordinary map UUID',()=>material.map=second);changed('ordinary map upload version',()=>second.needsUpdate=true);material.uniforms={uDetail:{value:texture}};const uniformStamp=stamp();material.uniforms.uDetail.value=third;check(stamp()!==uniformStamp,'custom uniform texture replacement must invalidate');changed('custom uniform texture upload',()=>third.needsUpdate=true);
  changed('forceSinglePass shader behavior',()=>material.forceSinglePass=true);changed('side shader behavior',()=>material.side=THREE.FrontSide);
  for(const m of [opaque,single]){const before=R_ShaderAssetStamp('ready',[m],[]);m.needsUpdate=true;check(R_ShaderAssetStamp('ready',[m],[])!==before,'ordinary material versions remain authoritative');}
 }finally{texture.dispose();second.dispose();third.dispose();material.dispose();opaque.dispose();single.dispose();}
});
