import '../src/gl_rsurf.js';
import * as THREE from 'three';
import * as post from '../src/gl_post.js';
import * as height from '../src/r_heightshadows.js';
import * as anim from '../src/r_anim.js';
import * as vars from '../src/engine/common/cvar.js';
import {createQuakeLightmapMaterial} from '../src/gl_rsurf.js';
import {NormalInputs,NormalInputKey} from '../src/normal_prepare.js';
const report=document.querySelector('#report'),views=document.querySelector('#views'),button=document.querySelector('#run'),download=document.querySelector('#download');
download.onclick=()=>{if(!window.textureResolutionResult)return;const url=URL.createObjectURL(new Blob([JSON.stringify(window.textureResolutionResult,null,2)+'\n'],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download='texture-resolution-receipt.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
const controls=[post.r_hdr,post.r_dynres,post.r_bloom,post.r_volumetric,post.r_bounce,anim.r_newer_lighting,anim.r_newer_normals,anim.r_newer_water,height.r_heightshadows];for(const c of controls)if(!vars.Cvar_FindVar(c.name))vars.Cvar_RegisterVariable(c);
const hex=bytes=>[...bytes].map(b=>b.toString(16).padStart(2,'0')).join(''),hash=async bytes=>hex(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)));
const linear=value=>{const s=value/255;return 255*(s<=.04045?s/12.92:((s+.055)/1.055)**2.4);};
function luma(bytes,i){return linear(bytes[i])*.2126+linear(bytes[i+1])*.7152+linear(bytes[i+2])*.0722;}
function pixelDifference(a,b){let changed=0;for(let i=0;i<a.length;i++)if(a[i]!==b[i])changed++;return changed;}
function compare(bytes,reference,size){let n=0,sum=0,error=0,gradient=0,referenceGradient=0,detail=0;for(let y=3;y<size-3;y++)for(let x=3;x<size-3;x++){const i=(y*size+x)*4,neighbors=[i-4,i+4,i-size*4,i+size*4];if(!bytes[i+3]||neighbors.some(j=>!bytes[j+3]))continue;const value=luma(bytes,i),ref=luma(reference,i);sum+=value;error+=(value-ref)**2;gradient+=Math.abs(value-luma(bytes,i+4))+Math.abs(value-luma(bytes,i+size*4));referenceGradient+=Math.abs(ref-luma(reference,i+4))+Math.abs(ref-luma(reference,i+size*4));detail+=Math.abs(value-neighbors.reduce((v,j)=>v+luma(bytes,j),0)/4);n++;}return{samples:n,mean:sum/n,rmsVsNatural:Math.sqrt(error/n),gradient:gradient/(2*n),gradientVsNatural:gradient/Math.max(referenceGradient,1e-12),fineDetail:detail/n};}
function checkerStats(bytes,size){let difference=0,left=0,right=0,nl=0,nr=0;for(let y=8;y<size-8;y++)for(let x=8;x<size-8;x++){if(Math.abs(x-size/2)<8)continue;const value=linear(bytes[(y*size+x)*4]);difference+=Math.abs(value-linear(bytes[(y*size+x+1)*4]));if(x<size/2){left+=value;nl++;}else{right+=value;nr++;}}return{neighborDifference:difference/(nl+nr),leftMean:left/nl,rightMean:right/nr};}
function lineContrast(bytes,size){const results={};for(const[band,width]of[2,4,8].entries()){const values=[];for(let y=Math.ceil((band*64+12)/256*size);y<Math.floor((band*64+52)/256*size);y++)for(let x=20;x<size-20;x++)values.push(linear(bytes[(y*size+x)*4]));values.sort((a,b)=>a-b);results[width+'texel']={p05:values[Math.floor(values.length*.05)],p95:values[Math.floor(values.length*.95)],contrast:values[Math.floor(values.length*.95)]-values[Math.floor(values.length*.05)]};}return results;}
function picture(label,bytes,size){const canvas=document.createElement('canvas');canvas.width=canvas.height=size;const ctx=canvas.getContext('2d'),image=ctx.createImageData(size,size);for(let y=0;y<size;y++)for(let x=0;x<size;x++){const i=(y*size+x)*4,o=((size-1-y)*size+x)*4;image.data.set([bytes[i],bytes[i+1],bytes[i+2],255],o);}ctx.putImageData(image,0,0);const figure=document.createElement('figure'),caption=document.createElement('figcaption');caption.textContent=label;figure.append(canvas,caption);views.append(figure);}
async function run(){button.disabled=true;views.replaceChildren();const resources=[],checks=[],metrics=[],errors=[];let renderer;const prior=controls.map(c=>c.string),check=(passed,name,data={})=>checks.push({passed,name,...data});try{
 for(const[name,value]of Object.entries({r_hdr:1,r_dynres:0,r_bloom:0,r_volumetric:0,r_bounce:0,r_newer_lighting:1,r_newer_normals:0,r_newer_water:0,r_heightshadows:0}))vars.Cvar_SetValue(name,value);
 renderer=new THREE.WebGLRenderer({antialias:false,preserveDrawingBuffer:true});renderer.setPixelRatio(1);renderer.setSize(512,512);renderer.setClearColor(0,0);renderer.debug.onShaderError=(gl,p,v,f)=>errors.push(gl.getProgramInfoLog(p)+'\n'+gl.getShaderInfoLog(f));const gl=renderer.getContext(),anisotropy=Math.min(16,renderer.capabilities.getMaxAnisotropy());
 const texture=(data,w,h,colorSpace=THREE.NoColorSpace)=>{const t=new THREE.DataTexture(data,w,h);t.colorSpace=colorSpace;t.flipY=false;t.wrapS=t.wrapT=THREE.RepeatWrapping;t.minFilter=THREE.LinearMipmapLinearFilter;t.magFilter=THREE.LinearFilter;t.anisotropy=anisotropy;t.generateMipmaps=true;t.needsUpdate=true;resources.push(t);return t;};
 const decode=async path=>{const response=await fetch('../'+path);if(!response.ok)throw Error('Missing actual authored asset '+path);const bytes=await response.arrayBuffer(),image=await createImageBitmap(new Blob([bytes])),surface=document.createElement('canvas');surface.width=image.width;surface.height=image.height;const ctx=surface.getContext('2d');ctx.drawImage(image,0,0);const data=ctx.getImageData(0,0,image.width,image.height).data;image.close();return{path,width:surface.width,height:surface.height,data,fileSHA:await hash(bytes),pixelsSHA:await hash(data)};};
 const lightmap=texture(new Uint8Array([128,128,128,255]),1,1),flat=texture(new Uint8Array([128,128,255,255]),1,1);lightmap.channel=1;
 const geometry=new THREE.PlaneGeometry(96,96);geometry.setAttribute('uv1',geometry.attributes.uv.clone());resources.push(geometry);const geometryBefore=geometry.attributes.position.array.slice(),uvBefore=geometry.attributes.uv.array.slice();const scene=new THREE.Scene(),surface=new THREE.Mesh(geometry),camera=new THREE.PerspectiveCamera(75,1,1,2048),orthographic=new THREE.OrthographicCamera(-48,48,48,-48,1,2048);scene.add(surface);orthographic.position.z=64;orthographic.lookAt(0,0,0);orthographic.updateMatrixWorld();
 post.R_PostBegin(renderer,true,512,512);
 // Hold the decoded authored normal input constant for this pigment-only
 // comparison. Automatic normal preparation is disabled so this finite trial
 // neither regenerates nor persists a second normal-data set.
 function material(diffuse,normal){diffuse.userData.newerPicture=true;diffuse._normalMap=normal;const m=createQuakeLightmapMaterial(diffuse,lightmap),control={floor:4,productionUniform:null},original=m.onBeforeCompile;m.onBeforeCompile=function(shader,...args){original.call(this,shader,...args);control.productionUniform=shader.uniforms.uPigmentMinFootprint;shader.uniforms.uPigmentMinFootprint={get value(){return control.floor===null?control.productionUniform.value:control.floor;}};};resources.push(m);return{m,control,diffuse,normal};}
 const actual=[];for(const[name,dimension]of[['tech01_1',256],['shot0sid',128]]){const image=await decode('newer/textures/'+name+'.webp'),normal=await decode('newer/textures/normals/'+name+'.webp');check(image.width===dimension&&image.height===dimension,name+' authored decoded dimensions',{width:image.width,height:image.height,fileSHA:image.fileSHA});const diffuse=texture(image.data,image.width,image.height,THREE.SRGBColorSpace),normalTexture=texture(normal.data,normal.width,normal.height);const entry={name,image,normalImage:normal,...material(diffuse,normalTexture)};entry.normalKey=await NormalInputKey(NormalInputs(diffuse));actual.push(entry);}
 // Preserve the original one-texel grain oracle separately from useful narrow
 // details. No threshold is changed or treated as equivalent to source quality.
 const checker=new Uint8Array(256*256*4),lines=new Uint8Array(256*256*4);for(let y=0;y<256;y++)for(let x=0;x<256;x++){const grain=(x<128?80:160)+((x+y)%2?50:-50);checker.set([grain,grain,grain,255],(y*256+x)*4);const width=[2,4,8,16][y>>6],v=Math.floor(x/width)%2?224:32;lines.set([v,v,v,255],(y*256+x)*4);}const checkerEntry=material(texture(checker,256,256),flat),lineEntry=material(texture(lines,256,256),flat);
 function draw(entry,floor,{size=512,pose='near',classic=false,ortho=false,jitter=0,jitterY=0,distance=null,readNormal=true}={}){entry.control.floor=floor;surface.material=entry.m;surface.rotation.y=pose==='oblique'?Math.PI/3:0;surface.position.set(jitter,jitterY,0);camera.position.set(0,0,distance??(pose==='far'?512:64));camera.lookAt(0,0,0);camera.updateMatrixWorld();post.R_PostBegin(renderer,true,size,size);post.classicLook.value=classic?1:0;if(entry.m.normalMap!==entry.normal){entry.m.normalMap=entry.normal;entry.m.needsUpdate=true;}height.R_HeightShadowScope(false);post.R_PostBind(renderer);const target=renderer.getRenderTarget(),started=performance.now();renderer.clear();renderer.render(scene,ortho?orthographic:camera);gl.finish();const submitAndFinishMs=performance.now()-started;const albedo=new Uint8Array(size*size*4),normal=readNormal?new Uint16Array(size*size*4):null;renderer.readRenderTargetPixels(target,0,0,size,size,albedo,0,2);if(readNormal)renderer.readRenderTargetPixels(target,0,0,size,size,normal,0,1);check(target.width===size&&target.height===size,'fixed framebuffer '+size);return{albedo,normal,submitAndFinishMs};}
 function gpuSize(input){const m=new THREE.RawShaderMaterial({glslVersion:THREE.GLSL3,vertexShader:'precision highp float;in vec3 position;void main(){gl_Position=vec4(position,1.);}',fragmentShader:'precision highp float;uniform sampler2D tex;out vec4 color;void main(){color=vec4(vec2(textureSize(tex,0)),vec2(textureSize(tex,2)));}',uniforms:{tex:{value:input}},depthTest:false,depthWrite:false}),g=new THREE.PlaneGeometry(2,2),target=new THREE.WebGLRenderTarget(1,1,{type:THREE.FloatType,depthBuffer:false}),s=new THREE.Scene();resources.push(m,g,target);s.add(new THREE.Mesh(g,m));renderer.setRenderTarget(target);renderer.render(s,new THREE.Camera());const size=new Float32Array(4);renderer.readRenderTargetPixels(target,0,0,1,1,size);return Array.from(size);}
 for(const entry of actual){const dimensions=gpuSize(entry.diffuse);check(dimensions[0]===entry.image.width&&dimensions[1]===entry.image.height&&dimensions[2]===entry.image.width/4&&dimensions[3]===entry.image.height/4,entry.name+' GPU preserves actual mip0 and generated mip2 dimensions',{gpuTextureSize:dimensions});for(const pose of['near','oblique','far']){const results=new Map([1,2,4].map(floor=>[floor,draw(entry,floor,{pose})])),natural=results.get(1),classic=draw(entry,1,{pose,classic:true}),production=draw(entry,null,{pose});check(entry.control.productionUniform?.value===2,entry.name+' '+pose+' actual production default is two texels',{actualDefault:entry.control.productionUniform?.value});check(pixelDifference(production.albedo,results.get(2).albedo)===0,entry.name+' '+pose+' unoverridden default exactly matches measured floor2');for(const floor of[4,2,1]){const frame=results.get(floor),stats=compare(frame.albedo,natural.albedo,512),classicControl=draw(entry,floor,{pose,classic:true});check(pixelDifference(frame.normal,natural.normal)===0,entry.name+' '+pose+' normal MRT unchanged at floor '+floor);check(pixelDifference(classicControl.albedo,classic.albedo)===0,entry.name+' '+pose+' Classic exact at floor '+floor);metrics.push({asset:entry.name,pose,floor,submitAndFinishMs:frame.submitAndFinishMs,...stats});picture(entry.name+' '+pose+' · floor '+floor,frame.albedo,512);}check(entry.m.normalMap===entry.normal,entry.name+' normal cache object unchanged');}
 check(await hash(entry.image.data)===entry.image.pixelsSHA,entry.name+' source RGBA pixels unchanged');check(await hash(entry.normalImage.data)===entry.normalImage.pixelsSHA,entry.name+' authored normal pixels unchanged');check(await NormalInputKey(NormalInputs(entry.diffuse))===entry.normalKey,entry.name+' normal-generation source identity unchanged');}
 const narrow={};for(const floor of[4,2,1]){const drawn=draw(lineEntry,floor,{ortho:true});narrow[floor]=lineContrast(drawn.albedo,512);picture('Authored 2/4/8 texel line pairs · floor '+floor,drawn.albedo,512);}check(narrow[1]['2texel'].contrast>100,'resolved two-texel feature positive control',narrow[1]);
 const native=draw(checkerEntry,0,{size:256,ortho:true}),nativeStats=checkerStats(native.albedo,256),grain={};for(const floor of[4,2,1]){const image=draw(checkerEntry,floor,{size:256,ortho:true}),classic=draw(checkerEntry,floor,{size:256,ortho:true,classic:true}),s=checkerStats(image.albedo,256);grain[floor]={...s,passesOriginalGrainSuppression:s.neighborDifference<nativeStats.neighborDifference*.35,passesOriginalMeans:Math.abs(s.leftMean-nativeStats.leftMean)<2&&Math.abs(s.rightMean-nativeStats.rightMean)<2&&Math.abs(s.leftMean-80)<2&&Math.abs(s.rightMean-160)<2,classicChanged:pixelDifference(classic.albedo,native.albedo)};check(grain[floor].classicChanged===0,'legacy checker Classic remains exact floor '+floor);}check(nativeStats.neighborDifference>40,'unchanged legacy native grain positive control',nativeStats);check(grain[4].passesOriginalGrainSuppression&&grain[4].passesOriginalMeans,'current floor4 still meets unchanged original grain oracle',grain[4]);
 check(geometryBefore.every((v,i)=>v===geometry.attributes.position.array[i])&&uvBefore.every((v,i)=>v===geometry.attributes.uv.array[i]),'geometry and native UVs remain exact');check(errors.length===0&&gl.getError()===gl.NO_ERROR,'all actual world-material variants render without GPU errors',{errors});
 // Four finite subpixel phases, each compared with an independent 2x2
 // spatial supersampling reference. This measures temporal sampling error,
 // rather than labelling all legitimate motion/detail changes as shimmer.
 const temporal=[],timings=[];
 for(const entry of actual){const size=256,distance=192,pixelWorld=2*distance*Math.tan(75*Math.PI/360)/size,phases=[0,.25,.5,.75],frames=[],references=[];
  for(const phase of phases){const center=phase*pixelWorld,reference=new Float64Array(size*size),valid=new Uint8Array(size*size).fill(1);for(const[dx,dy]of[[-.25,-.25],[.25,-.25],[-.25,.25],[.25,.25]]){const image=draw(entry,1,{size,distance,jitter:center+dx*pixelWorld,jitterY:dy*pixelWorld,readNormal:false}).albedo;for(let i=0;i<reference.length;i++){reference[i]+=luma(image,i*4)/4;if(!image[i*4+3])valid[i]=0;}}references.push({reference,valid});frames.push(Object.fromEntries([1,2,4].map(floor=>[floor,draw(entry,floor,{size,distance,jitter:center,readNormal:false}).albedo])));}
  for(const floor of[4,2,1]){let samples=0,error=0,temporalError=0,motion=0;for(let i=0;i<size*size;i++){if(!references.every(row=>row.valid[i])||!frames.every(row=>row[floor][i*4+3]))continue;for(let phase=0;phase<phases.length;phase++){const value=luma(frames[phase][floor],i*4),delta=value-references[phase].reference[i];error+=delta*delta;samples++;if(phase){const previous=luma(frames[phase-1][floor],i*4),actualDelta=value-previous,referenceDelta=references[phase].reference[i]-references[phase-1].reference[i];temporalError+=(actualDelta-referenceDelta)**2;motion+=actualDelta*actualDelta;}}}check(samples>100,'bounded temporal minification coverage '+entry.name+' floor '+floor,{samples});temporal.push({asset:entry.name,floor,framebuffer:size,distance,phases,reference:'four natural-mip subpixel renders per phase',samples,rmsVsSpatialReference:Math.sqrt(error/samples),temporalDeltaErrorRMS:Math.sqrt(temporalError/(samples*.75)),actualFrameDeltaRMS:Math.sqrt(motion/(samples*.75))});}
  for(const floor of[4,2,1]){draw(entry,floor,{readNormal:false});const samples=[];for(let i=0;i<3;i++)samples.push(draw(entry,floor,{readNormal:false}).submitAndFinishMs);const sorted=samples.slice().sort((a,b)=>a-b);check(samples.every(value=>Number.isFinite(value)&&value>=0),'bounded render timings recorded '+entry.name+' floor '+floor);timings.push({asset:entry.name,floor,framebuffer:512,samples,medianMs:sorted[1],measurement:'CPU wall time around clear + render submission + gl.finish; warm shader, excludes pixel readback; not pure GPU timer'});}
 }
 const eligible=[1,2,4].filter(floor=>grain[floor].passesOriginalGrainSuppression&&grain[floor].passesOriginalMeans),recommended=eligible[0]??null;const recommendation={floor:recommended,basis:'Smallest tested footprint satisfying the unchanged checker suppression and linear-mean oracle; inspect real-art and line-pair retention metrics alongside this constraint.',twoTexelContrast:recommended===null?null:narrow[recommended]['2texel'].contrast,naturalTwoTexelContrast:narrow[1]['2texel'].contrast,currentTwoTexelContrast:narrow[4]['2texel'].contrast};const result={status:checks.every(c=>c.passed)?'PASS':'FAIL',recommendation,framebuffer:{realArt:512,legacyChecker:256,dpr:1,dynamicResolution:0},anisotropy,deviceMaxTextureSize:renderer.capabilities.maxTextureSize,checks,metrics,temporalMinification:temporal,renderTiming:timings,narrowFeatureContrast:narrow,legacyGrain:{native:nativeStats,floors:grain},qualification:'Finite material-plane readback; actual world/ammo framebuffer and owner appearance acceptance are separate.'};window.textureResolutionResult=result;report.textContent=JSON.stringify(result,null,2);download.disabled=false;
 }catch(error){const result={status:'FAIL',error:error.stack,checks,metrics,errors};window.textureResolutionResult=result;report.textContent=JSON.stringify(result,null,2);download.disabled=false;}finally{post.classicLook.value=0;height.R_HeightShadowScope(false);post.R_PostShutdown();resources.forEach(r=>r.dispose());renderer?.dispose();controls.forEach((c,i)=>vars.Cvar_Set(c.name,prior[i]));button.disabled=false;}}
button.onclick=run;await run();
