// Store only original greedy command/order data, never pose/skin replacement.
import {register} from 'node:module';
import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {AliasMeshSignature,AliasMeshValidate,ALIAS_MESH_VERSION} from '../src/newer/assets/alias_mesh_format.js';
if(!process.env.QUAKED_THREE_MODULE)throw Error('Set QUAKED_THREE_MODULE');
const three=pathToFileURL(resolve(process.env.QUAKED_THREE_MODULE)).href;
register('data:text/javascript,'+encodeURIComponent("let three;export function initialize(d){three=d.three;}export function resolve(s,c,next){return s==='three'?{url:three,shortCircuit:true}:next(s,c);}"),{data:{three}});
await import('../src/engine/render/gl_rsurf.js');const pak=await import('../src/engine/common/pak.js'),model=await import('../src/engine/render/gl_model.js'),vid=await import('../src/engine/render/vid.js');
await import('../src/newer/install.js'); // Newer Game plugs into the engine's hooks (src/engine/common/hooks.js), after the loader and the renderer's bootstrap
const files=process.argv.slice(2);if(!files.length)files.push('pak0.pak');const names=new Set(),archives=[];
const raw=await readFile('pak0.pak');pak.COM_AddPack(pak.COM_LoadPackFile('palette',raw.buffer.slice(raw.byteOffset,raw.byteOffset+raw.length)));
for(const file of files){const b=await readFile(file),pack=pak.COM_LoadPackFile(file,b.buffer.slice(b.byteOffset,b.byteOffset+b.length));pak.COM_AddPack(pack);archives.push({file,sha256:createHash('sha256').update(b).digest('hex')});for(const f of pack.files)if(/^progs\/[^/]+\.mdl$/.test(f.name))names.add(f.name);}
vid.VID_SetPalette(pak.COM_FindFile('gfx/palette.lmp').data);model.Mod_Init();let records={};try{records=(await import('../src/newer/assets/alias_mesh_bakes.js')).ALIAS_MESH_BAKES;}catch{}
records=Object.fromEntries(Object.entries(records).filter(([key])=>{const a=JSON.parse(key);return a[5].length===a[2]&&a[6].length===a[1];}));
const witnesses=[];
for(const name of [...names].sort()){
 const header=model.Mod_ForName(name,true).cache.data,key=AliasMeshSignature(header),record={commands:Array.from(header.commands),order:Array.from(header.meshVertexOrder)};
 AliasMeshValidate(record,header);records[key]=record;witnesses.push({name,commands:record.commands.length,vertices:record.order.length});console.log('BAKED '+name+' '+record.commands.length+' commands');
}
await writeFile('src/newer/assets/alias_mesh_bakes.js','/**\n * @module newer/assets/alias_mesh_bakes\n *\n * Prepared alias meshes, generated by `tools/bake_alias_meshes.mjs` (do not edit: re-run the tool).\n *\n * Types: plain values and functions; no exported classes.\n *\n * State: no mutable exports.\n *\n * Errors: none raised here (no `Sys_Error`, `throw`, `Host_Error` or `PR_RunError`).\n */\n// Generated by tools/bake_alias_meshes.mjs; original strip/fan output only.\nexport const ALIAS_MESH_BAKES = '+JSON.stringify(records)+';\n');
await writeFile('newer/alias-mesh-provenance.json',JSON.stringify({version:ALIAS_MESH_VERSION,archives,records:witnesses},null,2)+'\n');
