"""Bundle only manifest-referenced HUD rasters; preserve every authored byte.
Short PACK entry aliases accommodate the face kit's long logical filenames.
No directory walk: unused atlases, loose owner artwork and historical files stay out.
"""
import pathlib, json, hashlib, struct
ROOT=pathlib.Path(__file__).resolve().parents[1]
paths={'newer/hud/index.json','newer/hud/playerface/manifest.json'}
hud=json.loads((ROOT/'newer/hud/index.json').read_text())
face=json.loads((ROOT/'newer/hud/playerface/manifest.json').read_text())
paths.update('newer/hud/'+p for p in hud['sprites'].values())
paths.update('newer/hud/playerface/'+a['source']+'.png' for a in face['assets'] if a.get('source'))
blobs=[];aliases={};proof=[]
for i,path in enumerate(sorted(paths)):
    data=(ROOT/path).read_bytes();name='startup/'+str(i)+pathlib.Path(path).suffix
    aliases[path]=name;blobs.append((name,data));proof.append({'path':path,'sha256':hashlib.sha256(data).hexdigest(),'bytes':len(data)})
blobs.append(('startup/index.json',json.dumps({'version':1,'files':aliases},separators=(',',':')).encode()))
out=bytearray(b'PACK'+b'\0'*8);table=[]
for name,data in blobs:
    table.append((name,len(out),len(data)));out.extend(data)
offset=len(out)
for name,pos,size in table:out.extend(struct.pack('<56sii',name.encode(),pos,size))
struct.pack_into('<ii',out,4,offset,len(table)*64)
path='newer/startup.pak';(ROOT/path).write_bytes(out)
spec={'file':path,'sha256':hashlib.sha256(out).hexdigest(),'bytes':len(out),'entries':len(blobs)}
(ROOT/'src/newer/assets/startup_pack.js').write_text("/**\n * @module newer/assets/startup_pack\n *\n * The start-up pack's description, generated by `tools/build_startup_pak.py` (do not edit: re-run the tool).\n *\n * Types: plain values and functions; no exported classes.\n *\n * State: no mutable exports.\n *\n * Errors: none raised here (no `Sys_Error`, `throw`, `Host_Error` or `PR_RunError`).\n */\n"+'// Generated by tools/build_startup_pak.py; authored HUD bytes remain canonical.\nexport const STARTUP_PACK = '+json.dumps(spec,separators=(',',':'))+';\n')
(ROOT/'newer/startup-pack-provenance.json').write_text(json.dumps({'pack':spec,'sources':proof},indent=2)+'\n')
print(path,len(out),'bytes',len(paths),'referenced sources')
