#!/usr/bin/env python3
"""Write docs/index.md: every Markdown document in docs/, grouped by topic.

The topic of a document is the first rule in TOPICS whose pattern matches its file name; a document no rule
matches goes under "Other", so a new document is never left out of the index (re-run this script after adding
one). The link text is the document's own first heading. The check that every link resolves is
tests/docs_index_test.py.

    python3 tools/build_docs_index.py          # rewrite docs/index.md
    python3 tools/build_docs_index.py --check  # exit 1 if docs/index.md is out of date
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / 'docs'
OUT = DOCS / 'index.md'

# (heading, one-line description, file-name pattern); first match wins
TOPICS = [
	('Playing and menus', 'Starting a game, the menu, loading and the options screen.',
	 r'single-player-menu|game-menu|gamepad|loading-|studio-logo|credits-sizing|newer-game-startup|enhanced-landing|options-|audio-volume|ambient-music|intro-readiness|visual-options|asset-readiness|fullgame|distribution|welcome-'),
	('Weapons and combat', 'Held weapons, shotgun pellets, shells, the death and respawn rules.',
	 r'weapon|nailgun|shotgun|super-nailgun|held-framing|clockwise-respawn|respawn-|death-remains|pinned-zombies|powerup|power-up|quad|ring-unseen|axe-|burn-decals|melee-'),
	('Enemies, skins and faces', 'Custom enemy skins, heights, heads, the Bestiary and the player portrait.',
	 r'enemy|face-|hud-|head-skins|height-authoring|demon|oldone|vore|bestiary|gloom-hood|shambler|zombie|rend-the-veil|animation-audit'),
	('Worlds, rock and textures', 'Level textures, rock relief, seams, seamless levels and portals.',
	 r'rock|texture|seam|level-|portal|e1m1|prepared-|seamless|classic-|demo-|profiler|pad-windows|entity-limit'),
	('Light, water and fire', 'Lighting, shadows, water, lava, glass and the fire and explosion effects.',
	 r'light|emissive|shadow|water|lava|glass|explosions|ripple|rocket-grenade|torch-fire|flashlight|model-lighting|height-map|caustics|depth-of-field'),
	('Project history and process', 'Commit scopes, delivery records and handoffs.',
	 r'commit|delivery|handoff|scoped|architecture'),
]


def title_of(path):
	fenced = False
	for line in path.read_text(encoding='utf-8').splitlines():
		if line.startswith('```'):
			fenced = not fenced
		elif not fenced and line.startswith('#'):
			return line.lstrip('#').strip().replace('[', '(').replace(']', ')')
	return path.stem


def build():
	docs = sorted(p for p in DOCS.glob('*.md') if p.name not in ('index.md', 'technical-notes.md'))
	groups = {name: [] for name, _, _ in TOPICS}
	groups['Other'] = []
	for p in docs:
		for name, _, pattern in TOPICS:
			if re.search(pattern, p.name):
				groups[name].append(p)
				break
		else:
			groups['Other'].append(p)
	out = ['# Quaked documentation index', '',
	       'Every document directly in this folder, by topic (subfolders hold images, evidence and their own READMEs). Start with the [technical notes](technical-notes.md) for the '
	       'feature-by-feature description, or the [README](../README.md) to play. Each document records what a '
	       'change does, how it was built, what was checked and what is still limited.', '',
	       '*This page is generated by `tools/build_docs_index.py`; add a document, then re-run it.*', '']
	descriptions = {name: desc for name, desc, _ in TOPICS}
	descriptions['Other'] = 'Documents that no topic rule claims yet.'
	for name, items in groups.items():
		if not items:
			continue
		out += ['## ' + name, '', descriptions[name], '']
		for p in items:
			out.append('- [%s](%s)' % (title_of(p), p.name))
		out.append('')
	return '\n'.join(out)


if __name__ == '__main__':
	text = build()
	if '--check' in sys.argv:
		sys.exit(0 if OUT.exists() and OUT.read_text(encoding='utf-8') == text else 1)
	OUT.write_text(text, encoding='utf-8')
	print('wrote', OUT.relative_to(ROOT), len(text.splitlines()), 'lines')
