// Generated by tools/build_startup_pak.py; authored HUD bytes remain canonical.
export const STARTUP_PACK = {"file":"newer/startup.pak","sha256":"84f14f16a1623b35b3b0a7eed15e37ab93d492b30e0422d8809651d3ae18eb8c","bytes":4892783,"entries":248};
