// Generated by tools/build_startup_pak.py; authored HUD bytes remain canonical.
export const STARTUP_PACK = {"file":"newer/startup.pak","sha256":"0896a653afafb278fdac91925992c5f5ef09d4054de0ff8bfb2ebef982f979b0","bytes":5135149,"entries":288};
