// Extracted from owner-supplied Quaked Rend the Veil 1.0.0; see tools/summoning_reference/provenance.json.
/** Locked production profile. No presets, inspector or game-owned rendering settings. */
const VERSION = '1.0.0';
const PROFILE = Object.freeze({
  name: 'Rend the Veil',
  sourceBuild: 'Forbidden Summoning 2.0.6',
  materialization: 'Shadow consuming the form',
  legacyRitualSeconds: 1.8,
  introSeconds: 0.5,
  appearanceSeconds: 1.0,
  unwindSeconds: 1.0,
  remnantsSeconds: 0.3,
  focusSeconds: 2.5,
  completeSeconds: 2.8,
  effectAuthoringHeight: 5.2,
  removedGlyphLayer: 2,
  activationPhase: 'focus',
  loop: false
});
const VISUALS = Object.freeze({
  "distortionStrength": 1.55,
  "distortionRadius": 2.05,
  "shape": 4,
  "lensStrength": 0.8,
  "inwardPull": 1.15,
  "refraction": 1.2,
  "chromatic": 0.1,
  "shimmer": 0.2,
  "turbulence": 1.1,
  "frequency": 3,
  "asymmetry": 0.58,
  "eldritch": 1.25,
  "foldSlices": 7,
  "foldAngle": 0.8,
  "mirrorAmount": 0.2,
  "structure": 2,
  "glyphDensity": 0.54,
  "glyphComplexity": 0.85,
  "glyphScale": 0.93,
  "glyphBrightness": 0.7,
  "glyphRotation": 0,
  "rotationSpeed": 0.19,
  "orbitalSpeed": 0.2,
  "geoInstability": 0.32,
  "flicker": 0.18,
  "depthOffset": 0.8,
  "layers": 3,
  "glyphConvergence": 0.72,
  "layer0": 1,
  "layer1": -0.7,
  "layer2": 1.3,
  "layer3": -1.6,
  "layer4": 0.45,
  "layer5": -0.35,
  "layer6": 1.8,
  "layer7": -1.1,
  "convergence": 1,
  "particleDensity": 850,
  "particleSpeed": 0.82,
  "orbitalAttraction": 0.85,
  "spiral": 1.2,
  "curvature": 0.75,
  "streakLength": 0.5,
  "streakBrightness": 0.35,
  "energyBrightness": 0.48,
  "convergenceRadius": 3.5,
  "pointSize": 1.35,
  "silhouetteOpacity": 0.97,
  "silhouetteBrightness": 0,
  "silhouetteInstability": 0.65,
  "duplicates": 3,
  "silhouetteConvergence": 1,
  "formationSpeed": 1,
  "edgeRefraction": 0.5,
  "contourBrightness": 0.64,
  "style": 1,
  "reconstructionSpeed": 1,
  "direction": 0,
  "edgeWidth": 0.055,
  "reconstructionNoise": 0.67,
  "fragmentation": 0.65,
  "stabilization": 0.85,
  "emissiveEdge": 0.75,
  "resolutionRate": 1,
  "snapIntensity": 1.6,
  "snapDuration": 0.06,
  "compressionAmount": 0.84,
  "flashBrightness": 0.4,
  "flashRadius": 0.82,
  "rippleSpeed": 8.5,
  "rippleRadius": 4.2,
  "rippleThickness": 1,
  "rippleDistortion": 0.85,
  "rippleRefraction": 0.65,
  "rippleChromatic": 0.3,
  "rippleStrength": 0.85,
  "rippleFalloff": 1.45,
  "rippleType": 1,
  "residualStrength": 0.28,
  "spatial": true,
  "lensing": true,
  "chromaticEnabled": true,
  "geometry": true,
  "rings": true,
  "impossible": true,
  "energy": true,
  "particles": true,
  "streaks": true,
  "silhouette": true,
  "reconstruction": true,
  "compression": true,
  "snap": true,
  "ripple": true,
  "residual": true,
  "magicPalette": 0,
  "shadowPool": true,
  "shadowVeil": true,
  "floorRunes": true,
  "shadowStrength": 1.3,
  "veilDensity": 1.75,
  "veilTwist": 1.8,
  "floorRuneBrightness": 1.2,
  "lightDimming": 0.7
});

export { VERSION,PROFILE,VISUALS };
