// Independent read-only streaming asset audit. No renderer, bake, model
// generation, archive extraction, or expanded geometry allocation is used.
import {open,readFile,readdir,writeFile,stat} from 'node:fs/promises';
import {createReadStream} from 'node:fs';
import {resolve,relative,join} from 'node:path';
import {createHash} from 'node:crypto';
import {Readable} from 'node:stream';
import {createGunzip} from 'node:zlib';
const args=process.argv.slice(2),root=resolve(args[0]||'.'),receipt=resolve(args[1]||'/private/tmp/quaked-prepared-corpus-audit.json');
const report={startedAt:new Date().toISOString(),root,status:'running',qualification:'Prepared asset/source integrity and schema audit; not expansion gameplay, GPU residency, or timing qualification.',limits:['No geometry regeneration or expanded triangle allocation','Normal input witnesses are checked against content keys; browser image decoding parity is a separate trial','Owned archives remain untouched and are never copied into this receipt'],maps:[],payloads:[],normalLevels:[],errors:[],bytes:{compressed:0,raw:0},sourceHashes:{}};
const check=(v,m)=>{if(!v)throw Error(m);},same=(a,b,m)=>check(a===b,`${m}: ${a} != ${b}`),hex=v=>typeof v==='string'&&/^[a-f0-9]{64}$/.test(v),sha=b=>createHash('sha256').update(b).digest('hex'),integer=Number.isSafeInteger;
function local(path){const full=resolve(root,path);check(!relative(root,full).startsWith('..'),'Path outside audit root '+path);return full;}
async function json(path){const raw=await readFile(local(path));report.sourceHashes[path]=sha(raw);return JSON.parse(raw);}
async function registry(path){const raw=await readFile(local(path),'utf8');report.sourceHashes[path]=sha(raw);const start=raw.indexOf(' = ');check(start>=0,'Registry assignment '+path);return JSON.parse(raw.slice(start+3).trim().replace(/;$/,''));}
async function directory(path){const fd=await open(local(path),'r');try{const size=(await fd.stat()).size,h=Buffer.alloc(12);same((await fd.read(h,0,12,0)).bytesRead,12,'PAK header');same(h.toString('ascii',0,4),'PACK','PAK signature');const offset=h.readUInt32LE(4),length=h.readUInt32LE(8);check(length%64===0&&length<=16*1024*1024&&offset+length<=size,'PAK directory bounds');const raw=Buffer.alloc(length);same((await fd.read(raw,0,length,offset)).bytesRead,length,'Complete directory');const out=new Map();for(let n=0;n<length;n+=64){const name=raw.subarray(n,n+56).toString().split('\0')[0].toLowerCase(),at=raw.readUInt32LE(n+56),bytes=raw.readUInt32LE(n+60);check(at+bytes<=size&&!out.has(name),'PAK member bounds/unique '+name);out.set(name,{path,offset:at,bytes});}return out;}finally{await fd.close();}}
async function memberIdentity(member){const hash=createHash('sha256');let count=0,prefix=Buffer.alloc(0);if(member.bytes===0)return{sha256:hash.digest('hex'),bytes:0,prefix};for await(const chunk of createReadStream(local(member.path),{start:member.offset||0,end:(member.offset||0)+member.bytes-1,highWaterMark:65536})){hash.update(chunk);count+=chunk.length;if(prefix.length<124)prefix=Buffer.concat([prefix,chunk.subarray(0,124-prefix.length)]);}same(count,member.bytes,'Complete source member');return{sha256:hash.digest('hex'),bytes:count,prefix};}
function schema(kind,h,expected){
 const segments=[];let bytes=0,counts={};
 if(kind==='rock'){
  same(h.version,'quaked-rockfield-1.2.0-1','Rock generator version');same(h.side,69,'Rock tile side');same(h.model,expected.name,'Rock embedded model');same(h.bspSha256,expected.bspSha256,'Rock embedded source');check(Array.isArray(h.charts),'Rock chart array');const signatures=new Set();let tiles=0;
  for(const c of h.charts){check(typeof c.signature==='string'&&!signatures.has(c.signature)&&Array.isArray(c.tiles),'Unique rock chart');signatures.add(c.signature);const sig=JSON.parse(c.signature);check(Array.isArray(sig)&&sig.length===5,'Rock field signature');const coords=new Set();for(const row of c.tiles){check(Array.isArray(row)&&row.length===3&&row.every(integer),'Rock coordinate/offset integers');same(row[2],tiles*69*69,'Contiguous rock tile');const key=row[0]+','+row[1];check(!coords.has(key),'Unique rock coordinate');coords.add(key);tiles++;}}
  same(h.charts.length,expected.spec.charts,'Rock chart count');same(tiles,expected.spec.tiles,'Rock tile count');bytes=tiles*69*69*2;segments.push({start:0,end:bytes,type:'half'});counts={charts:h.charts.length,tiles};
 }else if(kind==='sculpt'){
  same(h.version,1,'Sculpt codec version');same(h.generatorVersion,'quaked-sculpt-generator-1','Sculpt generator version');same(h.model,expected.name,'Sculpt embedded model');same(h.bspSha256,expected.bspSha256,'Sculpt embedded BSP');same(h.namespace,expected.spec.namespace,'Sculpt namespace');check(Array.isArray(h.records)&&h.records.length<=4096,'Sculpt records');const seen=new Set();let nativeOnly=0,triangles=0;
  for(const r of h.records){check(typeof r.signature==='string'&&!seen.has(r.signature)&&typeof r.settings==='string'&&hex(r.fieldSha256),'Sculpt signature/field identity');seen.add(r.signature);check(integer(r.surfaceId)&&r.surfaceId>=0&&r.surfaceId<expected.faces,'Native surface ordinal');same(r.offset,bytes,'Contiguous sculpt payload offset');const sig=JSON.parse(r.signature),field=expected.fields.get(sig[0]);check(field,'Recognized authored sculpt material');same(r.settings,field.settings,'Exact sculpt field recipe');same(r.fieldSha256,field.sha256,'Exact sculpt scalar bytes');
   if(r.nativeOnly){const n=r.nativeOnly;check(['triangle-budget','tile-budget'].includes(n.reason)&&integer(n.required)&&n.required>n.limit&&n.limit===(n.reason==='triangle-budget'?262144:16),'Recognized native-only generator limit');check(r.data==null&&r.vertices===undefined&&r.unique===undefined,'Native-only has no geometry');nativeOnly++;continue;}
   check(integer(r.vertices)&&r.vertices>=0&&r.vertices<=262144*3&&integer(r.unique)&&r.unique>=0&&r.unique<=r.vertices&&integer(r.triangles)&&r.vertices===r.triangles*3&&integer(r.topVertexCount)&&r.topVertexCount>=0&&r.topVertexCount<=r.vertices&&r.topVertexCount%3===0&&integer(r.skirtTriangles)&&r.skirtTriangles===(r.vertices-r.topVertexCount)/3,'Sculpt count relationships');let covered=0;check(Array.isArray(r.tileRegions),'Sculpt tile regions');for(const region of r.tileRegions){check(integer(region.startVertex)&&integer(region.endVertex)&&region.startVertex===covered&&region.endVertex>=covered&&region.endVertex<=r.topVertexCount&&region.startVertex%3===0&&region.endVertex%3===0,'Sculpt region coverage');check(region.origin===null||Array.isArray(region.origin)&&region.origin.length===2&&region.origin.every(integer),'Sculpt region origin');covered=region.endVertex;}same(covered,r.topVertexCount,'All sculpt top vertices covered');segments.push({start:bytes,end:bytes+r.unique*40,type:'float'});bytes+=r.unique*40;segments.push({start:bytes,end:bytes+r.vertices*4,type:'index',limit:r.unique});bytes+=r.vertices*4;triangles+=r.triangles;
  }
  same(h.records.length,expected.spec.surfaces,'Sculpt surface count');same(nativeOnly,expected.spec.nativeOnly||0,'Native-only count');same(triangles,expected.spec.triangles,'Sculpt triangle count');counts={surfaces:h.records.length,nativeOnly,triangles};
 }else{
  same(h.version,'quaked-normal-generator-1','Normal generator version');same(h.key,expected.key,'Normal full input key');same(h.width,expected.spec.width,'Normal width');same(h.height,expected.spec.height,'Normal height');check(integer(h.width)&&integer(h.height)&&h.width>=1&&h.height>=1&&h.width<=2048&&h.height<=2048,'Normal dimensions');check(integer(h.referenceWidth)&&integer(h.referenceHeight)&&h.referenceWidth>=0&&h.referenceHeight>=0&&h.referenceWidth<=2048&&h.referenceHeight<=2048&&(h.referenceWidth===0)===(h.referenceHeight===0),'Normal reference dimensions');const n=h.width*h.height,ref=h.referenceWidth*h.referenceHeight,w=expected.spec.input;check(w,'Normal input witness exists');same(h.referenceWidth,w.edge?.[0]||0,'Reference input width');same(h.referenceHeight,w.edge?.[1]||0,'Reference input height');segments.push({start:0,end:n*4,type:'bytes'},{start:n*4,end:n*8,type:'scalar'},{start:n*8,end:n*8+ref*4,type:'bytes'});bytes=n*8+ref*4;counts={width:h.width,height:h.height,referenceWidth:h.referenceWidth,referenceHeight:h.referenceHeight};
 }
 return{bytes,segments,counts};
}
async function auditPayload(kind,spec,expected){
 const parts=spec.parts||(Array.isArray(spec.file)?spec.file:[{file:spec.file,sha256:spec.sha256,bytes:spec.compressedBytes}]),compressedHash=createHash('sha256');let compressedBytes=0;
 check(parts.length>0&&parts.length<=32,'Bounded prepared parts');for(const p of parts)check(typeof p.file==='string'&&hex(p.sha256)&&integer(p.bytes)&&p.bytes>0&&(!(spec.parts||Array.isArray(spec.file))||p.bytes<=48*1024*1024),'Prepared part metadata');
 async function* chunks(){for(const part of parts){const hash=createHash('sha256');let bytes=0;for await(const chunk of createReadStream(local(part.file),{highWaterMark:65536})){bytes+=chunk.length;check(bytes<=part.bytes,'Compressed part byte ceiling');hash.update(chunk);compressedHash.update(chunk);compressedBytes+=chunk.length;yield chunk;}same(bytes,part.bytes,'Compressed part length');same(hash.digest('hex'),part.sha256,'Compressed part SHA '+part.file);}}
 const source=Readable.from(chunks()),gunzip=createGunzip({chunkSize:65536});source.on('error',e=>gunzip.destroy(e));source.pipe(gunzip);const rawHash=createHash('sha256');let rawBytes=0,header=Buffer.alloc(0),layout=null,headerBytes=0,payloadBytes=0,tail=Buffer.alloc(0),segment=0;
 function scan(chunk){let data=tail.length?Buffer.concat([tail,chunk]):chunk,at=0;while(at<data.length){while(segment<layout.segments.length&&payloadBytes===layout.segments[segment].end)segment++;const s=layout.segments[segment];check(s,'No trailing prepared bytes');const width=s.type==='half'?2:s.type==='bytes'?1:4,take=Math.min(data.length-at,s.end-payloadBytes),whole=take-take%width;for(let i=0;s.type!=='bytes'&&i<whole;i+=width){const p=at+i;if(s.type==='half')check(data.readUInt16LE(p)<=0x3c00,'Finite normalized rock HALF');else if(s.type==='index')check(data.readUInt32LE(p)<s.limit,'Sculpt index references existing tuple');else if(s.type==='float'||s.type==='scalar'){const v=data.readFloatLE(p);check(Number.isFinite(v)&&(s.type!=='scalar'||v>=0&&v<=1),'Finite geometry/normalized scalar');}}at+=whole;payloadBytes+=whole;if(whole<take)break;}tail=Buffer.from(data.subarray(at));check(tail.length<4,'Bounded alignment tail');}
 try{for await(const chunk of gunzip){rawBytes+=chunk.length;check(rawBytes<=spec.bytes&&rawBytes<=(kind==='rock'?256:kind==='normal'?64:512)*1024*1024,'Decoded payload byte ceiling');rawHash.update(chunk);if(!layout){header=Buffer.concat([header,chunk]);const prefix=kind==='sculpt'?8:4;if(header.length<prefix)continue;if(kind==='sculpt')same(header.readUInt32LE(0),0x31424451,'Sculpt magic');const length=header.readUInt32LE(kind==='sculpt'?4:0);check(length<=(kind==='normal'?65536:8*1024*1024),'Header bound');headerBytes=kind==='rock'?4+length+(length&1):(prefix+length+3)&~3;if(header.length<headerBytes)continue;const h=JSON.parse(header.subarray(prefix,prefix+length).toString());layout=schema(kind,h,{...expected,spec});same(headerBytes+layout.bytes,spec.bytes,'Exact complete payload layout');const remaining=header.subarray(headerBytes);header=null;if(remaining.length)scan(remaining);}else scan(chunk);}
  check(layout,'Complete prepared header');same(tail.length,0,'No partial trailing word');same(payloadBytes,layout.bytes,'Full payload consumed');same(rawBytes,spec.bytes,'Expanded size');same(rawHash.digest('hex'),spec.rawSha256,'Complete expanded SHA');same(compressedBytes,spec.compressedBytes,'Complete compressed length');same(compressedHash.digest('hex'),spec.sha256,'Complete concatenated gzip SHA');report.bytes.raw+=rawBytes;report.bytes.compressed+=compressedBytes;const result={kind,name:expected.name||expected.key,files:parts.length,compressedBytes,rawBytes,...layout.counts};report.payloads.push(result);return result;
 }finally{source.destroy();gunzip.destroy();}
}

try{
 const corpus=await json('newer/displacement/corpus.json'),rock=await json('newer/rockfield/manifest.json'),sculpt=await json('newer/displacement/manifest.json'),normal=await json('newer/normals/manifest.json'),recipes=(await json('newer/textures/index.json')).normals;
 same(corpus.levels.length,159,'Explicit159-map inventory');check(corpus.skipped.some(s=>/Dawn/i.test(s.campaign)),'Missing Dawn explicitly skipped');same(JSON.stringify(await registry('src/rockfield_bakes.js')),JSON.stringify(rock.levels),'Runtime rock registry');same(JSON.stringify(await registry('src/demon_bakes.js')),JSON.stringify(sculpt.levels),'Runtime sculpt registry');same(JSON.stringify(await registry('src/normal_bakes.js')),JSON.stringify(Object.fromEntries(Object.entries(normal.samples).map(([k,{input,...s}])=>[k,s]))),'Runtime normal registry');
 for(const manifest of [rock,sculpt])for(const[path,expected]of Object.entries(manifest.sources)){const actual=sha(await readFile(local(path)));report.sourceHashes[path]=actual;if(actual!==expected)report.errors.push('Current generator/source fingerprint '+path+': '+actual+' != '+expected);}
 const namespaces={shareware:'pak0.pak',newer:'newer/maps.pak',id1:'resources/id1/pak0.pak',hipnotic:'resources/hipnotic/pak0.pak',rogue:'resources/rogue/pak0.pak',dopa:'resources/dopa/pak0.pak',mg1:'resources/mg1/pak0.pak'},directories=new Map(),declared=new Set(corpus.levels.map(l=>l.namespace+':'+l.name));same(declared.size,159,'Unique namespace/map inventory');
 for(const[ns,path]of Object.entries(namespaces)){const entries=await directory(path);directories.set(ns,entries);for(const name of entries.keys())if(/^maps\/[^/]+\.bsp$/.test(name))check(declared.has(ns+':'+name),'Inventory includes actual '+ns+':'+name);}
 for(const file of(await readdir(local('maps'))).filter(n=>n.endsWith('.bsp')))check(declared.has('loose:maps/'+file),'Inventory includes actual loose map');
 const scalarRaw=await readFile(local('newer/textures/normals/demon-face.r16')),scalar=new Float32Array(scalarRaw.length/2);for(let i=0;i<scalar.length;i++)scalar[i]=scalarRaw.readUInt16LE(i*2)/65535;const fields=new Map();for(const[name,r]of Object.entries(recipes))if(r.displacement&&r.dataFile==='normals/demon-face.r16')fields.set(name,{sha256:sha(new Uint8Array(scalar.buffer)),settings:JSON.stringify([256,512,r.sampling||'repeat',r.displacement.depth,r.displacement.step,r.displacement.smoothing??0])});
 const auditedRock=new Set(),auditedSculpt=new Set(),normalKeys=new Set();
 for(const level of corpus.levels){check(level.namespace==='loose'||namespaces[level.namespace],'Only explicitly scoped campaigns');const member=level.namespace==='loose'?{path:level.loose,bytes:(await stat(local(level.loose))).size}:directories.get(level.namespace).get(level.name);check(member,'Actual source member exists');const identity=await memberIdentity(member);same(identity.sha256,level.bspSha256,'Actual BSP SHA '+level.namespace+':'+level.name);same(identity.bytes,level.bytes,'Actual BSP bytes');same(identity.prefix.readUInt32LE(0),level.bspVersion,'Actual BSP layout');check([29,0x32505342,0x42535032].includes(level.bspVersion),'Supported source BSP');const faces=identity.prefix.readUInt32LE(8+7*8)/(level.bspVersion===29?20:28);check(integer(faces),'Face lump alignment');const r=rock.levels[level.name]?.find(s=>s.bspSha256===level.bspSha256),d=sculpt.levels[level.name]?.find(s=>s.namespace===level.namespace&&s.bspSha256===level.bspSha256),n=normal.levels[level.namespace+':'+level.name];check(r&&d&&n,'Complete rock/sculpt/normal coverage '+level.namespace+':'+level.name);same(n.bspSha256,level.bspSha256,'Normal map source');same(r.generatorFingerprint,sha(Buffer.from(JSON.stringify(rock.sources))),'Rock generator fingerprint');same(d.generatorFingerprint,sha(Buffer.from(JSON.stringify(sculpt.sources))),'Sculpt generator fingerprint');check(Array.isArray(n.nativeKeys)&&Array.isArray(n.upgradedKeys),'Native and upgraded normal coverage recorded');same(JSON.stringify([...new Set([...n.nativeKeys,...n.upgradedKeys])].sort()),JSON.stringify([...n.keys].sort()),'Normal native/upgraded key union');const rk=level.name+':'+level.bspSha256;if(!auditedRock.has(rk)){await auditPayload('rock',r,{name:level.name,bspSha256:level.bspSha256});auditedRock.add(rk);}await auditPayload('sculpt',d,{name:level.name,bspSha256:level.bspSha256,faces,fields});auditedSculpt.add(level.namespace+':'+level.name);check(Array.isArray(n.keys)&&new Set(n.keys).size===n.keys.length,'Normal map key coverage');for(const key of n.keys)normalKeys.add(key);report.maps.push({namespace:level.namespace,name:level.name,bspSha256:level.bspSha256,normalKeys:n.keys.length,sculptNativeOnly:d.nativeOnly||0});console.log('AUDIT_MAP '+report.maps.length+'/159 '+level.namespace+':'+level.name);}
 same(auditedRock.size,147,'Unique source-distinct rock variants');same(auditedSculpt.size,159,'Every scoped sculpt variant');
 for(const[label,entry]of Object.entries(normal.levels)){check(Array.isArray(entry.keys)&&new Set(entry.keys).size===entry.keys.length,'Unique normal references '+label);if(entry.modelSha256){const colon=label.indexOf(':'),ns=label.slice(0,colon),name=label.slice(colon+1),member=directories.get(ns)?.get(name);check(member,'Native normal model source exists '+label);same((await memberIdentity(member)).sha256,entry.modelSha256,'Native model source SHA '+label);}for(const key of entry.keys){check(hex(key)&&normal.samples[key],'Referenced normal key exists '+label);normalKeys.add(key);}report.normalLevels.push({label,keys:entry.keys.length,modelSourceVerified:!!entry.modelSha256});}
 for(const key of normalKeys){const s=normal.samples[key],w=s.input;check(w,'Full normal input witness '+key);const input=['quaked-normal-generator-1',w.width,w.height,w.crafted,w.derive,w.strength,w.cap,w.rgba,w.fullbright,w.scalar,w.edge,w.authored];same(sha(Buffer.from(JSON.stringify(input))),key,'Normal key binds every source witness');await auditPayload('normal',s,{key});if(report.payloads.filter(p=>p.kind==='normal').length%100===0)console.log('AUDIT_NORMAL '+report.payloads.filter(p=>p.kind==='normal').length+'/'+normalKeys.size);}
 report.counts={maps:report.maps.length,rockVariants:auditedRock.size,sculptVariants:auditedSculpt.size,normalMapVariants:corpus.levels.length,normalLevels:report.normalLevels.length,normalSamples:normalKeys.size,nativeOnly:report.maps.reduce((n,m)=>n+m.sculptNativeOnly,0)};report.status=report.errors.length?'fail':'pass';if(report.errors.length)process.exitCode=1;
}catch(error){report.status='fail';report.errors.push(String(error.stack||error));process.exitCode=1;}
report.finishedAt=new Date().toISOString();await writeFile(receipt,JSON.stringify(report,null,2)+'\n');console.log('CORPUS_AUDIT '+JSON.stringify({status:report.status,counts:report.counts,bytes:report.bytes,errors:report.errors,receipt}));
